### ISSUE TITLE
[Suggestion] Remove close button and bottom edge for selected pinned tabs

### ISSUE THREAD

**Issue by zhuopeng-tan** [black7375/Firefox-UI-Fix#10]
Thanks for your work, it looks better than official UI.

![image](https://user-images.githubusercontent.com/77958663/119439537-25dc5a80-bd55-11eb-8c08-a49e1fad6539.png)

As the image shows, it's weird to show just a close button for selected pinned tabs, it's better to remove it.

And I suggest to removing the bottom edge for selected pinned tabs to be consistent with unpinned tabs.

**Comment by black7375** [comment]
Closed button is the intended design.

Inspired from chromium.
![Chomium Tab](https://user-images.githubusercontent.com/25581533/119445720-c5c9c200-bd1c-11eb-865c-f9b595bfc259.png)

Maybe just erase the next part.
https://github.com/black7375/Firefox-UI-Fix/blob/28caaad83e96949d4599b7eec45196f289a914d1/userChrome.css#L369-L413

---

Bottom shadow line is a bug and can be reproduced in case of tab overflow.
I'll fix it as soon as possible.

**Comment by zhuopeng-tan** [comment]
![image](https://user-images.githubusercontent.com/77958663/119446265-b9675880-bd60-11eb-8cdf-f818fbc0b23e.png)

Yeah, close button removed, it would be perfect if the bottom edge (the line between tab bar and tool bar) could be removed too.

Actually we can close pinned tab by middle click without close button.

**Comment by black7375** [comment]
Fixed it now, test please

**Comment by zhuopeng-tan** [comment]
![image](https://user-images.githubusercontent.com/77958663/119453060-9d1be980-bd69-11eb-8217-4279b260ad5e.png)

Perfect! Thanks!

How about creating a separate branch for the change(**Hide close button for selected pinned tabs**)?
https://github.com/black7375/Firefox-UI-Fix/blob/28caaad83e96949d4599b7eec45196f289a914d1/userChrome.css#L369-L413

**Comment by black7375** [comment]
I created it because it is a function that can split like and dislike.
https://github.com/black7375/Firefox-UI-Fix/tree/hide-closebutton-at-pinned

I'll merge regularly and I will try and ensure maximum compatibility, but support may be less compared to the base version.

---

Guessing, are you trying to sync with `git pull`?

**Comment by zhuopeng-tan** [comment]
> 
> 
> I created it because it is a function that can split like and dislike.
> https://github.com/black7375/Firefox-UI-Fix/tree/hide-closebutton-at-pinned
> 
> I'll merge regularly and I will try and ensure maximum compatibility, but support may be less compared to the base version.
> 
> Guessing, are you trying to sync with `git pull`?

At the present, I just copy the content, the reason that I suggest creating a separate branch is that maybe one day I need to setup a new machine, and for other users who also need this change.

It's a small change, so merge future updates shouldn't take much effort.

Again, thanks for you work.

**Comment by black7375** [comment]
Thanks for the answer

**Comment by zhuopeng-tan** [comment]
@black7375 
I just checked the latest version Chrome, it does not show close button for **pinned tabs**, so can we rebase/merge branch `hide-closebutton-at-pinned` to `master`?

![image](https://user-images.githubusercontent.com/77958663/119970750-b2e81380-bfe2-11eb-845c-a1b3effc4dc5.png)


> 
> 
> Closed button is the intended design.
> 
> Inspired from chromium.
> ![Chomium Tab](https://user-images.githubusercontent.com/25581533/119445720-c5c9c200-bd1c-11eb-865c-f9b595bfc259.png)
> 
> Maybe just erase the next part.
> 
> https://github.com/black7375/Firefox-UI-Fix/blob/28caaad83e96949d4599b7eec45196f289a914d1/userChrome.css#L369-L413
> 
> Bottom shadow line is a bug and can be reproduced in case of tab overflow.
> I'll fix it as soon as possible.

**Comment by black7375** [comment]
There is no plan yet, but if many people feel uncomfortable a lot later, we will reflect it.

**Comment by Stepan-H** [comment]
I feel wery uncomfortable and I unintentionally close a tab by missclick (unintentionally doubleclick)...

**Comment by zhuopeng-tan** [comment]
@black7375 @Stepan-H The behaviors `Hide close button for **pinned** tabs` and `Close pinned tabs by middle click or right click + menu` are same to Chrome, pinned tabs are expected to be accessed frequently, so users would keep them for long time

For regular tabs, showing close button makes sense.

> Closed button is the intended design.
Inspired from chromium.

**Comment by black7375** [comment]
Yes. I will seriously consider it when I work on it tomorrow.

**Comment by black7375** [comment]
This will be discussed again after 1.0. #31

**Comment by 7k5x** [comment]
Yeah man the close button is mostly useful but could be insanely annoying when I drop the mouse and close some tabs. <br> How about using JS to add toggling of it?

**Comment by black7375** [comment]
All features using JS should be introduced after the installer is created.
It requires too many settings from users.

**Comment by 7k5x** [comment]
Ok. I'm working on the installer script. I'll implement the backup and redirection later.<br>I agree on your statement that it requires too may settings from users.<br>This project shouldn't be bloated by any means.

**Comment by black7375** [comment]
@7k5x  check #32
Seems like a good example.

**Comment by 7k5x** [comment]
Crazy big script, but I think that's really good. Maybe someone should implement that on chrome too.<br>Google, are you listening?

**Comment by 7k5x** [comment]
@black7375 IMO putting options in `install.sh` should be minimized or be removed. Most people want things to just work. I'll review replacing the options with prompting the user input from the console.

**Comment by black7375** [comment]
First of all, changes to default options should be minimized.
It would be nice to control it by adding parameters.

**Comment by cubetastic33** [comment]
I agree, showing the close button on pinned tabs seems counter-intuitive and gets in the way. Pinned tabs are likely to be open for long and it looks ugly to see just a close icon whenever the tab is active.

**Comment by black7375** [comment]
1.0 has been released.
Now, closed button on tab will be removed.

**Comment by mikesafari** [comment]
> 
> 
> 1.0 has been released.
> Now, closed button on tab will be removed.

It looks like this is still an issue in Photon-Style.

**Comment by black7375** [comment]
reflected for `photon-stlye`.
