### ISSUE TITLE
132 There is no "chrome://global/skin/icons/radio.svg"

### ISSUE THREAD

**Issue by kidzgy** [black7375/Firefox-UI-Fix#1022]
### Describe the bug

In [ Lepton-Proton-Style](https://github.com/black7375/Firefox-UI-Fix/releases/download/v8.6.4/Lepton-Proton-Style.zip) 8.6.4, line 16431 of leptonChrome.css, file “chrome://global/skin/icons/radio.svg” does not exist.

### Screenshots

<img width="671" alt="2024-11-10_154605" src="https://github.com/user-attachments/assets/e25dd9d3-847e-4388-8ab7-4180deee1bdc">

### OS

Windows 11

### Firefox Version

132.0.1 

### Distribution

- [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [X] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [X] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

default

**Comment by black7375** [comment]
Edited to include Radio icon.
thank you for report!!

---

Related commit:

https://github.com/mozilla/gecko-dev/commit/09079239a4030f9a0a4d6280af67ee9b17f68696

**Comment by black7375** [comment]
I think this issue can be closed.
