### ISSUE TITLE
Incorrect tab after updating to latest Nightly version v134.0a1 

### ISSUE THREAD

**Issue by Progress200** [black7375/Firefox-UI-Fix#1023]
### Describe the bug

After updating to Nightly v134.0a1, the tab returns to the default floating tab of Proton. I already applied the latest version of Lepton (v8.6.4).
![image](https://github.com/user-attachments/assets/a4d25464-de77-4f3d-9962-c18da65f0766)

### Expected behavior

Normal Lepton tab behaviour
![image](https://github.com/user-attachments/assets/4cd4d7cf-e48a-471f-9bc0-57e7f020904f)

### OS

Windows 11

### Firefox Version

v134.0a1 (2024-11-10) (nightly)

### Distribution

- [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [X] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>

**Comment by denian71** [comment]
same thing for firefox beta - 133.0b9 (64-bit)

**Comment by black7375** [comment]
I wrote a small patch that fixes the bug.

https://github.com/mozilla/gecko-dev/commit/db0d30dc7c40f8280975109fffb94856dc1b94be#diff-3bc9a8d30c5dac9f5e2374b4419a283306710a5a4ccfea7ba005eed30907233bR307

**Comment by Progress200** [comment]
Shall we release a new Release? This bug is already affecting the Stable Firefox version.

**Comment by Progress200** [comment]
Shall we release a new Release? This bug is already affecting the Stable Firefox version.

**Comment by black7375** [comment]
I got it. I will release it today.

**Comment by black7375** [comment]
Released!!
