### ISSUE TITLE
I'm not getting the new Firefox colors

### ISSUE THREAD

**Issue by Fizbin99** [black7375/Firefox-UI-Fix#103]
Everything works fine but the new colors. It doesn't matter which theme I use. Clearing the startup cache doesn't work, refreshing doesn't work either. I'm wondering if it has something to do with the fact that I'm still using Windows 10 1809.

Thanks!

**Comment by black7375** [comment]
Hmm. Could you use these theme?

- https://addons.mozilla.org/en-US/firefox/addon/photon-colors/
- https://addons.mozilla.org/en-US/firefox/addon/photon-dark/
- https://addons.mozilla.org/en-US/firefox/addon/photon-light/

**Comment by Fizbin99** [comment]
Thanks for the reply. None of those themes make it work. Where is the code that makes it work located?

**Comment by black7375** [comment]
Select color theme at `about:addons`
![image](https://user-images.githubusercontent.com/25581533/122858116-43c3bd80-d309-11eb-8688-ba9fb57d49a5.png)

If the normal color theme doesn't work, it's a problem with Firefox itself.

**Comment by Fizbin99** [comment]
Yeah, I'm doing that. I think there is something wrong with the userContent file. The brackets aren't matching up according to my Notepad++ program.  It happens around line 87. If there is a a matching open and closing set of brackets they will turn red but around line 87 it won't match them up.  Maybe it's unrelated or maybe it's just the Notepad++ program.

**Comment by black7375** [comment]
> The brackets aren't matching up according to my Notepad++ program. It happens around line 87.

I tested it with emacs and VS Code, and there was no problem.
If the general theme does not apply, it is not a problem in this project, and it is not an area that can be solved, so close it.
