### ISSUE TITLE
Firefox 133 Breaks Tab Placement.

### ISSUE THREAD

**Issue by IcySon55** [black7375/Firefox-UI-Fix#1034]
### Describe the bug

The tabs are floating above the address bar.

### Expected behavior

No gap between tabs and address bar.

### Screenshots

![image](https://github.com/user-attachments/assets/72b89976-34db-46ac-a865-88c09d68d301)

### OS

Windows 10

### Firefox Version

133.0

### Distribution

- [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [X] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [ ] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Stock 
```
</details>

**Comment by terr72** [comment]
I can confirm the bug.
FF 133 on Linux with v8.6.4

**Comment by black7375** [comment]
It seems duplicated #1023
It should have been fixed based on the master branch.
