### ISSUE TITLE
Navbar has a fade-in animation 

### ISSUE THREAD

**Issue by jamesWalker55** [black7375/Firefox-UI-Fix#1036]
### Describe the bug

(Opening a new issue since the old one was closed)

Follow up to https://github.com/black7375/Firefox-UI-Fix/issues/1033. The fade in issue is still present:

https://github.com/user-attachments/assets/cc98da39-1d11-40f0-a88f-89748ed811f7

The fade-in occurs for the default Light/Dark themes but not custom themes.

Could this fade-in be disabled completely please?

### Expected behavior

The animation does not occur at all, like in previous releases

### OS

Windows 10

### Firefox Version

v133.0 (64-bit)

### Distribution

- [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [X] Light
- [X] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [ ] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>

**Comment by black7375** [comment]
I reopened an existing issue.
