### ISSUE TITLE
Less icons in the Menu with Lepton Photon-style

### ISSUE THREAD

**Issue by LordRishav** [black7375/Firefox-UI-Fix#108]
**Describe the bug**
There are less icons in the Application Menu in Photon-style than there are in original Lepton

**Expected behavior**
Both styles should have same number of icons

**Screenshots**
[Current state of icons in the menu with Photon-style](https://i.imgur.com/OOOUlG2.png)

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
 - Firefox Version: 	89.0.2
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [x] System Default
     - GTK Theme Name(Only Linux User): Breeze light

**Additional context**
N/A

**Comment by black7375** [comment]
It would be better to add to the FAQ.
https://github.com/black7375/Firefox-UI-Fix/pull/107#issuecomment-869476935

**Comment by LordRishav** [comment]
Makes sense, and the lack of icons don't interfere much in the workflow so I am fine with it. Thank you
