### ISSUE TITLE
Spacing between icons and menu-items in main menu is missing on macOS

### ISSUE THREAD

**Issue by kevinboss** [black7375/Firefox-UI-Fix#11]
**Describe the bug**
No spacing between menu entry and icon in main menu, see also:
<img width="470" alt="image" src="https://user-images.githubusercontent.com/4927587/119736922-c4b0a600-be7e-11eb-990d-ec3c899843fa.png">

**Expected behavior**
The same space as in all other menus, see for example the addon overflow menu:
<img width="470" alt="image" src="https://user-images.githubusercontent.com/4927587/119736617-46540400-be7e-11eb-87c7-619f9b2965fa.png">

**Environment (please complete the following information):**
 - Firefox Version: Nightly: 90.0a1, Build 20210526094846
 - OS: macOS 11
 - Theme: Dark

**Additional context**
Love your work, I love the course Mozilla is taking with proton now.

**Comment by black7375** [comment]
I haven't been able to test it on a mac. (Broke down 2 years ago)

However, it takes a lot of time, but I have found a way, and I will test it within this week.
https://github.com/sickcodes/Docker-OSX

There are many bugs in the Mac, such as padding and fill color..

**Comment by black7375** [comment]
## For contributor

**Debug Tutorial**

https://www.reddit.com/r/FirefoxCSS/comments/73dvty/tutorial_how_to_create_and_livedebug_userchromecss/

**Main Part of Icons**

https://github.com/black7375/Firefox-UI-Fix/blob/477ff4e2d4287987cdb3a86f3460f3b1e5976710/userChrome.css#L559-L669

**Comment by black7375** [comment]
Unlike the previous experience, Docker for OS X installation did not work as expected, and it was temporarily predicted and corrected.

Are there any changes?

**Comment by kevinboss** [comment]
The icons have been fixed, looks fine now. However it seems to have introduced an issue with the icon in front of the account menu-item, see:
![image](https://user-images.githubusercontent.com/4927587/119810247-27895800-bee6-11eb-9da8-c16968dc0077.png)

**Comment by black7375** [comment]
OK, I got confidence.

I'll fix it right away.

**Comment by kevinboss** [comment]
Now it is perfect.

Btw. is there some way to gift you a cup of coffee?

**Comment by black7375** [comment]
I have a contract to prohibit external revenue until next year.

You don’t need to get me anything.
Thank you!!
