### ISSUE TITLE
icons in URL bar (context menu)

### ISSUE THREAD

**Issue by gabri25ele** [black7375/Firefox-UI-Fix#110]
should I have icons in the context menu at URL bar?

![001](https://user-images.githubusercontent.com/33927879/124127120-a2143d00-da7b-11eb-8c03-b94adae8bbd8.png)

**Comment by black7375** [comment]
The menus in the URL Bar are not grouped together. I'll try to fix it tomorrow.

**Comment by black7375** [comment]
Applied!!
