### ISSUE TITLE
Microphone dialog box changing position

### ISSUE THREAD

**Issue by DanGM96** [black7375/Firefox-UI-Fix#111]
**Describe the bug**
Microphone and it's dialog loads before the other icons (permissions and autoplay). I've tested it on Google Meet.
When the page loads and you're about to "Block" Mic access, the other two icons load a bit late (this time varies) and makes the dialog box shift to the right, and that may cause you to click on "Allow" instead.
This only happens on new tabs, reloading the page on the same tab can't be reproduced.

**Expected behavior**
I expect the prompt to always be on it's initial loaded position.

**Screenshots**
![image](https://user-images.githubusercontent.com/36743739/124165652-6a57c600-da78-11eb-8fb2-bdb23cbb3c96.png)
![image](https://user-images.githubusercontent.com/36743739/124165687-75aaf180-da78-11eb-8344-c01d4aa576e0.png)

**Environment (please complete the following information):**
 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
 - Firefox Version: 89.0.2
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [x] Alpenglow(System: Dark)
   - [ ] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

**Additional context**
Oh it can make your Mic open without you even noticing it. That may cause problems.

**Comment by black7375** [comment]
It is not easy as it is dynamically detected and items are added.

**Comment by ojaha065** [comment]
This seems like something that should be fixed in Firefox. Accidentally allowing access to mic/webcam is something that should **absolutely never** happen. Have you checked if this is already reported in Mozilla bug tracker?

**Comment by DanGM96** [comment]
I have checked there but didn't find anything like this. First I thought the problem was with this repo fix, because I never had it before. The problem is I skipped Proton directly to this.
So this is a issue with Proton that wasn't present in Photon.
If you'd like, go ahead and post this on Bugzilla, or I might do later.

**Comment by black7375** [comment]
Firefox have same problem
![Honeycam 2021-07-03 09-41-08](https://user-images.githubusercontent.com/25581533/124338424-6ff7fd80-db97-11eb-81fb-8e3f89b4d984.gif)
![Honeycam 2021-07-03 09-40-15](https://user-images.githubusercontent.com/25581533/124338427-76867500-db97-11eb-88f5-5d72c65e0f7a.gif)
