### ISSUE TITLE
Multi-account container long click menu doesn't work (but right click menu works)

### ISSUE THREAD

**Issue by adnan360** [black7375/Firefox-UI-Fix#114]
**Describe the bug**
When Lepton is installed and [Firefox multi-account container](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers) addon is installed, I can't open a specific container tab by long clicking the New tab button. It doesn't do anything when I select a menu item. But surprisingly if I right click the new tab button and select anything, it seems to work.

Steps to reproduce:
- Install [multi-account containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers) addon
- Install Lepton on profile directory (user.js + chrome dir) and clear startup cache as instructed
- After browser restarted, long (left) click until the containers menu appears, then click a container (e.g. Work)

**Current behavior**

Menu disappears, doesn't open a new tab or manage containers as if I didn't click anything

**Expected behavior**

Open the selected container tab or manage containers settings when clicked on a menu item

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
 - Firefox Version: 89.0.2
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [x] Others: FreeBSD
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [x] System Default
     - GTK Theme Name(Only Linux User): Adwaita

**Additional context**
I tested in Librewolf Appimage on Linux, but Firefox on FreeBSD. I've tried from latest release (2.1.0) and latest master (a631555). Both gave same results. Without Lepton installed left click menu works fine.

**Comment by black7375** [comment]
That's interesting. I checked that it closes when I lose focus.

**Comment by black7375** [comment]
Are you try with this patch?

---

Advice of qaz69wsx
https://www.reddit.com/r/FirefoxCSS/comments/oelg2r/interesting_css_bug/

**Comment by black7375** [comment]
It is currently determined to have been fixed and will be closed.

**Comment by adnan360** [comment]
Yeah. Solved, thanks.
