### ISSUE TITLE
Broken hover highlights on zoom controls in menu

### ISSUE THREAD

**Issue by PencilAmazing** [black7375/Firefox-UI-Fix#115]
**Describe the bug**
The '+' and '-' buttons do not get highlighted when hovered on, and the percentage has off-centered highlighting

**Expected behavior**
A highlight to indicate that the buttons are clickable.

**Environment (please complete the following information):**
 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
 - Firefox Version: 89.0.2
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [x] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [ ] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

**Comment by black7375** [comment]
Thank you. fixed now!!
