### ISSUE TITLE
Menu icons improperly colored

### ISSUE THREAD

**Issue by Genocidal** [black7375/Firefox-UI-Fix#116]
**Describe the bug**
Application menu icons are black in dark themes.

**Expected behavior**
Icons should be white, as they were in previous versions of the theme and as they are on the toolbar and in the context menu.

**Screenshots**
![Screenshot (22)](https://user-images.githubusercontent.com/12386300/124399232-1f43ea00-dce8-11eb-84de-43b301d39236.png)

**Environment (please complete the following information):**
Check like `- [x]`.
 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
 - Firefox Version: [90.0b12]
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow(System: Light)
   - [x] Alpenglow(System: Dark)
   - [x] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

**Additional context**
None.

**Comment by black7375** [comment]
Check next config is true

https://github.com/black7375/Firefox-UI-Fix/blob/8b34a713a0a464cb0d2689771aaa61c8db3085e7/user.js#L6

**Comment by Genocidal** [comment]
> Check next config is true
> 
> https://github.com/black7375/Firefox-UI-Fix/blob/8b34a713a0a464cb0d2689771aaa61c8db3085e7/user.js#L6

Double-checked, it was set to true. I am on a fresh profile using the full user.js from the repo.

**Comment by black7375** [comment]
And then restart firefox with `Clear startup cache...` at `about:support`
