### ISSUE TITLE
Port install script to Powershell

### ISSUE THREAD

**Issue by jammehcow** [black7375/Firefox-UI-Fix#119]
**Is your feature request related to a problem? Please describe.**
The current install script is written in bash - preventing it from being run on most Windows-based machines without the use of git-bash/WSL.

**Describe the solution you'd like**
The install script should be ported to Powershell (as part of v3) for Windows installations.

**Describe alternatives you've considered**
-none

**Additional context**
Wanted an issue for tracking against the v3 "powershell script" milestone. Happy to take a dig at implementing it.

**Comment by 7k5x** [comment]
#109 
Won't be easy since powershell isn't as powerfull as bash.

**Comment by ojaha065** [comment]
> powershell isn't as powerfull as bash

This is very much not true. While personally I'm not a huge fan of PowerShell, everything that can be done using Bash, can also be done just as easily in PowerShell.

**Comment by 7k5x** [comment]
Ok..Maybe I should try to study it deeper.

**Comment by jammehcow** [comment]
> Won't be easy since powershell isn't as powerfull as bash.

You'll find that PS has a lot more power with .NET behind it. Everything done in the current bash install script can be done in PS just fine. I'll create a draft PR with the prototype if you'd like to see how it works.

**Comment by 7k5x** [comment]
Oh maybe that's the reason I felt powershell wasn't powerful enough. But do you need the .NET framework runtime to run .NET commands in powershell?

**Comment by theseer** [comment]
While I have to admit my days of writing extensions for Firefox date back to when chrome and XUL where still a thing: Why don't we create an actual extension to install things?

**Comment by ojaha065** [comment]
@theseer 
> Why don't we create an actual extension to install things?

It's just not possible anymore. WebExtensions API is very limited (especially if compared to XUL) when it comes to editing the browser UI. See #47 .

**Comment by theseer** [comment]
*Sigh* Thanks.

**Comment by jammehcow** [comment]
Created #122 for implementation.

**Comment by black7375** [comment]
Experimental powershell script is merged.
