### ISSUE TITLE
black pixels around the selected tab bottom corners

### ISSUE THREAD

**Issue by Bad3r** [black7375/Firefox-UI-Fix#12]
**Describe the bug**
black pixels around the selected tab bottom corners

**Expected behavior**
no black pixels around the selected tab bottom corners

**Screenshots**
![image](https://user-images.githubusercontent.com/25513724/120077171-0e63e100-c077-11eb-9ac5-1012fe9bfca5.png)

**Environment (please complete the following information):**
 - Firefox Version: [write from `about:support` - `version`]
 - OS:
   - [x] Linux --> (`5.12.7-arch1-1`)

 - Theme:
   - [x] Other
       - [Nord Polar Night Theme](https://addons.mozilla.org/en-US/firefox/addon/nord-polar-night-theme/)
  

**Additional context**
Using Firefox Nightly --> [`90.0a1 (2021-05-14) (64-bit)`]

**Comment by black7375** [comment]
I can't reproduce.

- OS: `Linux 5.11.14-1-MANJARO`
- Firefox Version: `90.0a1 - 20210529092554 (64bit)`
- Theme: Nord Polar Night Theme

![nord polar theme](https://user-images.githubusercontent.com/25581533/120077609-c8207900-c09a-11eb-870d-837022c7e89c.png)

I think we need more information to fix the bug.

**Comment by Bad3r** [comment]
I'll provide any information you need. I am not sure what would be useful to you. I am using x11 if that makes a difference.

FYI I have not modified `userChrome.css` or `userContent.css`. This is the contents of my chrome directory
```py
chrome
├── icons
├── userChrome.css
└── userContent.css
```

**Comment by black7375** [comment]
Are the following options enabled?
- `svg.context-properties.content.enabled`  => `true`
- (If not) `layout.css.backdrop-filter.enabled` => `true`

Change the settings, then run `Clear startup cache...` on `about:support` page.

**Comment by Bad3r** [comment]
That fixed the issue. Thank you!

**Comment by black7375** [comment]
Which option activation solved it?
Maybe.. `svg.context-properties.content.enabled`?

**Comment by Bad3r** [comment]
Enabling `svg.context-properties.content.enabled` and clearing the cache solved the issue. I missed the step in the instructions. Sorry about that

**Comment by black7375** [comment]
It seemed like that.
I will consider adding a file related to that configuration.
