### ISSUE TITLE
--tab-line-color should be "highlight" by default on Linux (Photon-style)

### ISSUE THREAD

**Issue by Alex-gnzl** [black7375/Firefox-UI-Fix#120]
**Description:**
Currently the tab highlight is hardcoded, making it blue on the system theme.

**Expected behavior:**
Should follow active GTK theme.

**Screenshots**
![Screenshot_20210712_140209](https://user-images.githubusercontent.com/42013738/125277670-68182600-e31a-11eb-9f95-478dff0ef694.png)
![Screenshot_20210712_135431](https://user-images.githubusercontent.com/42013738/125277682-6e0e0700-e31a-11eb-9fd6-e22bf75772a1.png)
![Screenshot_20210712_140435](https://user-images.githubusercontent.com/42013738/125277693-6fd7ca80-e31a-11eb-9c5a-b8cf00b77171.png)

**Environment:**
 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
 - Firefox Version: 89.0.2
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [x] System Default
     - GTK Theme Name(Only Linux User): Breeze GTK

**Additional info:**
This does not matter for custom themes, *only* System Default.
https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#system_colors
(i have tested this with Windows 10, and alas it doesn't work there.)

**Comment by black7375** [comment]
I was thinking of doing more GTK compatibility work after the dark mode.
For example, URL bar border, etc. should also be GTK highlight color.

Nice report.

**Comment by Alex-gnzl** [comment]
While I'm at it, might as well specify this:
- there isn't much jank regarding color otherwise, most things just work
- urlbar seems to have a highlight border when i open a new tab, but it's darker for some reason (i'm not sure if it's focused or not? it's odd - focused but not unfolded; might be simply broken on my firefox)
![Screenshot_20210712_145312](https://user-images.githubusercontent.com/42013738/125283358-06a78580-e321-11eb-9f79-ffe217fd6c1f.png)
- Highlight and HighlightText seem to be the only useful ones out of the bunch (see comparison screenshots between two GTK themes, Breeze (w/ custom colorscheme) and Adwaita Dark)
![Screenshot_20210712_145514](https://user-images.githubusercontent.com/42013738/125284185-d1e7fe00-e321-11eb-9aa8-22a8f2bd7ce3.png)
![Screenshot_20210712_145848](https://user-images.githubusercontent.com/42013738/125284195-d44a5800-e321-11eb-835f-66ea49ea3e43.png)
- Changing to a theme that isn't "System Default" **does not** affect "Highlight", but thankfully --tab-line-color gets overridden to the theme color, so it just works.

Thank you for this project!

**Comment by black7375** [comment]
Now, GTK Supported at develope verstion!!

![image](https://user-images.githubusercontent.com/25581533/125574349-ed2a5bac-7e3a-4c24-9eef-6422f5ed025d.png)
