### ISSUE TITLE
Divide line between unselected tabs also when dragging a tab?

### ISSUE THREAD

**Issue by Dupond** [black7375/Firefox-UI-Fix#121]
Hello,
This is more an idea than a real feature request.
Currently, with the [userChrome.css file](https://github.com/black7375/Firefox-UI-Fix/blob/master/userChrome.css), the divide line between unselected tabs doesn't appear when you have several tabs opened, and you drag a tab around.
I've slightly modified the code to take this case into account.
I'm not a programmer at all, so I'm not sure whether my code is nice or not; I don't pretend it to be an improvement; all I can say is that it works for me, so I've thought I could share it, in case it could be useful.
Anyway, here is the code I use, that alters lines 455-459 from the original code (I've just added `#navigator-toolbox:not([movingtab]) > #titlebar > #TabsToolbar` at the beginning of each line):
```
#navigator-toolbox:not([movingtab]) > #titlebar > #TabsToolbar .tabbrowser-tab:is([visuallyselected], [multiselected], :hover) + .tabbrowser-tab .tab-background::before,
#navigator-toolbox:not([movingtab]) > #titlebar > #TabsToolbar .tabbrowser-tab:is([visuallyselected], [multiselected], :hover) ~ .tabbrowser-tab[afterhovered] .tab-background::before,
#navigator-toolbox:not([movingtab]) > #titlebar > #TabsToolbar .tabbrowser-tab[last-visible-tab]:is([visuallyselected], [multiselected], :hover) ~ #tabs-newtab-button::before,
#navigator-toolbox:not([movingtab]) > #titlebar > #TabsToolbar .tabbrowser-tab[first-visible-unpinned-tab]:is([visuallyselected], [multiselected], :hover) .tab-background::before,
#navigator-toolbox:not([movingtab]) > #titlebar > #TabsToolbar #tabbrowser-arrowscrollbox[overflowing] tab.tabbrowser-tab[first-visible-unpinned-tab] .tab-background::before {
    opacity: 0 !important;
}
```
Best regards,
Dupond

**Comment by black7375** [comment]
I will check it tomorrow. Thank you.

**Comment by black7375** [comment]
I like your suggestion. applied!!
