### ISSUE TITLE
Customize the Context Menu 

### ISSUE THREAD

**Issue by MaxiMii05** [black7375/Firefox-UI-Fix#125]
**Is your feature request related to a problem? Please describe.**
The context menu gets quite large with some entries that most users never use. I for one don't need the option to "save to Pocket" or inspect accessibility properties that make the context menu much larger because of the long text in German.

**Describe the solution you'd like**
If possible, I would like the ability to choose the entries of the context menu in the usercss file by just setting a boolean to 1 for example. This explains how to edit the menu: https://www.reddit.com/r/firefox/comments/7dvtw0/guide_how_to_edit_your_context_menu/

**Additional context**
![image](https://user-images.githubusercontent.com/77237423/125948198-69f18b58-6528-4fc2-b673-ec51c8083798.png)

PS: Great work on this project, I really love it and seeing all those entries on the roadmap makes me excited for its future.

**Comment by MaxiMii05** [comment]
Of course, if you decide to add this, the other context menus should be paid attention to as well.
![Screenshot 2021-07-16 144142](https://user-images.githubusercontent.com/77237423/125949332-eb17b689-4359-494b-8756-611a4c916f56.jpg)

**Comment by black7375** [comment]
It is possible to do it manually, but I think it is difficult to fix it dynamically.

If you want to remove a specific menu, you can define it by referring to the following:
https://github.com/stonecrusher/simpleMenuWizard

**Comment by black7375** [comment]
I added it to the wiki, so close it.
https://github.com/black7375/Firefox-UI-Fix/wiki/Tips#customize-context-menu
