### ISSUE TITLE
Display container indicator when page is loading

### ISSUE THREAD

**Issue by Farow** [black7375/Firefox-UI-Fix#126]
**Is your feature request related to a problem? Please describe.**
It seems like the container indicator is hidden when the favicon is replaced with the loading animation.

**Describe the solution you'd like**
The container indicator should be visible below the loading animation.

**Additional context**
Using Photon style on Windows.

**Comment by black7375** [comment]
I'll fix it next week.

**Comment by black7375** [comment]
Now, it's fixed

**Comment by Farow** [comment]
Just a note, this doesn't seem to be included in the v2.2.3 release of Photon style.

**Comment by black7375** [comment]
I made a mistake. reflected.
