### ISSUE TITLE
Add notice that setting browser.proton.enabled to false will FORCE the proton design and disable customization

### ISSUE THREAD

**Issue by Snowman-25** [black7375/Firefox-UI-Fix#127]
**Describe the bug**
When browser.proton.enabled  is set to false, the userChrome.css and userContent.css will NOT take effect

**Expected behavior**
The provided files / installers should make sure that this config is set to TRUE

**Environment (please complete the following information):**
Check like `- [x]`.
 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix) (Most probably also affected)
   - [X] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
 - Firefox Version: 91.0b3
 - OS:
   - [ ] Linux
   - [X] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [ ] System Default
   - [X] [Gray and Black by MaDonna](https://addons.mozilla.org/de/firefox/addon/gray-and-black)

**Additional context**
Link to this on r/firefox: https://www.reddit.com/r/firefox/comments/omcyby/

**Comment by ojaha065** [comment]
Pretty interesting situation.

As far as I understand, `browser.proton.enabled` still worked in Firefox v89 and some people set it to `false` to disable Proton UI. In the current version of Firefox, Proton can no longer be disabled but having `browser.proton.enabled` set to `false` still unsets `-moz-proton` which is used in the wrapping @​media rule of [userChrome.css](https://github.com/black7375/Firefox-UI-Fix/blob/master/userChrome.css#L1). And thus Lepton style won't be applied if the user has previously changed that browser setting.

To fix this, the wrapping @​media rule could be removed ofc, but wouldn't that cause issues if someone installs Lepton in older version of FF? Maybe the easiest and most user friendly solution would be to set `browser.proton.enabled` to `true` in [user.js](https://github.com/black7375/Firefox-UI-Fix/blob/master/user.js)?

**Comment by black7375** [comment]
> To fix this, the wrapping @​media rule could be removed ofc, but wouldn't that cause issues if someone installs Lepton in older version of FF? Maybe the easiest and most user friendly solution would be to set `browser.proton.enabled` to `true` in [user.js](https://github.com/black7375/Firefox-UI-Fix/blob/master/user.js)?

I think this way is good too
