### ISSUE TITLE
Space beteen pinned tabs

### ISSUE THREAD

**Issue by BPower0036** [black7375/Firefox-UI-Fix#128]
**Describe the bug**
When you have 3 or more pinned tabs the space between those is normal, but when open so many tabs that you see the scrollboxes the space between de 2nd, 3rd, and so on is expanding.
You can see the problem even better when you add the following code, which I uses to get a microsoft edge look:
`.tabbrowser-tab[first-visible-tab="true"] {
  padding-left: 7px !important;`
}`

**Expected behavior**
The space remains the same

**Screenshots**
Only your code:
![afbeelding](https://user-images.githubusercontent.com/80090789/126105416-db50ca5f-63ab-4c2f-8e72-03975e972505.png)
![afbeelding](https://user-images.githubusercontent.com/80090789/126105425-8a40ae56-af5b-4e81-a755-38695cb3bd29.png)
With my code to see it better.
![afbeelding](https://user-images.githubusercontent.com/80090789/126105452-cd9e9110-b421-44f0-9bd6-079a32d179ef.png)
![afbeelding](https://user-images.githubusercontent.com/80090789/126105453-671ad559-8ff9-415c-9500-ca9f4cd87f78.png)

**Environment (please complete the following information):**
Check like `- [x]`.
 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
 - Firefox Version: [`90.0`]
 - OS:
   - [ ] Linux
   - [x] Windows 10
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [x] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

**Additional context**
The problem did occur after Firefox updated to version 90

**Comment by black7375** [comment]
I did investigate, but there was no margin in the middle.
What looks like space is the space for scrolling button.

**Comment by BPower0036** [comment]
But as you can see in my screenshots the space between that pinned tabs is clearly expanding, it is not only the space for the scrolling button.
> **Screenshots**
> Only your code:
> ![afbeelding](https://user-images.githubusercontent.com/80090789/126105416-db50ca5f-63ab-4c2f-8e72-03975e972505.png)
> ![afbeelding](https://user-images.githubusercontent.com/80090789/126105425-8a40ae56-af5b-4e81-a755-38695cb3bd29.png)

**Comment by black7375** [comment]
I tried it again, and it's possible.
```css
/* Space between Pinned tab and Scroll button */
  #scrollbutton-up,
  #scrollbutton-down,
  .scrollbox-clip,
  #TabsToolbar-customization-target > #tabbrowser-tabs[overflow] ~ .toolbarbutton-1 {
    transform: translateX(-2px) !important;
  }
```

However, there is a trade-off.
In tab scroll mode, the empty space(`.titlebar-spacer[type="post-tabs"]`) on the right side becomes larger.
And it's not possible to dynamically adjust it with CSS.

**Comment by BPower0036** [comment]
If that space occurs after the last tab and new tab button,
your solution is in my opinion better.
> ```css
> /* Space between Pinned tab and Scroll button */
>   #scrollbutton-up,
>   #scrollbutton-down,
>   .scrollbox-clip,
>   #TabsToolbar-customization-target > #tabbrowser-tabs[overflow] ~ .toolbarbutton-1 {
>     transform: translateX(-2px) !important;
>   }
> ```

**Comment by black7375** [comment]
I will make it around `-1.5px` and reflect it in the next release.
