### ISSUE TITLE
Could we disable the new sliding animation in the top right corner menu?

### ISSUE THREAD

**Issue by highbaser** [black7375/Firefox-UI-Fix#13]
Hi,

Could we add this to the `:root` section of your userChrome.css?
`--panelui-subview-transition-duration: 1ms !important;`
```
diff --git a/userChrome.css b/userChrome.css
index 30172b6..bc259b0 100644
--- a/userChrome.css
+++ b/userChrome.css
@@ -15,6 +15,8 @@
     --arrowpanel-menuitem-margin: 0 var(--arrowpanel-menuicon-padding) !important; /* Original: 0 8px */
     --arrowpanel-menuitem-padding: 5px !important; /* Original: 8px */
     --arrowpanel-padding:        0.8em !important; /* Original: 16px or .cui-widget-panel, .cui-widget-panel::part(arrowcontent) => 4px 0 */
+
+    --panelui-subview-transition-duration: 1ms !important; /* Disable top right corner menu sliding animation (0ms will not work!) */
   }
 
   :root[uidensity=compact] {
```
I just don't want to have an annoyingly animating smartphone UI in the top right corner menu. Unfortunately the sliding animation can neither be turned off by setting the OS preference regarding animations, nor by any other option as it's hardcoded into browser.css (within browser/omni.ja).

Thanks.

**Comment by black7375** [comment]
**As a result of checking:**
It is not usually appropriate to remove the animation because it exists in both `Photon` and `Proton`.

But I added it because I thought it was a good tip to enter the wiki.
https://github.com/black7375/Firefox-UI-Fix/wiki/Tips#remove-panel-animation
