### ISSUE TITLE
right-click context-menu icons

### ISSUE THREAD

**Issue by sean1138** [black7375/Firefox-UI-Fix#130]
not sure if these are already on the radar, didn't see any open issues that looked relevant.

"loop" and "watch in picture-in-picture" don't have icons when right-clicking a video:
![image](https://user-images.githubusercontent.com/6720184/126653155-85af4bec-c39d-4b4c-98f6-649173fd9426.png)

~~when right-clicking a text input "check spelling" text alignment doesn't match the other list items:
![image](https://user-images.githubusercontent.com/6720184/126653691-a2bf8fbd-0689-47bd-abff-30e530336f83.png)
![image](https://user-images.githubusercontent.com/6720184/126653871-7d75b98d-c8bf-4afc-be31-e244aece0b91.png)~~
text alignment can be [fixed in this comment](https://github.com/black7375/Firefox-UI-Fix/issues/130#issuecomment-885002264)

also noticed that the right edge of these context menu icons are colliding with a border/edge.
![image](https://user-images.githubusercontent.com/6720184/126660077-2fe6f608-f583-4961-aedd-8ee0c566ef17.png)
adding `!important` to this rule seems to fix the border collision at right of icons:
`--context-menu-background-padding: var(--context-menu-background-padding-default) !important;`
![image](https://user-images.githubusercontent.com/6720184/126660338-a4827334-c657-4d8f-8815-55f12e24aae5.png)
also missing a redo icon in the context menu - could just mirror or flip the undo icon horizontal.

will update if i find more.

**Comment by black7375** [comment]
It's a windows 7?
I need to reconfigure the VM environment, so I will recreate it on the weekend.

**Comment by sean1138** [comment]
![image](https://user-images.githubusercontent.com/6720184/126663864-c1eeb5e8-85a7-4f19-9d07-c55172c068bb.png)
disabling this rule seemed to fix my text alignment in the right-click context menus.
![image](https://user-images.githubusercontent.com/6720184/126663891-e8a1d359-6731-4735-a79f-3de1e6b268c5.png)
userChrome.css rule disabled:
```
:not(menu, #ContentSelectDropdown, #context-navigation) > menupopup > menuitem:not(.menuitem-iconic, [type="checkbox"], .in-menulist),
    :not(menu, #ContentSelectDropdown, #context-navigation) > menupopup > menu:not(.menu-iconic, [type="checkbox"], .in-menulist),
    #blockedPopupDontShowMessage {
      padding-inline-start: calc(var(--context-menu-background-padding) + var(--context-menu-text-padding)) !important;
    }
```
disabling that rule makes a rule a few lines before it take effect (line 1121 in my file) giving me what looks to be the correct text alignment.
![image](https://user-images.githubusercontent.com/6720184/126664756-85f5baf5-c463-427f-a25c-3ec222dd5fa9.png)

**Comment by sean1138** [comment]
disabling the padding-inline-start here brings everything into alignment with my ublock origin addon icon in the context menu.
```
:not(menu, #ContentSelectDropdown, #context-navigation) > menupopup > menuitem,
  :not(menu, #ContentSelectDropdown, #context-navigation) > menupopup > menu,
  #blockedPopupDontShowMessage {
    background-position: left var(--context-menu-background-padding) center !important;
    padding-inline-start: var(--context-menu-background-padding) !important;
  }
```
![image](https://user-images.githubusercontent.com/6720184/126666806-ba95aad9-8a25-41f6-aaaf-f2ba90ea0ee5.png)

![image](https://user-images.githubusercontent.com/6720184/126666838-e122fc1e-d80d-420a-8314-5a8c44f6d96d.png)

**Comment by sean1138** [comment]
this issue was supposed to be just for the missing icons, sorry about that.
probable fix for text alignment and padding for win7:
```
/* Padding - Windows 7 */
  @media (-moz-os-version: windows-win7 ){
    :root {
      /*--context-menu-background-padding: 1em;*/
      --context-menu-text-padding: calc(var(--menu-padding) + var(--context-menu-background-padding-default) + 16px);
    }

    :not(menu, #ContentSelectDropdown, #context-navigation) > menupopup > menuitem,
    :not(menu, #ContentSelectDropdown, #context-navigation) > menupopup > menu,
    #blockedPopupDontShowMessage {
      background-position: left var(--context-menu-background-padding) center !important;
      padding-inline-start: 0 !important;
    }

    :not(menu, #ContentSelectDropdown, #context-navigation) > menupopup > menuitem:not(.menuitem-iconic, [type="checkbox"], .in-menulist),
    :not(menu, #ContentSelectDropdown, #context-navigation) > menupopup > menu:not(.menu-iconic, [type="checkbox"], .in-menulist),
    #blockedPopupDontShowMessage {
      /*padding-inline-start: calc(var(--context-menu-background-padding) + var(--context-menu-text-padding)) !important;*/
    }

    /* Checkbox */
    :not(menu, #ContentSelectDropdown, #context-navigation) > menupopup > menuitem[type="checkbox"][checked="false"] > .menu-iconic-left {
      padding-inline-start: var(--context-menu-text-padding);
    }
  }

  /* Padding - Windows 8+ */
  @media (-moz-os-version: windows-win8 ),
         (-moz-os-version: windows-win10) {
    :root {
/* code unchanged from here on */
```
screenshot of the code for more context?
![image](https://user-images.githubusercontent.com/6720184/126673057-3152caca-750e-4067-9939-f67471bdfdef.png)
looks correct here with the above added to my userChrome.css file :)
![image](https://user-images.githubusercontent.com/6720184/126673218-7c6f644b-a098-4a20-874e-3d2d6fd575bb.png)

**Comment by black7375** [comment]
Thank you.
I think the code will help. We will add it to the CREDITS list after this patch.

**Comment by black7375** [comment]
Thank you 😍
