### ISSUE TITLE
Download popup window showing dark theme background instead of light theme.

### ISSUE THREAD

**Issue by mibby** [black7375/Firefox-UI-Fix#131]
**Describe the bug**
The downloads popup UI is showing a dark theme background forcefully. Using dev branch as of commit https://github.com/black7375/Firefox-UI-Fix/commit/e969dcd8109c98b38a395cf8bb298db88c207542

Caused by https://github.com/black7375/Firefox-UI-Fix/commit/bbfbbea45cebf48792d05d583f346b3787397f3d#diff-2f47ee8e5f8520c45fa369ed4e435af21b8273494d3d81eaa9b72ed77ca2f635R354-R356

**Expected behavior**
Normal old light theme background behavior in popup background UI.

**Screenshots**
With light theme.
![link](https://i.imgur.com/mIfCZUh.png)

With dark theme.
![link2](https://i.imgur.com/WS4ho3z.png)

**Environment (please complete the following information):**
Check like `- [x]`.
 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
 - Firefox Version: 90.0.2
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [x] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [ ] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

**Comment by black7375** [comment]
Thanks for report!
Modified to reflect only in dark mode.
