### ISSUE TITLE
New tab icon hard to see on hover

### ISSUE THREAD

**Issue by KaBankz** [black7375/Firefox-UI-Fix#132]
**Describe the bug**
When hovering over the new tab button the icon becomes hard to see.

**Screenshots**
![D3yY2REnsK](https://user-images.githubusercontent.com/20971850/127747833-57a39d66-4575-4951-afba-877a4a67d6e3.gif)

**Environment (please complete the following information):**
 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
 - Firefox Version: 91.0b9
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [ ] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

**Comment by black7375** [comment]
Now  fixed

**Comment by mvcoding** [comment]
Unfortunately this messes up the non-hover icon color for me. It's now the default grey instead of white and very hard to see. Environment is the same as above.

![tab](https://user-images.githubusercontent.com/16247136/129010775-58cde5d3-9820-4944-baf0-df43d3223d20.jpg)

**Comment by black7375** [comment]
![Lightmode default](https://user-images.githubusercontent.com/25581533/129029378-18c01373-d985-41dc-bbf9-ae82aef7a5c6.gif)
![Darkmode default](https://user-images.githubusercontent.com/25581533/129029372-5b2cb393-5d5a-4062-b353-2cb3d3b7a8a1.gif)
I confirmed that it was displayed strangely in light mode and fixed it.

**Comment by mvcoding** [comment]
Thanks for the quick fix! Works fine now.
