### ISSUE TITLE
Several height problems and similar issues with Lepton on Linux Mint Cinnamon

### ISSUE THREAD

**Issue by DarthCaesium** [black7375/Firefox-UI-Fix#133]
![Screenshot from 2021-07-20 21-05-29](https://user-images.githubusercontent.com/85497136/128191141-5ece11ba-e3e2-4b14-96da-b38bf9cf2570.png)
![Screenshot from 2021-08-04 14-27-33](https://user-images.githubusercontent.com/85497136/128191145-3be3231a-6d01-445f-bcb6-43d1f715e24f.png)
![Screenshot from 2021-08-04 14-27-59](https://user-images.githubusercontent.com/85497136/128191147-23692abb-f0da-43ad-aa73-28a55537e2b6.png)
![Screenshot from 2021-08-04 14-29-12](https://user-images.githubusercontent.com/85497136/128191148-e18cf44d-e7cc-4b6d-808e-54141930c979.png)
![Screenshot from 2021-08-04 14-29-25](https://user-images.githubusercontent.com/85497136/128191150-ae225910-dd97-4db9-ab52-2ca09bce2d65.png)

**Comment by DarthCaesium** [comment]
It's not Lepton's Photon Style.

**Comment by DarthCaesium** [comment]
For the new tab highlight, I figured out that when the title bar is enabled, because I use a separator for the top of the toolbar, I need to push the highlight and the new tab button up by 1 pixel. As for when the title bar is disabled, I figured out that the toolbar needs to be pushed down by 1 pixel. The problem, though, is that doing so doesn't seem to work, as it will stay at the same height.

**Comment by black7375** [comment]
Isn't photon-style?
Tab shape looks like a photon-style.

**Comment by DarthCaesium** [comment]
It is customised to be Photon-like. I actually installed the Original Lepton style rather than Lepton's Photon style.

**Comment by black7375** [comment]
Adjusting the layout so it doesn't break is quite tricky.
I recommend using the official distribution.

If you want to customize it yourself, please refer to the photon-style code.
https://github.com/black7375/Firefox-UI-Fix/tree/photon-style

**Comment by DarthCaesium** [comment]
I myself chose Lepton's Original Style because I wanted the added favicons and the other good parts of Proton and combine it with the good parts of Photon. So, my choices require the Original Style rather than Photon Style.
