### ISSUE TITLE
PDF Reader Broken

### ISSUE THREAD

**Issue by qingxiang-jia** [black7375/Firefox-UI-Fix#134]
**Describe the bug**
After applying the theme, the PDF reader is broken.

**Expected behavior**
The PDF reader works.

**Screenshots**
![image](https://user-images.githubusercontent.com/5571586/128257887-468206ad-733a-4443-910f-96642f1e9bed.png)

**Environment (please complete the following information):**
Check like `- [x]`.
 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: [write from `about:support` - `version`]
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [x] Light
   - [x] Dark
   - [x] Alpenglow(System: Light)
   - [x] Alpenglow(System: Dark)
   - [x] System Default
     - GTK Theme Name(Only Linux User): Gnome-professional-40.1

**Additional context**
When using the default theme, the PDF reader is not broken.

**Comment by black7375** [comment]
Now fixed.
Thanks for your report!!

**Comment by qingxiang-jia** [comment]
Thank you for fixing it so quickly!
