### ISSUE TITLE
`install.ps1` not working

### ISSUE THREAD

**Issue by 7k5x** [black7375/Firefox-UI-Fix#135]
**Describe the bug**
`install.ps1` does not install properly, and Firefox's appearance does not change.
Tested both on Powershell version 7 and 5, and they give out the exact same results.

**Screenshots**
![image](https://user-images.githubusercontent.com/85086136/128289115-eb0772de-79ff-49cf-8358-d429200431da.png)

**Environment (please complete the following information):**
 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] Firefox Nightly
 - OS:
   - [x] Windows
 - Theme:
   - [x] System Default
**Additional context**

**Comment by 7k5x** [comment]
The syntax is now correct, but it still doesn't install the theme and doesn't give an option to install. Am I the only one that's having this issue?

**Comment by black7375** [comment]
Found some more issue and fixed it.

**Comment by black7375** [comment]
Now it will be work!!

**Comment by 7k5x** [comment]
![image](https://user-images.githubusercontent.com/85086136/128878370-97b32f4f-7fcf-46c9-a111-d9f1a7a755b6.png)
Hmm..?

**Comment by black7375** [comment]
One parenthesis is missing.

**Comment by 7k5x** [comment]
![image](https://user-images.githubusercontent.com/85086136/128884776-f716a978-6ecd-41cf-93b2-53ec0298e2a0.png)

**Comment by black7375** [comment]
Hmm.. well work on my pc

![Install with powershell](https://user-images.githubusercontent.com/25581533/128889698-e39c34cb-27ac-4172-a4ee-b317b3701856.gif)

**Comment by 7k5x** [comment]
I guess it's only me..
