### ISSUE TITLE
Tab rounded corners look weird in compact

### ISSUE THREAD

**Issue by thebigsmileXD** [black7375/Firefox-UI-Fix#138]
**Describe the bug**
The bottom corners aren't the same as the top corners. 
On light theme, they don't seem to be rounded at all, so i am not too sure which one is intended
**Expected behavior**
Corners being same in light/dark mode and look smoother/less warped

**Screenshots**
![Edge vs FireFox, using compact mode](https://user-images.githubusercontent.com/8733998/128845426-014e23b7-256c-4f05-ad36-1a0afcd67651.png)
![Light mode](https://user-images.githubusercontent.com/8733998/129389842-d6dba35f-a9fd-470a-b7f6-d6183f223001.png)

**Environment (please complete the following information):**
Check like `- [x]`.
 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [x] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: [write from `about:support` - `version`]
Version 	91.0b9
Build ID 	20210729185755
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow(System: Light)
   - [x] Alpenglow(System: Dark)
   - [x] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

**Additional context**

**Comment by black7375** [comment]
![image](https://user-images.githubusercontent.com/25581533/129480451-03cdd9ff-88a7-492b-b30e-f0c5e260590d.png)
Added  bottom rounded corner at system light mode.
The original intention was to only exclude the GTK theme for Linux. (technical issue)

---
If you want to remove rounding, please remove to the following lines.
https://github.com/black7375/Firefox-UI-Fix/blob/f9781f9c26e2e805ab4848f5fd30d00288fff2d6/userChrome.css#L789-L831
