### ISSUE TITLE
Transparent menu-bar menus on custom themes

### ISSUE THREAD

**Issue by hdk5** [black7375/Firefox-UI-Fix#140]
**Describe the bug**
Menu-bar menus are too hard to see on themes other than default ones.

**Expected behavior**
Menus are not transparent and have solid white background.

**Screenshots**
Light - OK:
![image](https://user-images.githubusercontent.com/2550010/128937724-c37d4203-ff47-4a60-8e78-c8f9fc9f4176.png)

Firefox Alpenglow - too transparent:
![image](https://user-images.githubusercontent.com/2550010/128937774-20207bea-d378-41fa-af3c-7dfa8e97fdec.png)

[Dream of Waves](https://addons.mozilla.org/en-GB/firefox/addon/dream-of-waves/) - even more transparent
![image](https://user-images.githubusercontent.com/2550010/128937793-247bf06f-7407-4cbf-b574-66a12ce49670.png)

**Environment (please complete the following information):**
Check like `- [x]`.
 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 91.0
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [x] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [ ] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

**Additional context**

**Comment by hdk5** [comment]
Also, an address bar has a similar issue

![image](https://user-images.githubusercontent.com/2550010/128946125-33a78aea-d003-41f2-a518-f41f98128a4f.png)

**Comment by black7375** [comment]
![image](https://user-images.githubusercontent.com/25581533/129036581-3d0fc215-1cc8-4c03-9dab-ccb4411e895b.png)
Perhaps it has been fixed now.
