### ISSUE TITLE
Pull-down menu padding: reduce it further

### ISSUE THREAD

**Issue by b1k3rdude** [black7375/Firefox-UI-Fix#142]
I started using this UI fix  with FF 89.0 and it worked perfectly, but since FF 91.0 the vertical padding has increased. I have gone for the Lepton install, but could not see the option or where I choose the compact-fix in the install instructions.

Either a fix to the package for the compact option, or where I can manually edit the 'userchrome.css' to reduce the padding/spacing between the lines of text.

I have looked through the 'userchrome.css files but dont seem to be able to find an option that I can understand.

**Comment by black7375** [comment]
Do you mean this menu?
![image](https://user-images.githubusercontent.com/25581533/129030206-d6af0503-9059-4781-be52-dcd915c508a7.png)

**Comment by b1k3rdude** [comment]
Hello

Yes, but ALL of the pull down menu's. So File, Edit, View, History, Bookemarks, Tools and Help. Then Links and Application menu.

Since posting the above request I enabled compact density in customize option which reduced the padding a tiny bit more, but not to the same levels are your setting/s under FF 98.

**Comment by b1k3rdude** [comment]
Can I add context menu's to this request also please.

**Comment by ririliu** [comment]
you can find this code in  userchrome.css

 :root {
    --menu-padding: 0.35em;
  }

change it to 0.25em or lower will reduce the menu padding

**Comment by black7375** [comment]
It will come out with reduced padding in V4.0.

**Before**
![image](https://user-images.githubusercontent.com/25581533/131251929-266c2c5f-1d24-43b0-992e-114084aa8247.png)

**After**
![image](https://user-images.githubusercontent.com/25581533/131251919-82167e72-a5fd-45da-a315-a0b0e38d44d8.png)

**Comment by b1k3rdude** [comment]
@black7375 thank you :-)
