### ISSUE TITLE
Windows 7 White/Dark (Min/Max/Close Buttons)

### ISSUE THREAD

**Issue by QNetITQ** [black7375/Firefox-UI-Fix#143]
Hi. If you have a Mac, I can help you slightly optimize the style through PR, but I will ask for one favor in return. You just need to try a few styles on Mac and take a screenshot of the result. Interested?

**Comment by black7375** [comment]
I use [Docker-OSX](https://github.com/sickcodes/Docker-OSX) for Mac support.
I'll try it on the weekend.

Style suggestions are welcome!!

**Comment by QNetITQ** [comment]
That is, transparency does not function there at all?

**Comment by black7375** [comment]
> That is, transparency does not function there at all?

Not entirely. But I'm sure the Blur effect isn't working.

**Comment by QNetITQ** [comment]
Windows 7 White-Dark bug
![изображение](https://user-images.githubusercontent.com/85301851/129055220-5d05a394-272f-405f-a3b5-89f7addc8fbc.png)
![изображение](https://user-images.githubusercontent.com/85301851/129055316-b18b05a4-3c44-40ea-8682-0406d5570845.png)
Min/Max/Close Buttons

**Comment by QNetITQ** [comment]
New tab button deforms in windowed mode
![изображение](https://user-images.githubusercontent.com/85301851/129056250-b3ad7325-eceb-4a77-b7db-3c7f3370cc12.png)
![изображение](https://user-images.githubusercontent.com/85301851/129056285-1bc3414c-862a-44c2-9252-c1bcb7f86261.png)

 I'll take care of that
