### ISSUE TITLE
v3.0.0 higher contrast light mode doesn't apply

### ISSUE THREAD

**Issue by ildiem** [black7375/Firefox-UI-Fix#144]
**Describe the bug**
The light mode theme doesn't use the new, higher contrast background color shown in #24 , instead retaining the old background color.

**Expected behavior**
The background color would be `#E5E5EB` or `rgb(229, 229, 235)`.

**Screenshots**
![Screen Shot 2021-08-11 at 12 36 02 PM](https://user-images.githubusercontent.com/81544216/129068545-55bc4379-ef1d-4094-b8cf-f3c37a3704be.png)
![Screen Shot 2021-08-11 at 12 36 50 PM](https://user-images.githubusercontent.com/81544216/129068548-6ef4c66f-b281-43e6-bc0f-5ca19dcbc1f5.png)
See attached. Pointer doesn't show up but I guarantee I was highlighting the correct areas of the screen.

**Environment:**
 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: [write from `about:support` - `version`]
 - OS:
   - [ ] Linux
   - [ ] Windows
   - [x] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [x] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

**Additional context**
Running Firefox 91.0

**Comment by black7375** [comment]
It may only happen on Mac.
I have confirmed that it works on Linux and Windows.
![image](https://user-images.githubusercontent.com/25581533/129121962-51193b5e-4ebf-4653-8fd5-3860492287fd.png)

**Comment by black7375** [comment]
Fortunately, it was reproducible after testing.

**Before**
![image](https://user-images.githubusercontent.com/25581533/129481251-72c2c2bf-f83d-4643-a6d1-6efd9090a5b1.png)
- `#F0F0F0`

**After**
![image](https://user-images.githubusercontent.com/25581533/129481216-90401ef6-bc62-4a60-84d9-0db5b1dae7f7.png)
- `#E5E5EB`

**Comment by ildiem** [comment]
The bug seems to only be partially fixed in v3.1.0. The higher-contrast light theme applies when light mode is selected, but not when system theme is.


https://user-images.githubusercontent.com/81544216/129595334-4c354daf-4ddc-4656-aa54-04307ca5645c.mov

**Comment by black7375** [comment]
I don't have an environment to test on right now, so it will take some time to reproduce.

**Comment by black7375** [comment]
![image](https://user-images.githubusercontent.com/25581533/130349699-4d31440c-6673-4f73-8fc1-bfb5dcb87068.png)
![image](https://user-images.githubusercontent.com/25581533/130349722-3d0968a4-2fac-430d-b41c-277f5ed32819.png)
I recently had to configure Mac VM and I fixed it.

**Comment by ildiem** [comment]
Thanks for the fix!
