### ISSUE TITLE
Favicons not aligned on Windows 7

### ISSUE THREAD

**Issue by g-2-s** [black7375/Firefox-UI-Fix#145]
![Untitled](https://user-images.githubusercontent.com/54694327/129070123-3468c3d5-ce1f-4b83-8b02-ed8fb5c7a1b6.png)

Hi, latest update made favicons slightly misaligned on Windows 7, any way to fix this?

**Comment by black7375** [comment]
![image](https://user-images.githubusercontent.com/25581533/129455101-0422faa9-2e45-43cf-98b7-61a035247536.png)
Fixed now!!

And.. win7 dedicated theme has been improved!! #164
