### ISSUE TITLE
Don't seem to be able to install

### ISSUE THREAD

**Issue by Alice-Cheshire** [black7375/Firefox-UI-Fix#147]
**Describe the bug**
I'm having two separate issues, though the other is either an issue with Firefox itself or a user error that I'm just not catching. The first is that manually setting up a userchrome.css file doesn't seem to do a thing. After having tried to install Lepton that way I tried navigating to my profile and running install.ps1 manually from powershell (ran as an administrator) but it just errors out.

**Expected behavior**
I would expect it to actually install.

**Screenshots**
[https://i.imgur.com/eUMLlaG.png](https://i.imgur.com/eUMLlaG.png)
![image](https://user-images.githubusercontent.com/25581533/129214114-75b7f17b-689e-480a-b01d-ac0a69b5a15c.png)

**Environment (please complete the following information):**
Check like `- [x]`.
 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 91.0
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [x] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [ ] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

**Additional context**
I've never used a userchrome file before and have little experience with powershell so I have no idea if this is a user error or what. Starting to think it would just be less effort to switch over to Vivaldi and drop Firefox. I shouldn't have to put in this amount of effort just to change Firefox's appearance back to one that doesn't completely suck.

**Comment by black7375** [comment]
The currently recommended way is to use the following command:
`Powershell -c "iwr https://raw.githubusercontent.com/black7375/Firefox-UI-Fix/master/install.ps1 -useb | iex"`

Doesn't it work?

**Comment by Alice-Cheshire** [comment]
> 
> 
> The currently recommended way is to use the following command:
> `Powershell -c "iwr https://raw.githubusercontent.com/black7375/Firefox-UI-Fix/master/install.ps1 -useb | iex"`
> 
> Doesn't it work?

That gives me this error:
[https://i.imgur.com/YCpuK2X.png](https://i.imgur.com/YCpuK2X.png)

**Comment by black7375** [comment]
It can be resolved with install windows updates & dotnet runtime.
https://github.com/black7375/Firefox-UI-Fix/wiki/Compatibility-Issues-Solution#windows-7-powershell-script-not-works
