### ISSUE TITLE
Inactive tabs don't use Firefox theme on Windows 8.1

### ISSUE THREAD

**Issue by MrNukealizer** [black7375/Firefox-UI-Fix#149]
On Windows 8.1, both the Proton and Photon versions leave inactive tabs looking like this:
![Capture](https://user-images.githubusercontent.com/1545777/129110366-12ff059c-3ebc-4c3b-9f26-55f1ab934079.PNG)

The actual Photon UI always had inactive tabs look like the main theme rather than the title bar. On the other hand the Proton UI always had this problem which is why I instantly turned it off and now installed this looking for a fix. It would be nice if the inactive tabs would have the color scheme of the rest of Firefox like they used to, but even making the text color respect the Windows theme like the title bar so it's readable would be a big improvement.

**Comment by black7375** [comment]
Now works well!!

Default Theme
![image](https://user-images.githubusercontent.com/25581533/129446238-98362a13-6006-46ec-8357-abbb61b899b8.png)

Light Theme
![image](https://user-images.githubusercontent.com/25581533/129446288-f26c7538-4bd1-452e-8f5b-214225ee9f6f.png)

Dark Theme
![image](https://user-images.githubusercontent.com/25581533/129446362-250d7244-751a-46de-ae38-9b62358c9139.png)

**Comment by nbmrjuhneibkr** [comment]
Nothing has been fixed in https://github.com/black7375/Firefox-UI-Fix/tree/photon-style yet.
The issue has been reported for all variants of Lepton:
>both the Proton and Photon versions

**Comment by black7375** [comment]
I will be working on a release after  Monday, and it will be fixed in batches.
