### ISSUE TITLE
Update README.org to be more readable

### ISSUE THREAD

**Issue by TurtleDino** [black7375/Firefox-UI-Fix#15]
Love the project, however, in order to become more user-friendly, can you please update the project's README.org file to become more readable?

For instance:
1. Put a space between Lepton and (old name...) "Lepton(old name: Proton Fix)"
2. Capitalize the words "proton" and "firefox" in "proton is firefox's new design."
3. Include a section of why Lepton/Photon is needed (just explain in words)
4. Include spaces in "If you prefer Photon(88 or earlier)..."

These are just minor issues. All-in-all the project is already good, I just wanted to suggest some cleanup to the README.org to make it easier to read for newcomers.

**Comment by black7375** [comment]
Yes. I will apply it as soon as I start working in the morning.

Some screenshots will be updated as well.

good advice

**Comment by black7375** [comment]
I've been updating it. How about it?

**Comment by TurtleDino** [comment]
This is awesome! Yeah this works.
