### ISSUE TITLE
Scrollbtn-border-radius

### ISSUE THREAD

**Issue by Gaurav-Original-ClassicShellTester** [black7375/Firefox-UI-Fix#151]
Hello. With MANY tabs open, left-right scroll buttons appear in Firefox but even with your fix, a click in top left corner of screen/left edge of screen does nothing.

I change scrollbtn-border-radio to 0:
```
    --scrollbtn-border-radius:    0px;
```

This fixes it. Left-top hot corner left scroll button now correctly scrolls left.

Thank you for your fixes.

**Comment by black7375** [comment]
That's weird. It doesn't show up on my computer.

**Comment by black7375** [comment]
Close because there have been no additional issues for a long time.
