### ISSUE TITLE
Installation script problem

### ISSUE THREAD

**Issue by magillos** [black7375/Firefox-UI-Fix#152]
**Describe the bug**
Linux installation script creates 'chrome' directory inside the existing 'chrome' directory and then it puts its files in there making the changes not applying. 'chrome' directory has to be removed manually each time.

**Expected behaviour**
'chrome' directory should be recreated and files should go there. 

**Environment**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [x] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: [91.0]
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [x] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [x] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

**Comment by Jonta** [comment]
Fix before the proper fix:

Move files from /chrome/chrome/ to /chrome

Remember the .git*-files. Then you can `rmdir` the /chrome/chrome directory

**Comment by magillos** [comment]
Yes, manual fix is easy enough. I just wanted to report the issue in case someone else struggles with it. Cheers.

**Comment by black7375** [comment]
I modified the `autocp` function.
It's a minor bug, but it could affect a lot of people.
