### ISSUE TITLE
[Photon] Tab/title bar and toolbar changes height depending on the number of open tabs

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [black7375/Firefox-UI-Fix#154]
**Describe the bug**
With Lepton (Photon style) installed, the height of the tab/title and toolbar changes if I open enough tabs (~30) to make the tab bar scrollable.

**Expected behavior**
Height should stay the same under any conditions, as seen in original Photon (Firefox 78).

**Screenshots**
![2](https://user-images.githubusercontent.com/8460563/129238689-6b9771d3-b768-407f-8c88-26cdf4b2a4dc.png)

**Environment (please complete the following information):**
 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 91.0
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [x] System Default

**Additional context**
Tested normal and compact mode
Windows 10 1809
Windows UI scaling set to 125%
It's possible that this issue also affects other configurations

**Comment by nbmrjuhneibkr** [comment]
Did some additional testing on Windows 8.1 with 100% UI scale.
The issue is present in both modes.
![1](https://user-images.githubusercontent.com/8460563/129297300-0bc94feb-25e0-4b83-8f19-8f2d3fad30c2.png)

Also, it seems like here compact mode takes up more vertical space when compared to original Photon, while on Windows 10 with 125% it was smaller than original (with small number of tabs, at least). This needs to be consistent across platforms (and maybe also consistent with original Photon).

**Comment by black7375** [comment]
On Linux, this patch seems to work.

**Comment by black7375** [comment]
Also confirmed on Windows.

**Comment by nbmrjuhneibkr** [comment]
Can confirm that it's fixed.
However, toolbar height still doesn't match original Photon in neither of the examples, and the difference is inconsistent depending on the OS and UI scale:
![10](https://user-images.githubusercontent.com/8460563/129660746-34332ba5-c73d-45ac-ad57-7e67d09ed274.png)
![8](https://user-images.githubusercontent.com/8460563/129660739-ab17947b-aa7c-4d5e-90ee-66b89d08ae1f.png)
