### ISSUE TITLE
Multi containers colors

### ISSUE THREAD

**Issue by 3qrf4g** [black7375/Firefox-UI-Fix#156]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
there is no problem

**Describe alternatives you've considered**
there is no problem

**Additional context**
is it possible to give more options for the multi containers colors? I like it to be extended and cover the whole tab just like the old theme design before 89, my screen is small, and I can't see it very well.

Besides that, thank you so much for this theme.

**Comment by black7375** [comment]
I remember having a similar request in the past. #23
I was going to do it later, but I forgot.

I've added it to the 4.0 plan and we'll be looking for alternatives. #150
We will discuss it further in #23.
