### ISSUE TITLE
Context menu is white-on-white colors in both light and dark themes

### ISSUE THREAD

**Issue by Floirt** [black7375/Firefox-UI-Fix#157]
**Describe the bug**
I installed the photon style Lepton a few hours ago after my Firefox updated to 91, and my right click context menus are this horrible white on white background, font and icons. I use light mode but switching to dark mode had the same result.

**Expected behavior**
A right click menu with black icons and font on a white background, or the opposite for dark theme.

**Screenshots**
https://i.imgur.com/nAvZzsu.png
![image](https://user-images.githubusercontent.com/6320256/129281501-66491eb3-b3ed-4a4b-a241-b80e70caf4dc.png)
https://i.imgur.com/UJpRuUc.png
![image](https://user-images.githubusercontent.com/6320256/129281512-b4996be7-67d3-4c95-a1b0-d0006ccd899a.png)

**Environment (please complete the following information):**
Check like `- [x]`.
 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: [write from `about:support` - `version`]
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [x] Light
   - [x] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [ ] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

**Additional context**
I tried commenting out line 271 in userChrome.css as mentioned in #140 and I just get a dark theme context menu instead, which is helping for now.

https://i.imgur.com/ANezO5K.png
![image](https://user-images.githubusercontent.com/6320256/129281570-0e920b9b-53bf-46d5-b585-5ff41466de21.png)

**Comment by black7375** [comment]
Could you test like this?
https://github.com/black7375/Firefox-UI-Fix/issues/136#issuecomment-898493875

**Comment by black7375** [comment]
![image](https://user-images.githubusercontent.com/25581533/129527443-fbd5edde-2a90-48fb-89dc-82c0c8be6eef.png)
https://www.reddit.com/r/FirefoxCSS/comments/p2ee0v/lepton_30_released/h94m16c/?context=3

Improved compatibility between themes.
