### ISSUE TITLE
Misaligned context menus on Windows 8.1

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [black7375/Firefox-UI-Fix#158]
**Describe the bug**
All context menus (page, tabs, toolbar) appear to be misaligned with Lepton (Photon style) v3.0 on Windows 8.1.

**Screenshots**
![3](https://user-images.githubusercontent.com/8460563/129297814-6fd9bbdb-d11e-4c4d-b88f-b1788d22de09.png)

**Environment:**
 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 91.0
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [x] System Default

**Additional context**
Default (100%) Windows UI scale
I have not encountered this issue on Windows 10 with 125% scaling
I don't know if this issue also affects other branches of Lepton

**Comment by nbmrjuhneibkr** [comment]
It may be related to https://github.com/black7375/Firefox-UI-Fix/issues/145 (although it looks way worse than that one).

**Comment by nbmrjuhneibkr** [comment]
Oh, and it appears to be identical to https://github.com/black7375/Firefox-UI-Fix/issues/130 (but that issue was supposed to be fixed already).

**Comment by black7375** [comment]
I changed it like win7.
I think it will work, but I'm not sure.
Test please!!

**Comment by black7375** [comment]
![image](https://user-images.githubusercontent.com/25581533/129444565-1e7ac883-3b54-4f54-8861-ec0e056b5518.png)
Confirmed to be fixed.

**Comment by nbmrjuhneibkr** [comment]
Still broken for me.
Commit https://github.com/black7375/Firefox-UI-Fix/commit/cdc12c8330e7ed6540b5599d550e89a9fbc9c6ab is not present in the https://github.com/black7375/Firefox-UI-Fix/tree/photon-style branch.

**Comment by black7375** [comment]
Yes. It will be corrected in the future. https://github.com/black7375/Firefox-UI-Fix/issues/149#issuecomment-899011060

**Comment by Hapax96** [comment]
It is now fixed for me on Windows 8.1, thank you! In the settings I now also see all icons instead of just a few, also cool. :)

**Comment by nbmrjuhneibkr** [comment]
Can confirm that it's fixed with v3.1.0.

**Comment by Hapax96** [comment]
For me it is now also fixed on Windows 8.1. Thanks!
