### ISSUE TITLE
The problem with shadows

### ISSUE THREAD

**Issue by AntonZur** [black7375/Firefox-UI-Fix#160]
**Describe the bug**
Take a look at the screenshots. Pay attention to the strokes and shadows in the menu of the "Bookmarks" icon and folders in the Bookmarks Bar.

**Screenshots**
![0001](https://user-images.githubusercontent.com/88890316/129362562-3766ebab-8361-491e-99e5-923e7f74edca.jpg)
![002](https://user-images.githubusercontent.com/88890316/129362587-1a8069d5-b96a-4f1e-9dc3-d14b930da547.jpg)

**Environment (please complete the following information):**
Check like `- [x]`.
 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [x] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 93.0a1
 - OS:
   - [ ] Linux
   - [x] Windows 10
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [x] Light
   - [x] Dark
   - [x] Alpenglow(System: Light)
   - [x] Alpenglow(System: Dark)
   - [x] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

**Comment by black7375** [comment]
It has been mentioned in #136
Restoring the old settings had the #140 issues, so I fixed it after some testing.

Check this commit!!
https://github.com/black7375/Firefox-UI-Fix/commit/425d4e51984b3954ac62678630dbffdec29f4409
