### ISSUE TITLE
THANK YOU

### ISSUE THREAD

**Issue by animalillo** [black7375/Firefox-UI-Fix#162]
Just thank you, I can't express how much I want to thank you, i just can't stand the new firefox design and i wanted to some how thank you :)

**Is your feature request related to a problem? Please describe.**
In a way, it is, but the problem is with firefox itself, your design is better

**Describe the solution you'd like**
Your design is better

**Describe alternatives you've considered**
-

**Additional context**
Just thank you

Now that i thanked you, you can close this ticket if you wish ;)

**Comment by black7375** [comment]
I want to make a better experience.

Please support us in the future!!
Thank you to everyone who uses my program.
