### ISSUE TITLE
Weird tab behaviour when opening the Customize tab

### ISSUE THREAD

**Issue by Elaborendum** [black7375/Firefox-UI-Fix#163]
**Describe the bug**
The tabs move back and forth when moving the cursor on the "Customize toolbar" tab. Making it hard to close it or other tabs.

1. Pin at least one tab and open new tabs until they change size to accommodate themselves. One less tab than that is needed to replicate this.
2. Right-click the toolbar
3. Click on "Customize Toolbar", a new tab will open
4. Move the cursor anywhere while on the tab, see the movement of the other tabs.

**Expected behavior**
Tabs stay still normally

**Screenshots**

https://user-images.githubusercontent.com/71190696/129426622-4ad45ceb-54d9-49df-85aa-613a38f81728.mp4

**Environment (please complete the following information):**
Check like `- [x]`.
 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: [91.0]
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [ ] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

**Comment by BPower0036** [comment]
Just to let you know that I cannot confirm this issue.

**Comment by remyabel** [comment]
Yep I suffer from this same issue, but on Linux.

**Comment by Elaborendum** [comment]
Something I forgot to mention is that I'm using compact mode.

I've been testing it out a bit, and also realized that:
- It will happen if the customize tab is the one that makes all tabs change their width to accomodate themselves.
- It will happen with any number of tabs going forward, until the following.
- It will happen if the customize tab is the one to activate the option to scroll the tabs. This one is the most inconsistent to me, as it sometimes happens the moment the Customize tab opens, for a few seconds after it closes or doesn't happen at all.
- From then on it doesn't seem to happen with more tabs.

**Comment by 1Phase1** [comment]
I can confirm this issue, and noticed it early on after installing Lepton. I would've made a post like this myself but I didn't know how to word it.

**Comment by black7375** [comment]
This is a temporary solution.
`Bottom rounded corner`'s symmetrical yet neat implementation is very demanding.

**Comment by black7375** [comment]
Close because there have been no additional issues for a long time.
