### ISSUE TITLE
Notification popups are transparent on white themes.

### ISSUE THREAD

**Issue by hdk5** [black7375/Firefox-UI-Fix#165]
**Describe the bug**
Notification popups are transparent and, therefore, unreadable, on white themes.
Problem does not occur on dark themes.

**Expected behavior**
Notification popups background is opaque white.

**Screenshots**
Light theme:
![image](https://user-images.githubusercontent.com/2550010/129460259-e9046019-f989-4d9b-aaa9-46b7615ea13c.png)
![image](https://user-images.githubusercontent.com/2550010/129460260-0beaf4f9-da07-447f-afb8-79df22b31990.png)
Dark theme:
![image](https://user-images.githubusercontent.com/2550010/129460265-65d5db92-8273-408b-a8f5-901abbbec78d.png)

**Environment (please complete the following information):**
Check like `- [x]`.
 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 91.0
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [x] Light
   - [ ] Dark
   - [x] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [ ] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

**Additional context**

**Comment by fhtdtdj** [comment]
Can confirm, ran into the same issue with Photon Style/light.

**Comment by black7375** [comment]
![image](https://user-images.githubusercontent.com/25581533/129479378-588263d0-4120-487d-aa90-064d3ba8b394.png)

Now fixed.
However, it has not been applied to other distributions yet. https://github.com/black7375/Firefox-UI-Fix/issues/149#issuecomment-899011060
