### ISSUE TITLE
Container accent under Tab text in addition to Tab icon [Lepton Photon]

### ISSUE THREAD

**Issue by fourteen-1** [black7375/Firefox-UI-Fix#167]
**Is your feature request related to a problem? Please describe.**
Having it just under the tab icon makes it harder to identify.

**Describe the solution you'd like**
Having it under the tab text as well as the tab icon will make the tab easier to spot out.

**Describe alternatives you've considered**
The above is the best solution for this, since photon uses blue top border to indicate active tab, the container accent has to be the underline (unlike proton's design where active tab accent has been replaced by container accent).

**Additional context**
![firefox_0FfRtzfyEB](https://user-images.githubusercontent.com/73333396/129466759-73e94519-a680-46e0-81ef-616ccbe3d32a.png)

![DFWHObk6a8](https://user-images.githubusercontent.com/73333396/129466763-93ab6369-52da-49b4-85e2-d05d38ea8df1.png)

**Comment by black7375** [comment]
We will deal with serious bugs first and then discuss it in #23.
