### ISSUE TITLE
Radio button missing in back/forward history menu

### ISSUE THREAD

**Issue by acarasimon96** [black7375/Firefox-UI-Fix#168]
**Describe the bug**

In Lepton v3.0.0, there is a blank space next to the current page title on the back/forward history menu.

**Expected behavior**

An active radio button (or circular indicator) would appear next to the current page title, like in older versions of Lepton or vanilla Proton.

**Screenshots**

![image](https://user-images.githubusercontent.com/17580077/129485672-c24607f3-f562-447e-8d2d-f3dbeffdcce6.png)
![image](https://user-images.githubusercontent.com/17580077/129485800-45e56972-f1e3-474a-acf2-4940e609d0c8.png)

**Environment (please complete the following information):**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 91.0.0
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [x] System Default
     - GTK Theme Name(Only Linux User): Materia, Breeze

**Additional context**

This bug affects all items on the history menu, not just the first one, and regardless of which browser theme or density is being used. I'm also certain that this could be reproducible in Windows and macOS (I don't use Firefox in either OS), since changing the GTK theme did nothing to make the radio button appear while Lepton is installed.

I use Manjaro as my Linux distro and KDE Plasma as my desktop environment.

By the way, great job with the hard work putting into this userstyle. I wish Mozilla did a better job with designing Proton, let alone continuing compact mode support, but this project has made my experience with the new UI a lot more manageable.

**Comment by black7375** [comment]
![image](https://user-images.githubusercontent.com/25581533/129511821-52de116a-f03b-44f3-8fd3-61628d3b0c93.png)
Now it should work.
