### ISSUE TITLE
What about the other Page Actions that are lost?

### ISSUE THREAD

**Issue by McBobb** [black7375/Firefox-UI-Fix#169]
I see you said that the Page Snapshot function has moved to the toolbar, but there was a whole lot more that the Page Action menu provided — most importantly, the COPY PAGE URL function. Since Mozilla messed up selecting and copying from the address field, that's been an essential tool that I used many times a day, and now it's just gone; not in the Customization page, not in any menus, not among the tools; just gone; pfft!

Could you add to the userChrome.css file to bring back the rest of the Page Action menu; preferably back where it belongs, on the right side of the address field?

**Comment by black7375** [comment]
Unfortunately, we can't create a new menu with CSS alone.

I also want to restore the page action button and it's on the roadmap. #2
However, the manual installation method becomes very complicated, so I will provide it for advanced users first.

**Comment by sean1138** [comment]
> 
> 
> Since Mozilla messed up selecting and copying from the address field, that's been an essential tool that I used many times a day, and now it's just gone; not in the Customization page, not in any menus, not among the tools; just gone; pfft!
> 

try CTRL+L (should select the page address) then CTRL+C (copies selected address) and see if that works for you.
