### ISSUE TITLE
(Improvement) Don't display profile ending with .default in installation

### ISSUE THREAD

**Issue by 7k5x** [black7375/Firefox-UI-Fix#171]
When you install this project by the script, it shows you the folders, and one of them is a placeholder profile that ends with `.default`.
![image](https://user-images.githubusercontent.com/88917536/129657831-fb2de392-b12c-4104-9321-9d5a0ed051b5.png)
afaik this does nothing. I think deleting this output to avoid confusion could be an improvement.

**Comment by Turmfalke2** [comment]
Please don't. I am using multiple profiles and one of them ends in .default.

**Comment by black7375** [comment]
If so, I won't implement it because it's better to include the exception.

**Comment by Turmfalke2** [comment]
If you want to improve that selection: Is it possible to show the profile label as seen in the profile manager? In addition that is.

**Comment by black7375** [comment]
Do you mean `about:profiles`?
Then I think it works quite similarly.

I just found a nice extension.
- https://github.com/null-dev/firefox-profile-switcher
- https://github.com/null-dev/firefox-profile-switcher-connector

It would be nice to have this built in or integrated.
(However, license for this project may be changed to GPL3)

**Comment by Turmfalke2** [comment]
no. If you start firefox with `--new-instance --ProfileManager` you get to select which profile you want to use, but it shows you a human readable name instead of the hash used for the directory. It would be nice to see that name as well when selecting the profile during installation.

**Comment by black7375** [comment]
Ok, I confirmed.

Memo for UI:
![Screenshot_20210819_173945](https://user-images.githubusercontent.com/25581533/130037443-5f7d63e6-af01-47f1-b7d2-55558ce4709a.png)

**Comment by 7k5x** [comment]
Sorry I didn’t know you could change your profile like that😅

**Comment by Turmfalke2** [comment]
I am not even sure profile names need to be unique, but it might just help in some cases with picking the right one.
