### ISSUE TITLE
[Photon v3.1] System color scheme no longer applies to tab bar on Windows 8.1

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [black7375/Firefox-UI-Fix#172]
**Describe the bug**
Starting with v3.1.0, Photon style ignores Windows 8.1 color scheme. As a result, tab bar with "System default" Firefox theme looks the same as it does with "Light" theme. This also makes it nearly impossible to tell whether or not Firefox window is currently active.

**Expected behavior**
System color should be used for the tab bar when Firefox window is active.

**Screenshots**
![theme](https://user-images.githubusercontent.com/8460563/129659361-f92f8937-6a2d-4349-b8a2-4da659b29e1f.png)

**Environment:**
 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 91.0
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [x] System Default

**Additional context**
This issue does not affect Windows 10. Can't test Windows 7.

Weirdly enough, it's the polar opposite of default Proton behavior: on Windows 8.1 Firefox respects system color, and on Windows 10 it doesn't.

**Comment by sean1138** [comment]
win7 here, screenshot in case makes anything easier, this change doesn't bother me enough to change it back myself so i wasn't going to make an issue for it.  I run with compact and system theme settings.  Previous versions had some semi-transparent aero glass effect whereas 3.1 lepton-photon doesn't.
![image](https://user-images.githubusercontent.com/6720184/129688636-146d6ac5-6127-4392-a671-0628caef88d0.png)

I also noticed in 3.1 that the min/max/close window buttons' left edge get covered a tiny bit, when zooming in to screenshots can see the border effect at left edge is covered up.  when i maximize my browser window (2560 wide monitor) that left border on the buttons is not covered up.
![image](https://user-images.githubusercontent.com/6720184/129688718-cf89cb66-cc13-4a1e-9096-635ded6d4678.png)

**Comment by black7375** [comment]
There was a big mistake related to #144.
![image](https://user-images.githubusercontent.com/25581533/129891509-8ecde525-50c6-4123-84a7-1be59167feba.png)
![image](https://user-images.githubusercontent.com/25581533/129891573-19e09ccf-3090-4e69-9113-fa15a7ec47b8.png)

In `photon-style`(and `proton-style`) branch, I will release various bugs by tomorrow.
