### ISSUE TITLE
Stop displaying "close tab" button on inactive tabs

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [black7375/Firefox-UI-Fix#173]
**Is your feature request related to a problem? Please describe.**

Unlike default Firefox (both Photon and Proton), Lepton adds "close tab" button to all tabs, not just the active one:
![11](https://user-images.githubusercontent.com/8460563/129662998-70f5e21b-79e8-4d59-8252-c3bf4a2d24ee.png)

To make matters worse, the button itself is now larger than is was in Photon:
![22](https://user-images.githubusercontent.com/8460563/129663045-7cb8c56d-b85d-4acd-b291-ab3bb7b06fd1.png)

Combined with minimum tab width, and with the fact that the button is not visible before you point mouse cursor over it, all of this results in up to 36% chance to close a tab accidentally while trying to select it.

**Describe the solution you'd like**
The button should be displayed only on the currently active tab. Other tabs can be closed either by selecting them first, or from a context menu.

**Describe alternatives you've considered**
The button could stay as an optional feature, but default behavior should match original Firefox.

**Additional context**
Tested with Photon style, probably affects other variants too.
I've just recently started using Lepton (after Mozilla made Proton mandatory in Firefox 91), and have already closed tabs ~20 times while trying to select them.

**Comment by black7375** [comment]
It's a feature with some trade-offs. https://github.com/black7375/Firefox-UI-Fix/issues/45#issuecomment-899011665
It may be removed in a future major version, but it is a kind of breaking change and I do not plan to remove it in a minor patch.

Instead, I added it to the wiki.
https://github.com/black7375/Firefox-UI-Fix/wiki/Tips#remove-close-button-at-hover

**Comment by nbmrjuhneibkr** [comment]
Thanks for adding it to the wiki. I guess now I'll have to edit the code before applying each update. It's not great, but it's better than nothing.
I think that only cosmetic changes should be enabled by default.
This button may be convenient for someone, but closing a tab by accident may lead to data loss, which is a serious issue, in my opinion.

**Comment by black7375** [comment]
I'm currently experimenting with reducing the close button size and I like it quite a bit.
How is it? https://github.com/black7375/Firefox-UI-Fix/issues/179#issuecomment-902445056

**Comment by black7375** [comment]
See #179
We decided to adjust the size, thickness, and padding.
