### ISSUE TITLE
Script Installer

### ISSUE THREAD

**Issue by black7375** [black7375/Firefox-UI-Fix#18]
Refer https://github.com/black7375/Firefox-UI-Fix/pull/17#issuecomment-851834568

https://github.com/7k5x/Firefox-UI-Fix/commit/85d6d042c6739740ca08905958ffb6196f155191

**Comment by 7k5x** [comment]
I find Powershell to be horrifically hard since there aren't a lot of users. Can I write a batch script instead?

**Comment by black7375** [comment]
no problem~

**Comment by black7375** [comment]
Scripts from the following projects are available:  #32
It looks solid.

**Comment by black7375** [comment]
Installer has been made to some extent.
https://github.com/black7375/Firefox-UI-Fix/blob/master/install.sh

**Comment by 7k5x** [comment]
But how about people who don't have `git` installed?

**Comment by black7375** [comment]
Local installation is supported.
git is installed by default in Linux.
I don't remember using Mac for a long time.

**Comment by 7k5x** [comment]
![image](https://user-images.githubusercontent.com/85086136/122327307-9e0afa00-cf68-11eb-82b3-618445be7bd6.png)
Is this a mistake or is this on purpose? shouldn't there be a `==`?
