### ISSUE TITLE
[Suggestion] Add config files to maintain coding style

### ISSUE THREAD

**Issue by Ajith-stark** [black7375/Firefox-UI-Fix#182]
Provide `.prettierrc` and `.editorconfig` (optional) config file to maintain consistent coding styles.

**Comment by black7375** [comment]
LGTM
Yes. And we have to check with action whether linting works.

**Comment by Ajith-stark** [comment]
I never seen this much fast response before. :sweat_smile:

**Comment by black7375** [comment]
Applied on a V4.0
