### ISSUE TITLE
Incorrect text color

### ISSUE THREAD

**Issue by dokax** [black7375/Firefox-UI-Fix#183]
**Describe the bug**

**Expected behavior**

**Screenshots**
https://imgur.com/keH1iYI
![image](https://user-images.githubusercontent.com/25581533/130160159-f791bd2b-9bc5-4cca-bd4c-277de38b37b3.png)

https://imgur.com/QKLkcio
![image](https://user-images.githubusercontent.com/25581533/130160170-c3fb8eb9-ebe7-46ae-9cdf-a5831c3161ce.png)

**Environment (please complete the following information):**
Check like `- [x]`.
 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: [91.0.1]
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [ ] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark
   - [ ] Others: [sample] [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/)

**Additional context**

**Comment by black7375** [comment]
It will be fixed
