### ISSUE TITLE
[Photon] Tab bar scrolling arrows flash

### ISSUE THREAD

**Issue by ilia-kats** [black7375/Firefox-UI-Fix#184]
Steps to reproduce:
- Open a new window
- open many tabs, as many as need for them to not be full-width
- pin one tab
- select the right-most tab

The horizontal arrows meant for scrolling the tab bar will start flashing, resulting in the entire tab bar changing width multiple times per second. This is very annoying.

*edit*: I believe this is the same issue as #163, but it seems to occur in general, not just when customizing the UI.

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 91.0.1
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [x] System Default
     - GTK Theme Name(Only Linux User): Breeze Dark
   - [ ] Others:

**Comment by black7375** [comment]
Bottom Rounded Corner has been disabled on `photon-style`.
As this was not in the original design, this bug may be fixed.

**Comment by ilia-kats** [comment]
Confirmed, seems to be fixed. Thanks for the fast fix.
