### ISSUE TITLE
Avatar missing

### ISSUE THREAD

**Issue by dokax** [black7375/Firefox-UI-Fix#187]
**Describe the bug**
Just noticed that big avatar is disappear.
**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
Check like `- [x]`.
 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: [91.0.1]
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [ ] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark
   - [ ] Others: [sample] [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/)

**Additional context**

**Comment by black7375** [comment]
Now it's resolved.

**Comment by dokax** [comment]
Avatar in hamburger menu looks weird.
https://imgur.com/a/lupAqKj

**Comment by dokax** [comment]
The avatar in hamburger menu looks weird.

**Comment by black7375** [comment]
Now fixed.
Thank you for report
