### ISSUE TITLE
Close button not showed

### ISSUE THREAD

**Issue by zhuopeng-tan** [black7375/Firefox-UI-Fix#189]
**Describe the bug**
Close button on tab is not showed normally, the cross in the rectangle is not showed.

**Expected behavior**
Close button on tab is showed normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/77958663/130395848-7af58241-bbbf-4273-bb62-14382c44098d.png)

**Environment (please complete the following information):**
Check like `- [x]`.
 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 91.0.1
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [] Alpenglow(System: Dark)
   - [x] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark
   - [ ] Others: [sample] [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/)

**Additional context**
Version: [commit](https://github.com/black7375/Firefox-UI-Fix/commit/517ae7caf9a31bf86289ca9f9a0117173db65aa6)
This bug is involved after v3.1.1 since v3.1.1 is OK.

**Comment by black7375** [comment]
Did you just update the code?
An icon to replace the close button has been added. #179
https://github.com/black7375/Firefox-UI-Fix/blob/master/icons/dismiss-filled.svg

**Comment by zhuopeng-tan** [comment]
Yes, I used the [latest commit](https://github.com/black7375/Firefox-UI-Fix/commit/517ae7caf9a31bf86289ca9f9a0117173db65aa6), but just copied `userChrome.css` and `userContent.css` without the icon

**Comment by black7375** [comment]
It will work if you add the icon!!
Some people may make mistakes, so I will notice it noticeably at the next release note.
Thanks.
