### ISSUE TITLE
Some panel menu items are incorrectly aligned with the icon support.

### ISSUE THREAD

**Issue by rhdunn** [black7375/Firefox-UI-Fix#19]
**Describe the bug**
The following menu items don't have spacing that accounts for the icons, resulting in the icons starting in the icon gutter:
1. More Tools > Task Manager
1. More Tools > Remote Debugging
1. More Tools > Browser Console
1. More Tools > Responsive Design Mode
1. More Tools > Page Source
1. Help > Submit Feedback

**Expected behavior**
The text for menu items without an icon should be aligned with the text for menu items with icons.

**Environment (please complete the following information):**
 - Firefox Version: 89.0 (Release)
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [x] Alpenglow(System: Dark)
   - [ ] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

**Comment by black7375** [comment]
I always think compatibility is important.
Thanks for the report.

I only use Windows at home, so I'll have a chance to test it out in the evening.

**Comment by black7375** [comment]
One more question.

File structure should look like this.
```
At Profile's `chrome` directory
- userChrome.css
- userContent.css
- icons
  - bug.svg
  - command-frames.svg
  - ...
```

Is it copied correctly?

**Comment by black7375** [comment]
I'am reproduce this.
![image](https://user-images.githubusercontent.com/25581533/120487528-93b40200-c3a5-11eb-98ad-3498beb9f38e.png)

If I'm right, it's an icon's path setting issue.

**Comment by black7375** [comment]
@rhdunn Could you check file path?

**Comment by black7375** [comment]
If there is no response by tomorrow, or if there are no users with the same symptoms, it is assumed that the solution has been resolved.

**Comment by rhdunn** [comment]
Your image in https://github.com/black7375/Firefox-UI-Fix/issues/19#issuecomment-853023490 is what I'm seeing. The issue here is that the menu items that don't have an icon (e.g. Task Manager) should still have spacing *as if an icon was there* so the text is vertically aligned. That is, in the modified image below, all the text should be touching the blue line like the "Customize Toolbar" and "Eyedropper" menu items are.

![alignment](https://user-images.githubusercontent.com/47298/120897094-6c1a9f00-c61c-11eb-84ee-c59b7bc1371c.png)

**Comment by rhdunn** [comment]
To be clear, that menu should look something like this:

![aligned](https://user-images.githubusercontent.com/47298/120897276-27433800-c61d-11eb-8a71-acd1455279e2.png)

**Comment by black7375** [comment]
Can you check if your `chrome` folder has an icons folder?

**Comment by rhdunn** [comment]
Ah, I see. Copying the icons folder displays the icons, although they are displaying as black instead of white when using the dark theme.

**Comment by sean1138** [comment]
C:\Users\WinUsername\AppData\Roaming\Mozilla\Firefox\Profiles\randomstring\chrome
i don't have the icons folder here, creating it didn't change the left alignment of items without icons, what should be in the icons folder?
![image](https://user-images.githubusercontent.com/6720184/120897515-222eba80-c616-11eb-9a65-51095f536d76.png)

**Comment by black7375** [comment]
The icons folder should contain icons.

---

There have been many changes recently. Download and install again.
https://github.com/black7375/Firefox-UI-Fix/wiki/Installation-Guide

**Comment by black7375** [comment]
@rhdunn
> Ah, I see. Copying the icons folder displays the icons, although they are displaying as black instead of white when using the dark theme.

Because this setting
https://github.com/black7375/Firefox-UI-Fix/blob/68378ca020e4af28bf7cb60ad16ea099f4271fe8/user.js#L5-L6

**Comment by sean1138** [comment]
a css only fix might work?  not sure if the 16px is a consistent unit of measure throughout firefox's UI, never messed with userchrome.css before today.
`#appmenu-developer-tools-view .subviewbutton *{
    min-width: 16px;
  }`
![image](https://user-images.githubusercontent.com/6720184/120898486-94a19980-c61a-11eb-900c-c01a14e4abe1.png)

i came from the ghacks article about this project, missed copying the icons folder in the zip file download

**Comment by black7375** [comment]
Instead of, There are plans to provide an installer in the future. (to reduce mistakes)

I'll ask ghack if it's possible to update the article.

**Comment by black7375** [comment]
IMO, this is an installation issue, not a bug.
