### ISSUE TITLE
Style is preventing proper closing of items in the notification deck

### ISSUE THREAD

**Issue by gotyaoi** [black7375/Firefox-UI-Fix#190]
**Describe the bug**
Space is left over when closing notification in the tab notification deck. This seems to be due to the notification-message html node not being removed after it is visually removed.

**Expected behavior**
The node should be removed and the space should not be left over.

**Screenshots**
First the visual effect:
![bar-before](https://user-images.githubusercontent.com/2141918/130552816-3162e866-6127-4ba4-b74a-b8bc46e9898f.PNG)
![bar-after](https://user-images.githubusercontent.com/2141918/130552831-ccc3fe69-95ff-47eb-911b-bbbe8d4ae292.PNG)

Then the debugger:
![photon-before](https://user-images.githubusercontent.com/2141918/130552876-3dd9dd1d-50bb-49e9-b14e-8d38bcfdb5f8.PNG)
![photon-after](https://user-images.githubusercontent.com/2141918/130552889-1efd4b87-c4b1-479b-8437-503d59efc315.PNG)

Then the debugger from stock firefox:
![proton-before](https://user-images.githubusercontent.com/2141918/130552945-414dcfa1-22ad-4ab2-b71d-33cbfb305680.PNG)
![proton-after](https://user-images.githubusercontent.com/2141918/130552954-82b07835-806e-4311-80ff-a904a112e7f8.PNG)

**Environment (please complete the following information):**
Check like `- [x]`.
 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 91.0.1
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [ ] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark
   - [x] Others: [yakuza paint](https://addons.mozilla.org/en-US/firefox/addon/yakuza-paint/)

**Additional context**
This was working correctly sometime last month, but I didn't notice the problem immediately after updating, so I couldn't give an exact code version. Does not occur in stock firefox, which is why I included the debugger from stock as well.

**Comment by black7375** [comment]
Thanks for the report. Thanks I was able to fix it!!
I'm working on a release today or tomorrow, and I'll include it in `photon-style`.
