### ISSUE TITLE
Rounded corners in tabs in Lepton's Photon design

### ISSUE THREAD

**Issue by lanz** [black7375/Firefox-UI-Fix#191]
**Describe the bug**
I'm using Lepton's Photon design. The tabs have rounded corners.

**Expected behavior**
The tabs should have sharp corners like the real Photon design in previous Firefox versions.

**Screenshots**
![firefox](https://user-images.githubusercontent.com/56061103/130730366-e589c510-887e-41b3-888e-fcf0a6a86f0b.png)

**Environment (please complete the following information):**
Check like `- [x]`.
 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: [write from `about:support` - `version`]
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [x] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [x] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark
   - [ ] Others: [sample] [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/)

**Additional context**
This seems like it would be an easy fix. I just don't know what the proper CSS selector is.

**Comment by black7375** [comment]
Removed in latest commit.
Refer #184
