### ISSUE TITLE
Merge conflict in photon-style

### ISSUE THREAD

**Issue by gotyaoi** [black7375/Firefox-UI-Fix#192]
**Describe the bug**
Merge markers are left over in the userChrome.css file after https://github.com/black7375/Firefox-UI-Fix/commit/930d134b5876a9bab2ba7c263db24a4f33429fdf. Lines in question: https://github.com/black7375/Firefox-UI-Fix/blob/930d134b5876a9bab2ba7c263db24a4f33429fdf/userChrome.css#L887-L967

It seems to be affecting the tab separators, which is why I started looking for it.

**Comment by black7375** [comment]
Thanks for the report!
