### ISSUE TITLE
Remove 1px border-left on the first tab

### ISSUE THREAD

**Issue by kanlukasz** [black7375/Firefox-UI-Fix#195]
**Is your feature request related to a problem? Please describe.**

I'm not sure this 1px is necessary on the first tab.
If we have active the **first** tab, it's looks like weird a little

![image](https://user-images.githubusercontent.com/30685349/131178543-60b755c4-468e-43d9-a419-b33a89a5e93b.png)

---

**Describe the solution you'd like**

Remove 1px border-left on the **first** tab only

---

For example, in Thunderbird, there is no this 1px space:
![image](https://user-images.githubusercontent.com/30685349/131178862-12bfe10e-eb53-4fc2-9e62-2d79e015c130.png)

**Comment by black7375** [comment]
This issue has been moved to a bug, and this patch should fix it.

**Comment by kanlukasz** [comment]
I confirm. Works fine! 👍
