### ISSUE TITLE
New Profile doesn't get the install

### ISSUE THREAD

**Issue by Jonta** [black7375/Firefox-UI-Fix#196]
**Describe the bug**
- Installed Lepton in several Firefox-profiles with `bash -c "$(curl -fsSL https://raw.githubusercontent.com/black7375/Firefox-UI-Fix/master/install.sh)"`
- Made new Firefox-profile
- Ran `bash -c`-command above

**Expected behavior**
New profile got Lepton

**Environment:**
 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 91.0.2 (but this may have been 91.0.1 or 91.0.0)
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Others: 

**Additional context**
I copied the /chrome-folder from a different profile into the new one, and that didn't work

New profile's not in `lepton.ini`. Do I add it manually?

I know this bug report isn't great. I'm a bit wary of messing around with my profiles

**Comment by black7375** [comment]
Did you install the newly created profile as well?
**`user.js` file** and `chrome` directory should be copied correctly.

`lepton.ini` is not necessary as it is used to make the installation process easier or to obtain debugging information.

**Comment by Jonta** [comment]
> Did you install the newly created profile as well?

I don't know what you mean by this

> **`user.js` file** and `chrome` directory should be copied correctly.
> (It seems that the current `user.js` file is not copied.)

Copying `user.js` from a different profile seems to solve it. :)

> `lepton.ini` is not necessary as it is used to make the installation process easier or to obtain debugging information.

How do I correctly modify `lepton.ini` to include the new one?

Is it as simple as this?
- Copying a different one's
- Putting the new one at the bottom
- Modifying lines 1 & 5

**Comment by black7375** [comment]
Once installed, it seems to go well.

`lepton.ini` is created every time you install or update as a script.
The way to keep the information is to write the information to the [`chrome/LEPTON`](https://github.com/black7375/Firefox-UI-Fix/blob/master/LEPTON) file.

Here is the RFC information.
https://github.com/black7375/Firefox-UI-Fix/blob/6c7e0a549553b022ef84fe28dcfd1d53bcb4ebaa/install.sh#L442-L463
