### ISSUE TITLE
install.sh stays after install (if intentional: Has a cryptic/generic name)

### ISSUE THREAD

**Issue by Jonta** [black7375/Firefox-UI-Fix#199]
**Describe the bug**
Note: This may be related to my issues with https://github.com/black7375/Firefox-UI-Fix/issues/196

**Expected behavior**
- Install-file is gone

Or

- Install-file has a more descriptive name than `install.sh`

**Comment by black7375** [comment]
I don't think it's normal behavior to remove the install script after installation.

**Comment by Jonta** [comment]
> I don't think it's normal behavior to remove the install script after installation.

@black7375 Quite possible

How about having that be an option at the end of the install process? A [y/n]-prompt

Also: What about the name?

**Comment by black7375** [comment]
Do you have a name you would like to suggest?

**Comment by Jonta** [comment]
> Do you have a name you would like to suggest?

@black7375 

- install-lepton
- install-lepton-[version]
- install-lepton-[date-of-version-release]
- install-lepton-[date-of-version-download]
- install-lepton-[version]-[date-of-version-release]
- install-lepton-[version]-[date-of-version-download]

**Comment by black7375** [comment]
Script names must be the same.
If it changes, users running scripts over the network will have to come into the project page every time.

If users download the compressed file, `install.sh`(or `install.ps1`) is in the same context, so I think it will be easily recognizable.
`install-lepton.sh` is more intuitive, but I don't want to confuse existing users by changing the installation command.

**Comment by Jonta** [comment]
> Script names must be the same.
> If it changes, users running scripts over the network will have to come into the project page every time.
> 
> If users download the compressed file, `install.sh`(or `install.ps1`) is in the same context, so I think it will be easily recognizable.
> `install-lepton.sh` is more intuitive, but I don't want to confuse existing users by changing the installation command.

@black7375 Constant name makes sense

Not changing to e.g. `install-lepton.sh` sounds like [tech-debt](https://en.m.wikipedia.org/wiki/Technical_debt) to me

I did install this from `~` though, unsure where to put the file. Maybe "you can put this file anywhere" or similar should be part of the installation instructions

**Comment by black7375** [comment]
It's designed to be flexible, but for reasons I haven't specified.
In version `v4.5`, I am thinking of supporting dark mode in Addon, we need a code replacer.
This requires automation by the installation script, and the update of the installation script is required.

The same goes for the JS features that will be introduced in `v5.0`.
Therefore, README recommends the format to be downloaded over the network every time.
