### ISSUE TITLE
Inconsistent spacing between bookmarks menu folder items

### ISSUE THREAD

**Issue by acarasimon96** [black7375/Firefox-UI-Fix#201]
**Describe the bug**
Links in the dropdown menus of folders in the bookmarks bar appear squashed, while folders look nicely spaced in between them.

**Expected behavior**
The spacing between all bookmarks bar folder items would appear the same

**Screenshots**
![image](https://user-images.githubusercontent.com/17580077/131238685-9e3b5a76-225f-47c9-a88b-f19774e4d7bb.png)

**Environment (please complete the following information):**
 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 91.0.2
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [x] System Default
     - GTK Theme Name(Only Linux User): Breeze
   - [ ] Others: [sample] [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/)

**Additional context**
My Linux distribution is Manjaro, and I use KDE Plasma for my desktop environment.

The screenshot above was taken from my laptop. I can also reproduce this on my desktop with the same exact distro, Firefox version, Lepton version, and DE, but it uses Materia for the GTK theme and a different interface font.

Both systems had the spacing mode in Firefox set to Compact, and this can also be reproduced with Normal spacing mode. Touch spacing mode and Proton style menus such as the bookmarks button menu appear to be unaffected by this bug.

This bug has not occurred before version 3.2.0, and it was probably caused by c8ae935.

**Comment by black7375** [comment]
After the 4.0 release, I will make completely revision of the bookmark padding.
#136 is also included.

**Comment by black7375** [comment]
It's probably been fixed.
There were many commits related to the bookmark menu, so we recommend updating to the latest master branch.

**Comment by acarasimon96** [comment]
Just got Lepton updated using master branch and can confirm that the spacing looks a lot better now, although the Open All In Tabs item isn't aligned properly to the left (might be related to #161). Thanks for the fix!
![image](https://user-images.githubusercontent.com/17580077/132158353-9d7a0a57-38b6-43d5-8752-4de0bdbaa146.png)

**Comment by dankirkd** [comment]
@acarasimon96 and @black7375 These changes, or others, have now combined the padding settings used in the bookmark menus, with those used in Firefox menus.  Additionally, the settings now break earlier changes that were intended to render compact bookmark menus as they used to be on Windows.  I look forward to the previously hinted at post-4.0 bookmark padding revision.  Please consider a Windows specific setting.

**Comment by dankirkd** [comment]
@black7375 I should also mention that changing the compact padding back to 1px no longer works for some reason.
``` 
:root[uidensity="compact"] {
    --bookmark-menu-padding: 1.5px;
}
```
i.e. I can grow the padding, but efforts to reduce it fail.
