### ISSUE TITLE
When photon style is used, change light blue to darker blue

### ISSUE THREAD

**Issue by mStirner** [black7375/Firefox-UI-Fix#202]
**Is your feature request related to a problem? Please describe.**
No, feature only question/wish.

**Describe the solution you'd like**
Change the Firefox light blue (when you focus the search bar right top) to a darker blue, like the the tab active blue provided by photon. See screenshots for better understanding:

![firefox-1](https://user-images.githubusercontent.com/5003424/131265855-6f480403-72a7-4667-b038-ed30ce850d19.jpg)
or
![firefox-2](https://user-images.githubusercontent.com/5003424/131265932-c34a7fe3-609a-49ae-b868-b9edfe9eddc2.jpg)

It would be a much better look & feel, to use the photon blue color, rather then the new Firefox default.

#### Summary: 
Change color when "photon" style is used from `#218fa6` to `#0a84ff` (Values from color picker in gimp)
Should be apply for focus on on the search bar, or address bar and checkbox and other things where this light blue color  is used

Note: Used the provided installer. OS: Ubuntu 18.04 x64 LTS / Windows Server 2016 x64

**Comment by black7375** [comment]
Changing the basic color is a bit burdensome.
I'll add it to the wiki later.

**Comment by black7375** [comment]
Try using version `5.0.0` options.
https://github.com/black7375/Firefox-UI-Fix/wiki/Options#blue-accent-color
