### ISSUE TITLE
Option to have no icons in the main menu

### ISSUE THREAD

**Issue by mareg** [black7375/Firefox-UI-Fix#204]
**Is your feature request related to a problem? Please describe.**
Original Firefox didn't have icons in the top navigation menu, after applying the script they're added to all menus in the menu bar. This is inconsistent with other applications on my desktop (MATE Desktop, Fedora) and looks odd.

**Describe the solution you'd like**
I don't want to see icons on the top menu bar (like in original Firefox).

**Describe alternatives you've considered**
I'd consider having icons if padding was more like on the bookmarks tab. Either way icons are not expected to be there and I'd prefer not to see them on the top menu bar.

**Additional context**
See attached image:

![screenshot1](https://user-images.githubusercontent.com/533217/131666495-3c58a9af-f8af-4861-8fb4-da3227aa224d.png)

**Comment by black7375** [comment]
There are no plans to remove it.
However, documentation is possible.

I will add it to the wiki later.

**Comment by mareg** [comment]
Thanks. I don't mind icons anywhere else, but I would like an option to hide them on the menu bar.

**Comment by black7375** [comment]
https://github.com/black7375/Firefox-UI-Fix/wiki/Tips#remove-menubar-icon

You can remove this codes.

https://github.com/black7375/Firefox-UI-Fix/blob/0513ffd94dee646c822bcbde61ee04dfac23a043/userChrome.css#L2079-L2092

https://github.com/black7375/Firefox-UI-Fix/blob/0513ffd94dee646c822bcbde61ee04dfac23a043/userChrome.css#L2863-L2885

**Comment by mareg** [comment]
Thanks. I'm kind of confused, on the other desktop PC those icons don't show up and padding is nicer... :thinking:

![screenshot11](https://user-images.githubusercontent.com/533217/131826263-ea35078d-66ea-4e51-9d2c-fa8d40cf59ef.png)

**Comment by dankirkd** [comment]
> https://github.com/black7375/Firefox-UI-Fix/wiki/Tips#remove-menubar-icon
> 
> You can remove this codes.

That's not a great option if we still want to pick up future updates and fixes.  It means that we'd have to reapply the adjustment each time.  I'm with @mareg - the icons are too busy in the menu bar.  This was not part of the CSS when everyone flocked to use these "fixes" when Mozilla screwed with the UI, so it would be my vote that they are by default not added and instead folks can add the CSS you have in your tip, instead of making them a default.
