### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by dokax** [black7375/Firefox-UI-Fix#205]
**Describe the bug**

**Expected behavior**

**Screenshots**

https://imgur.com/OCEOZo4
![image](https://user-images.githubusercontent.com/25581533/131761210-cc11663c-bd04-4bdc-8a43-03c6fdfbdd5f.png)

https://imgur.com/HWgzN8a
![image](https://user-images.githubusercontent.com/25581533/131761221-6ab2e52f-04f9-48fc-bd74-14aeba14656b.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

**Comment by black7375** [comment]
It has been fixed. :+1:
