### ISSUE TITLE
Local pages with anchor in url loosing styling.

### ISSUE THREAD

**Issue by Michkovy** [black7375/Firefox-UI-Fix#208]
**Describe the bug**
I got locally saved html file that when appending an #xx anchor at the end and reloading the page looses certain css stylings.
 
I.e. the url:
file:///D:/.../Tracks/USA/BlackHillsRwy.html
file:///D:/.../Tracks/USA/BlackHillsRwy.html#O00

**Expected behavior**
CSS Stylings should not be lost on reload.

**Screenshots**
![Screenshot 2021-08-13 05 51 53 copy](https://user-images.githubusercontent.com/68487544/131849799-59f48263-f10c-4a53-91ce-a5ba853161d8.png)

**Environment:**
 - Distribution
   - [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
 - Firefox Version: 91.0.2
 - OS:
   - [X] Windows
 - Theme:
   - [X] Dark
   - [~] System Default

**Additional context**
This only happens in locally saved files, I got a 1:1 copy on a server an that is working fine. As is the local version when running vanilla FF.
I've attached a minimum working example of the page.
[RCDB.zip](https://github.com/black7375/Firefox-UI-Fix/files/7099105/RCDB.zip)

**Comment by black7375** [comment]
Change from blacklist to whitelist method!!
