### ISSUE TITLE
"Always Show Tab Icons" tip needs updating

### ISSUE THREAD

**Issue by acarasimon96** [black7375/Firefox-UI-Fix#209]
In Lepton version 4.0, I noticed that the current [instructions on how to make all tabs show an icon](https://github.com/black7375/Firefox-UI-Fix/wiki/Tips#always-show-tab-icon) doesn't work because the mentioned lines to remove from userChrome.css don't exist anymore in v4.0. I've figured out the new line numbers to remove for the tweak to work in that version, and they are [lines 1287-1305](https://github.com/black7375/Firefox-UI-Fix/blob/v4.0.0/userChrome.css#L1287-L1305). Unfortunately, I can't make edits to the wiki, so the best I can do is to let you know about this via an issue.

**Comment by black7375** [comment]
I knew other users had permission to write..
Changed to be possible.

Thanks!!
