### ISSUE TITLE
White space on top of the tab bar

### ISSUE THREAD

**Issue by wavexx** [black7375/Firefox-UI-Fix#211]
**Describe the bug**
Commit 7ddef19cfbd82dffb91291921258598595c43d22 introduced some white space on top of the tab bar when the menu is hidden. This is shown on FF on Linux, using the compact style, and is visible due to the dark menu background.

This is commit 0513ffd94dee646c822bcbde61ee04dfac23a043:

![2021-09-04T210418](https://user-images.githubusercontent.com/1017726/132105417-c27f3f2f-8e73-40df-b91b-43b9f56ff8ef.png)

This is with commit 7ddef19cfbd82dffb91291921258598595c43d22:

![2021-09-04T210510](https://user-images.githubusercontent.com/1017726/132105420-cd629a2a-e133-4cb5-b4c3-5e8ab0b37734.png)

Note that the red line is the window border, shown here for clarity.

The extra white space is 2px tall.
When the menu is shown, the space is gone.

**Expected behavior**

No space between the window border and the tab bar.

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): Arch-Theme
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Comment by black7375** [comment]
There's no problem with KDE. I need to check if it's a problem that only occurs in Gnome.
