### ISSUE TITLE
Smooth Scrolling

### ISSUE THREAD

**Issue by Hapax96** [black7375/Firefox-UI-Fix#214]
Hey,

I hope it's okay to post my question here. First of all thanks for the new version. I suddenly had the minimize, zoom in/out and close buttons missing in the top right corner, but after downloading the latest version they are back.

Now I am concerned about the smooth scrolling feature. Is this a new feature directly from Firefox? I am of the opinion that Smooth Scrolling was not present when I was still using the old version of the Proton theme. But only visual changes are made to Firefox and not functional ones, right?

Since I read about smooth scrolling in the changelog of the latest version, I thought you might be able to tell me how to disable it. I kind of don't like it at all.

I searched for smooth via about:config, but there are so many entries there and I don't want to just unknowingly disable anything that might end up being wrong.

Thanks in advance!

**Comment by black7375** [comment]
> I suddenly had the minimize, zoom in/out and close buttons missing in the top right corner, but after downloading the latest version they are back.

What do you mean?

Smooth scrolling is defined as follows.
https://github.com/black7375/Firefox-UI-Fix/blob/master/user.js#L30

**Comment by Hapax96** [comment]
> 
> 
> > I suddenly had the minimize, zoom in/out and close buttons missing in the top right corner, but after downloading the latest version they are back.
> 
> What do you mean?
> 
> Smooth scrolling is defined as follows.
> https://github.com/black7375/Firefox-UI-Fix/blob/master/user.js#L30

I mean that these buttons were gone:

![firefox_yr1AZ9B7gA](https://user-images.githubusercontent.com/88907420/132496355-08f2d057-14d6-497e-9b4b-0636455ea315.png)

But after I inserted the latest version of the theme, they are back. Maybe it was some other problem, if you don't know the problem, I don't know.

**Comment by black7375** [comment]
Yes. Maybe it was a different issue.
There is no code to modify the `minimize`, `maximazie` and `close` buttons.

If you want to modify the scrolling values ​​very slightly, I recommend:
https://github.com/black7375/Firefox-UI-Fix/wiki/Tips#only-sharpen-scrolling

**Comment by Hapax96** [comment]
> 
> 
> Yes. Maybe it was a different issue.
> There is no code to modify the `minimize`, `maximazie` and `close` buttons.
> 
> If you want to modify the scrolling values ​​very slightly, I recommend:
> https://github.com/black7375/Firefox-UI-Fix/wiki/Tips#only-sharpen-scrolling

Thanks for the feedback. However, I am unfortunately not familiar with it. So I have to replace line 30 to 71 with the code from the second link (line 28 to 32)?

**Comment by black7375** [comment]
1. Remove the line and try again. `user.js` is under the profile folder, not the chrome folder.
https://github.com/black7375/Firefox-UI-Fix/blob/64c7eeebfbf025c02cff787f3dafade54707dd9a/user.js#L33-L74

2. If you haven't returned to the original scrolling
Change the relevant settings in `about:config` to their default values.

3. Try replacing it with a value from Sharpen Scrolling.

**Comment by Hapax96** [comment]
Thanks again. Now after I have manually entered all the original values via about:config, I find scrolling much more pleasant again. How did the scrolling behavior change? By the new user.js or by a Firefox update?

**Comment by black7375** [comment]
Yeah. Delete your scrolling related lines.
