### ISSUE TITLE
FF 92: Make bookmarks-menu look like other menus 

### ISSUE THREAD

**Issue by Yaron10** [black7375/Firefox-UI-Fix#215]
Hello,

What's the simplest way to display bookmarks (_in the Bookmarks Toolbar_) as menus?
(padding, background, hover, border, separator etc.).

Bookmarks in `Menu -> Bookmarks`:
![תמונה](https://user-images.githubusercontent.com/10229320/132423854-4d880a71-5f79-4647-a6a9-5e28410eb099.png)

Bookmarks in the Bookmarks Toolbar:
![תמונה](https://user-images.githubusercontent.com/10229320/132423907-e6d4dd8e-8141-4338-bfee-cc47772f77fd.png)

***

With
```
:root
{
	--arrowpanel-background: -moz-Dialog !important;
}

#PlacesToolbar menuitem
{
	appearance: menuitem !important;
	padding-block: 0px !important;
}
```

I get:
![תמונה](https://user-images.githubusercontent.com/10229320/132564191-fa871a1a-cb7b-476d-874f-17a97d80d66f.png)
(padding, background, hover are relatively OK).

***

```
#PlacesToolbar menupopup[placespopup=true]::part(arrowscrollbox) 
{
	border: 1px solid gray !important;
}
```
Does work in the Browser ToolBox, but has no effect in userChrome.css.

With
```
#PlacesToolbar menupopup
{
	border: 1px solid gray !important;
}
```
I get:
![תמונה](https://user-images.githubusercontent.com/10229320/132566105-afc0a9e4-1296-4df8-b73e-b449de04ed73.png)
4px gap between the border and the menu.

Thank you.

***

I'm using a custom Windows 10 theme (NOT a FF theme).
Firefox displays menus in the custom theme look.
Up until FF 92 - bookmarks in the Bookmarks Toolbar were also displayed as menus.

**Comment by Yaron10** [comment]
http://forums.mozillazine.org/viewtopic.php?f=38&t=3079191

**Comment by black7375** [comment]
Until today, I hardly have time to touch Windows.
I'll fix it over the weekend!!

**Comment by Yaron10** [comment]
Great.
Thank you.

**Comment by black7375** [comment]
It looksandfeels like Windows 7, 8.

Changed the color of the menu in 7 and 8 to match.
https://github.com/black7375/Firefox-UI-Fix/commit/d641b09b4d2b7630cc1d465684ca26d09783fdda

On the Firefox, the bookmarks menu(`#PlacesToolbar`, `#BMB_bookmarksPopup`) seems to follow the shape of the panel.
But, It seems possible to slightly adjust the horizontal padding.

**Comment by Yaron10** [comment]
> It looksandfeels like Windows 7, 8.

If you're referring to my screenshots, I'm using a custom Windows 10 theme.

Using:
```
:root
{
	--arrowpanel-background: -moz-Dialog !important;
	--arrowpanel-border-radius: 0px !important;
	--panel-subview-body-padding: 3px 0px !important;

}

#PlacesToolbar menupopup
{
	background: -moz-Dialog !important;
	margin: 0px !important;
	border: 1px solid rgb(160, 160, 160) !important;
}

#PlacesToolbar menuitem
{
	appearance: menuitem !important;
	padding: 1px 5px 3px 0px !important;	/* RTL */
	margin: 0px 3px !important;
	min-height: unset !important;
}

#PlacesToolbar menupopup menuseparator
{
	appearance: menuseparator !important;
	position: unset !important;
	margin: 0px 0px 0px 3px !important;	/* RTL */
}
```

the result is:
![תמונה](https://user-images.githubusercontent.com/10229320/132921450-83d91cb1-61bb-42d0-8ba9-9fca82a6b926.png)
***
```
#PlacesToolbar menupopup[placespopup=true]::part(arrowscrollbox)
{
   border: 1px solid rgb(160, 160, 160) !important;
}
```
Any idea why this works in the Browser ToolBox, but has no effect in userChrome.css?

Thank you.

**Comment by black7375** [comment]
Because of `::part(arrowscrollbox)`
This syntax is not supported at `userchrome.css`.

**Comment by Yaron10** [comment]
@black7375,

Thank you for the important info. I appreciate it.
