### ISSUE TITLE
Need to fix the Reload Icon in Firefox 92

### ISSUE THREAD

**Issue by ADTC** [black7375/Firefox-UI-Fix#217]
### Issue 1:

Can this be un-commented?

https://github.com/black7375/Firefox-UI-Fix/blob/beb2e085b4618ce6302a93e027925fed19894845/userChrome.css#L2315-L2318

### Issue 2:

This file no longer exists. Need to replace it with `chrome://global/skin/icons/reload.svg`:

https://github.com/black7375/Firefox-UI-Fix/blob/beb2e085b4618ce6302a93e027925fed19894845/userChrome.css#L2401-L2404

https://github.com/black7375/Firefox-UI-Fix/blob/beb2e085b4618ce6302a93e027925fed19894845/userChrome.css#L2698-L2702

### Screenshots:
![image](https://user-images.githubusercontent.com/6047296/132935610-ef52c73c-1a05-4c1d-8d85-0780b82de3b1.png)

**Comment by ADTC** [comment]
@black7375 just let me know if you have no objections and I'll make a PR :)

**Comment by black7375** [comment]
Location of the icon is different depending on the Firefox version.
Reload button is in an easy-to-access place (toolbar), so leaving it blank to emphasize other menus is not a bad choice, so I'm thinking about it.

**Comment by Pentaphon** [comment]
> I want to hear users' opinions.

I would prefer to have the icon. A visual cue is always welcome.

**Comment by black7375** [comment]
Will be added back in v4.5!!
