### ISSUE TITLE
Tab UI Broken with GNOME 40 (Xorg)

### ISSUE THREAD

**Issue by qingxiang-jia** [black7375/Firefox-UI-Fix#22]
First of all, great job! The theme is REALLY beautiful!

I installed the version at 85d6d042c6739740ca08905958ffb6196f155191.

I am using GNOME 40 (under Xorg with ArchLinux, didn't try Wayland). I find both dark and light themes have broken tabs. The native theme looks find though. Below are screenshots for all three cases:

![Screenshot from 2021-06-01 16 18 27](https://user-images.githubusercontent.com/5571586/120401961-e7671280-c2f5-11eb-9c8d-fff91640132c.png)

![Screenshot from 2021-06-01 16 18 07](https://user-images.githubusercontent.com/5571586/120401973-eb933000-c2f5-11eb-993b-642dd48611df.png)

![Screenshot from 2021-06-01 16 17 33](https://user-images.githubusercontent.com/5571586/120401980-edf58a00-c2f5-11eb-9e64-ce50c5b189b2.png)

**Comment by qingxiang-jia** [comment]
After setting `svg.context-properties.content.enabled` to true, the UI is good. Closing the issue.

**Comment by black7375** [comment]
Something similar has happened before.  #12
We can improve it by creating an F&A.
