### ISSUE TITLE
pop-up menus from bookmarks toolbar folders incosistent with other menus

### ISSUE THREAD

**Issue by ilia-kats** [black7375/Firefox-UI-Fix#220]
If there is a folder in the bookmarks toolbar, then the pop-up menu once clicking on the folder has rounded borders and the selection of the individual bookmarks themselves also has rounded borders. This is incosistent with the rest of the menus in Firefox, which have square corners with selection going all the way horizontally without rounded borders. Please make the bookmarks pop-ups and the bookmarks selection also have square corners.

**Screenshots**

![bookmarks](https://user-images.githubusercontent.com/3499574/133605211-9eed5ebd-c7fb-4c6a-8693-9cdb4c6cf2a3.png)
![help menu](https://user-images.githubusercontent.com/3499574/133605225-ce1c7d82-3d62-415d-a319-6bd59fb528da.png)

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 92.0
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): Breeze Dark 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Comment by black7375** [comment]
It is probably a change in the latest version (v92).
The look and feel of bookmarks in the toolbar follows the panel.

There are some likes and dislikes, but I don't think Mozilla's decision was completely wrong, and I try to respect it.
