### ISSUE TITLE
The website pad's border is displayed incorrectly.

### ISSUE THREAD

**Issue by Monsterovich** [black7375/Firefox-UI-Fix#221]
**Describe the bug**
See the title.

**Screenshots**
![изображение](https://user-images.githubusercontent.com/3750982/133621328-a96873df-d688-4448-9177-ff33e3391dbf.png)

**Expected behavior**
That's how it looked like in firefox 89.0.
![изображение](https://user-images.githubusercontent.com/3750982/133621509-c69b8d5a-eb85-433c-875d-1f55587dcce9.png)

**Environment:**

 - Distribution
   - [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 92.0
 - OS:
   - [X] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [X] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Comment by black7375** [comment]
It is probably a change in the latest version (v92).
The look and feel of bookmarks in the toolbar follows the panel.

There are some likes and dislikes, but I don't think Mozilla's decision was completely wrong, and I try to respect it.

**Comment by black7375** [comment]
I made a little mistake by looking at the wrong tab.
I'll fix it tomorrow when I have time.

**Comment by black7375** [comment]
Now will be works!
Thanks for the detailed report with screenshots attached.
