### ISSUE TITLE
How do I remove this border around tabs

### ISSUE THREAD

**Issue by Odyssey346** [black7375/Firefox-UI-Fix#223]
**Describe the bug**
When I have dark mode enabled I see this ugly grey border around my tabs

**Expected behavior**
It should be gone

**Screenshots**
![image](https://user-images.githubusercontent.com/57069715/133965970-6b5174ab-afc1-43b6-83cc-1f77d2eb38f6.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [x] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

**Comment by black7375** [comment]
You can remove this lines.
https://github.com/black7375/Firefox-UI-Fix/blob/f2977bd3040f0246674a9cec6c44651a524b76e7/userChrome.css#L1119-L1141

I'm not going to remove it for contrast of the selected tab.

**Comment by Odyssey346** [comment]
Thanks! Maybe put it in the wiki?

**Comment by black7375** [comment]
Of course
