### ISSUE TITLE
Menu Bar and Bookmarks toolbar icon issues

### ISSUE THREAD

**Issue by DwayneNeri** [black7375/Firefox-UI-Fix#226]
On a long running install, as well as on a fresh installation on a new machine, there are icons/spacing added to the menu items on the Menu Bar, and the folder icon does not draw on anything on the Bookmarks toolbar or Library.

Lepton was installed properly using the download method, copying the user.js to the profile directory, and copying the chrome files to the chrome subdirectory.  I have not seen any other odd behavior in the UI.

I have two personal laptops (associated with the same Firefox sync account) that observe this behavior, but a third, work laptop, does not exhibit this behavior.  These are all Windows 10 machines running Firefox 92.0 64-bit.

![Lepton - Menu bar](https://user-images.githubusercontent.com/35276049/134387095-c5fbcea3-2026-410f-8444-1f1e8a9a52ab.png)
![Lepton - Bookmarks](https://user-images.githubusercontent.com/35276049/134387096-98a36e19-d44c-41df-8c54-e76f5da2d15c.png)

**Comment by black7375** [comment]
It seems that `chrome/icons` is not copied.

**Comment by DwayneNeri** [comment]
After copying the icons directory to the chrome directory, all of the bookmark icons now work.  Thank you!

Perhaps this should be logged as a separate item, but is it working by design to have the icons next to each of the menubar items (as in the first image)?  Traditionally, menu bars don't have icons on them.

**Comment by black7375** [comment]
It was the choice to increase overall UI consistency and scannability.
It's not a traditional UI, but I think it's user adaptable.

**Comment by DwayneNeri** [comment]
Understood. Problem 1 fixed due to user error. Problem 2 working as designed.  Thank you again!
