### ISSUE TITLE
Manual installation mistake (rename wrong folder to "chrome") that could mislead beginners

### ISSUE THREAD

**Issue by 1GodRage** [black7375/Firefox-UI-Fix#228]
Hi.
While following the Manual installation guide:
"3.2 Rename unziped directory to chrome"
if I do that, it won't be fine because there is already "chrome" folder inside.
Instead of guide to unzip, i would say that the manual should say that:
2.1 Download
2.2 open the zip (actually it says to unzip)
3.1 extract all the content of the zip in "profile folder".

The manual installation has an error, and could mislead beginners.

**Environment:**
documentation of: manual installation

**Comment by black7375** [comment]
Oh, I think we need to explain the `Download Zip` and `Release` situations separately.

**Comment by black7375** [comment]
Documentation update is complete.
This week has been a bit busy.
