### ISSUE TITLE
Make container lines larger

### ISSUE THREAD

**Issue by fabianski7** [black7375/Firefox-UI-Fix#23]
**Is your feature request related to a problem? Please describe.**
The small line below the favicon is very discreet.
The other active container indicators, like the ones in the address bar, are not as visible in the light theme and make the extensions area even more bloated.

**Describe the solution you'd like**
The line could be extended to the width of the tab (as it was in the previous design), at least for the active tab.

**Comment by black7375** [comment]
Is it difficult to distinguish in bright colors?
I've seen a lot of themes or users use them under favicons and I've decided it's a decent UI.

https://github.com/black7375/Firefox-UI-Fix/wiki/Screenshots#tab-state-comparison
Larger sizes can cause confusion when state becomes complex and require significant code changes.

**Comment by darius07** [comment]
Using this, I made is so there a line on the top of the bar for active tab and for containers:

/* CUSTOM Tab accent highlight */
#tabbrowser-tabs .tab-context-line { /* No idea if this does anything */
  display: none;
}

#tabbrowser-tabs .tab-background[selected="true"] {
    border-top: solid 2px var(--identity-icon-color, #4800FF) !important; /* #0078D7 is the default blue */
}

But you have to comment out/delete lines in Lepton below if you don't want to have the same line under the favicon 
/** Container Tab - Color line at icon's bottom *****************************/ and
/** Container Tab - Color line at icon's bottom *****************************/

How it looks in the end:
![UI change](https://user-images.githubusercontent.com/12880926/120467454-e0e5a300-c3a8-11eb-8746-8039f5b347ee.png)

**Comment by fabianski7** [comment]
> I've seen a lot of themes or users use them under favicons and I've decided it's a decent UI.

It definitely looks good, but I don't think it makes the container stand out the way it should be.


> #tabbrowser-tabs .tab-context-line { /* No idea if this does anything */
display: none;
}

I think this is already in Lepton, isn't it?

> #tabbrowser-tabs .tab-background[selected="true"] {
border-top: solid 2px var(--identity-icon-color, #4800FF) !important; /* #0078D7 is the default blue */
}

this is definitely a nice tip! thank you so much!

I also made a small change and left the indicators below the icon only for the non-active tabs. I really liked it

```
  .tab-icon-image:not([selected="true"]) {
    box-sizing: content-box;
    padding: 3px 0;

    border-bottom: 2px solid var(--identity-icon-color);
  }
```

![ksnip_tmp_aDcgkL](https://user-images.githubusercontent.com/47755037/120485880-0a500000-c3a4-11eb-95c2-4d9ee1194716.png)

**Comment by Termuellinator** [comment]
On first glance, Lepton looked quite nice, but the Container-Color only under tab Tab-Icon is a no-go for me - can't allocate the container to a tab on first glance, but have to stop and investigate the area more closely. If you change that up to have the line across the whole tab like in photon (and proton for that matter ^^), i'd give it another go ^^

**Comment by darius07** [comment]
A lot of trial and error here is full tab length highlight for container tabs + bonus custom color for active tab:

 

> /** Tab accent highlight for active tab and for container tabs START */
> 
> 	/* Moved this here as I deleted everything from "Container Tab - Color line at icon's bottom" */
> 	#tabbrowser-tabs .tab-context-line {
> 		display: none;
> 	}
> 
> 	/* 1px highlight line at the top of background container tabs */
> 	#tabbrowser-tabs .tab-background {
> 		border-top: solid 1px var(--identity-icon-color) !important;
> 	}
> 
> 	/* 2px highlight line at the top of active tab and custom color highlight line for active tab */
> 	#tabbrowser-tabs .tab-background[selected="true"]  {
> 		border-top: solid 2px var(--identity-icon-color, #4800FF) !important; 
> 		/* Change #4800FF to a color you want, #0078D7 is the default blue */
> 	}
>   
>  /* Tab accent highlight for active tab and for container tabs END */
> 

How it looks now (purple is the custom color active tab):
![UI change Final 1](https://user-images.githubusercontent.com/12880926/120491602-0c28bc00-c3c2-11eb-8f39-fb1f03999b16.png)
The active tab has a thicker highlight than background tabs:
![UI change Final 2](https://user-images.githubusercontent.com/12880926/120491694-1f3b8c00-c3c2-11eb-9659-2db03c7a07dc.png)

In order for this to work without also the favicon having the same underline remove these lines from Lepton:
  /** Container Tab - Color line at icon's bottom *****************************/
  /* None exist favicon & Pinned to select */
  /* None exist favicon - With Sound */
  /* Pinned Tab - Titlechanged Indicator override */
  /* Pinned Tab - Titlechanged & soundplaying */

I also removed these lines as I don't want to easily close pinned tabs
/** Pinned Tab - Replace Favicon to Close Button at Selected ****************/
  /* Left Padding - Assume the icon size is 17px */
  /* Right Padding - Assume the icon size is 17px */
  /* Sound Tab - Don't move overlay */

**Comment by Az0r** [comment]
@Termuellinator 

You can replicate photon's container line like follows:
```
/** Color line for Container Tab**/
  .tab-content::after {
    display: inline-block;
    width: -moz-available;
    height: 2px;
    position: absolute;
    bottom: 3px;
    left: 0;
    background: var(--identity-icon-color);
    content: '';
    margin: 0 var(--inline-tab-padding);
  }
```
![image](https://user-images.githubusercontent.com/15131687/120895515-915bdd00-c61d-11eb-8645-69bcc4327228.png)

In order to get rid of the line under the icon, you might have to remove `border-bottom: 2px solid var(--identity-icon-color);` from 

```
/** Container Tab - Color line at icon's bottom *****************************/
  .tab-icon-image {
    box-sizing: content-box;
    padding: 3px 0;

    border-bottom: 2px solid var(--identity-icon-color);
  }
```

**Comment by Termuellinator** [comment]
That looks really awesome, thank you!
Should be the default imho ^^

**Comment by Woundorf** [comment]
I want to add that if there is no favicon the default implementation does not indicate container (for example open in a container any of the linked images in this issue). With @Az0r's solution it works wonderfully.

**Comment by adql** [comment]
In addition to @Woundorf's comment, there is no container indication while the tab is loading, which on some websites and especially with a slow connection can take a while.

**Comment by black7375** [comment]
I will find the appropriate way to be displayed when loading.

**Comment by black7375** [comment]
New container line inpired by #167
![image](https://user-images.githubusercontent.com/25581533/131254951-28900ee4-97e7-4c0c-a35b-4cedddf350ef.png)

**Comment by gwarser** [comment]
> New container line inpired by #167

How to remove animation (I have animations disabled globally), make it static and full width?

**Comment by black7375** [comment]
Just remove this line
https://github.com/black7375/Firefox-UI-Fix/blob/a2b3d6cc4a48a85f594f0532ffeb313a18820afb/userChrome.css#L1390

**Comment by gwarser** [comment]
Nah, it looks like loading bar, I'm back at 16px.

**Comment by black7375** [comment]
![image](https://user-images.githubusercontent.com/25581533/131972329-4f66cef2-3dc1-4bb7-9c96-26d2e300b8cf.png)
There was an opinion that it looks like a loading bar, so I modified the position.
