### ISSUE TITLE
The speaker icon appears over the favicon.

### ISSUE THREAD

**Issue by KanchiMoe** [black7375/Firefox-UI-Fix#230]
**Describe the bug**

The speaker icon, when a video is playing or a tab is muted, appears over the website's favicon. And is smaller than in FF 88.

**Expected behavior**

Speaker Icon should not appear over the favicon. Should appear to the left of the close tab icon.

**Screenshots**
- Photon style, downloaded 28/09/21. https://i.imgur.com/YR2DGSm.png
- Firefox 88: https://i.imgur.com/N5jrB5G.png

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [x] Windows
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [X] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

**Comment by black7375** [comment]
Duplicated #166

I wouldn't accept it as the default, but it's possible as an option.
If we find a way, we can try adding it to the wiki. 
https://github.com/black7375/Firefox-UI-Fix/wiki/Tips
