### ISSUE TITLE
Lepton proton style looks tabs look bigger than stock Proton when you use Compact

### ISSUE THREAD

**Issue by Odyssey346** [black7375/Firefox-UI-Fix#231]
**Describe the bug**
When I installed Lepton Proton style, I wanted the same tabs but the rest of Lepton. However, I got much bigger tabs on compact which is not what I wanted

**Expected behavior**
If I use Compact, the tabs should have the same size.

**Screenshots**
Lepton Proton: 
![bilde](https://user-images.githubusercontent.com/57069715/135054154-b0a2aa57-678d-4164-956c-fff9f5d714bf.png)
Proton: 
![bilde](https://user-images.githubusercontent.com/57069715/135054189-75c5764b-a19c-4a96-93ea-69436b33c012.png)

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [x] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 92
 - OS:
   - [x] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

**Comment by black7375** [comment]
I also found the problem a while ago and fixed it. 
https://github.com/black7375/Firefox-UI-Fix/commit/04f0cf96cc897d98c1207d5260001f01c70e5076

It will be included in the next release.
