### ISSUE TITLE
Missing icons in main menu

### ISSUE THREAD

**Issue by zloy2452** [black7375/Firefox-UI-Fix#233]
**Describe the bug**
Missing some icons in main menu in "P**h**oton-Style" version.

**Expected behavior**
Same as original and "P**r**oton-Style" versions.

**Screenshots**
![1](https://user-images.githubusercontent.com/66868535/135259003-e751dddf-07c8-494e-ba73-fda7539dc8da.png)

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [x] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default

**Comment by akisblack** [comment]
![image](https://user-images.githubusercontent.com/41871089/135283664-2bf409e8-65a4-457f-b332-5bc181463be4.png)
This isn't a bug, it's a feature

**Comment by zloy2452** [comment]
Got it. Thanks.
