### ISSUE TITLE
Rounded titlebar corners are broken

### ISSUE THREAD

**Issue by TheOneKevin** [black7375/Firefox-UI-Fix#235]
**Describe the bug**
By default, rounded corners are transparent and look correct (see below). However, with the userChrome.css installed, they break.

**Expected behavior**
This is the simple userChrome.css provided by [`Revertron/Firefox-Proton-UI-Fix`](https://github.com/Revertron/Firefox-Proton-UI-Fix)

https://imgur.com/a/ePCOD5g
![image](https://user-images.githubusercontent.com/25581533/135827423-df528676-dadb-4f34-a210-5586f822da61.png)

And with commit 46dd6ff, this is what it looks like

https://imgur.com/jFBnSSJ
![image](https://user-images.githubusercontent.com/25581533/135827456-d3c0ddc4-f0ea-4dad-b804-9bbfc5a1ccdc.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only):  WhiteSur-dark
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

**Comment by black7375** [comment]
Thank you so much for the report.

It's supposed to be provided only on a specific screen, but it's happening in the main window... I think I'll have to do some research.
https://github.com/black7375/Firefox-UI-Fix/blob/46dd6ff743a73c7167432c3f8f2ba09454b14250/userChrome.css#L559

**Comment by black7375** [comment]
I fixed it by installing the Whitesur theme.

**Comment by TheOneKevin** [comment]
Wow, that was fast! Thank you so much, it's fixed now 😃
