### ISSUE TITLE
chrome://browser/content/places/places.xhtml

### ISSUE THREAD

**Issue by kr4ssi** [black7375/Firefox-UI-Fix#236]
Can you include this page too please?

chrome://browser/content/places/places.xhtml

**Comment by black7375** [comment]
What do you mean?

Do you want to proton theme's color?

**Comment by kr4ssi** [comment]
Yes like the settings-page and so on

**Comment by black7375** [comment]
I plan it to go into v4.5

Duplicated #57

**Comment by kr4ssi** [comment]
Sadly it's still not themed.

**Comment by black7375** [comment]
Oh, you're talking about access the content, right?
I'll reflect that in the next version.

**Comment by kr4ssi** [comment]
Yes. Why doesn't it work? Does it have to be in userContent.css too?

**Comment by black7375** [comment]
Yes, It should be defined in `userContents.css` as it is accessing by content, not by chrome(window).

**Comment by kr4ssi** [comment]
```
'use strict';

const css = require('css')
const fs = require('fs')

const userChrome = css.parse(fs.readFileSync('../userChrome.css', {
  encoding: 'utf8'
}))
userChrome.stylesheet.rules = userChrome.stylesheet.rules.find(rule => {
  return rule.type === 'media'
}).rules.filter(rule => {
  return rule.document === 'url("chrome://browser/content/places/places.xhtml")'
})
fs.writeFileSync('../places_userContent.css', css.stringify(userChrome))
```
`@import url("places_userContent.css");`

I'm even getting updates now, but would still be cool if you include it in your project, or even some sort of modular builder, so you don't have to put it into two files.

**Comment by kr4ssi** [comment]
Ok, seems there are missing some other rules. Like for inputs and Contextmenus. Damn.

**Comment by kr4ssi** [comment]
For inputs, I had to remote "html|" from:
`      #detailsPane html|input {
`

**Comment by kr4ssi** [comment]
Any hint what I have to import for context-menus?

**Comment by kr4ssi** [comment]
I think it's themed now, but in bright-mode.
![grafik](https://user-images.githubusercontent.com/44404263/143670646-8affe61d-b329-467c-a7cd-8a41adbc8437.png)

**Comment by kr4ssi** [comment]
Forgot to change branch, works like a charm!

Is it possible to change the context-menu too?

**Comment by black7375** [comment]
There are still some issues and that's why it's on the development branch.
I think it would be possible to change the context menu as well.

**Comment by kr4ssi** [comment]
Sounds promising!
Another thing I just noticed is that the muted-icon isn't in the upper left corner, maybe because the page doesn't have a favicon?

**Comment by black7375** [comment]
If there is no favicon, the sound button takes its position.
It's intentional UI/UX that makes it easy to press.

**Comment by kr4ssi** [comment]
The other rule with icons is missing:
https://github.com/black7375/Firefox-UI-Fix/blob/master/userChrome.css#L3827

**Comment by kr4ssi** [comment]
Great work, man! Only issue left is that the context-menu is still white, I don't know how to take a screenshot since it disappears when I take one.

**Comment by kr4ssi** [comment]
I really appreciate that you put that much work into it, since probably not a lot of users use this page in this way. I just wonder why the context-menu is white because it's not even default?

**Comment by black7375** [comment]
Can you tell me your system environment?
- OS
- Desktop Environment
- GTK Theme(run `gsettings get org.gnome.desktop.interface gtk-theme`)

**Comment by kr4ssi** [comment]
Mint 20.2
Cinnamon
Mint-Y

**Comment by black7375** [comment]
Linux follows the GTK theme.
Toggling dark mode on Cinnamon desktop works fine.

![Linux mint-2021-12-02-09-50-09](https://user-images.githubusercontent.com/25581533/144338744-5c6ad6fa-cd04-435c-b2e5-b7e610c38099.png)
![Linux mint-2021-12-02-09-58-52](https://user-images.githubusercontent.com/25581533/144338757-1f77de49-cfbd-47a0-9fe6-fdda020e4391.png)
![Linux mint-2021-12-02-09-46-48](https://user-images.githubusercontent.com/25581533/144338762-d76b5401-7c36-4e08-80ef-8824233ac150.png)
![Linux mint-2021-12-02-09-49-27](https://user-images.githubusercontent.com/25581533/144338780-a301afc0-8a34-4385-ba48-920ac696707d.png)

**Comment by kr4ssi** [comment]
I played a bit around and I can't get it to work. The thing is in the popup and on every other Page the Contextmenu has the correct color. Also my theme isn't Mint-Y, idk why gsettings outputs it.
![grafik](https://user-images.githubusercontent.com/44404263/144705764-62f40f7d-7005-481c-b492-0b3d4415a7a5.png)

**Comment by black7375** [comment]
As far as I know you just change the control and it works fine in the VM.

![Linux mint-2021-12-05-15-25-24](https://user-images.githubusercontent.com/25581533/144736516-3dda6030-7c9e-41f0-90f6-e78287dee0d1.png)

**Comment by black7375** [comment]
I think we've done enough implementation to close this issue.
