### ISSUE TITLE
a11y: Contrast: Low in linkbox on SUMO (support.mozilla.org)

### ISSUE THREAD

**Issue by Jonta** [black7375/Firefox-UI-Fix#238]
**Describe the bug**
- Dark mode
- Go to https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings
- The warning box `div.warning:nth-child(5)` has background colour #D7B600 (rgb (215, 182, 0)) and non-visited link colour #00DDFF (rgb(0, 221, 255))

**Expected behavior**
High enough contrast

#
**Screenshots**
![contrast-sumo](https://user-images.githubusercontent.com/359397/136005385-009d9768-c18c-440e-965f-59ef03585bab.png)

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): Layan-dark-solid
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

https://contrast-finder.tanaguru.com/result.html?foreground=00ddff&background=d7b600&ratio=4.5&isBackgroundTested=false&algo=Rgb

Contrast ratio is 1.20849, Tanaguru recommends at least 4.5

**Comment by black7375** [comment]
https://contrast-finder.tanaguru.com/result.html?foreground=%2337ffff&background=%23715100&ratio=4.5&isBackgroundTested=false&algo=Rgb

- Valid Contrast : 5.87349
