### ISSUE TITLE
Photon Style light theme color

### ISSUE THREAD

**Issue by black7375** [black7375/Firefox-UI-Fix#24]
**Is your feature request related to a problem? Please describe.**
https://www.reddit.com/r/firefox/comments/nly44l/this_week_proton_fixwill_be_called_lepton_tab/h075uu4?utm_source=share&utm_medium=web2x&context=3

> I prefer when all programs has similar design on the system. Windows 10 by default has light titlebars (light theme by default). But Firefox has light controls with dark titlebar (system theme), but it can be fixed by switching to the light theme. And light theme in your fix differs from original photon
> u/Yoskaldyr

**Describe the solution you'd like**
We can consider adjusting color.

**Additional context**
It's just something to keep in mind.

**Comment by black7375** [comment]
There may be a problem with forcing the size to be specified.

**Comment by TurtleDino** [comment]
Plus one-ing this issue. Someone on Reddit said the following. Not sure if it’s related to Photon or Lepton. 

“right now it optimized only for dark theme :( light theme is only partially usable :(

I hope in the nearest future it will be fixed for all standard themes (default, dark, light)”

**Comment by black7375** [comment]
Refer for Contrast ratio
https://bugzilla.mozilla.org/show_bug.cgi?id=1704347#c25

**Comment by black7375** [comment]
It retains feel and add contrast.
```css
:root[lwtheme-mozlightdark][lwthemetextcolor="dark"] {
   --lwt-accent-color: #E5E5EB !important;
}
```

**Before**
![image](https://user-images.githubusercontent.com/25581533/124208021-3f03c400-dad6-11eb-932d-2e775bd94f67.png)

**After**
![image](https://user-images.githubusercontent.com/25581533/124208050-4fb43a00-dad6-11eb-9e97-5b8447ee4331.png)
