### ISSUE TITLE
4.2: Odd Blue border glitch in Light theme download prompt

### ISSUE THREAD

**Issue by Pentaphon** [black7375/Firefox-UI-Fix#241]
**Describe the bug**
Odd Blue border glitch in Light theme download prompt

**Expected behavior**
There shouldn't be any border around "save file"

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/49374058/136502472-b6320c66-1a45-4cfc-8e79-2b9d8032ecdc.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 93.0
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [x] Light
   - [x] Dark
   - [x] Alpenglow (System: Light)
   - [x] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**
None

**Comment by black7375** [comment]
All right. I plan to fix it over the weekend.

**Comment by black7375** [comment]
Now, Fixed!!
