### ISSUE TITLE
Allow icons on the menu bar to be disabled and maybe one other thing.

### ISSUE THREAD

**Issue by 1031982** [black7375/Firefox-UI-Fix#243]
This is me coming from version 2.2.3 to 4.20.

**Is your feature request related to a problem?**

I find the icons in the menu bar to be add a thickness I would like to avoid.

Also, not sure if I simply selected the wrong file, if this was a separate fix from else-ware, or if this was a change done with this mod. Upon updating to version 4.20, the tabs switched back to floating bubbles. 

**The solution I'd like**
I would like the ability to no have icons on next to the listings on the menu bar. Either instructions on how to disable them by editing the required file(s), or a toggle.

In relation to the tab appearance, before I have them as an old style selection. I have included a screenshot of the tabs how I would like them if it's possible. If I am wrong, and this was something else, I apologize.

**Alternatives I've considered**
At this point, I have simply gone back to version 2.2.3, and if need be I will stay on that version.

**Additional context**
![tabs](https://user-images.githubusercontent.com/9312520/136682689-62b0bfc4-5512-4d03-8940-a9c8c194f6b5.jpg)

**Comment by black7375** [comment]
### Remove Menu bar icons

>  I would like the ability to no have icons on next to the listings on the menu bar. Either instructions on how to disable them by editing the required file(s), or a toggle.

![image](https://user-images.githubusercontent.com/25581533/136697907-f0e92d99-b242-4346-8b73-788f21496abf.png)

Remove this codes
https://github.com/black7375/Firefox-UI-Fix/blob/7acbf850ec212602c5845b640a2fb887e8d93bc9/userChrome.css#L2590
https://github.com/black7375/Firefox-UI-Fix/blob/7acbf850ec212602c5845b640a2fb887e8d93bc9/userChrome.css#L2634-L2647


> Also, not sure if I simply selected the wrong file, if this was a separate fix from else-ware, or if this was a change done with this mod. Upon updating to version 4.20, the tabs switched back to floating bubbles.

Perhaps you have chosen the wrong distribution.
Lepton consists of original, photon, and proton.

Try to
https://github.com/black7375/Firefox-UI-Fix/releases/latest/download/Lepton.zip

**Comment by 1031982** [comment]
Thank you! Removing those lines worked perfectly, and I did chose the wrong distribution.
