### ISSUE TITLE
Blue border in "Save file" popup

### ISSUE THREAD

**Issue by zloy2452** [black7375/Firefox-UI-Fix#246]
**Describe the bug**
Cancel button has blue border in "Save file" popup.

**Expected behavior**
No blue border.

**Screenshots**
![1](https://user-images.githubusercontent.com/66868535/137142218-7ffb1efe-5d61-4c31-861c-4e0f3a0300d2.png)

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 93.0
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [x] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default

**Comment by black7375** [comment]
It's probably a focus problem, but CSS can't solve it, and accessibility is more important, so I'll close it.
