### ISSUE TITLE
Tab+Navigation bar blinking up on hovering links in websites

### ISSUE THREAD

**Issue by Nomes77** [black7375/Firefox-UI-Fix#248]
**Describe the bug**

Tabbar and navigationbar moving +/- 2px up, when hovering links on websites (`github.com`, `https://www.ibki.nl/`). But when your mouse stays on the link it comes back to normal. It is a sort of blinking up and then down to normal
**Expected behavior**

Doesn't move up
**Screenshots**

Wast possible, blinkign was to fast.
**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version:  93.0
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

**Comment by BPower0036** [comment]
Even on hovering favorites, it happens

**Comment by BPower0036** [comment]
I can't reproduce it either, so maybe my PC and Firefox was a little bit sluggy last saturday afternoon.
