### ISSUE TITLE
Muted-Icon moves upwards some pixels while the tab is loading

### ISSUE THREAD

**Issue by kr4ssi** [black7375/Firefox-UI-Fix#249]
**Describe the bug**
Muted-Icon moves upwards some pixels while the tab is loading

**Expected behavior**
It shouldn't.

**Screenshots**
![7740ec4894bb](https://user-images.githubusercontent.com/44404263/137606154-6995dca0-cd0c-4753-a096-65c33ef60c2a.gif)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): Mint-Y
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**
I use [Mute Tab](https://addons.mozilla.org/de/firefox/addon/mute-tab-webextension/), but it's the same on a fresh profile after manually muting the tab.

**Comment by black7375** [comment]
This will be reflected in the next release.
