### ISSUE TITLE
Download popup with light background on dark theme

### ISSUE THREAD

**Issue by smowtenshi** [black7375/Firefox-UI-Fix#250]
**Describe the bug**
I recently noticed that when downloading files, a pop-up has white background even though I have dark theme set.

**Expected behavior**
The pop-up has background related to the theme.

**Screenshots**
![](https://files.catbox.moe/78d0xn.png)

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [x] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: Nightly 95.0a1 (20211016094819)
 - OS:
   - [x] Linux (Manjaro KDE)
   - [ ] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only):  Breath-Dark
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

Doing as said in https://github.com/black7375/Firefox-UI-Fix/issues/244#issuecomment-940115785 kind of solves the colors. Applying `userChrome.css` from `dev` branch doesn't help at all though. Are these issues related or is it something completely else?

**Comment by smowtenshi** [comment]
This is surprising. I guess I should report it on the Bugzilla.

**Comment by black7375** [comment]
Perhaps this media query doesn't applied properly.
```css
@media (-moz-toolbar-prefers-color-scheme: dark) {
}
```

**Comment by smowtenshi** [comment]
Seems like in https://github.com/black7375/Firefox-UI-Fix/blob/24fe2cfde109094ce3d8be97d7739ead3574f0ba/userChrome.css#L1124-L1137 rules 
```css
color: var(--in-content-page-color) !important;
background-color: var(--in-content-page-background) !important;
```
have that effect on the popup window. Though disabling them.. makes it a little bit weird, as you can see below. ![](https://i.imgur.com/ROCDWGU.png)

**Comment by black7375** [comment]
Now will be works!!
Thanks for the report :+1:

**Comment by black7375** [comment]
Hmm..

**Comment by black7375** [comment]
I found out something interesting.

If `privacy.resistFingerprinting` is `true`, dark mode is not applied to general content.
