### ISSUE TITLE
Updated to Windows 11 and multiple things broke

### ISSUE THREAD

**Issue by ojaha065** [black7375/Firefox-UI-Fix#254]
![problem_1](https://user-images.githubusercontent.com/37581768/138568065-b8482911-3921-474f-afb0-10d5b5e97591.png)
Weird empty space between the icons and the text. Same thing in every menu.
<br/>
<br/>

![problem_2](https://user-images.githubusercontent.com/37581768/138568089-91af12f5-6ccb-4d5a-9f54-365fb4467022.png)
Bookmarks menu is all over the place and icons are not aligned. Also, bookmark elements have larger padding than the other elements in the menu.
<br/>
<br/>

![Näyttökuva 2021-10-23 215537](https://user-images.githubusercontent.com/37581768/138568261-1b81ee26-2cb8-4859-8cde-9382f18b7abd.png)
Same thing in the history menu with the misaligned icons. Also notice the padding.
<br/>
<br/>

![problem_3](https://user-images.githubusercontent.com/37581768/138568282-526d1d79-cfba-431f-868a-daf5e287fd37.png)
Minor thing, but the zoom controls are not centered between the url bar and the search bar. I'm 90% sure they were before.
<br/>
<br/>

![Näyttökuva 2021-10-23 220140](https://user-images.githubusercontent.com/37581768/138568382-8b15078d-d506-411c-b3ff-1cc4f3a7bf68.png)
More misaligned icons in right click context menu
<br/>
<br/>

![problem_4](https://user-images.githubusercontent.com/37581768/138568301-a0a0c1c0-93b6-43db-a7a0-4de6c3f3318a.png)
![problem_5](https://user-images.githubusercontent.com/37581768/138568305-3dd4c76a-8588-4ebe-af75-9645e1094faa.png)
Background of the close, maximize and minimize button is always the same, regardless of the theme of the browser or Windows

**Environment:**

 - Distribution
   - [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 93.0
 - OS:
   - [ ] Linux
   - [X] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [X] Light
   - [X] Dark
   - [X] Alpenglow (System: Light)
   - [X] Alpenglow (System: Dark)
   - [X] System Default
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**
Worked fine before updating to Windows 11. Already installed Lepton with the latest files from the master branch. Firefox in Win11 works fine without Lepton installed.

**Comment by black7375** [comment]
The period is over, so it closes.
