### ISSUE TITLE
Not working for Temporary Containers

### ISSUE THREAD

**Issue by kanlukasz** [black7375/Firefox-UI-Fix#257]
**Describe the bug**
There is no color in tabs for Containers

**Expected behavior**
Before that, there were color lines

**Screenshots**
![tb91](https://user-images.githubusercontent.com/30685349/139063351-8cc76b8e-a6cd-4975-9203-ad5e6ff30889.gif)

**Environment:**

 - Distribution
```
[Info]
Ver=v4.2.2
Branch=photon-style
```
 - Firefox Version:
![image](https://user-images.githubusercontent.com/30685349/139063606-93797c14-5403-4073-9259-b6c66034202f.png)

 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default

**Comment by pickfire** [comment]
Shouldn't we remove color-mix since this is not enabled by default in firefox or to prevent users from having the same issue we mention it in the README?

**Comment by black7375** [comment]
It is recommended to activate it because it is a syntax used in many places such as win7, win8 menu emulation.

**Comment by pickfire** [comment]
Then should we at least add it to the README is part of the installation instructions?
