### ISSUE TITLE
Border around context menu (Lepton `dev` branch)

### ISSUE THREAD

**Issue by smowtenshi** [black7375/Firefox-UI-Fix#259]
**Describe the bug**

Around like a week ago I noticed border appearing around context menu on all elements. It's visible the most on a white background.

**Expected behavior**

Border doesn't appear, just like on a clear browser profile.

**Screenshots**

![](https://files.catbox.moe/zfocv1.png)![](https://files.catbox.moe/dogg15.png)![](https://files.catbox.moe/vn2v43.png)

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [x] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version:  Nightly 95.0a1 (20211031095403)
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only):   Breath-Dark
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

As far as I know, it happens only with `userChrome.css` from `dev` branch. Using the same file from `master` one seems to look fine.

**Comment by gwarser** [comment]
![image](https://user-images.githubusercontent.com/886325/139666201-dc7453e9-9990-45b3-b035-c3dde0ef7b3f.png)

System theme on Manjaro KDE.

**Comment by black7375** [comment]
Does the same appear in the latest commit?
It doesn't appear in my environment
![image](https://user-images.githubusercontent.com/25581533/139675312-b8fb346d-187e-492f-bf48-916fa8231251.png)

**Comment by gwarser** [comment]
Isn't this the latest?

![image](https://user-images.githubusercontent.com/886325/139704010-6849bfe4-8bf7-4488-a11d-d5b7fabf641e.png)

**Comment by smowtenshi** [comment]
> Does the same appear in the latest commit? It doesn't appear in my environment

Seems like it appears both in commit cc4371640cba6ea49863cf7ce49321679d2c4646 on branch `dev` and b598053df86c3c3a56368f5bbf5c18fd972d4d2f on `master`.
![](https://files.catbox.moe/0lzb2q.png) Screenshot shows branch `master` on a clean profile.

It might be also related to bug gwarser mentioned.

**Comment by black7375** [comment]
I just updated Nightly and the bug appears.

**Pure Nigthly**
![image](https://user-images.githubusercontent.com/25581533/139785765-e38c0467-2a4c-4df5-a174-bf90fbc09d5e.png)

And nothing could remove it.
- `padding: 0;`
- `margin: 0;`
- `clip-path: inset(3.5px 3.5px);`
- `background: transparent;`

**Comment by black7375** [comment]
@gwarser  Fortunately, tab border is modifiable.

**Comment by black7375** [comment]
In Pure nightly, the symptom has disappeared, and the patch now works(`v95+`) as well.
It will include at next release.

**Comment by Mark42XLII** [comment]
> In Pure nightly, the symptom has disappeared, and the patch now works(`v95+`) as well. It will include at next release.

The issue persists for me on photon-style.

**Comment by Mark42XLII** [comment]
@black7375 I did a bisect and this got reintroduced on the latest Nightly builds, on commit 7eae852013b66acbfd38f85786d75f16fa188208.

**Comment by black7375** [comment]
That's weird. Could you please create a new issue?
