### ISSUE TITLE
Style over checkbox items

### ISSUE THREAD

**Issue by Mitezuss** [black7375/Firefox-UI-Fix#260]
**Describe the bug**

Style on the checkbox menu

**Expected behavior**
Should be like another styles (like menutiems)

**Screenshots**
![0](https://user-images.githubusercontent.com/35956777/139786302-154227f4-f977-4c5a-8627-4630a9357161.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
   
**Additional context**
See the borders of both styles on the screenshot

**Comment by black7375** [comment]
Yes. It should be based on the style of the checkbox (Default Style).

\+ Info
Borders and padding can be mimicked, but background gradients are hard to fully emulate.

**Comment by Mitezuss** [comment]
@black7375

but can change the style of the checkbox to like another ? for have all same

**Comment by black7375** [comment]
If the `appearance` of the checkbox or radio box is set to `none`, the check mark does not appear.
This is a pretty big problem.

**Comment by Mitezuss** [comment]
I see, ok.

Maybe is not for this issues, but:

what about redo icon? paste and go ? and miss another icons

**Comment by black7375** [comment]
I haven't found a suitable icon yet.

**Comment by Mitezuss** [comment]
@black7375 

Can do this style, for checkbox ? (windows 7):

![0](https://user-images.githubusercontent.com/35956777/140654163-7f578dd7-f7fb-4fdb-9022-6b76b4fd5754.png)
