### ISSUE TITLE
Icon for downloads > Copy Location

### ISSUE THREAD

**Issue by Mitezuss** [black7375/Firefox-UI-Fix#261]
**Describe the bug**
Not showing the icon on Firefox 93

**Expected behavior**
Show the icon

**Screenshots**

Not showing, using:
```
  #downloadsContextMenu > menuitem[command="downloadsCmd_copyLocation"] {
    --menuitem-image: url("chrome://browser/skin/link.svg");
  }
```
![1](https://user-images.githubusercontent.com/35956777/139803669-6cf3583c-eab3-40af-8bb8-5d1b9fb75721.png)

Fix with:
```
  #downloadsContextMenu > menuitem[command="cmd_copy"] {
    --menuitem-image: url("chrome://browser/skin/link.svg");
  }
```

![0](https://user-images.githubusercontent.com/35956777/139803786-1f112b54-f0fe-49d0-85b5-1abe48751c09.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default

**Additional context**

Check the fix.

Regards.

**Comment by black7375** [comment]
The path of the icons has been changed in Nightly, and is included for compatibility.
