### ISSUE TITLE
text selected on new bookmark

### ISSUE THREAD

**Issue by Mitezuss** [black7375/Firefox-UI-Fix#263]
**Describe the bug**
White color

**Expected behavior**
Black color

**Screenshots**

![1](https://user-images.githubusercontent.com/35956777/139946007-f31bb7a4-0197-4f3a-8dca-5f327964fdf5.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default

**Additional context**
Default style (without css):
![2](https://user-images.githubusercontent.com/35956777/139946127-df63a884-97f6-42ba-b659-f40520ad229e.png)

**Comment by Mitezuss** [comment]
For light theme, workaround:
```

    #editBMPanel_folderMenuList menu:not([disabed], :active)[_moz-menuactive="true"],
    #editBMPanel_folderMenuList menuitem:not([disabed], :active)[_moz-menuactive="true"] {
      color: black !important;
    }
```

**Comment by Mitezuss** [comment]
workaround for light theme:

```
    #editBMPanel_folderMenuList menu:not([disabed], :active)[_moz-menuactive="true"],
    #editBMPanel_folderMenuList menuitem:not([disabed], :active)[_moz-menuactive="true"] {
      color: black !important;
    }
```

**Comment by black7375** [comment]
Now will be support colorful background.

**System Default - GTK**
![image](https://user-images.githubusercontent.com/25581533/140251163-3b4b5ad2-2c4b-4534-8563-cfe3e252e931.png)
**Light**
![image](https://user-images.githubusercontent.com/25581533/140250959-507d0ead-9666-4874-9888-e2bad0912de1.png)
**Dark**
![image](https://user-images.githubusercontent.com/25581533/140251075-1236081c-d493-4fc2-b9ed-9ee8b97b1a45.png)
**Alpenglow**
![image](https://user-images.githubusercontent.com/25581533/140251547-53a91044-fe28-4dc8-a54c-09b6da423463.png)
