### ISSUE TITLE
Scroll speed being disobeyed 

### ISSUE THREAD

**Issue by q64ceo** [black7375/Firefox-UI-Fix#264]
Love the fix, dude! However for some reason your fix has slowed down my custom scroll speed. I cannot figure out how to make it obey the min scroll amount. In all of your themes. I've played around with user.js but I cannot find the specific reason why it's going against my min scroll speed.

EDIT: was able to correct it within about:config. Could you add something to your documentation to help others who are in my situation?

**Comment by black7375** [comment]
The scrolling feature will be removed in the next major version(`v4.5`).  #225
