### ISSUE TITLE
Suggestion: Hide VPN promo from private browsing new tab

### ISSUE THREAD

**Issue by bbigam** [black7375/Firefox-UI-Fix#265]
**Is your feature request related to a problem?**
New VPN promo in Private Browsing new tab - basically an ad, in Firefox 94

**The solution I'd like**
I'd like it to be gone, and I have code for it! This in userContent.css will do the trick:
```
    /** Private Browsing ***************/

    /* Remove VPN promo */

    html.private .promo {
    display: none !important;
    }

```
**Alternatives I've considered**
Not needed

**Additional context**
It works!

**Comment by bbigam** [comment]
Note: I couldn't find any about:config options that fixed this specific issue, though I tried several vpn, promo, or privatebrowsing options.

**Comment by black7375** [comment]
It can add the following code to file `userContent.css`.
```css
  @-moz-document url("about:privatebrowsing") {
    .promo {
      display: none !important;
    }
  }
```

Since sustainable development is possible only when Mozilla can earn a profit, I think it is better to keep the default value unless it is excessively degraded in usability or infringing on privacy.
