### ISSUE TITLE
Rounded corners (Windows)

### ISSUE THREAD

**Issue by macruspareto** [black7375/Firefox-UI-Fix#266]
First of all, thanks for your effort, Black! Just by looking into the Open/Closed Issues section, I can only imagine how much of your personal time has been put into this project...

I use Firefox on Win 8.1 and on Linux Xubuntu. 
To my personal taste, the new Proton UI (rounded corners, detached tabs, bold fonts, bold frames) is more coherent with Linux, I just decided to keep it without any customization.

But on Windows, with sharp corners everywhere and thinner fonts, do you think you could tweak the url bar and the search bar, remove this "roundedness" and make it thinner?

(Also, the Min/Max/Close buttons are blacked, need to comment out 2 lines in the user.css as someone has suggested).

Thanks!

![Untitled](https://user-images.githubusercontent.com/62118677/140626298-b72b80a6-6271-4124-b648-9ceb9fbcd4f3.png)

**Comment by black7375** [comment]
Strangely, this bug is not reproducible.
Can I get information about `about:support` - `Copy text to clipboard`?

**Comment by black7375** [comment]
Try using version `5.0.0` options.
https://github.com/black7375/Firefox-UI-Fix/blob/0fd746b1ce75579b44916c7f4fb73e7673e819e0/user.js#L71-L77

---

Min/Max/Close buttons are blacked resolved at #218
