### ISSUE TITLE
Add an easy to find means (e.g. css variable at the top) for removing icons from main menubar for photon version

### ISSUE THREAD

**Issue by redmasq** [black7375/Firefox-UI-Fix#267]
**Is your feature request related to a problem?**
The 89 and previous version of Firefox under windows did not have the icon preceding the menu on the main bar.

**The solution I'd like**
Since some people may actually like the icon (I hate it, but I can see the appeal to some), a CSS property with a 1 or 0 might could be used to turn off the padding using multiplication. I am wondering if a negative margin can be used to hide the icon without removing it. Otherwise, notation as comment of the line number start for the rule to comment will have to suffice.

**Alternatives I've considered**
At the very least, add comment at the top that contains the line numbers to edit. Also, a prebuilt package with that variant would suffice as well, but yet one more thing to maintain.

**Additional context**
Thanks for making this in the first place. Saved me a ton of trouble.

**Comment by redmasq** [comment]
To get the end result for which I was hoping, I did the following to userChrome.css:

- Commented started at 3574 to 3595.
- Removed the additional padding on 2695
- Changed the padding on 2700 to 3px from the 19px that was there.

**Comment by black7375** [comment]
After `v4.5` was released, I was thinking of making them all with the same CSS settings in the next update.

Firefox has a syntax that can determine whether or not CSS is applied based on the existence of a setting in about:setting.
```css
@supports -moz-bool-pref("ABOUT.CONFIG.SETTTING.NAME") {
}
```

**Comment by redmasq** [comment]
I wasn't aware of that particular feature, but I don't do a lot of work with the userChrome. It sounds like a plan at least.

**Comment by black7375** [comment]
Try using version 5.0.0 options.
https://github.com/black7375/Firefox-UI-Fix/wiki/Options#remove-menubar-icon
