### ISSUE TITLE
Animations should not be enabled by default

### ISSUE THREAD

**Issue by kanlukasz** [black7375/Firefox-UI-Fix#268]
**Is your feature request related to a problem?**

I'm not sure that animations should be enabled by default.

Of course, this is debatable according to personal taste, but there is no benefit to it, and it raises a problem because now any user who wants to disable it must always overwrite / modify the new version

**Alternatives I've considered**

I don't know if this is possible, but it might be a good idea to separate CSS modules into separate files and use `@import` in the `userChrome.css` file? Then it would be easier to **turn on / off** new features

What do you think?

**Comment by smowtenshi** [comment]
I think even with `@import` directives, you'd have to modify main file every update to turn features on/off, wouldn't you?

**Comment by black7375** [comment]
1. Removed animations for menus and menu items that could appear dull.
2. Now,  If you use a setting that makes less motion, it will be disabled.
3. As I wrote in issue #267, I'm planning to make it adjustable via `about:config`.

**Comment by kanlukasz** [comment]
> 
> 
>     1. Removed animations for menus and menu items that could appear dull.
> 
Mainly I meant this new animations of tabs :-)

>     2. Now,  If you use a setting that makes less motion, it will be disabled.
Which setting you mean? Where can i find it?
> 
>     3. As I wrote in issue [Add an easy to find means (e.g. css variable at the top) for removing icons from main menubar for photon version #267](https://github.com/black7375/Firefox-UI-Fix/issues/267), I'm planning to make it adjustable via `about:config`.

Wow that sounds great!

**Comment by black7375** [comment]
Related information can be found here.
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion#user_preferences

**Comment by kanlukasz** [comment]
Okay, so if I understand correctly, having animations turned off in Windows  ( `Windows 10: Settings > Ease of Access > Display > Show animations in Windows` ) , future versions of `Firefox UI FIX Photon` will obey this setting and animations will be turned off, right?

**Comment by black7375** [comment]
Yes, All right

**Comment by kanlukasz** [comment]
With 4.5.1 works fine, thanks
