### ISSUE TITLE
Drop-down panel (Edit Bookmark) text unreadable 

### ISSUE THREAD

**Issue by kstev99** [black7375/Firefox-UI-Fix#269]
When using practically any DARK theme except for System Default, the Edit Bookmarks Panel activated with the star in address bar is too dark to read or edit when not highlighted. 

**Expected behavior**
The bookmarks panel information should be readable whether the content is highlighted or not

Images are while using Beautiful GX Proton theme which looks great except for this issue
When text is not selected:
![image](https://user-images.githubusercontent.com/32485060/141658393-eb41bafe-db80-419a-aff1-0b0cf47d6cf5.png)
Text Selected when opening Edit Bookmarks Panel (Star)
![image](https://user-images.githubusercontent.com/32485060/141658490-ce74252a-4f5a-4973-867f-b8fdf1531604.png)

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [X] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version:  	94.0.1
 - OS:
   - [ ] Linux
   - [X] Windows 10
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [X] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     

**Additional context**
 I have tried Proton Dark, New Opera Dark, Argon, Proton V2 themes just to name a few of many,  I have added code to the bottom of the userchrome and usercontent to maintain some of my preferences,  (Sorry for the bad coding, but it works)  attaching those two files in case this is something that I have added
[chrome.zip](https://github.com/black7375/Firefox-UI-Fix/files/7532740/chrome.zip)

**Comment by black7375** [comment]
I added field color.

**Comment by kstev99** [comment]
Thanks!  That helped.  Do you mind telling me what line you changed?  I would like to play around with variables

**Comment by black7375** [comment]
https://github.com/black7375/Firefox-UI-Fix/commit/ee8a08cdaa6b518fc7323b5c6133fff399d17340

This  is `1076` line.

**Comment by kstev99** [comment]
Thanks for all you do.  Issue fixed
