### ISSUE TITLE
The 'New tab' button is in a different location from the settings. 

### ISSUE THREAD

**Issue by Johndoe0153** [black7375/Firefox-UI-Fix#270]
**Describe the bug**

Umm... I'm not sure about this bug. Maybe it likes it was just originally did. So If I'm wrong plz let me know :(

So I found - maybe - a bug in new tab button. I set that button on the end of right side in the toolbar settings. But after quit from setting and after I start firefox again, it just moved into right of tab.

Therefore, if this is the actually bug, I hope we can fix it ASAP. Thank you for your effort XD And sorry for English :(

**Expected behavior**

I expect that it will locate where I set.

**Screenshots**

![bug1](https://user-images.githubusercontent.com/87603390/141730603-766cc8b1-df22-4293-9e5a-7cf29fef803e.png)
![bug2](https://user-images.githubusercontent.com/87603390/141730605-47b4c7cc-dbaa-4399-a266-8c08fcb4e3fc.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [x] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/)) I use [Monte Cristo](https://addons.mozilla.org/ko/firefox/addon/monte-cristo/) theme.

**Additional context**

Addtionally, my Windows' version is Windows 11.

**Comment by black7375** [comment]
It's weird.
In my environment, works well :cry: 
![image](https://user-images.githubusercontent.com/25581533/141734621-1c059ad6-911d-458e-a8bc-a8558af6beb4.png)
![image](https://user-images.githubusercontent.com/25581533/141734675-3dd86f49-a688-4de3-89fe-e2cd9b1ba189.png)
