### ISSUE TITLE
+ disappears when hovering over the New Tab button

### ISSUE THREAD

**Issue by 10Meisterbaelle** [black7375/Firefox-UI-Fix#271]
https://user-images.githubusercontent.com/45918080/141786424-67cdd47a-1dbc-4e73-a76c-93b2f26fc1b4.mov

**Comment by Johndoe0153** [comment]
I think you have to discribe your enviroment... Such as "I use Windows and default dark theme."

It will make much more helpful to fix the bug :)

**Comment by black7375** [comment]
Are you using
- Mac OS
- System Default Theme
- Proton Style

?

I recently did a simple bug patch.

**Comment by 10Meisterbaelle** [comment]
Yes, but this bug also occured in Photon Style. I will try it out later.

MS_Y ***@***.***> schrieb am Di., 16. Nov. 2021, 06:12:

**Comment by black7375** [comment]
It's probably been fixed.
Please let me know if you have any issues with the latest version as well.

**Comment by 10Meisterbaelle** [comment]
It is fixed

MS_Y ***@***.***> schrieb am Do., 25. Nov. 2021, 02:22:
