### ISSUE TITLE
Library-Popup stays dark in bright-mode

### ISSUE THREAD

**Issue by kr4ssi** [black7375/Firefox-UI-Fix#272]
**Describe the bug**
The Library-Popup looks the same in non-dark-mode as in dark-mode just with some white borders.

**Expected behavior**
Bright background and Inputs as in Settings-Page.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/44404263/141881988-40666d0b-64ee-4476-bf5a-18434108dacb.png)

**Environment:**
 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [x] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

**Comment by black7375** [comment]
Property `-moz-toolbar-prefers-color-scheme` disappeared from nightly. #250
Instead, nightly supports `prefers-color-scheme`'s browser theme style.
However, In lower versions of Firefox, it(`prefers-color-scheme`) only follows the system theme.

`prefers-color-scheme` is currently applied for compatibility.
Therefore, if the system theme is dark mode series, dark mode is applied.
It's a bit of a complicated compatibility issue and probably the intended result.

Please let me know if the system theme is light.

**Comment by kr4ssi** [comment]
System Theme is a mix of different mostly Dark GTK-Themes, but changing them doesn't change the colors in the popup. I don't really care, since I use the dark theme. I just noticed it.

**Comment by temporarium** [comment]
lepton v4.5.1 on latest firefox on Plasma desktop

![Screenshot_20211119_191805](https://user-images.githubusercontent.com/4754345/142706606-6ab70917-dbd5-475c-847d-5dc5df0966ac.png)

![Screenshot_20211119_192006](https://user-images.githubusercontent.com/4754345/142706653-1b17402e-e1a4-45d5-995f-4c625e8887ff.png)

**Comment by black7375** [comment]
@temporarium 

What's your desktop environment  and GTK Theme?

- GTK theme: run `gsettings get org.gnome.desktop.interface gtk-theme`

**Comment by temporarium** [comment]
Plasma Breeze Dark.
`gsettings get org.gnome.desktop.interface gtk-theme` reports 'Default'

On another system with XFCE: 'Adwaita' - same issue. Only in the "Libraries" window. The rest of the interface is excellent!!!

**Comment by black7375** [comment]
@temporarium I think I've found the cause. Would you like to test it?

**Comment by temporarium** [comment]
> @temporarium I think I've found the cause. Would you like to test it?

Of course! Though I'm not using proton or photon, just the default lepton.

**Comment by temporarium** [comment]
4.5.2 fixed the issue! Thank you

![Screenshot_20211125_083053](https://user-images.githubusercontent.com/4754345/143450549-bdbb61be-176d-4040-bb3f-a7ab6be6ea63.png)
!
