### ISSUE TITLE
How do I disable fade/fading in context menus?

### ISSUE THREAD

**Issue by mid-kid** [black7375/Firefox-UI-Fix#273]
**Describe the bug**
Prior to a recent update, the highlight color in context menus would just pop in and out when moving the cursor around. This has now changed and it now fades the color in and out.

**Expected behavior**
I want it to pop in and out like the old behavior

**Screenshots**
Can't really screenshot context menus. Just right-click anywhere.

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [x] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): Adwaita
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**
If this is a stylistical change you intend to keep I don't see anything wrong with it, but I'd love to know where in the code the relevant CSS rule lives so I can patch it out. I just find it distracting and being inconsistent with the rest of the system bothers me.

**Comment by black7375** [comment]
Could you try v4.5.1?
Context menu fade animation is removed!!
