### ISSUE TITLE
Close Tab "X" Invisible

### ISSUE THREAD

**Issue by 200computer** [black7375/Firefox-UI-Fix#274]
**Disclaimer:** This is my first github issue request, please have mercy. I am a novice/enthusiast at python, node, javascript, css/bootstrap and IOT. My first programs were in QBasic and on a TI-83+.

**Issue:** The "x" that should appear on hover for closing a tab is not visible. The container(?) for it changes to a darker background and functions as expected by single click to close tab, but no "x" appears. I "installed" via the fix at https://www.ghacks.net/2021/05/09/how-to-fix-the-firefox-89-user-interface/ . I browsed through the userChrome and userContent css files but didn't see anything that jumped at me for a fix. I am a css novice but would be glad to attempt a fix (even if just for me) if someone would point me at the right line of code. Thanks to the developer and the community for this awesome tool by the way! Firefox user that I can be sure of since 2003~(guess it was 2004!) (back when it was cool(?) and new to have a gmail! (again, guess it was 2004!))

**normal:**
![image](https://user-images.githubusercontent.com/94572734/142708560-4ae3d9a0-95c0-4072-9f17-0fc46ea08acb.png)

**on hover:**
![image](https://user-images.githubusercontent.com/94572734/142708055-25071c06-1424-4ef1-ac38-b64e6b804e62.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 94.0.1
 - OS:
   - [ ] Linux
   - [x] Windows 10 Pro 21H1
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [x] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

**Comment by black7375** [comment]
The problem is that the `icons` folder is not copied.
I also recommend setting user.js as well.

https://github.com/black7375/Firefox-UI-Fix/wiki/Installation-Guide#3-copy-files
