### ISSUE TITLE
Some add-on icons are off-centered in context menus in Windows 7/8.x

### ISSUE THREAD

**Issue by mattprkr2** [black7375/Firefox-UI-Fix#275]
**Describe the bug**
In Windows 7/8.x, some add-on icons on the context menu (by right-clicking on the page or tab) are not centered (shifted to the right, touching the line). 
Sometimes, certain add-on icons are centered on the context menu.

**Expected behavior**
Some add-on icons on the context menu must be centered.

**Screenshots**

![1](https://user-images.githubusercontent.com/94847618/142901923-d73fdcd3-8102-4e25-96d3-63b528278cea.PNG) ![2](https://user-images.githubusercontent.com/94847618/142902020-abcd1812-56eb-44f5-a5e8-6e11b3174341.PNG)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [x] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 94.0.1 (release), 95.0b10 (Beta/Developer Edition), 96.0a1 (Nightly)
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [x] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**
I'm not good or have no experience at CSS editing. Also, I never used a userChrome.css file in Firefox before because I'm not aware that UI customization is possible on Firefox until I found this interesting project.

**Comment by black7375** [comment]
Thanks for report!!
I'll check it.

**Comment by black7375** [comment]
It's been fixed.
