### ISSUE TITLE
`-moz-proton` blocks `userChome.css` from being applied in Nightly 20211123094249

### ISSUE THREAD

**Issue by smowtenshi** [black7375/Firefox-UI-Fix#276]
**Describe the bug**

After upgrading to the newest build of Nightly, which is 20211123094249, `userChrome.css` stops working. Removing `(-moz-proton)` in line 4 seems to fix the issue (and doesn't raise warnings in Browser Toolbox as shown in Screenshots).

**Expected behavior**

**Screenshots**

![screenshot](https://user-images.githubusercontent.com/7839556/143037613-95fc2d66-b4e4-4a09-9265-c2fcca9aef58.png)

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [x] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

**Comment by black7375** [comment]
Confirmed.
I will check several compatibility such as firefox esr and proceed with removal.

**Comment by fournm** [comment]
I could be mistaken, but seems like something else is up with this on Photon style at least. Removing the -moz-proton query didn't seem to resolve it.

**Comment by Valmar33** [comment]
Photon style also remains borked for me on Nightly, despite the removal of `-moz-proton`.

**Comment by smowtenshi** [comment]
I suggest you open separate issue for Photon style.

**Comment by Valmar33** [comment]
> I suggest you open separate issue for Photon style.

Oops. I meant Proton, not Photon. :/

**Comment by black7375** [comment]
It seems to work without a big problem when removed.

---

Applied to development branches.
- `dev`
- `photon-style-dev`
- `proton-style-dev`

**Comment by Valmar33** [comment]
@black7375 

I think you forget to push it to the photon-style-dev branch too.

**Comment by jkhsjdhjs** [comment]
Yes, thanks for the hint, was wondering why the photon style still wouldn't work. I just applied it locally and it works again!

**Comment by black7375** [comment]
Oh that's right
Just applied and pushed.
