### ISSUE TITLE
Lepton Photon Version 4.5.2 changes Tab Style

### ISSUE THREAD

**Issue by Greek64** [black7375/Firefox-UI-Fix#278]
**Describe the bug**
Version 4.5.2 significantly changes the Tab Style of Photon Style.

**Expected behavior**
Same Tab Style as can be seen in the Readme.

**Screenshots**
4.5.1:  
![4 5 1](https://user-images.githubusercontent.com/32879245/143414972-441912fc-18a7-4daf-83c6-3cc20e9cebc8.jpg)

4.5.2:  
![4 5 2](https://user-images.githubusercontent.com/32879245/143415111-01eaf8d9-6fca-4c33-befe-ad11a0f5d1c4.jpg)

**Environment:**
 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 91.3.0esr
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Comment by black7375** [comment]
Hello, Your OS looks win7.

---

It's probably set to `proton style`.

**Photon Style**
![Win7-2021-11-25-19-37-06](https://user-images.githubusercontent.com/25581533/143426617-28f76a27-e49f-425e-badc-28cd07abd64f.png)

**Proton Style**
![Win7-2021-11-25-19-42-11](https://user-images.githubusercontent.com/25581533/143427047-f9e0de4f-86ba-47a3-a0e0-9d70798d6b6b.png)

**Comment by Greek64** [comment]
> Hello, Your OS looks win7.

Correct.

> It's probably set to `proton` style.

After re-investigating, you are indeed correct.
It is completely my fault. I usually download the zips from the release page and rename them to `Lepton-Photon-Style_vx.x.x`. Apparently I downloaded the Proton zip and re-named it to Photon, which arose this confusion (and prevented me from thinking this is the wrong zip).
Sorry for the noise (And thanks for the project)

**Comment by black7375** [comment]
No problem.
Names are similar, so it's easy enough to make a mistake.
