### ISSUE TITLE
userChrome.css not applied on Firefox nightly

### ISSUE THREAD

**Issue by fournm** [black7375/Firefox-UI-Fix#279]
**Describe the bug**

After upgrading to Nightly 2021-11-23 (and persisting to 2021-11-25 so far), userChrome.css is not applied. This does not seem to be tied to the same issue as the -moz-proton removal for the proton style.

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

**Comment by black7375** [comment]
Could you try
- https://github.com/black7375/Firefox-UI-Fix/archive/refs/heads/photon-style-dev.zip

**Comment by gbl08ma** [comment]
I had the same problem as the issue author and that one worked for me, phew. Was about to curse about the removal of userChrome support.

**Comment by Noodles-321** [comment]
> Could you try
> 
>     * https://github.com/black7375/Firefox-UI-Fix/archive/refs/heads/photon-style-dev.zip
>       ?

Thanks! I met the same problem in 96.0. But this one works.  

I was using Developer Edition with Lepton. It worked perfectly in 95.0, but stopped working after upgrading to 96.0. I suppose this is also related to #287?

**Comment by black7375** [comment]
All right.
A patched version has been released.
