### ISSUE TITLE
Allow browser.tabs.drawInTitlebar to be set by user

### ISSUE THREAD

**Issue by Fabian42** [black7375/Firefox-UI-Fix#281]
**Is your feature request related to a problem?**
The option to show a title bar gets turned off on every start of Firefox. This is very confusing behaviour and it took me a while and some help by a Bugzilla user to figure out that this customisation causes it. Settings that the user changes manually should be kept.

**The solution I'd like**
Remove line 3 of `user.js`.

**Comment by smowtenshi** [comment]
I suggest you removing that line manually.

**Comment by Fabian42** [comment]
I did, but of course that doesn't apply to everyone using this.

**Comment by Me4Linux** [comment]
Fabian42 has got a point. It's quite easy to configure the tabbar to show up or not but by setting "browser.tabs.drawInTitlebar" permanently to "true" in user.js this choice is taken away from the user. Yes it can be circumvented (removing or commenting the line) but I guess for a lot of users simply don't know that.

**Comment by black7375** [comment]
I forgot to comment.
I think the current value is a better default, but I don't think it's bad to leave it to the user's choice.
