### ISSUE TITLE
Inactive pinned tabs do not use their full width.

### ISSUE THREAD

**Issue by cjkr** [black7375/Firefox-UI-Fix#282]
**Describe the bug**
Inactive pinned tabs do not use their full widths. This behaviour is intermittent however.

**Expected behavior**

Inactive pinned tabs should have the same width as active pinned tabs.

**Screenshots**

![Screenshot_20211128_091904](https://user-images.githubusercontent.com/7858684/143731987-e76c672f-72bc-422d-a721-d43ca3f9492c.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 94.0.2
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): Materia-compact
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

About 50% of the time, this problem does not arise and all the pinned tabs have equal width.

**Comment by cjkr** [comment]
It appears that this problem was solved with a Firefox update. Updating to Firefox 95.0.1 apparently solved the issue.

**Comment by black7375** [comment]
It was difficult to reproduce, but I'm glad

**Comment by cjkr** [comment]
I realize that the problem had not been solved. To reproduce the bug, have at least two pinned tabs. Focus on the left-most tab and close Firefox. When you reopen it, with the focus on that left-most tab, the widths of the other tabs should be reduced as shown in the original submit.

**Comment by black7375** [comment]
![image](https://user-images.githubusercontent.com/25581533/153530454-4412a1ab-f6ec-44f2-b413-53a2dfb4e0ab.png)
I'm trying continuously, but it's not easy.
Will you be able to test the reproduce procedure or provide it as an video?

**Comment by black7375** [comment]
![image](https://user-images.githubusercontent.com/25581533/153708648-acfdc25f-e281-4b60-beae-37e664f83cdc.png)
![image](https://user-images.githubusercontent.com/25581533/153708667-a8f2aa05-7595-41e8-af93-f180eb08ff2f.png)

I succeeded in reproducing it.
It seems like Firefox itself is a problem.
I'll report it.

**Comment by black7375** [comment]
I think I accidentally resolve a bug!
@cjkr Could you test it?

**Comment by cjkr** [comment]
> I think I accidentally resolve a bug! @cjkr Could you test it?

Yes, it's actually working as expected. Thanks.
