### ISSUE TITLE
Tabs bar

### ISSUE THREAD

**Issue by WalrusInAnus** [black7375/Firefox-UI-Fix#286]
Why is the tabs bar so dark? It seems like the entire addon was made with dark theme in mind, but with the light one, the tabs bar look like covered with grey filter. The default unmodified UI looks a LOT better in that regard. Can you change that to default style please?

edit: Maybe it's some sort of a transparency effect actually. I don't know! I am no programmer and I don't understand this voodoo in the slightest. I am simply looking for a way to make Firefox look like the old one. The new one is unsusable for me.
I was hoping this addon would fix it, but tab bar is just weird.

**Comment by black7375** [comment]
This is an intentional background color for accessibility. https://github.com/black7375/Firefox-UI-Fix/issues/144

**Comment by WalrusInAnus** [comment]
> This is an intentional background color for accessibility. #144
> 
> Try to remove this lines
> 
> https://github.com/black7375/Firefox-UI-Fix/blob/1da2535f8d84fe0ef05c2b6020a44c38a3698323/userChrome.css#L6-L15
> 
> https://github.com/black7375/Firefox-UI-Fix/blob/1da2535f8d84fe0ef05c2b6020a44c38a3698323/userChrome.css#L512-L514

Unfortunately that makes no difference.
This is what it looks like.
![image](https://user-images.githubusercontent.com/17233430/145167052-49c310df-f8bb-4b59-aba2-274f0aa098c7.png)


I like the default style 
![image](https://user-images.githubusercontent.com/17233430/145167198-207b7355-8ab6-4a7d-9790-0bab3bb93296.png)

Is this doable somehow?

**Comment by WalrusInAnus** [comment]
Noone?

**Comment by black7375** [comment]
What's your OS and theme name?

**Comment by WalrusInAnus** [comment]
Windows 10, and what do you mean by theme? Which one of the three you made?

**Comment by black7375** [comment]
Firefox's self theme. ex) ststem default, alpenglow ..etc

**Comment by WalrusInAnus** [comment]
Oh ok.
I use light theme.
