### ISSUE TITLE
 userChrome.css not applied on Firefox Developer Edition

### ISSUE THREAD

**Issue by mapuya19** [black7375/Firefox-UI-Fix#287]
**Describe the bug**
After upgrading to Firefox 96.0b1, userChrome.css is not applied.

**Expected behavior**
Lepton applied to Firefox Developer Edition.

**Screenshots**
<img width="437" alt="Screen Shot 2021-12-07 at 2 09 49 PM" src="https://user-images.githubusercontent.com/15944396/145091080-d240c4d2-27e9-455b-9f42-cfd95cc1dd5b.png">
<img width="1624" alt="Screen Shot 2021-12-07 at 2 09 45 PM" src="https://user-images.githubusercontent.com/15944396/145091088-51efb25c-3ec5-4cda-aedd-bebda291b977.png">

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [ ] Windows
   - [x] Mac
   - [ ] Other: 
 - Theme:
   - [x] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Comment by mapuya19** [comment]
Lepton still works on my installation of Firefox 95, so I can't tell if it's Firefox Dev Edition or just this user profile that's messed up.

**Comment by black7375** [comment]
It is applicable if you use the development branch.
https://github.com/black7375/Firefox-UI-Fix/issues/276

I will release it in 1-2 days

**Comment by black7375** [comment]
I've been busy lately and forgot there was a Firefox release.
It's been released first.
Check it out.
