### ISSUE TITLE
lwtheme-mozlightdark is removed

### ISSUE THREAD

**Issue by black7375** [black7375/Firefox-UI-Fix#288]
**Describe the bug**

`:root[lwtheme-mozlightdark]`  was selector for default themes(system theme, a default light, and a default dark).

However, it was recently confirmed to be removed from Nightly.
It causes a lot of compatibility issues.

**Expected behavior**

It should be possible to distinguish whether it is the system default theme, compact light, compact dark or not.

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [x] Linux
   - [x] Windows
   - [x] Mac
   - [ ] Other: 
 - Theme:
   - [x] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

https://github.com/mozilla/gecko-dev/commit/5dbdec13b640fbc22aaa8153157b9a8da663afc1

It can be converted
```css
:root[style*="--lwt-accent-color: rgb(240, 240, 244); --lwt-text-color: rgba(21, 20, 26);"], /* Light Theme */
:root[style*="--lwt-accent-color: rgb(28, 27, 34); --lwt-text-color: rgba(251, 251, 254);"] /* Dark Theme */
```

**Comment by adql** [comment]
Is it related to this display problem of unfocused tabs in dark mode? (with auto system theme)

![Screenshot from 2021-12-09 12-10-31](https://user-images.githubusercontent.com/6893125/145386475-921a624c-a06a-45aa-8c09-5f9571e6602a.png)

I'm on 95.0 (not Nightly), but the Gecko commit you referred to happened before it was released. Same problem on a fresh profile, but if I try it on 91.4.0ecr it works fine. Also on the normal dark theme (not system) it works fine.

If it's unrelated then I'll open a new issue.

**Comment by black7375** [comment]
Would you please make a new issue if it's not Nightly?

**Comment by adql** [comment]
Done. #291
