### ISSUE TITLE
view-source

### ISSUE THREAD

**Issue by kr4ssi** [black7375/Firefox-UI-Fix#289]
**Describe the bug**
There is no style attached to view-source

**Expected behavior**
From what I see in userContent.css there is some styling: https://github.com/black7375/Firefox-UI-Fix/blob/master/userContent.css#L1145

**Screenshots**
![grafik](https://user-images.githubusercontent.com/44404263/145320206-fd6d2d02-abff-4b19-9a97-0a67291bc710.png)

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 95
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

**Comment by black7375** [comment]
It's not a developer tool, it's the color scheme that gives the source view a dark theme.

![image](https://user-images.githubusercontent.com/25581533/145321226-9d86e7c4-a878-4c7d-abbe-fd7e89170ac2.png)

view-source:https://github.com/black7375/Firefox-UI-Fix/issues/289

**Comment by kr4ssi** [comment]
I just wanted to show by the developer tool that there is no style attached.

![grafik](https://user-images.githubusercontent.com/44404263/145325411-53742d05-3c39-43e8-b9d3-51f855d12442.png)

**Comment by kr4ssi** [comment]
Strangely enough for local files it works

**Comment by black7375** [comment]
This could be the cause.
https://github.com/black7375/Firefox-UI-Fix/wiki/Compatibility-Issues-Solution#not-works-darkmode-in-contents
