### ISSUE TITLE
White background and barely readable inactive tabs on dark system theme

### ISSUE THREAD

**Issue by adql** [black7375/Firefox-UI-Fix#291]
**Describe the bug**

When Firefox's theme is set to `System theme – auto` and the system theme is dark, the tab bar has a bright background and the unfocused tabs have a white text on bright background, rendering them unreadable. Only the focused tab appears as it should. 

**Expected behavior**
`System theme – auto` has a usable tab bar with dark backgrounds.

**Screenshots**

![Screenshot from 2021-12-09 12-10-31](https://user-images.githubusercontent.com/6893125/145472063-dfeed4a0-5665-4456-9731-0e669a335e28.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [x] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 95.0
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): Adwaita-Dark
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

The problem doesn't occur with Firefox's (always) dark theme. Also `Alpenglow` theme works as expected with both light and dark variants.

I'm on `i3wm` and using [xsettingsd](https://github.com/derat/xsettingsd) to switch system themes.

**Comment by adql** [comment]
Edit: Photon and Proton styles are affected as well.

**Comment by adql** [comment]
I have just tested it on beta (96.0b3) and on nightly (97.0a1) and in both the bug is gone! I also tried a direct download of the current version to make sure it's not an issue in the compiled Arch version, and the bug persists.

This may be some random thing in the current (95.0) Firefox version which is resolved later, assuming nobody reintroduces it.

**Comment by black7375** [comment]
It's definitely weird.
I think it can only be reproduced in a specific environment.

**Comment by adql** [comment]
> I think it can only be reproduced in a specific environment.

Certainly. I originally encountered it on the default GTK dark theme Adwaita-dark. It can be reproduced for example on [Greybird-dark](https://github.com/shimmerproject/Greybird). But it can't be reproduced on the dark variants of [Adapta](https://github.com/adapta-project/adapta-gtk-theme) – here it all looks fine.

Anyway, it currently remains to wait for 96.0 and see if the bug is still resolved by itself or is somehow reintroduced.

**Comment by black7375** [comment]
I think the problem is solved in the latest version.

**Comment by adql** [comment]
Yeah, it was already on the later Firefox versions as I mentioned above. Sorry for not checking back.
