### ISSUE TITLE
Question about SCSS

### ISSUE THREAD

**Issue by BPower0036** [black7375/Firefox-UI-Fix#294]
**Is your feature request related to a problem?**
No
**Question**
I saw that you made a branch called [`scss`](https://github.com/black7375/Firefox-UI-Fix/tree/scss)? I don't know it, but can use the same way as css.
So can I put the **scss** file in the same folder (`...\chrome\`) as currently the **css** files are?

**Comment by smowtenshi** [comment]
No, SCSS requires compilation to CSS first.

**Comment by BPower0036** [comment]
Okay, I am inexperienced when it come to SCSS so lets see how things go.

**Comment by black7375** [comment]
Yes it will compile.

https://github.com/black7375/Firefox-UI-Fix/blob/b8498ee852f7428aa9613b31fe1649ad35c55603/package.json#L11

---

It will take some time to fully migrate.
