### ISSUE TITLE
Hover and pressed colours in main menu are quite dark

### ISSUE THREAD

**Issue by Poopooracoocoo** [black7375/Firefox-UI-Fix#296]
**Describe the bug**

I'm not sure when this happened or if this is on purpose but menu items have dark hovered and pressed colours.

**Expected behavior**

Colours more like what's found in the rest of Firefox, pictured above.

**Screenshots**

![image](https://user-images.githubusercontent.com/51363864/146759030-577c862e-716a-428a-9d26-f458c6b5c931.png)
![image](https://user-images.githubusercontent.com/51363864/146759169-307b8db3-a386-4489-9581-550558238dff.png)
![image](https://user-images.githubusercontent.com/51363864/146759141-7430d3d1-66cd-4339-997b-3340c36bf9c3.png)
![image](https://user-images.githubusercontent.com/51363864/146759098-4929285e-aacc-4ae3-a871-f4eed59aa013.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

**Comment by black7375** [comment]
I'll check it out today or tomorrow.

**Comment by black7375** [comment]
I adjusted it to be a little more natural. Could you check it out?

**Comment by Poopooracoocoo** [comment]
Thank you! Not sure if you've already found this but I'll say it anyway.
So I'm seeing much better hover and pressed colours for menu items!! But unfortunately the buttons have the same hover and pressed colour and that is the darker pressed colour.

**Comment by black7375** [comment]
I've updated a few more. There is more consistency in my eyes.

**Comment by Poopooracoocoo** [comment]
Thank you! I'll close this issue :)
