### ISSUE TITLE
remove separator between tabs?

### ISSUE THREAD

**Issue by Skrell** [black7375/Firefox-UI-Fix#297]
If I wanted to add some CSS to REMOVE and HIDE the separators between tabs what would I need to do?  Bearing in mind I'm using your Photon inspired square tabs.

**Comment by black7375** [comment]
You can use photon style distribution.

![image](https://user-images.githubusercontent.com/25581533/147301713-e1bf0301-72f1-4077-a2d2-6eb2bf8e6808.png)

- Code: https://github.com/black7375/Firefox-UI-Fix/tree/photon-style
- Download: https://github.com/black7375/Firefox-UI-Fix/releases/latest/download/Lepton-Photon-Style.zip
- Download using git: `git clone https://github.com/black7375/Firefox-UI-Fix chrome -b photon-style`

---

Separately, you can remove the following lines:

https://github.com/black7375/Firefox-UI-Fix/blob/1351fe9a60b2957d27241b24476cfafce779e303/userChrome.css#L3290-L3353
