### ISSUE TITLE
Remove tab outline

### ISSUE THREAD

**Issue by nikkehtine** [black7375/Firefox-UI-Fix#298]
I want to remove the active tab outline at the top because it doesn't look good with the theme I'm using.
![obraz](https://user-images.githubusercontent.com/27138416/147503309-4d1ab5e0-b5f5-47f3-a47c-969492c50cd4.png)
What lines do I need to delete?

**Comment by black7375** [comment]
You can remove this lines.
https://github.com/black7375/Firefox-UI-Fix/blob/1351fe9a60b2957d27241b24476cfafce779e303/userChrome.css#L3204-L3226
