### ISSUE TITLE
how to decrease the spacing/padding in the contextual menu?

### ISSUE THREAD

**Issue by mooms06** [black7375/Firefox-UI-Fix#30]
Especially the spelling suggestions (see image)

![image](https://user-images.githubusercontent.com/25405517/120479259-0923d080-c3ae-11eb-9968-4beaf7e32e54.png)

**Comment by black7375** [comment]
Adjust this.

https://github.com/black7375/Firefox-UI-Fix/blob/8ea735862467ebc52800649b76531b8b1e0ace35/userChrome.css#L538-L558

**Comment by mooms06** [comment]
Which one should I modify for normal density ?

**Comment by black7375** [comment]
Targets with `:root:not([uidensity=touch])` in front of them.

**Comment by mooms06** [comment]
That's perfect, thank you very much !

I've settled for this, seems good to me:

```
  /** Menu - Reduce Padding ***************************************************/
  :root:not([uidensity=touch]) menupopup > menuitem, menupopup > menu {
    padding-block: 0.10em !important; /* Original: 0.5em */
  }
  :root:not([uidensity=touch]) .menu-text, .menu-iconic-text {
    padding-inline-end: 0 !important; /* Original: 2px */
  }
  :root:not([uidensity=touch]) .menupopup-arrowscrollbox {
    padding-block: 1px !important;    /* Original: 4px*/
  }
  :root:not([uidensity=touch]) #context-navigation:not([hidden]) {
    padding: 0 0 1px !important;      /* Original: 0 0 4px*/
  }
  :root:not([uidensity=touch]) .menu-right {
    margin-right: 1px !important;     /* Original: 12px */
  }
```

Result:
![image](https://user-images.githubusercontent.com/25405517/120482191-27d79680-c3b1-11eb-98b5-d2be57944edc.png)

**Comment by black7375** [comment]
I think it would be good to apply it to compact mode later.

**Comment by mooms06** [comment]
I don't plan to use compact mode, but to me it should be set to 0.10em or 0.15em on default mode, 0.35 is still too much IMO.
