### ISSUE TITLE
address bar context menu color

### ISSUE THREAD

**Issue by oldrust** [black7375/Firefox-UI-Fix#300]
On some firefox themes, the color of the address bar right click menu is dark with white icons, although the tab and page context menus are white with dark icons. Is there an option to change the colors of address bar context menu to be the same as other context menu colors?

**Comment by black7375** [comment]
Can you provide the URL and screenshot of that theme?

**Comment by oldrust** [comment]
[](url)https://addons.mozilla.org/en-US/firefox/addon/yellow-bluetheme/?utm_content=addons-manager-reviews-link&utm_medium=firefox-browser&utm_source=firefox-browser

**Comment by oldrust** [comment]
[](url)https://postimg.cc/ZvznSG9R

[](url)https://postimg.cc/gLpz535L

**Comment by black7375** [comment]
Interesting. I think it's worth investigating.
It seems that you need to configure the environment such as OS or Desktop Environment to find out.

One more question: Is it normally displayed in pure Firefox without a theme?

**Comment by oldrust** [comment]
In a new profile it works correctly, even with the built-in Dark theme it shows white background. It's probably some extension that is mesing up, i have a lot of them installed. Btw i use xfce 4.16 on arch linux.

**Comment by oldrust** [comment]
in about:config
widget.gtk.alt-theme.dark set to false fixes the problem.

**Comment by black7375** [comment]
It has been added to the wiki to prevent similar cases.

https://github.com/black7375/Firefox-UI-Fix/wiki/Compatibility-Issues-Solution#different-context-menu-colors-for-content-and-toolbar
