### ISSUE TITLE
No hover highlight in some items in video control context menu

### ISSUE THREAD

**Issue by steve121418** [black7375/Firefox-UI-Fix#301]
**Describe the bug**
Using Windows 10/11:
 + [Play this video](https://assets.zorincdn.com/zorin.com/videos/16/pro.webm) or Open a local video file (example: MP4) by dragging into the tab bar
 + Right-click on the video
 + When hovering on some items in the context menu, no highlight.
    + Affected items: Play, Mute, Speed (including sub-context items), Full Screen, Hide Controls, Take Snapshot, Save Video As, Copy Video Link, Email Video

**Expected behavior**
Hovering affected items in video control context menu mentioned above must be highlighted.

**Screenshots (note the difference)**
[Lepton 4.5.5](https://www.mediafire.com/file/ovj8b1visc0lw7f/Lepton_4.5.5.gif/file)

https://user-images.githubusercontent.com/25581533/148177178-704a1667-b50d-4228-8b16-81edd2546480.mp4

[Lepton 4.5.4](https://www.mediafire.com/file/6vipqgqfcnr6jk0/Lepton_4.5.4.gif/file)

https://user-images.githubusercontent.com/25581533/148177215-c1105153-9396-4c0e-a984-e833230ae42d.mp4

Reason I can't upload it here: 
![Screenshot 2022-01-05 at 15-02-05 New Issue · black7375 Firefox-UI-Fix](https://user-images.githubusercontent.com/96946491/148174424-e1dbf502-faf6-43d4-b5db-90c955cdb6ce.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [x] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 95.0.2 (release), 96.0b10 (Beta/Developer Edition), 97.0a1 (Nightly)
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [x] Light
   - [x] Dark
   - [x] Alpenglow (System: Light)
   - [x] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): 
   - [x] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**
 + Using Lepton 4.5.5 (release). No issues on Windows 7/8.x
 + I don't know if this affects macOS or Linux versions of Firefox
 + No issues on Lepton 4.5.4
 + I don't know CSS editing :)

**Comment by black7375** [comment]
Thank you for the detailed report.
I'll check it out when I get home, fix it as soon as possible and make a release.

**Comment by black7375** [comment]
Hopefully it's been fixed now.
