### ISSUE TITLE
Page Info tabs have overlapping text and icons

### ISSUE THREAD

**Issue by aphedges** [black7375/Firefox-UI-Fix#302]
**Describe the bug**
In the "Page Info" window, the text and icons for the tabs at the top are overlapping on macOS. I do not have this issue on my Windows machine.

**Expected behavior**
The text and icons should not overlap.

**Screenshots**
![Screenshot of "Page Info" tabs](https://user-images.githubusercontent.com/14283972/148284163-8bb96f14-6694-49a9-b095-b603344111c8.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version:  	95.0.2
 - OS:
   - [ ] Linux
   - [ ] Windows
   - [x] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Comment by black7375** [comment]
Now it should look like this:
![image](https://user-images.githubusercontent.com/25581533/148385379-1fd9f9de-755e-4d95-b5c3-5dd9923e84e4.png)

**Comment by aphedges** [comment]
The commit works for me:

![Screenshot of "Page Info" tabs](https://user-images.githubusercontent.com/14283972/148459435-875d3353-5f30-4c24-84bc-9332bddf5f93.png)

Thanks!
