### ISSUE TITLE
Compact mode does not change tab size

### ISSUE THREAD

**Issue by gwarser** [black7375/Firefox-UI-Fix#304]
**Describe the bug**
In customize choosing between normal and compact change size of everything else but tabs.

**Expected behavior**
Tabs should not be  so tall.

**Screenshots**
![image](https://user-images.githubusercontent.com/886325/148662329-6cb0f880-f157-4af5-8cd1-ffe9602bbd89.png)
![image](https://user-images.githubusercontent.com/886325/148662334-c893efd2-a5dc-49ce-8df8-1cd3bc22f3be.png)

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): Adwaita
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

**Comment by black7375** [comment]
Not a lot, but a little less.
I remember that I couldn't reduce the size of the icons on the tab bar and because of Windows compatibility.
![image](https://user-images.githubusercontent.com/25581533/148675164-f7de6918-ab22-4ae1-ae9f-f1494017d0a6.png)

**Comment by black7375** [comment]
It seems to be a problem that only happens with `v96` or higher.
I modified it.
