### ISSUE TITLE
Double "Manage Bookmarks" at bookmarks menu (top and bottom)

### ISSUE THREAD

**Issue by SnowManWithCarrot** [black7375/Firefox-UI-Fix#306]
**Describe the bug**

Double "Manage Bookmarks" at the bookmarks menu

**Expected behavior**

Is there a way to remove the bottom one since the top one is enough and placed where it easiest to access anyway.

**Screenshots**

![MBM](https://user-images.githubusercontent.com/86745065/149006618-c2e36525-1fcb-42af-9602-38624597da80.jpg)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [x] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

**Comment by black7375** [comment]
Just you can remove

```css
#BMB_bookmarksShowAll {
  display: none;
}
```

**Comment by SnowManWithCarrot** [comment]
Excellent ! thank you.
