### ISSUE TITLE
Photon Style Tabs

### ISSUE THREAD

**Issue by Hapax96** [black7375/Firefox-UI-Fix#307]
Hello,

I have been using Photon style for quite a while and since a few days I have big tabs again like in Proton style. Apparently this is related to a Firefox update.

So I downloaded the latest version of the provided Photon style, but after that the tabs were still big and between the tabs also black lines.

Does the Photon style still need to be adjusted?

Best regards

**Comment by R3G3N3R4T0R** [comment]
Can Confirm Firefox 96 broke it(Which shouldn't be there a few days back). It has Proton style tabs for Windows and this abomination on Linux.
![image](https://user-images.githubusercontent.com/54089608/149325713-8400abc6-cb19-4ad7-ba88-6608acf89003.png)
some Theme still work especially official ones but none of the user submitted ones do.

**Comment by Hapax96** [comment]
I had used the latest version (4.5.6). Which one I had before, I don't know. Anyway, from one day to the next, my tabs in Firefox were large again instead of narrow. I can't take screenshots, otherwise I would have to replace all files again. It's just like I said, all the tabs are big, as it is with Firefox's Proton style, although I'm using your Photon style, which actually has small/narrow tabs, right?

**Comment by Hapax96** [comment]
I have now changed it again. This is what it looks like when I use the latest version of the Photon style.

![firefox_vrJsFflZQg](https://user-images.githubusercontent.com/88907420/149346575-e83e15b9-692d-4dcd-8195-d434200a95aa.png)

**Comment by black7375** [comment]
Since there is currently no win8 environment, I will configure it over the weekend and check it out.

**Comment by black7375** [comment]
The tab size problem was solved at #304
