### ISSUE TITLE
Photon style panel is missing icons present in the old design

### ISSUE THREAD

**Issue by Oondanomala** [black7375/Firefox-UI-Fix#308]
**Describe the bug**
The panel is missing the new tab, passwords, addons and themes, help, and quit icons

**Expected behavior**
Have the mentioned icons just like the old panel

**Screenshots**

Old Panel
![OLD](https://user-images.githubusercontent.com/25581533/123602947-dd4b0d80-d7e8-11eb-93a6-2b263bdd99f7.png)
Photon Style Panel
![NEW](https://user-images.githubusercontent.com/25581533/123761424-5746c980-d8b1-11eb-9a0f-83fb305f9f08.png)
Example of how it should be
![FIXED](https://i.imgur.com/Lpo85Kf.png)
**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [x] Other: ([Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/))

**Comment by black7375** [comment]
It can be a kind of breaking change, so we'll put it as an option in the next major version.

**Comment by blueclouds8666** [comment]
i also find annoying that for example addons has no icon. i hope you can bring back that feature

**Comment by black7375** [comment]
Try using version 5.0.0.
It has been changed to the default setting.
