### ISSUE TITLE
Non-animated Dark Themes break in Librewolf 96.0

### ISSUE THREAD

**Issue by R3G3N3R4T0R** [black7375/Firefox-UI-Fix#309]
**Describe the bug**

After the Librewolf 96.0 update, my installed themes broke and now they seem to have a grey overlay on the background, the original background is only revealed on the selected tab. After a few testing I found that it only happens when the titlebar is disabled, and when the theme is a non-animated dark background.

**Expected behavior**

The top bar background should be shown in its entirety and not just the rectangle on the selected tab.

**Screenshots**

![image](https://user-images.githubusercontent.com/54089608/149427847-725f628e-d9ba-4457-9569-64e49904a038.png)

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: Librewolf 96.0
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): Artix-dark 
   - [x] Other: [Bright Light Waves](https://addons.mozilla.org/en-US/firefox/addon/bright-light-waves-by-m-donna), [Calm Sunrise](https://addons.mozilla.org/en-US/firefox/addon/calm-sunrise-by-madonna), [Colourful Spectrum](https://addons.mozilla.org/en-US/firefox/addon/colourful-spectrum-259634), and other non animated dark themes

**Additional context**

DE: LXQt 1.0.0
WM: Openbox 3.6.1

**Comment by black7375** [comment]
It seems like a pretty exceptional situation.
I need to configure Openbox as well.
![lubuntu-2022-01-14-10-28-03](https://user-images.githubusercontent.com/25581533/149435840-176aae24-f428-4ef8-8e05-5790dafac470.png)

Do you have any custom css code you have applied?

**Comment by R3G3N3R4T0R** [comment]
> Do you have any custom css code you have applied?

I have WebRTC indicator disabled on this one, and I have tried tinkering with the titlebar icons, but ultimately I tried testing it on a new profile with original chrome folder and unmodified user.js and it still stayed like that.
Note that you need to have the title bar unchecked in "Customize Toolbar...", or it will not appear

**Comment by black7375** [comment]
I succeeded in reproducing it.
Now it will works

**Comment by R3G3N3R4T0R** [comment]
Yes it does work now. Thank for the fast response.
