### ISSUE TITLE
v1.0 Plan

### ISSUE THREAD

**Issue by black7375** [black7375/Firefox-UI-Fix#31]
https://github.com/black7375/Firefox-UI-Fix/issues/26#issuecomment-852981225

Release 1.0 after 3 high-priority issues are resolved.
- ~~#19~~
- ~~#26~~
- ~~#29~~

**Comment by 7k5x** [comment]
I think you should create a release(It's located at the right side of your code) instead of making a milestone.<br>Also congratulations on your first release!

**Comment by black7375** [comment]
This is a plan.
The above issues need to be resolved first.

**Comment by black7375** [comment]
Any recent commit users have this same problem? https://github.com/black7375/Firefox-UI-Fix/issues/14#issuecomment-854912304

**Comment by black7375** [comment]
Now that all three are closed, I start working on the release.

**Comment by luximus-hunter** [comment]
wicked

**Comment by black7375** [comment]
`v1.0` is released!!
