### ISSUE TITLE
userContent.css included in local html files, modifying how they should look

### ISSUE THREAD

**Issue by forestrf** [black7375/Firefox-UI-Fix#310]
**Describe the bug**
Opening a local html file (using file:///) applies the style userContent.css to it, modifying how the html looks compared to how it looks when server by a web server.

**Expected behavior**
No userContent.css is applied to local files

**Environment:**
 - Distribution
   - [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 95.0.2
 - OS:
   - [ ] Linux
   - [X] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [X] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
   - [ ] Other:

**Additional context**
I'm doing web development without using a local web server, just plain html files. Using a web server would work as a workaround but this can be very annoying.

**Comment by black7375** [comment]
Styles are only reflected if they end in `/` to apply only to directories.
There may be a problem with the `index`.

https://github.com/black7375/Firefox-UI-Fix/blob/6a94b0134fae509e295e947ba3077bbc48b8b394/userContent.css#L995
https://github.com/black7375/Firefox-UI-Fix/blob/6a94b0134fae509e295e947ba3077bbc48b8b394/userContent.css#L1285

If `.html` is included, I think it will be fine.

**Comment by forestrf** [comment]
I'm very sorry, I updated firefox just now to 96.0.1, which made me update the Firefox-UI-Fix "extension" too, and now my local html looks correctly.
I may have been using an old version, or maybe I modified the userContents file (but I'm pretty sure I didn't).
Sorry. I think this issue can be closed given that the current firefox and "extension" together work well and there's no problem anywhere.

**Comment by black7375** [comment]
sounds good
