### ISSUE TITLE
Incorrect Tab Highlight When Using System Theme

### ISSUE THREAD

**Issue by TheBrokenRail** [black7375/Firefox-UI-Fix#311]
**Describe the bug**
The tab highlight is the default Firefox blue instead of the system Ubuntu orange.

**Expected behavior**
It should match the system colors, as in Ubuntu orange.

**Screenshots**
![Screenshot from 2022-01-14 13-18-24](https://user-images.githubusercontent.com/17478432/149565566-dbe9d816-129e-4d1e-952d-076b53bebbde.png)

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: `96.0`
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): Yaru
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Comment by black7375** [comment]
It's weird. Tab highlight is displayed normally in my environment.
![Ubuntu 64-bit-2022-01-16-01-08-15](https://user-images.githubusercontent.com/25581533/149628935-56794b63-c422-4c7f-b28d-86709965a29b.png)

**Comment by TheBrokenRail** [comment]
The issue started for me when I updated to Firefox 96. I also just made sure Firefox-UI-Fix was up-to-date and cleared my startup cache (from `about:support`) and the issue is still happening,

**Comment by black7375** [comment]
I have confirmed the problem.
I haven't had much time lately, so it may take a day or two to resolve.

**Comment by black7375** [comment]
It should be fixed now

**Comment by TheBrokenRail** [comment]
Just updated, cleared startup cache, and the tab highlight is still blue not orange.

**Comment by black7375** [comment]
That's weird.
I've tested it on several OS's and it works.
![Ubuntu 64-bit-2022-01-17-14-22-27](https://user-images.githubusercontent.com/25581533/149712593-3d431f3b-a1c8-4b0b-b060-64a2a883164a.png)
![Linux mint-2022-01-17-14-50-37](https://user-images.githubusercontent.com/25581533/149715029-233ad97a-18d0-4f62-8bf5-9873db1434aa.png)
![image](https://user-images.githubusercontent.com/25581533/149716168-3d890e3a-b65e-493e-b61d-4b5b52cbed5a.png)

**Comment by TheBrokenRail** [comment]
Tried again. Turns out the install script was updating the wrong profile, it works now! Thanks!

**Comment by badlydrawnface** [comment]
it works with the default gtk themes (firefox 97 dpkg through ubuntu 21.10), however it defaults to the blue with every single addon theme
![vmplayer_tCX9kHOUjI](https://user-images.githubusercontent.com/53501005/156701384-82d4f1fa-c2dd-4519-83fb-49e56bd2a2ed.gif)

I have opened a separate issue regarding this [here](#337)
