### ISSUE TITLE
Transparent tab bar on macOS

### ISSUE THREAD

**Issue by Anton2319** [black7375/Firefox-UI-Fix#312]
**Describe the bug**
When the macOS top panel (menubar) is opened in fullscreen (green button), the Firefox tab panel is transparent and site content is visible underneath. I am running macOS 10.15 Catalina with the latest updates.

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 96.0
 - OS:
   - [ ] Linux
   - [ ] Windows
   - [x] Mac
   - [ ] Other: 
 - Theme:
   - [x] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
![Screenshot 2022-01-15 at 00 09 05](https://user-images.githubusercontent.com/40764618/149587318-57ec4354-a92b-43ef-827c-0e49f57f56e8.png)
![Screenshot 2022-01-15 at 00 13 43](https://user-images.githubusercontent.com/40764618/149587349-103b13c7-b669-4dc6-85aa-8443e6ce4278.png)

**Comment by black7375** [comment]
I'm using a virtual machine, not a real Mac.
That's why I can't reproduce it.
![image](https://user-images.githubusercontent.com/25581533/149626994-d3bd81e7-a096-4f66-9670-5c5e6335e8e0.png)

It may take some time to fix or may require several attempts.

**Comment by Anton2319** [comment]
That seems that your firefox window opened in another fullscreen mode (dock enabled).
macOS has a green button fullscreen mode (it creates a virtual desktop with an application). Here's the difference:
When you double-tap on the window header it opens in fullscreen on the same desktop you have opened.
Like this:
![Screenshot 2022-01-15 at 20 18 24](https://user-images.githubusercontent.com/40764618/149631241-7ce96c43-d0cf-4f3e-8b15-ec70c9d500a3.png)
When you press the green button it opens Firefox on another desktop like this:
![Screenshot 2022-01-15 at 20 18 36](https://user-images.githubusercontent.com/40764618/149631666-b2bf47eb-7704-4287-ba9a-b6caf79de482.png)
How it looks like in mission control:
![Screenshot 2022-01-15 at 20 18 43](https://user-images.githubusercontent.com/40764618/149631322-fd279959-70df-4257-8135-a8f9932eca09.png)

**Comment by black7375** [comment]
I got it.
Thanks for the kind explanation

I'll test it tomorrow.

**Comment by black7375** [comment]
It would have been solved now.
It was an unexpected compatibility issue.

The code that was a problem. (for memo)
Appears only when hovering over the top in fullscreen.
```css
#navigator-toolbox {
  transform: translateY(44px);
  z-index: 2;
}
```

**Comment by Anton2319** [comment]
Thank you! Now that's fixed
![Screenshot 2022-01-18 at 15 39 20](https://user-images.githubusercontent.com/40764618/149939076-c7a441f7-cab4-4b81-a212-f426e891085a.png)
