### ISSUE TITLE
No X Button On Tabs

### ISSUE THREAD

**Issue by pollen00** [black7375/Firefox-UI-Fix#313]
**Describe the bug**

The X button is missing from tabs. The highlight shows up when hovering.

**Screenshots**
![image](https://user-images.githubusercontent.com/36719558/149605625-f4cf453f-9cdc-4cff-98b6-20a5c78dd9de.png)

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [X] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [X] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [X] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Comment by black7375** [comment]
Did you copy the `icons` directory?
I think it's the same symptoms as following issues  #189 #274 

A lot of people seem to be confused.
 I'll add information to the FAQ in the README.
