### ISSUE TITLE
Installation using powershell on Windows

### ISSUE THREAD

**Issue by CADBIMDeveloper** [black7375/Firefox-UI-Fix#314]
**Describe the bug**
Installation guide in readme.org says you should run powershell as administrator, but in that case it shows admin user firefox profiles only and I can't update FF current user profile.

However I run PS from current user and it updated everything without any problems. But I had previous version of FF-UI-Fix (it was broken after FF had been updated to the latest version).

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [x] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 96.0.1
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

**Comment by black7375** [comment]
It's a mistake because I'm not familiar with Windows.
I will revise the guide immediately.
Thanks for your report !!
