### ISSUE TITLE
I'd like to use multirow from MrOtherGuy with Lepton

### ISSUE THREAD

**Issue by L0rent** [black7375/Firefox-UI-Fix#315]
Hi.
I use Firefox DEV v97.0b3 64 bits on Windows 10. I installed Lepton and it works. Thank you for your job.
Now, I would like multirow tab like the css of MrOtherGuy (https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/multi-row_tabs.css).
In FF DEV 88.0b9, I use to copy the code into userChrome.css.

But I don't know how to do. Can you tell me how to do please? Thank you.

**Comment by black7375** [comment]
1. Go to the profile folder and find `chrome` folder.
  Please refer to the [installation guide](https://github.com/black7375/Firefox-UI-Fix/wiki/Installation-Guide)
2. Find `userChome.css` in `chrome` and paste code at bottom.

However, I haven't tested it, so I don't guarantee it will work.

**Comment by L0rent** [comment]
I already tried that, it didn't work.

How to have multirow with your code?

**Comment by black7375** [comment]
If it doesn't work, you have to wait.
I plan to add new features after various compatibility issues and the introduction of option systems.

**Comment by krystian3w** [comment]
Try move multi-row to other file and link like in CustomCSSforFX:

`@import "./css/multi-row.css"; /**/` - enabled
`/* @import "./css/multi-row.css"; /**/` - disabled

if this not these bug then need wait to fixed in one of two project (glitches).

**Comment by black7375** [comment]
Try to use [`v7.0.0`](https://github.com/black7375/Firefox-UI-Fix/releases/tag/v7.0.0).
