### ISSUE TITLE
theme doesnt seem to apply correctly

### ISSUE THREAD

**Issue by DaedalusMDW** [black7375/Firefox-UI-Fix#316]
**Describe the bug**
since the cluster bomb of 96.0.1 i had to update to the latest version of this code.  i have a custom "firefox color" theme which no longer is respected.

**Expected behavior**
colors should match the theme.  blue accent bar should be purple.

**Screenshots**
screen of the applied theme preview
https://pasteall.org/media/0/0/001464fd3dff1bf17e586d9daf1aaf77.png
![image](https://user-images.githubusercontent.com/25581533/149667190-46f8a1fb-aa0a-4240-b6b8-b10d5dc0f27d.png)

what it looked like before the update (the style was correct (photon) before 96.0.1)
https://pasteall.org/media/0/b/0bcc004abf18b46a508b9097ff43d3c5.png
![image](https://user-images.githubusercontent.com/25581533/149667198-d99cf95d-46c6-4fe4-b6a9-fd7f15a98d2e.png)
(should i make a separate feature request to rid those ugly icons on the title bar?)

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 96.0.1
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [x] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

**Comment by smowtenshi** [comment]
> (should i make a separate feature request to rid those ugly icons on the title bar?)

See https://github.com/black7375/Firefox-UI-Fix/wiki/Tips#remove-menubar-icon

**Comment by DaedalusMDW** [comment]
i did some more fiddling and found most of the colors change correctly, just not the blue accent.  the odd part is it used to work fine up until today (admittedly running a very old variant of the style)
(thanks for the icon tip, i feel dumb now 🙂 )

**Comment by smowtenshi** [comment]
This might be related to #311 I guess

**Comment by black7375** [comment]
I updated from #311, check it out~
I will mark this as an `duplicate` issue and deal with it together.
