### ISSUE TITLE
How to Disable TitleBar Icons

### ISSUE THREAD

**Issue by MonfGeiger** [black7375/Firefox-UI-Fix#317]
First off, I need to give thanks to this project in its entirety. I ran into the ugly proton style and didnt like it, ran into a winaero tutorial on how to "disable" proton and bring back old photon, sourced it all back to here, and see this? You do good work devs and contributors, whether its just one person or multiple, you people are the GOAT

Now i get into the meat of it: I had to redo the steps to disable proton after it came back for some reason and now I see these titlebar icons next to the menus
![Screenshot 2022-01-19 115803](https://user-images.githubusercontent.com/28603306/150196562-e49fe311-f6a6-47ef-9528-068f8aab1292.png)

Now it surprised me, its something that over time I could get used to, no offense meant to anyone, but i'm more used to the titlebar menus not having any icons and just text options that unfold the standard dropdown menus and their icons and such, so, here's my question

Can I disable the icons circled in red in the screenshot _somehow_, without breaking the UI fix and keeping the rest of the assigned icons in their respective menu(s) alone, or is that not currently possible?

**Comment by black7375** [comment]
Check wiki's tip
https://github.com/black7375/Firefox-UI-Fix/wiki/Tips#remove-menubar-icon
