### ISSUE TITLE
Stretched Tab Bar

### ISSUE THREAD

**Issue by qingxiang-jia** [black7375/Firefox-UI-Fix#318]
**Describe the bug**

Tab height has increased since Firefox 96.0.2 (at least on Linux). The "Add" button has been stretched. Technically it's not a problem of this project but I guess it would be nice if we could catch up.

Thank you for working on this theme. It is this theme that brought me back to Firefox.

**Expected behavior**

Previous tab height, or just a bit lower (or just match the change).

**Screenshots**

![image](https://user-images.githubusercontent.com/5571586/150398968-52323d78-c3d0-4cf3-88db-ecaee0770ddd.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [x] Light
   - [x] Dark
   - [x] Alpenglow (System: Light)
   - [x] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

**Comment by black7375** [comment]
Ok, I'll check it in weekend

**Comment by black7375** [comment]
## investigated result

### Theme

- master branch( https://github.com/black7375/Firefox-UI-Fix/commit/6c25391e70dfdeb9c14ecc7500d26c39a83b4c37 )

### Compare

- 97.0b5
  - compact: `#navigator-toolbox` [`69px`], `#TabsToolbar` [`36px`]
  - normal: `#navigator-toolbox` [`75px`], `#TabsToolbar` [`38px`]
  - touch: `#navigator-toolbox` [`84px`], `#TabsToolbar` [`45px`]
- 91.5.0esr
  - compact: `#navigator-toolbox` [`65px`], `#TabsToolbar` [`32px`]
  - normal: `#navigator-toolbox` [`75px`], `#TabsToolbar` [`38px`]
  - touch: `#navigator-toolbox` [`84px`],`#TabsToolbar` [`45px`]

---

There is a change in compact mode.
I'll work on it after dinner.

**Comment by qingxiang-jia** [comment]
Much appreciated!

**Comment by qingxiang-jia** [comment]
Thank you for the fix. I will close the issue.

**Comment by black7375** [comment]
Thanks for reporting!!
If there's anything weird next time, please let me know.
