### ISSUE TITLE
Nothing works for Photon style in Firefox v96

### ISSUE THREAD

**Issue by BeakBryno7** [black7375/Firefox-UI-Fix#319]
**Describe the bug**
Everything for Photon style is broken in v96. Nothing works after the update.

**Expected behavior**
Everything is supposed to work. Icons should be shown, However, nothing works.

**Screenshots**
![Screenshot (614)](https://user-images.githubusercontent.com/22396923/150475044-346cfd00-64d6-4ee3-8cbe-2d6c751abd23.png)

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

**Comment by black7375** [comment]
I think it's same problem as #276
Try the latest version theme

**Comment by black7375** [comment]
Close because there was no response for a long time.
