### ISSUE TITLE
Windows 7: Hard to read the text in some dropdown menus

### ISSUE THREAD

**Issue by MikeMilligan** [black7375/Firefox-UI-Fix#320]
**Describe the bug**
On Windows 7 the text in some dropdown menus is unreadable because the background color is wrong. I tested this with my same profile on a laptop running Windows 10 and it doesn't happen.

**Expected behavior**
I should be able to clearly see the text just like in the second screenshot.

**Screenshots**
With Lepton:

![Screenshot 1](https://i.ibb.co/kMfNLf0/dropdown-lepton.png)

Without Lepton:

![Screenshot 2](https://i.ibb.co/HdQsQCN/dropdown-original.png)

**Environment:**

 - Distribution
   - [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 96.0.1
 - OS:
   - [ ] Linux
   - [X] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [X] System Default
     - GTK Theme Name (Linux only): 
   - [x] #322

**Additional context**

**Comment by ojaha065** [comment]
I have had this exact issue on my work PC for a while now but on my home pc it's perfectly fine. Both are running FF 96.0.2 with Lepton on Windows 11. I haven't checked if removing Lepton fixes it, so it's possible it's not a Lepton issue at all.

**Comment by MikeMilligan** [comment]
> I haven't checked if removing Lepton fixes it, so it's possible it's not a Lepton issue at all.

Oh I forgot to mention that in my original bug report. In my case removing Lepton fixes it, but I like it too much to use Firefox without it.

**Comment by rakmaty1** [comment]
The exact same issue happens also with Lepton's photon style on Win 7 and it is present in all themes (system, light, dark, alpenglow)

**Comment by black7375** [comment]
I updated it.
Check please

**Comment by black7375** [comment]
I think the issue has been solved.

**Comment by rakmaty1** [comment]
@black7375 It doesn't seem to work for me after updating, the menus are still unreadable :(

**Comment by black7375** [comment]
@rakmaty1 Sorry. There was a typo mistake.
