### ISSUE TITLE
download dialog has no Drop down arrow

### ISSUE THREAD

**Issue by kidzgy** [black7375/Firefox-UI-Fix#324]
**Describe the bug**
![微信截图_20220126164201](https://user-images.githubusercontent.com/6967810/151130822-64eab892-4baa-4d69-a1ef-260141e6fbad.png)
![微信截图_20220126164112](https://user-images.githubusercontent.com/6967810/151130851-963e6b5b-9de3-4b9d-8e6f-7465d1f65e35.png)

FF96, Lepton-Proton-Style v4.5.7.

**Comment by kidzgy** [comment]
dropmarker {
    display: -moz-box !important;
    width: 12px !important;
    height: 12px !important;
  }

Modifying the code to this will solve the problem.Delete the [appearance: none !important;].

**Comment by smowtenshi** [comment]
![image](https://user-images.githubusercontent.com/7839556/151229306-6df0174c-7087-45bd-bfe8-e070a0072ab0.png)
That's how it looks like after removing `appearance: none !important;` 🤔

**Comment by kidzgy** [comment]
![2022-01-27_090920](https://user-images.githubusercontent.com/6967810/151273154-a1bd7d4e-5add-4583-a42f-0c23ff4c2903.jpg)
Here's what mine looks like.

**Comment by black7375** [comment]
> Basically seems like the code for dropmarker::part(icon) isn't applied.
Yes you are right.

I will find a way to apply it.

**Comment by black7375** [comment]
![image](https://user-images.githubusercontent.com/25581533/151287754-29f54b06-e032-4dfd-af55-666560966b19.png)

Unfortunately, I couldn't find the arrow on the download button.
Is there any way to display three things?

**Comment by kidzgy** [comment]
this is my firefox.
https://pan.baidu.com/s/18CE9F-x-aA54LORYx739Cg?pwd=fyxm

**Comment by kidzgy** [comment]
I am sorry! Please put this file [DownloadPlus.uc.js] into [chrome] folder.
[DownloadPlus.uc.zip](https://github.com/black7375/Firefox-UI-Fix/files/7948195/DownloadPlus.uc.zip)

![微信截图_20220127144334](https://user-images.githubusercontent.com/6967810/151306085-1693c67c-6fc8-4a9d-8542-02be445bdc96.png)

**Comment by kidzgy** [comment]
why not this?
`  dropmarker {
    display: -moz-box !important;
    appearance: none !important;
    width: 12px !important;
    height: 12px !important;
    list-style-image: url("chrome://global/skin/icons/arrow-down.svg") !important;
    -moz-context-properties: fill !important;
    fill: currentColor !important;
  }
`
or remove the whole code about dropmarker?

**Comment by black7375** [comment]
> why not this?

This is to prevent unintended side effects.
I don't guarantee custom except pure firefox.
It provides fairly solid compatibility due to numerous user issues, and in general, I think it's better for the custom code to fit this project.

---

Try follow code.

```js
// 625 Line
saveTo.querySelector('.box-inherit.button-box').appendChild(document.createXULElement('dropmarker');

// to
saveTo.querySelector('.box-inherit.button-box').appendChild(document.createXULElement('dropmarker').setAttribute("exportparts", "icon: dropmarker-icon"));
```
