### ISSUE TITLE
Curvy tab bar

### ISSUE THREAD

**Issue by julie777** [black7375/Firefox-UI-Fix#326]
**Is your feature request related to a problem?**
Firefox has really gotten rid of tabs. The tab bar is just a bunch of bits of text floating in nothing when I have many tabs open. I can't even tell which is the open tab. 

I like the idea that you have reconnected tabs with the toolbars.

**The solution I'd like**
I would really like tabs to look like old fashioned file folder tabs with the uppers corners significantly rounded off so seeing the active tab is obvious.

**Alternatives I've considered**
I've tried to modify the CSS myself, but I am not a web developer and don't know enough to get it completely right.

**Additional context**
The current trend to get rid of borders and flow everything together on a white background is a real issue. It can be very hard to work when for example, a drop down menu is just menu text that is drawn on top of page text with no borders and all of it mixing together. I don't want everything I do to be like solving a CAPTCHA.

Thanks for your work.

**Comment by black7375** [comment]
Any examples of designs you would recommend?

**Comment by julie777** [comment]
I really preferred the old tabs that looked like paper file folders. They made it easy to see which one was active.

![image](https://user-images.githubusercontent.com/5090005/151901866-ee64ec5b-62c8-43e5-bfde-f103ff6384b0.png)

**Comment by BPower0036** [comment]
If you have the system theme enabled, how can you not see which tab is not open?
![afbeelding](https://user-images.githubusercontent.com/80090789/151939978-d7618033-e331-4ee3-b234-e0ae519caf94.png)

**Comment by black7375** [comment]
I can put it as an option later, but not right away.

**Comment by black7375** [comment]
Try to use [`v7.0.0`](https://github.com/black7375/Firefox-UI-Fix/releases/tag/v7.0.0).
