### ISSUE TITLE
Make bookmarks bar not part of the current page.

### ISSUE THREAD

**Issue by julie777** [black7375/Firefox-UI-Fix#327]
**Is your feature request related to a problem?**
By connecting the current tab to the toolbar (location bar) you provide a great visual distinction. The tab bar and any tools on it are global.

The current tab is connected to the location bar, which identifies the current location and there are many tools that apply to the current tab and location, and sadly some that don't. So the tab connected mostly makes sense. But then below the tab connected to the location is the bookmarks bar which has nothing to do with the current location.

**The solution I'd like**
I would like to see even a better connection of the active tab, the location bar and tools that are associated with the current tab and the page content for that tab. 

I have no idea what is possible with just CSS, but I really like the idea of what you are doing, which like a theme for layout instead of just colors.
**Alternatives I've considered**

**Additional context**
I can imagine a solution where the window title bar (hidden by default these days) is at the top.
Next is  the menu bar, usually hidden.
Followed by the always visible toolbar which includes all global tools and can have a second row, the bookmarks bar which already has the ability to hold tools in addition to bookmarks.
Next is the tab bar, which is only tabs, followed by the location bar which is completely restricted to information about the currently active tab. An is connected to the active tab and to the page content. With all the recent additions to the location bar itself (shield, lock, reading mode, container, zoom, start, etc.), it read does deserve its own row.

**Comment by black7375** [comment]
Try to use `v6.0.0`

![](https://user-images.githubusercontent.com/25581533/185807595-ff898b51-c372-4bcf-9dcd-7d97760b1d51.gif)

- https://github.com/black7375/Firefox-UI-Fix/releases/tag/v6.0.0
- https://github.com/black7375/Firefox-UI-Fix/wiki/Options#boomark-bar
- https://github.com/black7375/Firefox-UI-Fix/wiki/Options#toolbar-overlap-mode
