### ISSUE TITLE
Not all hamburger menu icons show in photon-tab style

### ISSUE THREAD

**Issue by shahmilav** [black7375/Firefox-UI-Fix#329]
## Is your feature request related to a problem?
When using the default lepton theme, in the hamburger (three-bar) menu in the top-right, all the icons are visible (e.g. New Tab, New Window, etc). However in the photon theme only a few icons are there making it seem unbalanced.

## The solution I'd like
All icons shown in the Photon theme.

## Screenshots

* all icons (lepton default)
![All icons](https://user-images.githubusercontent.com/25581533/119774062-20942280-beb1-11eb-80aa-c18dd52f18d7.png)

* some icons (photon default)

![some icons](https://user-images.githubusercontent.com/25581533/119773812-b5e2e700-beb0-11eb-923c-55ae1a8ca249.png)

## Alternatives I've considered
I've tried using the **photon-style-tabs** branch however the branch seems bugged: it does not work.

### Additional context

I think that is all but if anything else is needed I'd be happy to help.

**Comment by black7375** [comment]
Hello, Do you have been try to [photon-style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)?
There are only a few icons.

Later, work is underway so that it can be set as an option.
https://github.com/black7375/Firefox-UI-Fix/blob/865b30a42f55f9a21ca4a53c7552f1ea49413feb/src/icons/panel.scss#L27

**Comment by shahmilav** [comment]
Yes, I am using photon-style.

I understand that there are only a few icons, but is there anything I can do to get all icons?

The included file did not work, in fact there is no such file.

**Comment by black7375** [comment]
This is because it is a development version.
It's hard to predict exactly what it will be released as much as it is  busy.

**Comment by black7375** [comment]
Try using version 5.0.0.
It has been changed to the default setting.
