### ISSUE TITLE
Proposal for improving appearance 

### ISSUE THREAD

**Issue by Cheshire-Behemoth** [black7375/Firefox-UI-Fix#33]
Please make folders in the sidebar of the bookmarks completely flooded color, such as blue. Now their frame look is just terrible.
I also want a dedicated tab to be not just highlighted by a blue stripe from above, but there was a complete fill with color, for better visual perception and speed of finding it among a variety of open tabs.

**Comment by gabri25ele** [comment]
icon colorized (like do CustomCSSforFx) for me it would be a fantastic improving appearance 

![Immagi33ne](https://user-images.githubusercontent.com/33927879/120527848-1dca8d80-c3db-11eb-881d-9afb6129615a.png)

**Comment by black7375** [comment]
- Sidebar Color: Doesn't the color change depending on the theme? We should report it to Bugzilla first.
- Dedicated tab: Do you mean conatainer tab?
- Icon Colorize: Depending on the theme, it may have problems. For example, purple won't look good in `aplenglow` theme.

**Comment by gabri25ele** [comment]
>     * Icon Colorize: Depending on the theme, it may have problems. For example, purple won't look good in `aplenglow` theme.

I agree, but in fact I have never used themes with CustomCSSforFx

**Comment by black7375** [comment]
Sidebar screenshot
![image](https://user-images.githubusercontent.com/25581533/120736589-0921ee80-c4dc-11eb-931a-d1eb7ad2ff27.png)

**Comment by gabri25ele** [comment]
we wait with spasmodic anticipation an improving appearance: the **colorized icons**...

![icon2](https://user-images.githubusercontent.com/33927879/121053046-3eb82780-c7bb-11eb-8ca6-915fb2c3bf5c.png)

![icon1](https://user-images.githubusercontent.com/33927879/121053034-3b24a080-c7bb-11eb-9c28-a6746f3fa1b3.png)

**Comment by gabri25ele** [comment]
folders with color with this
https://www.userchrome.org/what-is-userchrome-css.html#colorbookmarkfolder
maybe can integrate into code a similar thing

**Comment by black7375** [comment]
I'll add it to the wiki first.

**Comment by Cheshire-Behemoth** [comment]
Folders flooded with color - this is exactly what I asked. But about color icons, it seems to me that they look too much and violate the common interface style.

**Comment by gabri25ele** [comment]
> 
> 
> Folders flooded with color - this is exactly what I asked. But about color icons, it seems to me that they look too much and violate the common interface style.

color icons is a must have of all time!

**Comment by black7375** [comment]
A filled folder icon is a reasonable request.

As I said before, there are no plans to add color icons. I'm not confident in dealing with proper colors as well as theme compatibility.

**Comment by gabri25ele** [comment]
> As I said before, there are no plans to add color icons. I'm not confident in dealing with proper colors as well as theme compatibility.

sadness

I'll have to hope for Aris and his CustomCSSforFx

**Comment by 82d** [comment]
remove the color strip in themes where it is not provided
![5](https://user-images.githubusercontent.com/15121782/129254488-32e4564b-0d8b-474f-a176-9fabb2bfad38.png)
>>
![Без имени](https://user-images.githubusercontent.com/15121782/129254708-309a829a-42ec-4539-80cf-5b112c98fde2.png)
```
#appMenu-fxa-separator {
  display: none;
}
```
the code from the Issues. which was satisfied and closed removes this strip.

**Comment by black7375** [comment]
New icons are introduced!!
It's not a filled folder, but it changes noticeably.

![image](https://user-images.githubusercontent.com/25581533/131241047-eb61784c-247f-493a-b48b-b58d907ac216.png)
