### ISSUE TITLE
Pinned tab style looks strange with many open tabs

### ISSUE THREAD

**Issue by burrhole** [black7375/Firefox-UI-Fix#330]
**Describe the bug**
Opening a large number of tabs (enough to enable the tab scrolling buttons) with a few pinned tabs causes the pinned tabs to display strangely, looking as though they're shifted down

**Expected behavior**
The pinned tabs should look consistent with the rest of the UI

**Screenshots**
With a few open tabs
![image](https://user-images.githubusercontent.com/31171855/153591637-eecf06e6-418b-4fe7-bf6d-6b0e189c0978.png)
![image](https://user-images.githubusercontent.com/31171855/153591858-1d1bcb20-c025-43bd-8a80-82ec5fa632fb.png)

When more tabs are opened
![image](https://user-images.githubusercontent.com/31171855/153591681-c400b28f-5c49-4507-bd4e-c2f7b4d0f26f.png)
![image](https://user-images.githubusercontent.com/31171855/153591904-83e9750b-5e1b-44ca-b3e6-afba2c10550e.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**
The tab highlighting also shifts down, but that is difficult to screenshot

**Comment by black7375** [comment]
@BPower0036  Yes, I know.
I was checking a few things before commit.
Please check that you just uploaded it.

**Comment by BPower0036** [comment]
No, it doesn't work.

**Comment by black7375** [comment]
is that so? It is difficult to achieve compatibility than thinking to make uniform height, sorting, and functionality.

The following factors should be considered.
- UI Density
- Screen Size
- Tab Overflowing
- Distribution
- OS
- ..etc

It would be helpful if you could let me know the OS and UI Density you are using.

**Comment by black7375** [comment]
I updated the code. Please do the test.

**Comment by BPower0036** [comment]
Windows 10
Firefox 97.0.1
Compact
Screen size: 1920x1080

**Comment by burrhole** [comment]
FWIW, the latest userChrome.css looks good on my system as well; just for reference I'm using compact mode on a 2560x1440 monitor (unscaled) on ff 97.01.

![image](https://user-images.githubusercontent.com/31171855/154794741-fe5ee624-8de4-4ff2-aa96-8f76bf0851fe.png)
![image](https://user-images.githubusercontent.com/31171855/154794749-aa789533-5549-4a7f-b1d4-8e9750d7dac5.png)

**Comment by black7375** [comment]
Yeah, I think it's been resolved. Thank you all for the testers.
