### ISSUE TITLE
Leftmost tab has 1px gap in fullscreen

### ISSUE THREAD

**Issue by Mintyseer** [black7375/Firefox-UI-Fix#332]
**Describe the bug**

The leftmost tab in regular Lepton is separated from the screen's left edge by an 1px gap, making it somewhat unsatisfying-looking. 

**Expected behavior**

This gap should either be wider, so that it looks intended rather than a misalignment, or gotten rid of altogether.

**Screenshots**

How it currently is (zoomed in upper left corner):
![Screenshot 2022-02-12 151754](https://user-images.githubusercontent.com/94312236/153727093-f53c3d3d-c41a-43c9-9751-7db268d9b7db.png)
How it should be (zoomed in upper left corner):
![new](https://user-images.githubusercontent.com/94312236/153727121-589aa02b-de20-4731-9852-0748ff553f79.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [x] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [x] Light
   - [x] Dark
   - [x] Alpenglow (System: Light)
   - [x] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

Present on Windows 10/11 and Linux Mint 20.

**Comment by Mintyseer** [comment]
Semirelated issue: tabs reach the top of the window in windowed mode, but don't reach the top of the window in fullscreen mode.

**Comment by black7375** [comment]
Hmm.. That's weird.
It's hard to find a code that affects at this time.

- https://searchfox.org/mozilla-central/search?q=sizemode&path=css&case=false&regexp=false
- https://github.com/black7375/Firefox-UI-Fix/search?q=fullScreen
- https://searchfox.org/mozilla-central/search?q=inFullscreen&path=css
- https://searchfox.org/mozilla-central/search?q=sizemode%3Dfullscreen&path=&case=false&regexp=false

But, you can adjust the margin when it is `maximized`.
```css
:root[tabsintitlebar="true"][sizemode="maximized"] #TabsToolbar {
  margin-left: -1px;
}
```

**Comment by Mintyseer** [comment]
> Hmm.. That's weird. It's hard to find a code that affects at this time.
> 
>     * https://searchfox.org/mozilla-central/search?q=sizemode&path=css&case=false&regexp=false
> 
>     * https://github.com/black7375/Firefox-UI-Fix/search?q=fullScreen
> 
>     * https://searchfox.org/mozilla-central/search?q=inFullscreen&path=css
> 
>     * https://searchfox.org/mozilla-central/search?q=sizemode%3Dfullscreen&path=&case=false&regexp=false
> 
> 
> But, you can adjust the margin when it is `maximized`.
> 
> ```css
> :root[tabsintitlebar="true"][sizemode="maximized"] #TabsToolbar {
>   margin-left: -1px;
> }
> ```

Seemed to have fixed the issue. I don't really see any other problems that this change could introduce, so I recommend that it gets included in the next release.

**Comment by black7375** [comment]
It will be included in the next release.
