### ISSUE TITLE
Tab bar height increased in 4.5.8

### ISSUE THREAD

**Issue by osovitskiy** [black7375/Firefox-UI-Fix#333]
**Describe the bug**
After upgrading 4.5.7 -> 4.5.8 tab bar height got bigger and also a 1px padding appear between tab and navigation panel

**Screenshots**
4.5.7
![Untitled1](https://user-images.githubusercontent.com/4147169/153777688-f7d45fb5-675c-4bc1-8623-d4e5cb7afe29.png)
4.5.8
![Untitled2](https://user-images.githubusercontent.com/4147169/153777689-22a37f38-605b-4cbe-83bb-ca5c08130a91.png)

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows 8.1
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Comment by black7375** [comment]
Nice report thanks

**Comment by osovitskiy** [comment]
The fix works for me, thanks!

**Comment by black7375** [comment]
I know that there is still one to two bugs yet, but I'll fix by the weekend this week.
