### ISSUE TITLE
Weird Line Under Tab (Firefox 97)

### ISSUE THREAD

**Issue by TheBrokenRail** [black7375/Firefox-UI-Fix#334]
**Describe the bug**
Weird line underneath tab.

![Screenshot from 2022-02-18 22-20-22](https://user-images.githubusercontent.com/17478432/154784186-8067e6e2-4198-4400-9685-73f00bf764fb.png)

**Expected behavior**
No line.

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: `97.0`
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): `Yaru`
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Comment by black7375** [comment]
I updated the code. Please do the test.

**Comment by smowtenshi** [comment]
I think this "line" is just that tiny space above URL bar, so it's not really a bug.
![image](https://user-images.githubusercontent.com/7839556/154799595-91bfd593-ed49-4ca0-a457-980aaa3f7bf9.png)
(this is how it displays on default theme)

**Comment by TheBrokenRail** [comment]
> I updated the code. Please do the test.

It fixed it! Thanks!

> I think this "line" is just that tiny space above URL bar, so it's not really a bug. ![image](https://user-images.githubusercontent.com/7839556/154799595-91bfd593-ed49-4ca0-a457-980aaa3f7bf9.png) (this is how it displays on default theme)

Regardless of what the "line" is, it isn't supposed to be there, so it's a bug.

**Comment by black7375** [comment]
Tabs in the form attached to the toolbar feel connected only when the same color is connected, so it is better to have no lines.
