### ISSUE TITLE
Pinned tabs shrunk after upgrading to 4.5.9

### ISSUE THREAD

**Issue by osovitskiy** [black7375/Firefox-UI-Fix#336]
**Describe the bug**
After upgrading from 4.5.8 to 4.5.9 pinned tabs width reduced and also separator line appeared like between normal tabs

**Screenshots**
4.5.8
![Untitled1](https://user-images.githubusercontent.com/4147169/155415022-0798dcb1-ab1a-4fe0-be8e-5e896bdc3a12.png)
4.5.9
![Untitled2](https://user-images.githubusercontent.com/4147169/155415033-bdb4e30e-202e-4b87-b636-104461556f94.png)

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows 8.1
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Comment by black7375** [comment]
Are you feeling uncomfortable?

For tab separators, there is also on V88.
![image](https://user-images.githubusercontent.com/25581533/155435269-31b7ffc9-217a-4901-91e4-bee8ef105488.png)

![image](https://user-images.githubusercontent.com/25581533/155435112-e084c4e5-1978-4ab2-b6e5-14607481c3ae.png)

**Comment by osovitskiy** [comment]
Reduced width feels to narrow for my taste, so I ended up applying an override for myself:
```
--- a/userChrome.css
+++ b/userChrome.css
@@ -2814,7 +2814,7 @@ menuitem.openintabs-menuitem,
 }

 .tab-content[pinned] {
-  --inline-tab-padding: 8px; /* Prevent overflow pinned tab's divide line not aligned */
+  --inline-tab-padding: 10px; /* Prevent overflow pinned tab's divide line not aligned */
   padding-inline: var(--inline-tab-padding) !important;
 }
```

Feel free to close the task unless you want to incorporate the change.

**Comment by black7375** [comment]
I have been adjusted except for compact.
