### ISSUE TITLE
Tab highlight not working for custom themes and Alpenglow with FF 97+

### ISSUE THREAD

**Issue by badlydrawnface** [black7375/Firefox-UI-Fix#337]
**Describe the bug**
With (around) FF 97+, the tab highlight of the photon style doesn't not adapt to the highlight color of custom themes, including Alpenglow, falling back to the default blue. Unlike issue #311, there is no problem with system or GTK themes, just with custom, addon themes. (GIF from version 97, Ubuntu 21.10 dpkg)
![vmplayer_tCX9kHOUjI](https://user-images.githubusercontent.com/53501005/156701384-82d4f1fa-c2dd-4519-83fb-49e56bd2a2ed.gif)

All Lepton installations are done through the respective PowerShell/bash scripts through the master branch, on all profiles involved.

**Expected behavior**
The tab highlight in Firefox should match the custom theme's highlight color.

**Screenshots**
![Screenshot 2022-03-03 210450](https://user-images.githubusercontent.com/53501005/156700481-e29c651c-9ce6-4f8e-ab35-1cf098d932af.png)
Dracula 1.9 with stock FF 90 (Windows)

![Screenshot 2022-03-03 210949](https://user-images.githubusercontent.com/53501005/156700520-6a5314e3-f5d9-44e1-8705-82a3857030f9.png)
Dracula 1.9 with FF 90 and lepton photon style (Windows)

![Screenshot 2022-03-03 211017](https://user-images.githubusercontent.com/53501005/156700555-f5d428e5-01e7-47e9-b872-b826903fe035.png)
Dracula 1.9 (NOT THE LATEST 1.9.2, that will default blue becuase no more tab highlight) with FF 98 and lepton photon (Windows)

![Screenshot 2022-03-03 230752](https://user-images.githubusercontent.com/53501005/156700705-4e219111-a92d-4c63-b5cf-7a6944c74557.png)
Yaru-Dark GTK theme (to refute #311) with FF 97 and lepton photon (ubuntu 21.10 dpkg)

### From here on out, all images will be photon with Alpenglow Dark on either FF 90/93 (expected appearance) and 97/98 (actual appearance)

![alpenglow93win](https://user-images.githubusercontent.com/53501005/156704324-4b4a2302-362d-48d2-83aa-dff3203f37ef.png)
Alpenglow on FF 93 (Windows)

<img width="1440" alt="alpenglow93mac" src="https://user-images.githubusercontent.com/53501005/156704358-5946f409-def9-49d1-b190-1402867b658d.png">
Alpenglow on FF 93 (Mac)

![alpenglow93linux](https://user-images.githubusercontent.com/53501005/156704380-7cdf6d6f-9cf8-44ba-8ce2-c2af7af9898d.png)
Alpenglow on FF 93 (Ubuntu)

Now here is the where the issue arises: the latest versions

![alpenglow98win](https://user-images.githubusercontent.com/53501005/156704438-bf6969ab-0f03-4ba3-a586-2762b6d8b438.png)
Alpenglow on FF 98 (Windows)

<img width="1440" alt="alpenglow97mac" src="https://user-images.githubusercontent.com/53501005/156704464-61bfbb3b-9f27-4b16-8fd9-4451f2af5ad3.png">
Alpenglow on FF 97 (Mac)

![alpenglow98linux](https://user-images.githubusercontent.com/53501005/156704492-9d836e1b-8355-4200-a401-35004e0dc8c5.png)
Alpenglow on FF 97 (Ubuntu)

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 90, 93 (work), 97, 98, 99 (don't work)
 - OS:
   - [x] Linux
   - [x] Windows
   - [x] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [x] Alpenglow (System: Light)
   - [x] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [x] Other: [Dracula Dark Theme (v1.9)](https://addons.mozilla.org/en-US/firefox/addon/dracula-dark-colorscheme/), [Gamer But Blue](https://addons.mozilla.org/en-US/firefox/addon/gamer-but-blue/), [Hacker (animated)](https://addons.mozilla.org/en-US/firefox/addon/hacker-animated/), and [Dark Blueprint](https://addons.mozilla.org/en-US/firefox/addon/vivaldi-blueprint)

 
**Additional context**
FF 98 (aurora) on Windows is my daily driver, and has the same issues as 97 stable, so I didn't go out of my way to try 97 on Windows, knowing it would give me the same results.

**Comment by black7375** [comment]
I think it would have been resolved.

Memo:
It's related with #321

**Comment by black7375** [comment]
I'll close it because I was solved now.
