### ISSUE TITLE
Strange lack of 1px in the corner and at the top of the tabs

### ISSUE THREAD

**Issue by kanlukasz** [black7375/Firefox-UI-Fix#339]
**Describe the bug**
As per title

**Screenshots**
![image](https://user-images.githubusercontent.com/30685349/156882276-05e899b0-5509-4475-a927-0d95b4605c19.png)

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style) Latest release
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version:  97.0.2
 - OS:
   - [ ] Linux
   - [x] Windows 10
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**
May be related with https://github.com/black7375/Firefox-UI-Fix/issues/332

**Comment by black7375** [comment]
There was an issue where 1px border was not displayed at the top of the tab bar. #358
![image](https://user-images.githubusercontent.com/25581533/181667536-a48a423c-0e96-4cc5-9146-009714385a9a.png)
![image](https://user-images.githubusercontent.com/25581533/181667670-dae70c57-a233-498b-bb1b-c26dea12bece.png)

It is a line added for consistent OS design.
Do you need an option to remove?

**Comment by kanlukasz** [comment]
I think solving the 1px missing in the corner problem will be sufficient.
The horizontal line is not a big problem, especially since it results from OS

**Comment by black7375** [comment]
Now it will look like this:
![image](https://user-images.githubusercontent.com/25581533/181691204-4558c4ef-29e1-4006-aaad-25172f39e6fe.png)

Thanks for report!!

**Comment by black7375** [comment]
Try to use `v5.3.1` 

https://github.com/black7375/Firefox-UI-Fix/releases/tag/v5.3.1
