### ISSUE TITLE
Version that puts tabs below address bar AND bookmarks toolbar

### ISSUE THREAD

**Issue by Doctor-Butts** [black7375/Firefox-UI-Fix#34]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Either a version that puts the tabs bar below the address and bookmarks bar OR a piece of code I can plop into the css to do it on my own.

**Describe alternatives you've considered**
Rolling back firefox.

**Comment by black7375** [comment]
https://github.com/black7375/Firefox-UI-Fix/issues/9#issuecomment-852995842
> The problem of the bugs that are still too much to manage additional themes is a priority.
Maybe we can discuss it later.
>
> You can try posting your code to the wiki first.
https://github.com/black7375/Firefox-UI-Fix/wiki/Tips

Do you have any code that you used before?

**Comment by black7375** [comment]
Supported on the wiki.
https://github.com/black7375/Firefox-UI-Fix/wiki/Tips#tabs-on-bottom
