### ISSUE TITLE
2 Icons Showing for Open Link in New Private Tab

### ISSUE THREAD

**Issue by thunderstone135** [black7375/Firefox-UI-Fix#340]
**Describe the bug**
Hi, I just want to let you know that 2 icons are showing for Open Link in New Private Tab in version 4.6.0.

**Expected behavior**
It should only show one icon. I prefer the original icon though (the one in violet), but that's just me since I like the contrast in color.

**Screenshots**
![Imgur](https://i.imgur.com/ENLkxvv.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: Using Waterfox G4.0.7
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

**Comment by black7375** [comment]
Recent commits would be resolved.

**Comment by thunderstone135** [comment]
Thanks for the immediate response 👍

**Comment by adamp01** [comment]
@black7375  - I can remove the Private Tab context menu icon on the Waterfox side and have this handled on your end, if you are happy to add it back in?

It's a leftover artifact from the original version of Private Tab so I feel it would make more sense to do it this way.

Let me know what you think, and once again we appreciate the work you are doing to improve the integration with Waterfox.

**Comment by black7375** [comment]
Sounds good.
I agree with your opinion.
