### ISSUE TITLE
Email address on `accounts.firefox.com` is unreadable in dark mode

### ISSUE THREAD

**Issue by smowtenshi** [black7375/Firefox-UI-Fix#341]
**Describe the bug**

Logging into Firefox Accounts you're presented with an email address that's unreadable in Lepton dark mode.

**Expected behavior**

Text color of `div.prefillEmail` should be visible and in contrast with the parent's element background color.

**Screenshots**

![Screenshot](https://user-images.githubusercontent.com/7839556/156947244-ae8a23c6-f193-4fb4-bb10-8e5853ab423a.png)

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [x] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 99.0a1 (build 20220306094505)
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

**Comment by black7375** [comment]
Now, It's fixed.
Thanks for reports.
