### ISSUE TITLE
Edit Bookmark Text And Background Uses The Same Color

### ISSUE THREAD

**Issue by thunderstone135** [black7375/Firefox-UI-Fix#343]
**Describe the bug**
Hi, I just want to let you know that when I click Edit Bookmark > Show all the bookmarks folders, the text and background uses the same color.

**_Edit:_** Apparently, Light Theme is not affected (Add Bookmark uses Dark Theme though). If you are using Dark Theme, however...

**Expected behavior**
The color should be the same with Add Bookmark. Please see the screenshots for comparison.

**Screenshots**

**_Edit Bookmark_**
![Imgur](https://i.imgur.com/CG0LAFS.png)

**_Add Bookmark_**
![Imgur](https://i.imgur.com/Jj3PeEw.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: Using Waterfox G4.0.7
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

**Comment by black7375** [comment]
Are you using the latest code?
It looks like the following screenshot.
![image](https://user-images.githubusercontent.com/25581533/157020336-27f3068d-8b66-4854-91cc-d5684d0d7e30.png)

Please let me know if you are using a theme installed with an add-on.

**Comment by thunderstone135** [comment]
I am using the latest code. The screenshot you provided was for Add Bookmark. I was talking about the Edit Bookmark (when you click the Star Icon on the Address Bar).

**Comment by thunderstone135** [comment]
Hi, I have some interesting discoveries when I performed a live debug.

**_Default_** - I changed nothing here
![Imgur](https://imgur.com/pLcm0VH.png)

**_Black_** - I changed it to Black
![Imgur](https://imgur.com/zFPrHEA.png)

**_Result_** - What happened when I changed it to Black
![Imgur](https://imgur.com/CyKkncW.png)

Now, if I edit userchrome.css directly and change this line 👇 

```
#editBMPanel_folderTree:-moz-lwtheme > treechildren,
#editBMPanel_tagsSelector:-moz-lwtheme {
  background-color: color-mix(in srgb, var(--arrowpanel-background) 35%, var(--in-content-box-background)) !important;
}
```

To this one 👇 

```
#editBMPanel_folderTree:-moz-lwtheme > treechildren,
#editBMPanel_tagsSelector:-moz-lwtheme {
  background-color: rgb(0, 0, 0) !important;
}
```

**_Result_** - I edited userchrome.css directly
![Imgur](https://imgur.com/iwFrjMX.png)

With that said, I'm not sure why Waterfox is not acknowledging this line 👇 

```
#editBMPanel_folderTree:-moz-lwtheme > treechildren,
#editBMPanel_tagsSelector:-moz-lwtheme {
  background-color: color-mix(in srgb, var(--arrowpanel-background) 35%, var(--in-content-box-background)) !important;
}
```

But acknowledges this one 👇 

```
#editBMPanel_folderTree:-moz-lwtheme > treechildren,
#editBMPanel_tagsSelector:-moz-lwtheme {
  background-color: rgb(0, 0, 0) !important;
}
```

All I know is that Waterfox is based on Firefox ESR specifically version 91.7.0. Could that be it? 🤔

**Comment by black7375** [comment]
It's a quitly strange
![Win10-2022-03-08-09-29-00](https://user-images.githubusercontent.com/25581533/157156812-6bf00c26-df1d-4486-ba7d-4a03c6bfce2a.png)

In my waterfox, it is applied normally.

---

One thing guess.
You can check `layout.css.color-mix.enabled` to `true` at `about:config`.

**Comment by thunderstone135** [comment]
Wow, you nailed it 👍 Thanks man 🥇 

I changed the pref and restarted Waterfox, then boom. I wonder why it was set to false by default 🤔

**Comment by black7375** [comment]
It may be because the water fox setting value used in the past has been maintained.
I don't know exactly...:cry:
