### ISSUE TITLE
[macOS] Lepton cuts off the top of the page in fullscreen

### ISSUE THREAD

**Issue by badlydrawnface** [black7375/Firefox-UI-Fix#344]
**Describe the bug**
All lepton styles, when in fullscreen, cut off the top part of the screen, making it difficult to access unless you hide the toolbars in fullscreen or exit fullscreen. In fact, when you hide the toolbars in fullscreen, it is impossible to turn it back on, as well as use the toolbar in fullscreen. I had to go into troubleshooting mode to turn the toolbars back on in fullscreen.

**Expected behavior**
The UI should work like stock Firefox in macOS fullscreen.

**Screenshots**
![Kapture 2022-03-07 at 08 01 59](https://user-images.githubusercontent.com/53501005/157039913-cfe248f2-6a25-40b4-a1a9-3be46da1b3e5.gif)
*its a signed off youtube, fresh profile, btw, firefox 97*
<img width="1440" alt="Screen Shot 2022-03-07 at 8 11 12 AM" src="https://user-images.githubusercontent.com/53501005/157040922-650aab5e-f60c-426e-b259-1ce9a9a6cabe.png">
firefox 98 aurora

**Environment:**
 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [x] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 97.0.2, 98.0b10
 - OS:
   - [ ] Linux
   - [ ] Windows
   - [x] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**
Tested all three Lepton styles, and they all had this issue.

**Comment by black7375** [comment]
I checked it, and fullscreen has different behavior only in Mac.
I acted to be deactivated on the Mac.

Thanks for reports :+1:

**Comment by black7375** [comment]
Now, it has been solved.
