### ISSUE TITLE
Icons/Text squished together

### ISSUE THREAD

**Issue by ctrlcmdshft** [black7375/Firefox-UI-Fix#345]
**Describe the bug**
Icons/Text messed up in newest beta 99.0b1 in bookmark and right click menus 

**Expected behavior**
Shouldn't be squished together

**Screenshots**
in bookmark and right click menus 

![firefox_878](https://user-images.githubusercontent.com/61129128/157328668-ca36db1b-f993-44e4-ba24-8829c932fc5f.jpg)

![firefox_879](https://user-images.githubusercontent.com/61129128/157328807-4a56da0e-999d-4fb4-b02a-b70bd43496a2.jpg)

 - Lepton's proton style
 - Firefox Version: 99.0b1
 - OS: Windows
 - Theme: Dark

**Comment by black7375** [comment]
I think this issue duplicate with #331

**Comment by ctrlcmdshft** [comment]
that fixed it but had to manually update as the powershell command didnt work for me this time
