### ISSUE TITLE
Tab dividers are too agressive

### ISSUE THREAD

**Issue by waclaw66** [black7375/Firefox-UI-Fix#346]
Tab dividers are now too agressive and thick. 
I preffer the previous appereance with thin dividers and no dividers between pinned tabs.

**Is your feature request related to a problem?**
Both

**The solution I'd like**
Make it as it was previsouly (4.5.3) if possible.

**Screenshots or video**
Before
![obrazek](https://user-images.githubusercontent.com/15554561/157668697-74246147-34f9-4405-bf76-21699c56af13.png)

Now
![obrazek](https://user-images.githubusercontent.com/15554561/157668709-7a918c43-b24d-4da1-8496-01be2af513b5.png)

**Comment by black7375** [comment]
Pinned tab seperator will remain in place because it also existed in the old version of Firefox.

https://github.com/black7375/Firefox-UI-Fix/issues/336#issuecomment-1049375418

> For tab separators, there is also on V88.
> ![image](https://user-images.githubusercontent.com/25581533/155435269-31b7ffc9-217a-4901-91e4-bee8ef105488.png)

---

Are you Windows 10 users?
I'll check the thickness difference over the weekend.

**Comment by waclaw66** [comment]
@black7375 yes, it's Win10. Thickness of dividers could be less intrusive.

**Comment by black7375** [comment]
It would have been fixed now.

**Comment by waclaw66** [comment]
Perfect, now it is pleasing to the eyes. Thanks.
