### ISSUE TITLE
Installing the Lepton Photon style makes the background of the save file dialog box entirely white.

### ISSUE THREAD

**Issue by gettysburg** [black7375/Firefox-UI-Fix#347]
**Describe the bug**

After installing Lepton by first setting ``toolkit.legacyUserProfileCustomizations.stylesheets`` to ``true``

and then copying the following files and folders

``icons``
``userChrome.css``
``userContent.css``

into my ``chrome`` folder,

I noticed that the dialog asking you what to do with a file you are downloading has now gone all white.

**Expected behavior**

This is the expected look of the dialog, prior to the installation of Lepton.

![before](https://user-images.githubusercontent.com/2256003/159071064-9524e9c3-0145-472e-bc97-e6865b2287f0.JPG)

**Screenshots**

However, with Lepton (Photon Style) installed and enabled, it now looks like this:

![after](https://user-images.githubusercontent.com/2256003/159072568-067befd6-0aeb-4424-b1cc-e5ebe101fba7.JPG)

Surely, this is not how it's supposed to look - this happens on all 3 versions, Lepton (Photon Style), Lepton (Proton Style) and Lepton.

**Environment:**

 - Distribution
   - [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [X] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [X] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: Firefox 91.7.1esr
 - OS:
   - [X] Windows Server 2019 LTSC / 1809.17763.2628
 - Theme:
   - [X] System Default
    
**Additional context**

Thank you for this awesome UI fix, I really disliked what they did to the Firefox UI over the last year. Lepton (Photon Style) completely restores that old look, except for maybe adding too many icons.

Maybe release a version without the icons, and let the browser handle that part?

Anyway, hope a fix for this can be found - ask away if you need more information about my setup.

**Comment by black7375** [comment]
In the [current development version](https://github.com/black7375/Firefox-UI-Fix/tree/scss), on / off is configured to make it possible.

https://github.com/black7375/Firefox-UI-Fix/blob/5f07cb56a7bc42fdbe4804ffa55d359bbcc1464a/user.js#L66

However, it is still unstable.
I plan to have a beta period of about a month before the final release.

---

I have no intention of changing the default value at the moment.

**Comment by gettysburg** [comment]
Thanks, that's all I needed to hear regarding the dialog.

How about the icons, is there a pref for those as well? I don't remember Firefox 78 having so many icons, and Firefox 78 ESR is what I used for a long time now.

**Comment by gettysburg** [comment]
Also: Would that have any design implications or would my browser still look the same?

Or the same question, asked differently: Does that preference only affect that one download dialog?

**Comment by gettysburg** [comment]
Could you please answer my two remaining replies?

So far your UI fix made Firefox usable again for me, but the white Popup-Menu's are.. ugly. How is the beta test going, regarding stability?

So, if I understood you correctly, I would have to just install an updated version of **Lepton (Photon Edition)**, _because that's what I prefer_, and all these white backgrounds would be colorized / grey again?

**Comment by black7375** [comment]
There are a few things such as documentation and install script work, but it is a goal to release at the end of this month.

**Comment by black7375** [comment]
Try using version 5.0.0 options.
- `userChrome.theme.proton_chrome` to `false`

**Comment by gettysburg** [comment]
Thank you, I confirm that ``userChrome.theme.proton_chrome`` set to ``false`` in ``user.js`` fixes the issue:

![image](https://user-images.githubusercontent.com/2256003/165341393-cd30038e-8cd2-4720-b04a-5e055aaf1889.png)

Only thing I noticed is some font drawing height issue, this is what I mean:

![image](https://user-images.githubusercontent.com/2256003/165342095-863925f4-462a-4c9f-8996-1efbf85d7681.JPG)

Both the file type and url should be drawn on the same height as the labels.

But since this happens with ``userChrome.theme.proton_chrome`` set to ``true`` as well and in a new, unmodified profile, this is up to Mozilla to fix.

Thank you for the great configuration system by the way, I like your work, you are keeping Firefox usable 👍

**Comment by gettysburg** [comment]
Thank you, I confirm that ``userChrome.theme.proton_chrome`` set to ``false`` in ``user.js`` fixes the issue:

![image](https://user-images.githubusercontent.com/2256003/165341393-cd30038e-8cd2-4720-b04a-5e055aaf1889.png)

Only thing I noticed is some font drawing height issue:

![image](https://user-images.githubusercontent.com/2256003/165344134-a2ecda95-47fb-42b8-920b-da3bd62602af.JPG)

Both the file type and url should be drawn on the same height as the labels.

But since this happens with ``userChrome.theme.proton_chrome`` set to ``true`` as well and in a new, unmodified profile, this is up to Mozilla to fix.

Thank you for the great configuration system by the way, I like your work, you are keeping Firefox usable 👍
