### ISSUE TITLE
Context Menu Icons

### ISSUE THREAD

**Issue by ncodee** [black7375/Firefox-UI-Fix#35]
**Describe the solution you'd like**
It would be great if you could add icons to the context menu, when right clicking on a webpage. (Save Page As, Screenshot, Search with Google etc...)

**Additional context**
Thank you for the great work you have done so far.

**Comment by LordRishav** [comment]
I would like to see it too. I do believe Proton looks cool and modern, but the lack of icons in context menus and now the menus makes it difficult to recognize items on the first glance. Lepton makes it better, but I would still like context menu icons which were removed in FF 88 (before Proton).

**Comment by black7375** [comment]
It's already on the roadmap. #2
It is currently being worked on and will be released within this month.

Thanks for the suggestion.
