### ISSUE TITLE
strange glitches when Dev Tools and Responsive Design Mode are active?

### ISSUE THREAD

**Issue by catalin560** [black7375/Firefox-UI-Fix#353]
![Capture](https://user-images.githubusercontent.com/22744333/162419650-dd6ba4e4-74b1-4e2c-bb17-91a579cf52c4.JPG)

Firefox v99.0 (64-bit), Windows 10

For some reason when `Responsive Design Mode` is active if I right click on the page (for example where the blue "X" is in the image), the Context Menu will appear somewhere else entirely... I'm not sure if this is a issue with Firefox itself or is it because of these user styles...

Also the UI seems to behave strange when Light Mode is selected in Dev Tools options, some icons will default to dark background (like the hand icon in the red circle), or will transition to a dark background when hovering over them (like the rest of the icons on the top bar right side, the camera, the cog and the close buttons, and even the select options on the middle of the top bar, like the `No Throttling` or the `test` selects)...

**Comment by black7375** [comment]
![image](https://user-images.githubusercontent.com/25581533/181668384-279bfe03-fd1d-4888-b633-e4ced1c05591.png)
I think the issue is solved in the latest version.
