### ISSUE TITLE
Right-click menu icons overlapping text

### ISSUE THREAD

**Issue by grantlison** [black7375/Firefox-UI-Fix#354]
**Describe the bug**
In the right-click menus the icons on the left are overlapping the text of the options.
Started happening with the new firefox update.

**Expected behavior**
The text is moved rightwards to not overlap the icons.

**Screenshots**
![image](https://user-images.githubusercontent.com/55083972/162551915-3ddcf29f-467b-4b17-bf99-71a4ea1e8823.png)

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Comment by black7375** [comment]
Try a theme upgrade.
As far as I can remember, this is a bug that has already been fixed. #331

**Comment by grantlison** [comment]
Theme upgrade worked. Sorry for not finding the other issue.
