### ISSUE TITLE
Hamburger menu cut on right side

### ISSUE THREAD

**Issue by waclaw66** [black7375/Firefox-UI-Fix#359]
**Describe the bug**
Hamburger menu is cut on right side since Firefox 100b.

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/15554561/163322483-9a40ba34-8dbf-4903-9ebe-c53eaaaec383.png)

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

**Comment by black7375** [comment]
I understand that some languages are truncated.
https://bugzilla.mozilla.org/show_bug.cgi?id=1763910

Could you tell me what language it is?
If that bug is fixed but it doesn't work, I'll patch it.

**Comment by waclaw66** [comment]
@black7375 Correct, it's Czech. I'll be monitoring that Firefox bug and let you know when it's fixed there. Thanks.

**Comment by waclaw66** [comment]
Firefox devs successfully fixed this issue in 100b9.
