### ISSUE TITLE
Lepton v4.6.3 is missing some icons on FF v100.0a1 nightly

### ISSUE THREAD

**Issue by eladkarako** [black7375/Firefox-UI-Fix#361]
<img width="415" alt="2022-04-16_095804" src="https://user-images.githubusercontent.com/415238/163667103-88ca03a1-2b39-4cb0-bf52-909de41619c0.png">
<img width="114" alt="2022-04-16_095440" src="https://user-images.githubusercontent.com/415238/163667104-8710598f-b7d4-4e86-a2f2-00f31e256f80.png">
<img width="151" alt="2022-04-16_095537" src="https://user-images.githubusercontent.com/415238/163667107-611a99b5-543f-45ea-a022-de3c23f46110.png">
<img width="203" alt="2022-04-16_095619" src="https://user-images.githubusercontent.com/415238/163667108-47b7261c-116b-4118-935a-bc25cd75bc89.png">
<img width="202" alt="2022-04-16_095654" src="https://user-images.githubusercontent.com/415238/163667109-5efdf391-4c81-4f21-be2b-5643b99cbaf3.png">
<img width="217" alt="2022-04-16_111330" src="https://user-images.githubusercontent.com/415238/163667699-5583c37a-b404-49fc-94bb-015fc0e68442.png">

**Comment by black7375** [comment]
In most cases,  problems caused by check boxes or radio buttons will be solved with the issue #349 .

They have to keep a checkmark, so it's quite tricky.

---

`Redo` or `Paste and Go` has no proper icon, and I don't have enough ability to make them.

Fortunately, there is no big problem even if it is empty as an icon with a continuous meaning.

The same as 
![image](https://user-images.githubusercontent.com/25581533/163714814-3bdf2be6-21ca-42ec-8c91-7ddbf31f1b6b.png)

**Comment by eladkarako** [comment]
yes I can see, this is a duplicate.

**Comment by eladkarako** [comment]
<blockquote>problems caused by check boxes or radio buttons will be solved with the issue https://github.com/black7375/Firefox-UI-Fix/issues/349 .</blockquote>

not sure how helpful this comment would be (if any),  
but I think styling of checkboxes is done by hiding the actual checkbox and using a <a href="https://gist.github.com/eladkarako/ab7a98b67a42010eca087c26d3ead76b">little trick to style a label instead</a> (or sometime the `:before` of the checkbox), the checkbox state-behavior is kept, and the label can be styled with ease, at least this is how bootstrap and jquery are doing it. 

as for images I often joining two, mostly from https://github.com/tabler/tabler-icons 
(source: https://github.com/notlmn/awesome-icons )
