### ISSUE TITLE
Some dropdown menus on certain webpages are hard to read in Windows 10/11

### ISSUE THREAD

**Issue by eaw4690** [black7375/Firefox-UI-Fix#362]
**Describe the bug**
In Windows 10/11, dropdown menus on certain web pages are hard to read when hovering depending on the theme installed.
Theme used: [Example theme here](https://addons.mozilla.org/en-US/firefox/addon/sapphire-mountain/) or use Firefox Alpenglow
[Example web page here](https://www.mozilla.org/en-US/firefox/all/)

**Expected behavior**
Dropdown menus when hovered must be readable on certain themes.

**Screenshots**
Without Lepton
![2](https://user-images.githubusercontent.com/104198709/164680414-cd63da2a-4b1c-4388-baba-3e7b81f9905a.PNG)
With Lepton
![1](https://user-images.githubusercontent.com/104198709/164680437-4032ac0a-00cc-4db8-8ed8-4190bff3dc5a.PNG)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [x] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 99.0 (stable), 100.0b (Beta/Developer Edition)
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [x] Alpenglow (System: Light)
   - [x] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [x] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**
It seems that [button_background_hover](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme#colors) on the theme applied the color of the dropdown menu when hovering.
Might be related: #320

**Comment by eaw4690** [comment]
#320

**Comment by black7375** [comment]
Thank you for your detailed issue !!
I will reflect on the next release.

**Comment by black7375** [comment]
After `v5.0` , it should be fixed!!
