### ISSUE TITLE
Wrong padding for 2 menuitems(checkbox)

### ISSUE THREAD

**Issue by benzBrake** [black7375/Firefox-UI-Fix#363]
**Describe the bug**
Wrong padding for 2 menuitems(those are checkbox):
1. download buttons context popup 
`#toolbar-context-autohide-downloads-button`
2. alltabs-button popup
`#allTabsMenu_sortTabsButton`
**Screenshots**

![wrong_padding_1](https://user-images.githubusercontent.com/11323774/164887983-70060e4b-4139-489e-be95-29f9c60ea9ed.png)
![wrong_prefix_2](https://user-images.githubusercontent.com/11323774/164887984-acd3754c-4a62-4705-a0a2-3ffe81f9c5c4.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [x] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

**Comment by black7375** [comment]
Can I see screenshot?

**Comment by benzBrake** [comment]
> Can I see screenshot?

I have uploaded the screenhosts

**Comment by BPower0036** [comment]
You have to change `[checked="false"]` to `:not([checked="true"])` in `icons_layout`
(**`> menuitem[type="checkbox"]:not([checked="true"])`**)
```
/* Padding - Windows */
@media (-moz-os-version: windows-win7), (-moz-os-version: windows-win8), (-moz-os-version: windows-win10), /* Legacy - v99 */
       (-moz-platform: windows-win7), (-moz-platform: windows-win8), (-moz-platform: windows-win10) {
  /* Checkbox */
  :root {
    --context-menu-text-padding: calc(var(--menu-padding) + var(--context-menu-background-padding-default) + 16px);
  }
  :not(menu, #ContentSelectDropdown, #context-navigation)
    > menupopup
    > menuitem[type="checkbox"]:not([checked="true"])
    > .menu-iconic-left {
    padding-inline-start: var(--context-menu-text-padding);
  }
}
