### ISSUE TITLE
Powershell: Cannot bind positional parameters because no names were given

### ISSUE THREAD

**Issue by someone755** [black7375/Firefox-UI-Fix#364]
**Describe the bug**
When trying to update (read: already installed once) by running the powershell script on Windows 10 21H2, this is the output:
```
PS C:\Users\user> Powershell -c "Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iwr https://raw.githubusercontent.com/black7375/Firefox-UI-Fix/master/install.ps1 -useb | iex"
Checking PowerShell version... [5]
Checked install type: Local ......................OK
Profiles dir found ...............................OK
Profiles info file found .........................OK
Profile paths updated ............................OK
Lepton info file found ...........................OK
Lepton info file created .........................OK
  C:\Users\user\AppData\Roaming\Mozilla\Firefox\Profiles/41fsrr1o.default
> C:\Users\user\AppData\Roaming\Mozilla\Firefox\Profiles/pfd89dpk.default-release
  C:\Users\user\AppData\Roaming\Waterfox\Profiles/b4k7ojpm.default
  C:\Users\user\AppData\Roaming\Waterfox\Profiles/dz910fcs.68-edition-default
Selected profile .................................OK
Started install ..................................OK
Copy-Lepton : Cannot bind positional parameters because no names were given.
At line:694 char:3
+   Copy-Lepton "${currentDir}" "user.js"
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Copy-Lepton], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousPositionalParameterNoName,Copy-Lepton

End install ......................................OK
Lepton info file found ...........................OK
Lepton info file created .........................OK
```

**Expected behavior**

After selecting the profile folder, the script should proceed without an error.
**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [x] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [x] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

Copying the files from the release .zip manually works alright. I've tested this on two computers and both exhibit the same problem.

**Comment by black7375** [comment]
After `v5.0.0`, works well
![image](https://user-images.githubusercontent.com/25581533/165160758-8a77671c-e1ab-400d-bab4-5a6fb0a81d21.png)

Thanks for report.

**Comment by Ryunam** [comment]
Hi, unfortunately I think this should be re-opened or investigated further. I'm stumbling on the same exact error with the latest version, whenever trying to update through the Powershell script command.

This is the error that comes up now:

```
Copy-Lepton : Cannot bind positional parameters because no names were given.
At line:843 char:3
+   Copy-Lepton "${currentDir}" "user.js"
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Copy-Lepton], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousPositionalParameterNoName,Copy-Lepton
```

**Comment by black7375** [comment]
What was the path to run the script?

**Comment by Ryunam** [comment]
I used the command provided in the readme of the repo, that is `Powershell -c "Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iwr https://raw.githubusercontent.com/black7375/Firefox-UI-Fix/master/install.ps1 -useb | iex"`

If you're referring to the profile path, it is `C:\Users\My-Username\AppData\Roaming\Mozilla\Firefox\Profiles\2d0ifbuu.default-release`.

**Comment by black7375** [comment]
Temporary solution: Try running it outside of the profile path.

**Comment by black7375** [comment]
Now it should be resolved.
Refer: #436
