### ISSUE TITLE
Unreadable text on Add-on Developer Hub page

### ISSUE THREAD

**Issue by filips123** [black7375/Firefox-UI-Fix#365]
**Describe the bug**

When using Firefox-UI-Fix with Firefox dark theme, text on [Add-on Developer Hub](https://addons.mozilla.org/en-US/developers/) becomes unreadable because of [CSS changes](https://github.com/black7375/Firefox-UI-Fix/blob/proton-style/userContent.css#L540-L767).

**Expected behavior**

All text should be readable. Additionally, it would be nice if all of the developer hub supported dark mode, not just the main page.

**Screenshots**

<details>
  <summary>Main developer hub page</summary>
  
  * Some text is dark on dark background.
  * Text in the footer (under Contribute section) is white.
  * Links do not have consistent colors.
  * "Resources" footer still has white background.
  * Background image in the "Build best-in-class extensions and themes" box is missing.
  
  ![screenshot main page](https://user-images.githubusercontent.com/16626308/164984256-dc0025f2-c963-4cf5-bcb0-c3803bf8d542.png)
</details>

<details>
  <summary>Addon details page</summary>

  * Almost all text is white on white background.
  * Page does not use dark mode.

  ![screenshot addon details page](https://user-images.githubusercontent.com/16626308/164984639-a4aca954-a678-4fcf-b964-55dd358715fe.png)
</details>

<details>
   <summary>Addon statistics page</summary>

  * Text under charts is white on white background.
  * Page does not use dark mode.

    ![screenshot addon statistics page](https://user-images.githubusercontent.com/16626308/164984800-c65777a3-9b66-440c-90fe-2a499511d27c.png)
</details>

**Environment**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [x] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 101.0a1
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**

I will soon submit PR that fixes unreadable text (but without complete dark mode support).

**Comment by black7375** [comment]
It may be difficult to test right away because I didn't migrate the 2FA when I changed phone last year.
Sooner or later, I'll look for old phone.

**Comment by black7375** [comment]
Yesterday I found Mozilla account and applied dark mode.
Would you like to test?

cc @filips123  @und3fined

**Comment by und3fined** [comment]
@black7375 hi there, i used version 5.2.0. No problem with Addons Hub page

**Comment by black7375** [comment]
It hasb't been released yet (need to use the latest commit)

**Comment by und3fined** [comment]
> It hasb't been released yet (need to use the latest commit)
5.2.0 there

<img width="716" alt="Screenshot 2022-06-24 at 09 34 27" src="https://user-images.githubusercontent.com/2163878/175450821-82c232f5-0fc9-47c5-86c7-f91748765b38.png">

**Comment by black7375** [comment]
To be a little more clear,

**Main developer hub page**
- Bugs and color adjustments where background images were not visible

![image](https://user-images.githubusercontent.com/25581533/175451516-081ef9a2-34f5-4822-a4bd-0a706fc092e3.png)

**Addon details page & Addon statistics page**

- Dark mode supports

![image](https://user-images.githubusercontent.com/25581533/175451742-e118190e-4f43-4bd3-b29a-b3b823327b7c.png)

![image](https://user-images.githubusercontent.com/25581533/175451989-db3448b2-ac04-4a8c-a2d5-8c02117cd81e.png)

**Comment by filips123** [comment]
It works mostly fine for me on the latest commit, but there are still a few minor problems.

* This gray text should probably be a bit brighter for better contrast and readability:

![screenshot](https://user-images.githubusercontent.com/16626308/175523118-d175f5b8-e74e-43ec-aa1f-42e4a7776704.png)
![screenshot](https://user-images.githubusercontent.com/16626308/175523381-8b469a69-82df-4022-b18b-fa346529e3d7.png)

* Activity feed/recent changes content is still white:

![screenshot](https://user-images.githubusercontent.com/16626308/175524305-98a2c524-a789-4b6b-afb9-acb5841beab9.png)


* Boxes for validation result are also still white:

![screenshot](https://user-images.githubusercontent.com/16626308/175524167-d7792b9b-af91-43ac-ac64-3e426104f759.png)

Other things seem to work fine and it looks quite nice.

**Comment by black7375** [comment]
Thank you for taking the time to test. 
I revised it according to your feedback.

![image](https://user-images.githubusercontent.com/25581533/175583195-e36599fa-57e9-413b-975f-0c1fb3601fd1.png)

![image](https://user-images.githubusercontent.com/25581533/175585916-f3b3b335-56fb-48cf-a932-3f4d167fc0d6.png)

![image](https://user-images.githubusercontent.com/25581533/175580587-e9928634-0921-40e7-9312-724bced6d11e.png)

**Comment by filips123** [comment]
Thanks!

**Comment by black7375** [comment]
Included in the `v5.2.1` release.
