### ISSUE TITLE
V5 Unclear instructions, complicated setup, chaotic documentation

### ISSUE THREAD

**Issue by catalin560** [black7375/Firefox-UI-Fix#369]
I've been trying to get the old UI that was used in 88 and earlier, but it just doesn't work anymore... I've been following the instructions from here: https://github.com/black7375/Firefox-UI-Fix/wiki/Installation-Guide and here https://github.com/black7375/Firefox-UI-Fix/wiki/Options to no avail... please return to the old release format where you provided 2 separate designs...

Plus, you still haven't fixed the issues in #353 with the context menu.

**Comment by black7375** [comment]
Are you photon-style user?
Here is a setting file.
https://github.com/black7375/Firefox-UI-Fix/blob/photon-style/user.js

https://github.com/black7375/Firefox-UI-Fix/blob/55bbb6887c52d325eea6b06c1b0c1f7290281986/user.js#L30-L54

**Comment by catalin560** [comment]
it doesn't work...

![Capture](https://user-images.githubusercontent.com/22744333/165459726-650cccae-0088-4286-8f8b-d59ea1323ef1.JPG)

**Comment by bb010g** [comment]
@catalin560 Have you made `/chrome/css/leptonChrome.css` and `/chrome/css/leptonContent.css` available under your profile? `/chrome/userChrome.css` and `/chrome/userContent.css` now reference them.
