### ISSUE TITLE
Context Menu color

### ISSUE THREAD

**Issue by sam595** [black7375/Firefox-UI-Fix#37]
Thanks for your work！ this is more straightful ui.
anyway i wonder is there a way to change Context Menu color？
『context menu color will auto correct depend on Background Tab Text Color your theme used』
https://i.imgur.com/7mqFSic.png
![image](https://user-images.githubusercontent.com/25581533/122501134-a8b6a500-cfe3-11eb-98e2-c1d959933f2c.png)

the different color just feel strange, is there a way to change it？thanks！

**Comment by black7375** [comment]
I'll try it later, but it might be good to have it resolved upstream. like #33

**Comment by black7375** [comment]
Now, supported context menu color at `dev` branch.
![alpenglow context menu](https://user-images.githubusercontent.com/25581533/125150186-79500f80-e12d-11eb-9b61-0647ff8426a1.png)
