### ISSUE TITLE
V5 Nav Bar (Cut Off) And Menu + Tab Bar (Missing)

### ISSUE THREAD

**Issue by thunderstone135** [black7375/Firefox-UI-Fix#370]
**Describe the bug**
Hi, I just want to let you know that that after installing the latest version, the Nav Bar was cut off and Menu + Tab Bar went missing.

**Expected behavior**
The latest version should act like previous versions even if there were modifications to the code.

**Screenshots**
Nav Bar is only showing 2/3 and Menu + Tab Bar is totally not showing up.
If I revert to the previous version, everything is working fine.
![Imgur](https://imgur.com/XnJv15L.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [x] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: Waterfox G4.1.1
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**`user.js` setup**
I'm using the same one posted **[here](https://github.com/black7375/Firefox-UI-Fix/blob/master/user.js)**.

**```javascript```**
I'm using default Waterfox Prefs.

**Additional context**
N/A

**Comment by thunderstone135** [comment]
**Update:**
I noticed that there's a v5.0.1 released, so I installed that. This time, however, Menu + Tab Bar are cut off.

Tab Bar
![Imgur](https://imgur.com/3HKoGxo.png)

Tab Bar + Menu Bar
![Imgur](https://imgur.com/GtDhTHn.png)

**Comment by black7375** [comment]
I applied the basics setting, and it works well in my environment.

![Win10-2022-04-26-19-39-25](https://user-images.githubusercontent.com/25581533/165282418-f70f23fe-45a7-4c24-b07a-63f58f1fd2e0.png)
![Win10-2022-04-26-19-33-41](https://user-images.githubusercontent.com/25581533/165281839-06885938-209f-4679-bb3f-5ed908ed38e3.png)
![Win10-2022-04-26-19-34-04](https://user-images.githubusercontent.com/25581533/165281842-5bf1df7f-1316-40ac-b6aa-a9b19e74ced1.png)

- Watefox Version: `G4.1.1.1`

I think I need something to set up for reproduction.

**Comment by thunderstone135** [comment]
I noticed that you don't have the window maximized.
Mine is set to maximized and the Menu + Tab Bar are cut off.
If I don't maximize them (like yours), they show up just fine.

**Comment by siedenburg2** [comment]
I set tabs to small over the firefox customization tab and had the same problem.
If the css folder is delted you could at least get your tabs back.

After some tries I went back to v4, set the layout back to default and than updated to 5.0.1, now I got the tabs, but it seems like they are to high in fullscreen.

FF 99.0.1 on Windows 11

**Comment by s-rog** [comment]
windowed:
![Capture](https://user-images.githubusercontent.com/55400948/165263509-4bcffbdc-3790-4fac-b315-a5567201b1b0.PNG)
maximized:
![Capture1](https://user-images.githubusercontent.com/55400948/165263505-e37d3769-42f2-44d9-8eef-3121b9f7b90c.PNG)
(reposted from #368)

**Comment by hdk5** [comment]
Same issue here.

Menu bar enabled:
![2022-04-26 19_27_17-V5 Nav Bar (Cut Off) And Menu + Tab Bar (Missing) · Issue #370 · black7375_Firef](https://user-images.githubusercontent.com/2550010/165348438-c244fc31-e574-44b5-8264-3007727f11e1.png)

Menu bar disabled:
![2022-04-26 19_27_31-V5 Nav Bar (Cut Off) And Menu + Tab Bar (Missing) · Issue #370 · black7375_Firef](https://user-images.githubusercontent.com/2550010/165348493-225e0a18-0bd4-458d-a5c7-5b8920bf158a.png)

Even with title bar enabled the menu bar looks a few pixels short after update
![2022-04-26 19_29_07-V5 Nav Bar (Cut Off) And Menu + Tab Bar (Missing) · Issue #370 · black7375_Firef](https://user-images.githubusercontent.com/2550010/165348893-f8ba3657-31f6-40b7-96a3-fcb3e44fe72f.png)

**Comment by gettysburg** [comment]
Same issue happens to me when maximized:

![image](https://user-images.githubusercontent.com/2256003/165353177-5357c46c-cef1-4421-9538-c67a22fcaa78.png)

As you can see, the top of the window is cut off when Firefox is maximized.

I am using Lepton (Photon Edition) with the default ``user.js`` except for ``userChrome.theme.proton_chrome`` which I set to ``false`` in order to fix #347.

**Comment by black7375** [comment]
I applied a patch to apply padding. Does it work?

**Comment by thunderstone135** [comment]
> I applied a patch to apply padding. Does it work?

Yep. That fixes it ❤️

**Comment by s-rog** [comment]
> I applied a patch to apply padding. Does it work?

It works! but `userChrome.padding.drag_space` still doesn't work when maximized.

**Comment by black7375** [comment]
@s-rog 
It's a expected behavior.
I replicated the old firefox's behavior.
https://searchfox.org/mozilla-esr78/source/browser/themes/windows/browser.css#117-120

I think it should be implemented as an additional option like like `userChrome.padding.drag_space.maximized`.

It seems to work correctly, so I'll close it. Thank you for the test.

**Comment by gettysburg** [comment]
I can confirm the fix, adding

```
@media (-moz-os-version: windows-win7),
    (-moz-platform: windows-win7),
    (-moz-os-version: windows-win8),
    (-moz-platform: windows-win8),
    (-moz-os-version: windows-win10),
    (-moz-platform: windows-win10) {
    :root[tabsintitlebar="true"][sizemode="maximized"] #navigator-toolbox {
      padding-top: 8px;
    }
  }
```

to ``leptonChrome.css`` fixes the issue on my Windows Server 2019 LTSC system.

**Comment by gettysburg** [comment]
I can confirm that adding

```
@media (-moz-os-version: windows-win7),
    (-moz-platform: windows-win7),
    (-moz-os-version: windows-win8),
    (-moz-platform: windows-win8),
    (-moz-os-version: windows-win10),
    (-moz-platform: windows-win10) {
    :root[tabsintitlebar="true"][sizemode="maximized"] #navigator-toolbox {
      padding-top: 8px;
    }
  }
```

to ``leptonChrome.css`` fixes the issue on my Windows Server 2019 LTSC system.

Thank you for the fast response and release of a patch.

**Comment by gettysburg** [comment]
I can confirm that adding

```
@media (-moz-os-version: windows-win7),
    (-moz-platform: windows-win7),
    (-moz-os-version: windows-win8),
    (-moz-platform: windows-win8),
    (-moz-os-version: windows-win10),
    (-moz-platform: windows-win10) {
    :root[tabsintitlebar="true"][sizemode="maximized"] #navigator-toolbox {
      padding-top: 8px;
    }
  }
```

to ``leptonChrome.css`` fixes the issue on my Windows Server 2019 LTSC system running Firefox 91.8.0esr.

Thank you for the fast response and release of a patch.

**Comment by gettysburg** [comment]
@black7375 

I just upgraded to v5.2.0 - Photon Edition, and the bug re-appeared.

So I opened `leptonChrome.css` and instantly figured out why:

```
@media (-moz-os-version: windows-win7),
    (-moz-platform: windows-win7),
    (-moz-os-version: windows-win8),
    (-moz-platform: windows-win8),
    (-moz-os-version: windows-win10),
    (-moz-platform: windows-win10) {
    :root[tabsintitlebar="true"][sizemode="maximized"] #navigator-toolbox {
      padding-top: 8px;
    }
 }
```

was missing.

Is this intentional, or was the patch not added by mistake?

Alternatively, maybe you decided to fix it using a different way, but there is a bug in your code somewhere?

**Comment by thunderstone135** [comment]
@gettysburg we actually discussed it on e37743cd9ac5b77693a7f172cf390f124c3b4c4f.
I also posted the temporary workaround there.
I'm sure @black7375 will post an official fix later.

**Comment by gettysburg** [comment]
@thunderstone135 Thank you for the update.
