### ISSUE TITLE
V5 Add Bookmarks Menu Wrong Position (Via Drag)

### ISSUE THREAD

**Issue by thunderstone135** [black7375/Firefox-UI-Fix#372]
**Describe the bug**
Hi, I just wanted to let you know that when I add a bookmark (via drag), the Bookmarks Menu appears at the center instead of the right side of the screen.

**Steps to reproduce**
1. Open Waterfox, then open a website on a second tab (the bug will not trigger with just one tab open)
2. Click and drag the Green Lock icon (beside the website link) to the Bookmarks Menu icon at the right side (you need to have the Bookmarks Menu added from Customize Toolbar)

**Expected behavior**
The Bookmarks Menu should appear at the right side of the screen just like in the previous versions.

**Screenshots**
![Imgur](https://imgur.com/9No7QrQ.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [x] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: Waterfox G4.1.1
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**`user.js` setup**
I'm using the same one posted **[here](https://github.com/black7375/Firefox-UI-Fix/blob/master/user.js)**.

**```javascript```**
I'm using default Waterfox Prefs.

**Additional context**
N/A

**Comment by black7375** [comment]
I've patched it, and it seems to work in my environment.
Could you test it?

**Comment by thunderstone135** [comment]
> I've patched it, and it seems to work in my environment. Could you test it?

Yep. That fixes it as well ❤️
