### ISSUE TITLE
[V5] Photon style speaker icon is not visible over the favicon

### ISSUE THREAD

**Issue by defunky** [black7375/Firefox-UI-Fix#373]
**Describe the bug**
The speaker icon is not visible over the favicon, it's hidden until you hover of the tab where it favicon turns into a speaker with the PLAYING text under the tab name.

**Expected behavior**
The speaker icon should be visible at all times on top of the favicon without any text additional text

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**`user.js` setup**
Default photon user.js

**Additional context**

**Comment by black7375** [comment]
Since there was no response for a long time, it is considered to be solved.
