### ISSUE TITLE
[feature request] overly complex installation. please include manual instructions for Windows as well.

### ISSUE THREAD

**Issue by eladkarako** [black7375/Firefox-UI-Fix#377]
afaik, sass is great for repo code maintenance, but distribution might be easier to use for users by simply providing compiled (and beatified if possible) css and svg end result.
you may use 'github actions' for that (it's free and can handle css compilation and other stuff).

**Comment by black7375** [comment]
I didn't understand exactly what this suggestion was.
Do you mean to provide a css file encoding svg as base64?
