### ISSUE TITLE
Active pinned tabs are wider than inactive ones

### ISSUE THREAD

**Issue by LazySoda** [black7375/Firefox-UI-Fix#38]
**Describe the bug**
The width of a pinned tab is increased when selected as the active tab, visibly pushing other tabs when going between pinned and normal tabs.

**Expected behavior**
Pinned tabs having the same width when active, so as to not bump other tabs around.

**Screenshots**
![tabs](https://user-images.githubusercontent.com/47133694/120565264-0679b780-c450-11eb-8537-685d2bfcad2c.png)

**Environment (please complete the following information):**
 - Firefox Version:  89.0
 - OS: Windows
 - Theme: Dark

**Additional context**
Compact mode is enabled.

I'm not 100% sure this deserves to be called a bug, but I wanted to report it anyway.
Thanks so much for making this fix though!

**Comment by black7375** [comment]
It will be discussed after determining #10

**Comment by black7375** [comment]
We decided to reflect #10, and apply only to personal settings (`my-setting`).
Therefore, priority is measured low.

**Comment by black7375** [comment]
It was resolved through the reorganization of `v5.0.0`.
