### ISSUE TITLE
Hide tab bar option

### ISSUE THREAD

**Issue by waclaw66** [black7375/Firefox-UI-Fix#386]
Is there an option to completely hide tab bar? E.g. while using Sidebery?

**Comment by black7375** [comment]
Try to use `v6.0.0`

![](https://user-images.githubusercontent.com/25581533/185762054-1efbb7b2-98fd-4f31-84c5-f765d3df3d63.png)

- https://github.com/black7375/Firefox-UI-Fix/releases/tag/v6.0.0
- https://github.com/black7375/Firefox-UI-Fix/wiki/Options#tab-bar-1

**Comment by waclaw66** [comment]
Very nice, but on FF 104.0b10 in Windows 10 the navbar sits lower than expected.

![obrazek](https://user-images.githubusercontent.com/15554561/186146317-379738ba-be2c-4d5d-a257-f4367b39ce66.png)

**Comment by black7375** [comment]
Thanks, I'll fix it.

**Comment by black7375** [comment]
I added some support for Windows. https://github.com/black7375/Firefox-UI-Fix/commit/02fa9bd036ff416f100689bedebf94f3af8c61b1
Try again please.

**Comment by waclaw66** [comment]
Now it works properly, thanks!
