### ISSUE TITLE
[feature request] right-to-left support (Hebrew/Arabic/..)

### ISSUE THREAD

**Issue by eladkarako** [black7375/Firefox-UI-Fix#387]
thanks for maintaining this repository,  

I've recently installed FF (and LibreWolf) for elderly users,  
the additional icons were excellent!  

When I've changed languages,  
I did however noticed that the icons in RTL languages (Hebrew/Arabic) were kept on the left side.  

<img width="748" alt="2022-05-06_172850" src="https://user-images.githubusercontent.com/415238/167175789-c05a2df7-74fd-45ba-9c20-08a8b4416a4c.png">

**Comment by black7375** [comment]
Since it requires a significant change, I will respond after the code refactoring is completely over.

**Comment by black7375** [comment]
Hello, RTL support is in `master` branch. Would you like to test?

**Comment by eladkarako** [comment]
sorry the installation was too complex for me so I've stopped using it eventually.  
perhaps pinning it and let users know testing is needed.
