### ISSUE TITLE
Active tab showing incorrectly in 102 with some themes

### ISSUE THREAD

**Issue by ali-nz** [black7375/Firefox-UI-Fix#388]
**Describe the bug**
Active tab has a full border in 102

**Expected behavior**
Active tab only shows accent colour at the top

**Screenshots**
101:
![101](https://user-images.githubusercontent.com/81746959/167305698-96c9e92f-1804-4e07-a0aa-c03abc01b749.jpg)

102:
![102](https://user-images.githubusercontent.com/81746959/167305737-08b96c06-f1d2-4acb-a5e4-6d883fd48f95.jpg)

**Environment:**

 - Distribution
   - [x] Lepton's photon style
 - Firefox Version: 102.0a1
 - OS:
   - [x] Win 10 x64
 - Theme:
   - [x] Other: [Classic System Theme](https://addons.mozilla.org/en-GB/firefox/addon/classicsystemtheme/)

**`user.js` setup**

Default

**Comment by black7375** [comment]
Now it should be work.
