### ISSUE TITLE
Toolbar size is too small on Mac

### ISSUE THREAD

**Issue by Legionivo** [black7375/Firefox-UI-Fix#389]
**Describe the bug**
Toolbar size is too small on Mac Big Sur, it's really hard to click on Close/Minimise/etc. See screenshot compared with Chrome. 

**Screenshots**
![Screenshot 2022-05-09 at 16 36 01](https://user-images.githubusercontent.com/12167296/167434176-aee7ead4-c1eb-4dc1-a277-6e94be6cfcaf.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - Version 	100.0
Build ID 	20220428192727
 - OS:
   - [ ] Linux
   - [ ] Windows
   - [x] Mac
   - [ ] Other: 
 - Theme:
   - [x] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**`user.js` setup**

```javascript
None
```

**Additional context**

**Comment by black7375** [comment]
More tools - Customize Toolbar
![image](https://user-images.githubusercontent.com/25581533/167476043-5772fca4-f97d-48fb-acd1-1ead97444861.png)

Disable titlebar
![image](https://user-images.githubusercontent.com/25581533/167475751-fa34b9e2-3c6b-40f3-a7d9-a249320f9ca9.png)

![image](https://user-images.githubusercontent.com/25581533/167475662-1d5e1f5d-cbde-4b9b-88cf-e1a572c87f25.png)

**Comment by Legionivo** [comment]
> More tools - Customize Toolbar ![image](https://user-images.githubusercontent.com/25581533/167476043-5772fca4-f97d-48fb-acd1-1ead97444861.png)
> 
> Disable titlebar ![image](https://user-images.githubusercontent.com/25581533/167475751-fa34b9e2-3c6b-40f3-a7d9-a249320f9ca9.png)
> 
> ![image](https://user-images.githubusercontent.com/25581533/167475662-1d5e1f5d-cbde-4b9b-88cf-e1a572c87f25.png)

I don't have bookmarks bar enabled

**Comment by Legionivo** [comment]
@black7375 thanks, but Titlebar is disabled in my case.
