### ISSUE TITLE
How to Reduce Icon Spacing by any amount?

### ISSUE THREAD

**Issue by MonfGeiger** [black7375/Firefox-UI-Fix#391]
I noticed that the icon spacing for some of my bookmarks (mainly the twitter ones) is a tad bit much, causing the menu window to reach nearly all the way from the top of my screen down to the bottom (picture provided, had to delete names because NSFW reasons)
![Screenshot 2022-05-09 202438](https://user-images.githubusercontent.com/28603306/167530629-f6fa8e69-7432-4250-abed-13eb75cf0e43.png)
is there an option I can adjust to reduce the spacing of these bookmarks to shrink the menu size to whatever levels I desire?

**Comment by MonfGeiger** [comment]
huh.....I forgot to check and see if I had that menu_compact flag enabled just now, so I did a comparison of it disabled and enabled, made screenshots, and side-by-side checked them. lo and behold, I saw no reasonable difference between the spacing of the bookmarks with it enabled/disabled. I think userchrome.padding.menu_compact only affects the right click menu and its other dropdown options, and I dont think it affects the other menus like tools, or help, or even history, im not seeing any difference in spacing there enabled/disabled

**Comment by black7375** [comment]
By default, you should apply the above patch because it has the min-height property.

**Comment by black7375** [comment]
Test with a new version please.
