### ISSUE TITLE
UI Icons Blurry, Just Like Chromium

### ISSUE THREAD

**Issue by bytos** [black7375/Firefox-UI-Fix#392]
This looks like a huge oversight, the Bookmarks Toolbar and Tab icons (open & closed folders, bookmarks, sand clock) look like Chromium UI icons, very blurry.

What happened to the Photon folder icons? No one thought of using something better than this?

Is like most elements were changed, except for these icons. Hard to remember if these are FF v91+ icons that were not replaced.

Firefox v78 UI icons don't look like these.

The only reason for not moving to Chromium is the lack of UI icon scaling.

![a](https://user-images.githubusercontent.com/16452541/167878806-e426905b-36f8-4ee1-8d99-82ca8d8714a5.png)

**Comment by black7375** [comment]
I know, but it's not easy to fix. #213
I'll handle it all at once in the above issue.

--

Unfortunately, I'm not a designer but a developer.  I can't make icons. :cry: 
There is a limit to the existing icon adjustment if you need to fix the thickness, not just the size adjustment.

So I need the help of the designer.

I think it is an important issue, so I will pinned the above issue.

**Comment by bytos** [comment]
Thanks for the response, I understand what you are saying.

Can't believe that in the 21st century we can't have a decent browser UI.

Firefox ESR v78 was decent and Mozilla just decided to crap on it (ESR v91+).

I've seen companies being destroyed from the inside, it looks just like Mozilla's doing.
