### ISSUE TITLE
weird line separators between tabs

### ISSUE THREAD

**Issue by catalin560** [black7375/Firefox-UI-Fix#393]
![Capture](https://user-images.githubusercontent.com/22744333/168005739-edfe4779-689d-4ae0-be97-f86d2fd3f25d.JPG)

I think it used to be transparent, but as it is now it looks out of place, it seems to alternate between white/black depending on the FF theme

**Comment by black7375** [comment]
Can you tell me the information about OS, Firefox Version, and Theme(URL if custom theme)?

**Comment by catalin560** [comment]
Windows 10, FF 100.0, any of the default themes: Dark, Light, System theme, tried with latest release 5.1.0 but its like this since 5.0.0

**Comment by black7375** [comment]
Reproduction is quite difficult.
On my windows VM, it looks like this:

![Win10-2022-05-13-16-17-16(2)](https://user-images.githubusercontent.com/25581533/168231913-d7ba16df-6888-4e1c-98ef-858a275b1d40.png)

**Comment by black7375** [comment]
Ok, I'am reproduce this.
![Win10-2022-05-13-16-33-57](https://user-images.githubusercontent.com/25581533/168234474-c71dc2e3-a9e4-41ce-b729-406371fa6d8c.png)

The following option must be conflicted and disabled.
- `userChrome.tab.dynamic_separtor` is `false`

**Comment by catalin560** [comment]
thanks! that fixed it

**Comment by Poopooracoocoo** [comment]
I can't seem to set `userChrome.tab.dynamic_separtor` to `false` in about:config. It just goes back to `true` when I restart Firefox. Please help
