### ISSUE TITLE
Tab highlights turned weird; lepton and lepton-photon seem to be identical; tab overflow issue

### ISSUE THREAD

**Issue by TheHarmonicRealm** [black7375/Firefox-UI-Fix#395]
Hi. I was using the version of lepton from January 6 2022 until today. It had the rounded tabs etc. and Photon Lepton looked like this (quite different):

![image](https://user-images.githubusercontent.com/44441682/168198384-4060560d-93b7-4a9e-b000-6db5402fe4a7.png)

I just updated to Lepton now and it looks quite off. First off unless I'm mistaken with what I'm doing both Lepton (1) and Lepton-Photon (2) look the same:
![image](https://user-images.githubusercontent.com/44441682/168198975-cb80fcac-d964-4df8-9d29-23ec0233455b.png)
![image](https://user-images.githubusercontent.com/44441682/168199077-6df06a5a-8578-4c69-a05f-bf7dae94d95f.png)

and there's those really jarring tab highlights (which when the browser starts up are not there -- as it loads it starts out with the normal simple blue on the top of the tab) and separators (https://github.com/black7375/Firefox-UI-Fix/issues/393 has this). Is this intended? If so how can I revert it? Also something seems to be up with the two versions' tab bars looking identical now.

The problem which most immediately prompted me to update was that in lepton (but not the photon style) as of i think just the other day -- firefox 100 -- when there's not a large number of tabs open the left and right get the > and < symbols which do nothing except slightly shift the tabs, and then go away if you switch any tabs or anything. 
![image](https://user-images.githubusercontent.com/44441682/168199998-00f80a86-04bc-4a84-8546-4c59d3a2cf39.png)

Also the new tab plus is vertically quite stretched.
![image](https://user-images.githubusercontent.com/44441682/168200115-49bcfd87-d998-4422-b026-522b8fadd5fa.png)

I'm on Windows 10 Version 10.0.19043 Build 19043.

My display is 1920x1080p. I downloaded 5.1.0 today. Disabling Color to go back to default themes does not change it and my chrome folder is just the unmodified Lepton stuff.

Thanks!

**Comment by black7375** [comment]
IMO, This seems to be a configuration conflict issue.
It should be explicitly disabled.
https://github.com/black7375/Firefox-UI-Fix/wiki/Options#using-userjs

Try this config
```javascript
user_pref("userChrome.tab.connect_to_window",          true); // Original, Photon
user_pref("userChrome.tab.color_like_toolbar",         true); // Original, Photon

user_pref("userChrome.tab.lepton_like_padding",       false); // Original
user_pref("userChrome.tab.photon_like_padding",        true); // Photon

user_pref("userChrome.tab.dynamic_separtor",          false); // Original, Proton
user_pref("userChrome.tab.static_separator",           true); // Photon
// user_pref("userChrome.tab.static_separator.selected_accent", true); // Just option

user_pref("userChrome.tab.newtab_button_like_tab",    false); // Original
user_pref("userChrome.tab.newtab_button_smaller",      true); // Photon
// user_pref("userChrome.tab.newtab_button_proton",    true); // Proton

user_pref("userChrome.icon.panel_full",                true); // Original, Proton
// user_pref("userChrome.icon.panel_photon",           true); // Photon
// user_pref("userChrome.icon.panel_sparse",           true); // Just option

// Original Only
user_pref("userChrome.tab.box_shadow",                false);
user_pref("userChrome.tab.bottom_rounded_corner",     false);

// Photon Only
user_pref("userChrome.tab.photon_like_contextline",    true);
user_pref("userChrome.rounding.square_tab",            true);
```
