### ISSUE TITLE
"Clear downloads" button in firefox download manager not visible

### ISSUE THREAD

**Issue by MrAnon-dev** [black7375/Firefox-UI-Fix#396]
**Describe the bug**
"Clear downloads" button in firefox download manager is not styled properly.

**Expected behavior**
Icon should be visible when there is any download.  It´s there, when I hover over it, it shows up

**Screenshots**

![button_fail](https://user-images.githubusercontent.com/65110156/168417507-6453c8cd-8693-4677-8c8c-970b0f105f62.png)
![button_ok](https://user-images.githubusercontent.com/65110156/168417622-1a30a1ef-7964-4461-9108-cce8a8868db9.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): Ubuntu 20.04 LTS Yaru theme 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**`user.js` setup**

```javascript
// Your setting
```

**Additional context**

Firefox v100.0
Lepton v5.1.0

**Comment by black7375** [comment]
I don't have a problem in my environment.
I'll look into it.
![image](https://user-images.githubusercontent.com/25581533/168676147-920c70c5-e4be-42b8-abd1-432b82cab6cb.png)

**Comment by black7375** [comment]
There is no response for a long time, so close.
