### ISSUE TITLE
Tabs flicker when text is overflowing

### ISSUE THREAD

**Issue by catalin560** [black7375/Firefox-UI-Fix#397]
For some reason this happens when you move the mouse cursor around...

windows 10, FF100

![2022-05-14 20-16-31](https://user-images.githubusercontent.com/22744333/168443325-49659126-2275-42d7-afaa-3f6af0e595e4.gif)

I apologize for the bad crop 😃

**Comment by black7375** [comment]
Please specify your customization.

**Comment by catalin560** [comment]
[user.zip](https://github.com/black7375/Firefox-UI-Fix/files/8705610/user.zip)

I think its just the `"userChrome.tab.dynamic_separtor", false`

**Comment by yokoffing** [comment]
This happens to me as well.

**Comment by black7375** [comment]
Now that I checked, screenshot used option [`userChrome.centered.tab.label`](https://github.com/black7375/Firefox-UI-Fix/wiki/Options#tab-1).
There is a bug patch included in `6.0.0`.  https://github.com/black7375/Firefox-UI-Fix/commit/8ffcd5469786ab1e6806e190a9b1a732a8aba0fc

Try to use 6.0.0 above.
I will open it again when a reproducible situation occurs.

**Comment by yokoffing** [comment]
> Now that I checked, screenshot used option [`userChrome.centered.tab.label`](https://github.com/black7375/Firefox-UI-Fix/wiki/Options#tab-1).

It was happening me again today when using `userChrome.centered.tab` (not `label`) in `6.0.0`.
