### ISSUE TITLE
Photon like components

### ISSUE THREAD

**Issue by schelef** [black7375/Firefox-UI-Fix#399]
**Is your feature request related to a problem?**
lepton photon-style missing ui elements 

**The solution I'd like**
add separator between hamburger icon & profiles icon  add circle nav button 

**Screenshots or video**
![Screenshot_2](https://user-images.githubusercontent.com/105252992/170163679-8e9ee2e1-8d57-481d-92c5-9b37aef82d69.png)
![Screenshot_1](https://user-images.githubusercontent.com/105252992/170163715-1c940ec4-12b5-4c00-af84-ad79ae74dadf.png)
![Screenshot_3](https://user-images.githubusercontent.com/105252992/170163728-f718efed-4102-40ed-b07f-a10be16c7ec2.png)

**Comment by black7375** [comment]
It is not a high priority, but I think it can be implemented later.

**Comment by black7375** [comment]
Try to use [`v7.0.0`](https://github.com/black7375/Firefox-UI-Fix/releases/tag/v7.0.0).

**Comment by schelef** [comment]
> Try to use [`v7.0.0`](https://github.com/black7375/Firefox-UI-Fix/releases/tag/v7.0.0).

which settings address the changes i proposed

**Comment by black7375** [comment]
Set the following options to `true`
- `userChrome.decoration.panel_button_separator`
- `userChrome.decoration.panel_arrow`
- `userChrome.combined.nav_button`
- `userChrome.combined.sub_button.as_normal`
