### ISSUE TITLE
Tab box-shadow

### ISSUE THREAD

**Issue by surapunoyousei** [black7375/Firefox-UI-Fix#400]
**Describe the bug**

Firefox box-shadow can get in the way

**Expected behavior**

This is more of a question than a bug report. When some Firefox themes are applied as shown in the following picture, the effect of coloring around the tabs in Proton UI is originally applied in Lepton, but the coloring surrounds the tabs.

If you remove the box-shadow using the browser toolbox, you will see the following. I know it depends on your policy, but is this ever going to be the default?

<before>

![image](https://user-images.githubusercontent.com/73892113/170823753-ec2a31e6-2e2c-480e-99c9-0a634e53fd90.png)

<after>

![image](https://user-images.githubusercontent.com/73892113/170823838-35103d11-0ca6-4fc7-a8b0-799664716f48.png)

**Environment:**

 - Distribution
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [?] Linux
   - [x] Windows
   - [?] Mac
   - [?] Other: 
 - Theme:
   - [?] Light
   - [x] Dark
   - [?] Alpenglow (System: Light)
   - [x] Alpenglow (System: Dark)
   - [] System Default

**Comment by surapunoyousei** [comment]
私は以下の CSS でこの box-shadow をきれいに消すことができました。

```
:root:not([lwtheme-mozlightdark], [style*="--lwt-accent-color: rgb(28, 27, 34); --lwt-text-color: rgba(251, 251, 254);"]) #TabsToolbar[brighttext] #tabbrowser-tabs:not([noshadowfortests]) .tabbrowser-tab:is([visuallyselected="true"], [multiselected]) > .tab-stack > .tab-background:-moz-lwtheme {
  box-shadow:none !important;
}
```

**Comment by black7375** [comment]
It's a `userChrome.tab.box_shadow` option.
https://github.com/black7375/Firefox-UI-Fix/blob/c7fdfafeeda2b0d7dfd27fe3e29be45344a468f9/user.js#L50

For compatibility of themes such as opera GX emulation, I will keep them as default value.
https://addons.mozilla.org/en-US/firefox/addon/beautiful-opera-gx-fucsia/
![image](https://user-images.githubusercontent.com/25581533/170828030-7019fcd7-d542-408c-a7d0-9da0a6f43d43.png)

**Comment by surapunoyousei** [comment]
Thanks

**Comment by black7375** [comment]
\+
For themes that do not have much color contrast with the tab background, it can also be used to improve accessibility. (Ex. Built-In dark theme)

**Comment by surapunoyousei** [comment]
Thank you for further information.

I would like to incorporate it and use it, so I asked the questions I was wondering about. I apologize for not reading it properly.

**Comment by black7375** [comment]
It's probably because the documentation didn't go well.
I know it's important, but it's not easy to take time..
