### ISSUE TITLE
Updated Firefox to v101 , now seeing blue bar above current tab

### ISSUE THREAD

**Issue by deusexcalamus** [black7375/Firefox-UI-Fix#405]
as the subject says, I'm seeing a blue bar above the currently active tab, see attached screenshot, I expect something changed and this CSS needs to be updated.
Platform is Windows 10
![image](https://user-images.githubusercontent.com/8674645/171846806-a8d411aa-35a7-4aaf-9184-6ef5e8496628.png)

**Comment by FrankJunk** [comment]
Having same issue. Thought my mouse was bugging out and I was misclicking tabs. Dead space above the tabs. Only happens when set to "Compact (Not Supported" density in customise. Problem doesn't persist in Normal or Touch.

**Comment by black7375** [comment]
It seems to be duplicated with #384

**Comment by deusexcalamus** [comment]
This still isn't fixed with latest photon release.
