### ISSUE TITLE
Menu icon overlap with text

### ISSUE THREAD

**Issue by superfreeman1989** [black7375/Firefox-UI-Fix#406]
**Describe the bug**

Menu icon overlap with text
**Expected behavior**

Not overlapping

**Screenshots**

![2022-06-06 06_48_46-New Issue · black7375_Firefox-UI-Fix — Mozilla Firefox](https://user-images.githubusercontent.com/15226945/172147120-befafed2-8657-42e0-a92a-53de40991a81.png)
![2022-06-06 06_48_33-New Issue · black7375_Firefox-UI-Fix — Mozilla Firefox](https://user-images.githubusercontent.com/15226945/172147121-df5f1eba-74be-4d89-ab6a-456f9b0cab82.png)

**Environment:**

 - Distribution
   - [x ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 101.0
 - OS:
   - [ ] Linux
   - [ x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**`user.js` setup**

```javascript
// Your setting
// ** Theme Related Options ****************************************************
// userchrome.css usercontent.css activate
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);

// Proton Enabled #127
user_pref("browser.proton.enabled", true);

// Proton Tooltip
user_pref("browser.proton.places-tooltip.enabled", true);

// Fill SVG Color
user_pref("svg.context-properties.content.enabled", true);

// CSS Color Mix - 88 Above
user_pref("layout.css.color-mix.enabled", true);

// CSS Blur Filter - 88 Above
user_pref("layout.css.backdrop-filter.enabled", true);

// Restore Compact Mode - 89 Above
user_pref("browser.compactmode.show", true);

// about:home Search Bar - 89 Above
user_pref("browser.newtabpage.activity-stream.improvesearch.handoffToAwesomebar", false);

// Browser Theme Based Scheme - Will be activate 95 Above
// user_pref("layout.css.prefers-color-scheme.content-override", 3);

// ** Useful Options ***********************************************************
// Integrated calculator at urlbar
user_pref("browser.urlbar.suggest.calculator", true);

// Integrated unit convertor at urlbar
// user_pref("browser.urlbar.unitConversion.enabled", true);

// Draw in Titlebar
// user_pref("browser.tabs.drawInTitlebar", true);
// user_pref("browser.tabs.inTitlebar",        1); // Nightly, 96 Above

```

**Additional context**

**Comment by black7375** [comment]
There is no problem in the latest commits.
Check again if the setting is correct.

**Comment by superfreeman1989** [comment]
Thank you. Fixed.
