### ISSUE TITLE
Wrong padding in Bookmarkpopup

### ISSUE THREAD

**Issue by BPower0036** [black7375/Firefox-UI-Fix#408]
**Describe the bug**

The following code is causing the problem:
```
  @media (-moz-os-version: windows-win10), (-moz-platform: windows-win10) {
    /* Bookmark Popup - None icon menu */
    menupopup:is(#BMB_bookmarksPopup) menuitem:not(.menuitem-iconic, [disabled="true"]),
    menupopup:is(#BMB_bookmarksPopup) menu:not(.menu-iconic),
    #PersonalToolbar menupopup[placespopup="true"] menuitem:not(.menuitem-iconic, [disabled="true"]),
    #PersonalToolbar menupopup[placespopup="true"] menu:not(.menu-iconic) {
      margin-inline: var(--arrowpanel-menuitem-padding-inline) !important;
      padding-inline-start: calc(var(--arrowpanel-menuicon-padding) + var(--context-menu-text-padding)) !important;
      background-position: left calc(var(--arrowpanel-menuicon-padding)) center !important;
    }
  }
```
[css/leptonChrome.css#L6254-#L6265](https://github.com/black7375/Firefox-UI-Fix/blob/master/css/leptonChrome.css#L6254-#L6265)

**Expected behavior**

No space.
```
  @media (-moz-os-version: windows-win10), (-moz-platform: windows-win10) {
    /* Bookmark Popup - None icon menu */
    menupopup:is(#BMB_bookmarksPopup) menuitem:not(.menuitem-iconic, [disabled="true"], #BMB_viewBookmarksToolbar),
    menupopup:is(#BMB_bookmarksPopup) menu:not(.menu-iconic),
    #PersonalToolbar menupopup[placespopup="true"] menuitem:not(.menuitem-iconic, [disabled="true"]),
    #PersonalToolbar menupopup[placespopup="true"] menu:not(.menu-iconic) {
      margin-inline: var(--arrowpanel-menuitem-padding-inline) !important;
      padding-inline-start: calc(var(--arrowpanel-menuicon-padding) + var(--context-menu-text-padding)) !important;
      background-position: left calc(var(--arrowpanel-menuicon-padding)) center !important;
    }
  }
```

**Screenshots**

![afbeelding](https://user-images.githubusercontent.com/80090789/172685399-cfd137af-fdb7-4f21-9f90-9f1cf9f88120.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**`user.js` setup**

```javascript
// Your setting
```

**Additional context**

**Comment by black7375** [comment]
I don't think it's a padded bug because the bookmark items and layouts should be aligned.
Instead, I made `Show` and `Hide` icoons enabled.
![image](https://user-images.githubusercontent.com/25581533/172744089-33d23828-0335-47b4-9376-07ca44aaae23.png)

Thanks to reports,
