### ISSUE TITLE
Still seeing blue bar above active tab with compact mode enabled after update to FFv101 & latest Photon

### ISSUE THREAD

**Issue by deusexcalamus** [black7375/Firefox-UI-Fix#409]
As in issue #405, I'm still seeing the blue bar above current tab with compact mode enabled.
![image](https://user-images.githubusercontent.com/8674645/172753718-75b5bcf0-ac09-4ed6-af33-01c345fe0b84.png)

**Comment by black7375** [comment]
I forgot to do the branch sync.
I sync the branch, uploaded the file again, now.

**Comment by deusexcalamus** [comment]
Confirmed fixed.
