### ISSUE TITLE
Missing icons in the menu

### ISSUE THREAD

**Issue by helpthemfix** [black7375/Firefox-UI-Fix#412]
**Describe the bug**
The share and select multiple tabs icons are not there.

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 101.0-2
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark

**Screenshots**

![Screenshot (1)](https://user-images.githubusercontent.com/92321993/173168660-d6854987-4ad8-4882-be9b-4c66e46823d0.png)

![Capture](https://user-images.githubusercontent.com/92321993/174603399-3fb2c86d-ba30-4e4e-80e5-6d348a689d93.PNG)

**Comment by udontkn0wme** [comment]
> I couldn't find the appropriate icon for Past and Go and Close Multiple Tabs. 😢

Share could be the generic share icon https://www.iconfinder.com/icons/352893/share_icon

Close multiple tabs an X in a circle 

Redo a mirrored Undo

Paste and go like a Paste with an arrow?

**Comment by black7375** [comment]
[share](https://github.com/black7375/Firefox-UI-Fix/blob/master/icons/share.svg) and [redo](https://github.com/black7375/Firefox-UI-Fix/blob/master/icons/redo.svg) already exist.

I'm not a designer, but only a very minimal icon custom.
(It is necessary to contribute to designers who can make custom icons.)


Target of icons
- Close Multiple Tabs
- Paste & Go
- Paste & Search

**Comment by helpthemfix** [comment]
Any update on these?

**Comment by black7375** [comment]
Close Multiple Tabs is going to use [Filter dismiss](https://github.com/microsoft/fluentui-system-icons/blob/main/assets/Filter%20Dismiss/SVG/ic_fluent_filter_dismiss_24_regular.svg) or [Table dismiss](https://github.com/microsoft/fluentui-system-icons/blob/main/assets/Table%20Dismiss/SVG/ic_fluent_table_dismiss_24_regular.svg).
However, `Paste & Go` and `Paste & Search` need the contribution.

**Comment by black7375** [comment]
You can now use full icon with `userChrome.icon.menu.full` to `true`.
I've learned inkscape and made icons.

![image](https://user-images.githubusercontent.com/25581533/195980572-285e1be9-5852-414c-aaf8-3ad397d5e61a.png)
![image](https://user-images.githubusercontent.com/25581533/195980653-8b2d393d-321b-486b-99d7-494f5322a1e8.png)
![image](https://user-images.githubusercontent.com/25581533/195980627-9e81f6cd-534c-4722-8276-bd48b7b59580.png)

**Comment by udontkn0wme** [comment]
> You can now use full icon with `userChrome.icon.menu.full` to `true`. I've learned inkscape and made icons.

And where do I find that?

**Comment by black7375** [comment]
1. [Install](https://github.com/black7375/Firefox-UI-Fix/wiki/Installation-Guide) `From Latest Code` or `From Git (Click)`.
2. [Set](https://github.com/black7375/Firefox-UI-Fix/wiki/Tutorial) `userChrome.icon.menu.full` to `true` && restart

**Comment by udontkn0wme** [comment]
> 1. [Install](https://github.com/black7375/Firefox-UI-Fix/wiki/Installation-Guide) `From Latest Code` or `From Git (Click)`.
> 
>     2. [Set](https://github.com/black7375/Firefox-UI-Fix/wiki/Tutorial) `userChrome.icon.menu.full` to `true` && restart

I have done that but the icons are still issing.

**Comment by black7375** [comment]
@udontkn0wme 
You may have used the release file.
Required the latest commit, as reflected in [v6.3.0](https://github.com/black7375/Firefox-UI-Fix/releases/tag/v6.3.0).
