### ISSUE TITLE
Windows 7/8.1 - Title bar misalignments

### ISSUE THREAD

**Issue by Kiki79250CoC** [black7375/Firefox-UI-Fix#413]
**Describe the bug**
In Windows 7 and 8.1, the top section have some misalignments (compared to Lepton 5.1).
When the Window is maximized, the top part is partially off-screen.

(I also noticed that the tabs have a space between the tabs themselves and the top of the window on Windows 7 compared to Lepton 4.6 and Firefox 88)

---

**Expected behavior**
Obviously, the one that was present in Lepton 5.1, without this weird off-screen problems.

**Screenshots**

_Windows 7, **Lepton 5.2.0**:_

![image](https://user-images.githubusercontent.com/54137141/173225155-c19333c1-d0d6-4f78-a695-f44b829a718c.png)
![image](https://user-images.githubusercontent.com/54137141/173226424-8060a87a-9a68-4c8c-87d2-d3d8b742627a.png)

<details>
    <summary>Comparaison images<a href="http://...."></a></summary>

> _Windows 7, **Lepton 5.1.0** (for comparaison):_
> 
> ![image](https://user-images.githubusercontent.com/54137141/173225970-b2f7e13b-5a49-410c-ae24-42b64d980027.png)
> ![image](https://user-images.githubusercontent.com/54137141/173226195-ad9ee263-7aae-456e-b763-a74bd1df7ee0.png)
> 
> _Windows 7, **Lepton 4.6.0** (for comparaison):_
> 
> ![image](https://user-images.githubusercontent.com/54137141/173226490-6a397b39-9a82-4047-8ed9-e631fddd77d6.png)
> 
> _Windows 7, **Firefox 88.0.1** (for comparaison):_
> 
> ![image](https://user-images.githubusercontent.com/54137141/173227167-85449b7d-01b5-4989-ae44-e875678d91d0.png)
> ![image](https://user-images.githubusercontent.com/54137141/173227127-b8119e30-58f8-4a41-b401-ac79af781f39.png)

</details>

---

_Windows "7.1" (Which is 8.1 **but with Aero**), **Lepton 5.2.0**:_

![image](https://user-images.githubusercontent.com/54137141/173225167-ee9532cf-9c1a-4931-aa5b-6e3227820e4a.png)
![image](https://user-images.githubusercontent.com/54137141/173226754-b9c2f5b7-9b0e-4bee-bdb2-624e0d37482b.png)

<details>
    <summary>Comparaison images<a href="http://...."></a></summary>

> _Windows "7.1", **Lepton 5.1.0** (for comparaison):_
> 
> ![image](https://user-images.githubusercontent.com/54137141/173225895-b0f0dd77-8975-4ef1-9ec1-6fe82c229949.png)
> ![image](https://user-images.githubusercontent.com/54137141/173226705-445c5486-1269-4a8a-b23d-c92ebf9d6fe3.png)
> 
> _Windows "7.1", **Firefox 88.0.1** (for comparaison):_
> 
> ![image](https://user-images.githubusercontent.com/54137141/173227557-5390e6a3-4bd1-4a60-a6ae-a9a580fbf53f.png)
> ![image](https://user-images.githubusercontent.com/54137141/173227542-1330f8ad-6ed7-45db-88fd-f4053bafbb04.png)

</details>

**Environment:

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [X] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 101.0.1
 - OS:
   - [ ] Linux
   - [X] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [X] Light
   - [X] Dark
   - [X] Alpenglow (System: Light)
   - [X] System Default
   - [X] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Note:** Haven't tested on the two variants I don't use, but those are probably impacted too if the same modifications have been applied.

**`user.js` setup**
> Using user.js provided with Lepton, no modifications are made on this file.

**Additional context**

**Comment by thunderstone135** [comment]
You can find the temporary workaround on e37743cd9ac5b77693a7f172cf390f124c3b4c4f.

**Comment by black7375** [comment]
It seems to happen only in Windows.
Please check the patch.

**Comment by thunderstone135** [comment]
Works great 👍
