### ISSUE TITLE
Missing icons in URL bar

### ISSUE THREAD

**Issue by helpthemfix** [black7375/Firefox-UI-Fix#418]
**Describe the bug**
The redo and paste and go icons are missing.

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 101.0-2
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark

**Screenshots**

![Capture](https://user-images.githubusercontent.com/92321993/174603399-3fb2c86d-ba30-4e4e-80e5-6d348a689d93.PNG)

**Comment by black7375** [comment]
I couldn't find the appropriate icon for `Past and Go` and `Close Multiple Tabs`. :cry:

**Comment by helpthemfix** [comment]
> I couldn't find the appropriate icon for `Past and Go` and `Close Multiple Tabs`. 😢

ooh that's a bummer 😞
