### ISSUE TITLE
selected pined tab has underline when enough tabs are opened to bring up the tab scroll arrows

### ISSUE THREAD

**Issue by gotyaoi** [black7375/Firefox-UI-Fix#420]
**Describe the bug**
In photon style, when a tab is selected, the line at the bottom of the tab is removed to visually merge it with the navigation bar below it. However, this does not occur for pinned tabs in the case that enough regular tabs have been opened to cause the scroll arrows to appear on either side of the tab container. The behavior of regular tabs is still correct in this case, and pinned tabs are correctly handled when the tab scroll arrows are not present.

**Expected behavior**
The line below a pinned tab should always be removed when it is selected.

**Screenshots**
![pinned few](https://user-images.githubusercontent.com/2141918/175404226-c663611a-d34f-41d9-85e1-9159e7143530.PNG)

![regular few](https://user-images.githubusercontent.com/2141918/175404336-f28c0ce7-e317-40ac-a987-e668d2c1bf40.PNG)

![pinned many](https://user-images.githubusercontent.com/2141918/175404369-10c4f9cb-f4c4-4b3c-983b-e4a1bbcf7018.PNG)

![regular many](https://user-images.githubusercontent.com/2141918/175404431-c76dd057-b49d-44a2-8c52-d13b03afbf17.PNG)

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 101.0.1
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [x] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**`user.js` setup**

```javascript
// Your setting
```

**Additional context**

**Comment by gotyaoi** [comment]
Did a little bit of looking at this, it appears to be partially related to https://github.com/black7375/Firefox-UI-Fix/blob/d658028b7bca02a36c6c41fb609120198bc59270/css/leptonChrome.css#L3988-L3990. Disabling that rule removes the line by restoring the z-index: 2 from chrome://browser/skin/tabs.css:119, though there's a leftover box shadow from the tab-background class.

**Comment by black7375** [comment]
Hello, I am investigating this issue.
Could you tell me the link to your theme?

**Comment by gotyaoi** [comment]
https://addons.mozilla.org/en-US/firefox/addon/yakuza-paint/

**Comment by black7375** [comment]
I think it's solved.
Let me know if there's still a problem.

**Comment by gotyaoi** [comment]
Works perfectly for me now, thank you.
