### ISSUE TITLE
Right-click menu got another outline box added with ver 102.0

### ISSUE THREAD

**Issue by SnowManWithCarrot** [black7375/Firefox-UI-Fix#421]
**Describe the bug**

Ver. 102.0 (64-bit) added an additional box to right-click menu.

**Expected behavior**

The additional menu outliner box wasn't present before the 102.0 update.

**Screenshots**

![2](https://user-images.githubusercontent.com/86745065/176398644-4d1e3b7a-ae35-4de7-a87b-c1c7e8187141.jpg)

**Environment:**

 - Distribution
   - [ x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x ] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [x] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**`user.js` setup**

```javascript
// Your setting
```

**Additional context**

**Comment by rockenren** [comment]
Same in Photon style on Windows.

**Comment by rockenren** [comment]
Can confirm, 5.2.1 fixed this issue.
