### ISSUE TITLE
Bookmarks top side goes out of the browser frame with too many bookmarks added ver. 102.0

### ISSUE THREAD

**Issue by SnowManWithCarrot** [black7375/Firefox-UI-Fix#422]
**Describe the bug**

Bookmarks top side goes out of the browser frame with too many bookmarks added.
The bottom part of the bookmarks menu is fine and have an arrow showing for scroll-down but the top side of the bookmarks menu is just cut outside of the browser frame.

**Expected behavior**

**Screenshots**

top (bugged part)
![top](https://user-images.githubusercontent.com/86745065/176397279-ee5bb466-9c01-42c7-9a3c-bab4c7279bfc.jpg)
bottom (non-bugged)
![bottom](https://user-images.githubusercontent.com/86745065/176397272-e62781fe-9bb9-47cf-8ea4-d5ea653be41a.jpg)
How it Looks and should look when bookmarks are not too many:
![how it should look](https://user-images.githubusercontent.com/86745065/176397948-1004e488-0d47-4657-9fad-9082a00a7cab.jpg)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [x] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**`user.js` setup**

```javascript
// Your setting
```

**Additional context**

**Comment by black7375** [comment]
![image](https://user-images.githubusercontent.com/25581533/181665592-1cfcdef6-561f-4aaa-a57c-0f4d8a1a1878.png)

In my browser(103.0b9), the shape of the arrow is displayed normally.
I think it is difficult to adjust the pop-up menu location according to the number of internal items with CSS. (Beyond the possible scope of the project)

**Comment by SnowManWithCarrot** [comment]
I didn't mean that I don't get an arrow when i have many bookmarks and I scroll down.

I meant that the top side of overcrowded bookmark folder is missing or going out of the Firefox Frame. (check this new screen it also explains the rest of this post below)

![BM](https://user-images.githubusercontent.com/86745065/182019130-19ff2049-7497-45ae-bb06-20c581b8b8a8.png)
On side note is there any way to limit the "width" of the bookmarks ? - you can see on your screenshot how it is dynamically determined from a long bookmark you have (it still have a limit but it is too long for me) and I would really like to have a way to limit that to half of what is seen on your screenshot.

**Comment by SnowManWithCarrot** [comment]
even 104.0 didn't fixed the issue so I assume it is how firefox will be from now on so closing.

**Comment by SnowManWithCarrot** [comment]
This was fixed in v105.0 - adding comment for future references if same issues re-occurs.
