### ISSUE TITLE
Zoom icon is not in line

### ISSUE THREAD

**Issue by udontkn0wme** [black7375/Firefox-UI-Fix#424]
**Describe the bug**
Zoom icon in the side panel is inot in line with other icons

**Expected behavior**
Make it in line with other icons

**Screenshots**
![image](https://user-images.githubusercontent.com/108428099/176515415-af61e4a4-cbbe-4084-ac65-156821f8b205.png)

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**`user.js` setup**

```javascript
// Your setting
```

**Additional context**

**Comment by Vulatera** [comment]
No issue on my side
![dfsdf](https://user-images.githubusercontent.com/83128759/176872007-6f444ec3-259b-4fa6-93f2-782ad077c729.jpg)

Firefox 102.0
Lepton's proton style v5.2.1
Windows 10
Dark Theme

**Comment by krystian3w** [comment]
Maybe GNU/Linux and macOS specific.

**Comment by udontkn0wme** [comment]
> Maybe GNU/Linux and macOS specific.

I'm using Windows 10

**Comment by krystian3w** [comment]
So still needed is other fixes than bfa5a3d?

**Comment by udontkn0wme** [comment]
I tried that but it didn't do anything.

**Comment by udontkn0wme** [comment]
It works for Librewolf but I dont want to use that browser..

**Comment by black7375** [comment]
There was a symptom that the zoom icon did not appear because the selector was changed in Nightly.
But in other environments, it was not reproduced.

Did you use custom CSS?

**Comment by udontkn0wme** [comment]
Nope, I just downloaded, unzipped and copied into profile folder. Didn't change anything about it.

**Comment by black7375** [comment]
![image](https://user-images.githubusercontent.com/25581533/179565162-7baa51e5-353f-45e0-ad7b-a040ff3ad571.png)

I succeeded in reproducing. It appears when multiple settings are set at the same time.

- `userChrome.icon.panel_full`
- `userChrome.icon.panel_photon`

Make `false` the `userChrome.icon.panel_photon` setting.
