### ISSUE TITLE
Upgraded to 5.2.1 on Firefox 102, blue bar above active tab has returned.

### ISSUE THREAD

**Issue by deusexcalamus** [black7375/Firefox-UI-Fix#425]
Similar to my previous issues (issue #405 issue #409) there's now a blue bar above the active tab.
![image](https://user-images.githubusercontent.com/8674645/176554311-ad290082-7c94-4433-972c-f2c5c63eb0b0.png)

**Comment by black7375** [comment]
Is `userChrome.tab.photon_like_contextline` value `true` in the `about:config`?

**Comment by deusexcalamus** [comment]
Looks that way. [image](https://user-images.githubusercontent.com/8674645/177048398-99488d19-51c5-4f2b-b995-a2c383209b2e.png)

**Comment by black7375** [comment]
Yes. That setting is the cause.
Make it `false` in `user.js` & Restart.

**Comment by deusexcalamus** [comment]
That's got it fixed.
