### ISSUE TITLE
Firefox 102 + Photon 5.2.1 = Black borders on tabs sides

### ISSUE THREAD

**Issue by virtualdj** [black7375/Firefox-UI-Fix#429]
**Describe the bug**
After Firefox updated to 102 I had to upgrade the Photon style with the [new one](https://github.com/black7375/Firefox-UI-Fix/releases/download/v5.2.1/Lepton-Photon-Style.zip); however, a **black thick border** appears on the **left and right side** of each non-selected tab now. There's also an additional gray border on the left side of the + button that disappears when hovering on it.

**Expected behavior**
This issue is similar to the one that I'd written [here](https://github.com/black7375/Firefox-UI-Fix/issues/355#issuecomment-1093966249) (you can see from the screenshots there the difference), apart from the + border problem.

**Screenshots**
![Black borders on the tabs side](https://user-images.githubusercontent.com/3251704/176995399-f6751628-49da-4caf-bf8e-3145fd2b0dd5.png)

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 102.0
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [x] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**`user.js` setup**

```javascript
// No changes from the supplied file
```

**Additional context**

**Comment by black7375** [comment]
These symptoms are due to the conflict of setting.
To reduce the mistake of the user, we clearly distinguished `true`/`false`.

Try to using lastest `photon-style` setting.
https://github.com/black7375/Firefox-UI-Fix/blob/photon-style/user.js

**Comment by virtualdj** [comment]
> Try to using lastest `photon-style` setting.
> https://github.com/black7375/Firefox-UI-Fix/blob/photon-style/user.js

Yep, that fixed both the 2 issues, thanks! With the new `user.js`:

![New user.js](https://user-images.githubusercontent.com/3251704/177195299-bfb2fe1d-53b7-443a-a49e-f0294f294167.png)
