### ISSUE TITLE
I added this project to Producthunt.com

### ISSUE THREAD

**Issue by robertheadley** [black7375/Firefox-UI-Fix#43]
[Check it out](https://www.producthunt.com/posts/firefox-ui-fix-proton)

**Comment by black7375** [comment]
Wow, That's a good contribution.

**Comment by robertheadley** [comment]
Feel free to create an account and add yourself as the creator, update anything. I am very thankful for this project.

**Comment by black7375** [comment]
Thank you again, and I think it's been open for enough time, so I'll close it!!
