### ISSUE TITLE
The selection circle that appears on the multiple choice sections in the settings is misaligned

### ISSUE THREAD

**Issue by AntoLiguori** [black7375/Firefox-UI-Fix#431]
**Describe the bug**
The selection circle that appears on the multiple choice sections in the settings is misaligned towards the right.

**Expected behavior**
The outer circle should be equidistant from the inner circle.

**Screenshots**
![Screen - Copy](https://user-images.githubusercontent.com/80221798/177876043-c4358f8c-598a-4653-a532-6d4e12cfe82e.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 102.0.1
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [x] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [x] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Comment by black7375** [comment]
The outside circle is made using [outline](https://developer.mozilla.org/en-US/docs/Web/CSS/outline).
On my computer, it works well, and the detailed implementation must be modified in Mozilla.
I don't know why it's not aligned.
![image](https://user-images.githubusercontent.com/25581533/177910908-b5152ceb-733d-4e48-bd52-1183617c00bf.png)

**Comment by AntoLiguori** [comment]
Weird. I'll check it on my linux system as well. I think I'll open an issue on bugzilla too

**Comment by black7375** [comment]
It is a problem that cannot be handled in this project and is difficult to reproduce, so I will close it.
