### ISSUE TITLE
Need more icon

### ISSUE THREAD

**Issue by afi-dev** [black7375/Firefox-UI-Fix#432]
Some icons are missing 

Here are some missing icons:

![image](https://user-images.githubusercontent.com/44731817/178162916-18a404f5-4aad-4857-a044-bb1077413c3f.png)

It would be great if they could be added, best regards Afi

**Comment by black7375** [comment]
What do you mean?
There are icons on the red line.

**Comment by afi-dev** [comment]
I would like that you add in your fix the support of the icons present elsewhere than on menu, **indeed my request consists in facilitating the customization because too fastidious**, if I am not mistaken it is enough to include all the file css of `C:\Program Files\Mozilla Firefox\browser\omni.ja\chrome\browser\skin\` as well as the icons to allow **more personalization**

I hope you understand my request, here is the list of icons that would be interesting to add:

![add-circle-fill](https://user-images.githubusercontent.com/44731817/178175075-8a76f538-ac87-407f-9eca-a7abfd26615d.svg)
![back](https://user-images.githubusercontent.com/44731817/178175084-824f8086-05eb-4c3b-a9d4-5116c2fcfac1.svg)
![bookmark](https://user-images.githubusercontent.com/44731817/178175094-d84d22e0-70f7-4116-a6eb-8010d3803f3e.svg)
![bookmark-12](https://user-images.githubusercontent.com/44731817/178175105-68e8927d-8b5b-4712-b961-2ccb31b452ef.svg)
![bookmark-hollow](https://user-images.githubusercontent.com/44731817/178175113-ce1476b1-6915-447c-9a55-dbced19fd934.svg)
![bookmark-star-on-tray](https://user-images.githubusercontent.com/44731817/178175122-2225136e-53c9-42ab-a275-f6e09c3160aa.svg)
![bookmarks-toolbar](https://user-images.githubusercontent.com/44731817/178175144-00bd4655-6404-448d-99df-a6211c2d7bc5.svg)
![canvas](https://user-images.githubusercontent.com/44731817/178175155-44bd3cc3-a1f8-4377-9d6e-a7c3fd47d5aa.svg)
![canvas-blocked](https://user-images.githubusercontent.com/44731817/178175160-02afa0f9-776e-44ab-9c43-41cab5e7f4b4.svg)
![characterEncoding](https://user-images.githubusercontent.com/44731817/178175188-8bc3df9a-1209-4a9e-9b74-394c59ea2945.svg)
![chevron-animation](https://user-images.githubusercontent.com/44731817/178175207-78ae4aba-f2c1-4602-94eb-35b5c66176f9.svg)
![customize](https://user-images.githubusercontent.com/44731817/178175222-5a36cdd7-74d9-4206-84cc-06060c8117d3.svg)
![device-desktop](https://user-images.githubusercontent.com/44731817/178175226-aa7017e1-6424-45e7-a498-56f3fad8e90d.svg)
![device-phone](https://user-images.githubusercontent.com/44731817/178175236-fca9fb08-a21a-4618-bb29-890aca4aa23b.svg)
![device-tablet](https://user-images.githubusercontent.com/44731817/178175241-81be667b-0808-40a3-bcbe-43a2d34b83c9.svg)
![device-tv](https://user-images.githubusercontent.com/44731817/178175252-88afcfe6-9fd5-4706-9df5-1992f4029560.svg)
![device-vr](https://user-images.githubusercontent.com/44731817/178175272-3d676abb-c2b3-492e-86ac-865e62fd6d08.svg)
![drm-icon](https://user-images.githubusercontent.com/44731817/178175286-93502bcc-14d8-413e-82e7-b06466f1bf7b.svg)
![edit-cut](https://user-images.githubusercontent.com/44731817/178175296-15182421-5370-4f2d-9a13-830082a70efa.svg)
![edit-paste](https://user-images.githubusercontent.com/44731817/178175310-d441c823-c3e3-4b4f-a0d4-c6d8fdf065ea.svg)
![fingerprint](https://user-images.githubusercontent.com/44731817/178175344-cbeeddf2-dd0a-40ad-b22f-d57c641197f1.svg)
![forget](https://user-images.githubusercontent.com/44731817/178175375-66dbf76d-4105-4519-a84f-487e8e3b2fea.svg)
![forward](https://user-images.githubusercontent.com/44731817/178175386-ea8d03bb-fd97-4e7b-8588-eb170fd6ccbd.svg)
![fullscreen](https://user-images.githubusercontent.com/44731817/178175401-2e6e4857-9091-4d9a-b4fd-72433ce0f148.svg)
![history](https://user-images.githubusercontent.com/44731817/178175412-2c2b30a0-6568-46ba-aebb-3ab83a323246.svg)
![home](https://user-images.githubusercontent.com/44731817/178175421-ba0ec2b8-ca92-4133-805e-6af46343c1b3.svg)
![import](https://user-images.githubusercontent.com/44731817/178175429-6a9648d4-5465-43fc-b0a3-f1eed331a72c.svg)
![import-export](https://user-images.githubusercontent.com/44731817/178175440-c6f2847b-a1f2-472c-8505-2fc5bd0685d0.svg)
![indicator-accessibility](https://user-images.githubusercontent.com/44731817/178175451-41d452a2-fe81-410e-910b-440da5751f83.svg)
![ion](https://user-images.githubusercontent.com/44731817/178175456-5934e8cf-2dca-4852-a4aa-becafc0b389b.svg)
![library](https://user-images.githubusercontent.com/44731817/178175459-519d357f-6d13-425c-8a80-e41e3da9a0d9.svg)
![login](https://user-images.githubusercontent.com/44731817/178175469-5939505d-70cd-414e-8348-164210f736f9.svg)
![logo-android](https://user-images.githubusercontent.com/44731817/178175477-e155c7fd-8f58-4623-9da1-1d053dbb7d90.svg)
![logo-ios](https://user-images.githubusercontent.com/44731817/178175483-031d30d6-7dd6-4a5c-8d6e-b833a9f433e2.svg)
![mail](https://user-images.githubusercontent.com/44731817/178175486-7b5b88e0-633f-4520-b1b3-5929ce7afa7e.svg)
![menu](https://user-images.githubusercontent.com/44731817/178175492-0b937ed6-51dc-46a3-ac84-d5a3de87c2c6.svg)
![menu-badged](https://user-images.githubusercontent.com/44731817/178175496-77ab89e1-4cb8-4037-a1c8-87dffa14eb8f.svg)
![new-tab](https://user-images.githubusercontent.com/44731817/178175503-49fbee36-8cd5-47c8-abcf-da53b58ca786.svg)
![notification-fill-12](https://user-images.githubusercontent.com/44731817/178175505-677f6dac-bc43-4e3d-8c57-631d83769466.svg)
![open](https://user-images.githubusercontent.com/44731817/178175526-572534b4-395d-4b27-9baf-60dc057bd803.svg)
![permissions](https://user-images.githubusercontent.com/44731817/178175529-6cabb988-357e-444c-973e-4bb2a46e0cc1.svg)
![pin-12](https://user-images.githubusercontent.com/44731817/178175541-2168aa58-4445-4712-8351-227acf55bdf8.svg)
![privateBrowsing](https://user-images.githubusercontent.com/44731817/178175548-69a402d2-f25f-4c05-9e21-2cfd63785ad2.svg)
![reader-mode](https://user-images.githubusercontent.com/44731817/178175552-46c357b4-9a53-4062-833b-ec6cd6040dfd.svg)
![reload-to-stop](https://user-images.githubusercontent.com/44731817/178175558-783aa2d0-2f18-44df-a551-c3b9d9541d9d.svg)
![save](https://user-images.githubusercontent.com/44731817/178175563-1e6fb4a7-f271-4ca0-8cf8-530880904271.svg)
![screenshot](https://user-images.githubusercontent.com/44731817/178175567-34e19cbf-8428-4d7f-b1dc-900cbf15e6ef.svg)
![search-indicator-badge-add](https://user-images.githubusercontent.com/44731817/178175573-264ef189-916e-4b22-a33b-f31ba3ec13a9.svg)
![sidebars](https://user-images.githubusercontent.com/44731817/178175578-50327dfd-75da-48ae-8bae-d2c4d1c52e4a.svg)
![sidebars-right](https://user-images.githubusercontent.com/44731817/178175583-3013bba5-01db-453f-b4a0-16cb4b0a8f06.svg)
![sort](https://user-images.githubusercontent.com/44731817/178175588-c01d3dde-3266-4a9d-b073-6729e75c3ca2.svg)
![stop-to-reload](https://user-images.githubusercontent.com/44731817/178175598-da4a508c-e684-4061-8a96-87174c363753.svg)
![subtract-circle-fill](https://user-images.githubusercontent.com/44731817/178175601-89bdbaef-8646-4dab-8e71-d84de8052811.svg)
![success-animation](https://user-images.githubusercontent.com/44731817/178175612-ea302bdc-1a7d-4f32-af74-23b54375b757.svg)
![sync](https://user-images.githubusercontent.com/44731817/178175623-aac562ac-a2a0-4eb3-9fc0-f0b10585973f.svg)
![tab](https://user-images.githubusercontent.com/44731817/178175637-ce72721d-7df1-41cb-8cf0-aa05179790c2.svg)
![tab-crashed](https://user-images.githubusercontent.com/44731817/178175645-e00d0761-77bf-461f-ac05-8a84ac109a3e.svg)
![thumb-down](https://user-images.githubusercontent.com/44731817/178175659-8b6d373a-0113-4dad-ab97-44661876414f.svg)
![toolbar-drag-indicator](https://user-images.githubusercontent.com/44731817/178175668-8cd11802-9b49-4e90-ae41-70bed9306aca.svg)
![topsites](https://user-images.githubusercontent.com/44731817/178175684-baa30bb1-edfa-411b-89d2-6d4d2da608ab.svg)
![tracking-protection](https://user-images.githubusercontent.com/44731817/178175697-2d01b49a-33f4-4b85-8132-877314ba03bf.svg)
![tracking-protection-active](https://user-images.githubusercontent.com/44731817/178175708-3219bf74-37c9-462a-a78c-bc3ccc0325bf.svg)
![tracking-protection-active-brighttext](https://user-images.githubusercontent.com/44731817/178175714-48c01d74-30ac-4c6f-b932-3f23c3606c97.svg)
![tracking-protection-disabled](https://user-images.githubusercontent.com/44731817/178175717-db474e7e-8275-4f8d-934a-51c7eeba2f21.svg)
![trending](https://user-images.githubusercontent.com/44731817/178175725-4ba8dfc6-1f34-49d5-bad6-61f89616e4a3.svg)
![update-badge](https://user-images.githubusercontent.com/44731817/178175728-72983f17-342f-4917-9782-7fde26debbd6.svg)
![wifi](https://user-images.githubusercontent.com/44731817/178175734-8cd8ddfa-36a8-4499-855b-b0e4df3c9f4a.svg)
![window](https://user-images.githubusercontent.com/44731817/178175737-01182606-50ea-402a-ad60-b667da3be128.svg)
![zoom-out](https://user-images.githubusercontent.com/44731817/178175741-3571aac1-53c6-47d1-a46e-4d86762673fd.svg)

best regards Afi

**Comment by black7375** [comment]
You can access icon like 
- `chrome://global/skin/icons/page-portrait.svg`
- `chrome://browser/skin/permissions.svg`

More examples at https://github.com/black7375/Firefox-UI-Fix/blob/master/css/leptonChrome.css
