### ISSUE TITLE
Accent color not applied in Firefox 103 beta

### ISSUE THREAD

**Issue by Farow** [black7375/Firefox-UI-Fix#433]
**Describe the bug**
After updating to version 103, the accent color is no longer applied on the window/tab bar.

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**`user.js` setup**

```javascript
// Default settings
```

**Comment by black7375** [comment]
It seems to work on my device.
Try to install theme in the latest version.
![Win10-2022-07-19-02-02-31](https://user-images.githubusercontent.com/25581533/179564399-729ea3d9-c9b2-474b-ab66-72b26ba44197.png)

Related: #382

**Comment by Farow** [comment]
Is the accent color applied if dark mode is active? Just to clarify, I mean the accent color from windows. In the following screenshot you can see it's applied on the about dialog (brown titlebar) but not on the main window.

![2022-07-19_150337](https://user-images.githubusercontent.com/5174933/179747109-038f5d40-9e58-4d5c-9d27-2a54874357e4.png)

If it works again in 104 that's great. I'll test when it hits beta and let update the issue.

**Comment by Farow** [comment]
The new commit fixes the issue, thanks!
