### ISSUE TITLE
Add instruction to enable accent color for window title on Windows

### ISSUE THREAD

**Issue by Zueuk** [black7375/Firefox-UI-Fix#435]
**Is your feature request related to a problem?**
One of the main reasons for me to use this UI fix always was the ability to use system accent color for the window title, but every time I update the UI fix I have to look for the way to do this, since it was not enabled by default. This time I just cannot find it 🤷‍♀️

So right now, my FF window looks like this
![image](https://user-images.githubusercontent.com/5717247/180205548-161604f2-1dc7-415e-ab7b-1f84022a779b.png)

**The solution I'd like**
If this is indeed not a bug but an option, add an easily searchable (by Ctrl-F "accent") instruction to readme.md to modify whatever js/css/etc files for my browser window to look the way it is supposed to look with my OS settings.

**Comment by black7375** [comment]
IMO, It seems to be the same isuue as #433

**Comment by black7375** [comment]
If you have a problem with `v5.3.0`, reopen this issue.

**Comment by Zueuk** [comment]
The only difference is that the top edge is not white now. My Firefox version is 102.0.1

![image](https://user-images.githubusercontent.com/5717247/180770593-7c42f61b-4ae9-4300-b7dd-8b5053509afa.png)

Still no accent color on the window title - is it really supposed to work without any css or settings modifications?

**Comment by black7375** [comment]
You need `userChrome.compatibility.accent_color` to `true` at Firefox `v102`.
https://github.com/black7375/Firefox-UI-Fix/releases/tag/v5.3.0

However, due to compatibility issues, Firefox `v103`+ should be `false`.

**Comment by Zueuk** [comment]
Thanks, that fixed it! Now to remember to switch this after the next version comes out...
