### ISSUE TITLE
install.ps1 Copy-Lepton function bug

### ISSUE THREAD

**Issue by NLZ** [black7375/Firefox-UI-Fix#436]
Getting this error running install.ps1

```
Copy-Lepton: C:\Users\nlz\Code\Firefox-UI-Fix\install.ps1:843
Line |
 843 |    Copy-Lepton "${currentDir}" "user.js"
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot bind positional parameters because no names were given.
```

This is because the function Copy-Lepton has two parametes with both set to `Position=0`, the second should be `1`.

https://github.com/black7375/Firefox-UI-Fix/blob/9c34fe92348b5c5e7bd35d7ddfaef35c878e527c/install.ps1#L825-L830

**Comment by black7375** [comment]
Thank you for finding the cause!
