### ISSUE TITLE
`-moz-accent-color` and `-moz-accent-forgroundcolor` variable problem

### ISSUE THREAD

**Issue by BPower0036** [black7375/Firefox-UI-Fix#437]
I have now a little of a strange problem. It doesn't matter if I make a new profile, refresh my profile or install firefox dev on window 10.
The problem is that when `-moz-accent-color` is set for a  variable, like `--uc-accent-color: -moz-accent-color` firefox loads the variable, but strangely doesn't set its accent color.
If I change `-moz-accent-color` to a color like `red` it works, but `-moz-accent-color` doesn't work.
`-moz-accent-color` only works when applied directly, without using it via a variable.
The problem occurs not only at the titlebar but also when `userContent.page.proton_color.system_accent` is set true

(I have FireFox 102.0.1)

Made a new profile with the default .css folowing your intallation guide vs with it should look
![afbeelding](https://user-images.githubusercontent.com/80090789/180394233-673dfde2-a851-4048-9bb3-6a639eb86d00.png)
![afbeelding](https://user-images.githubusercontent.com/80090789/180394290-23353065-e80d-4b3f-9daa-c0f5605b778d.png)

_Originally posted by @BPower0036 in https://github.com/black7375/Firefox-UI-Fix/issues/433#issuecomment-1192283203_

**Comment by black7375** [comment]
It is included in `v5.3.0`.
It's a subtle problem that needs hard coding.
