### ISSUE TITLE
Icons on all menu exept the "Main program menu" appear on the letters.

### ISSUE THREAD

**Issue by Phantomia13** [black7375/Firefox-UI-Fix#439]
**Describe the bug**
Hi, i am using your ui for long time now and thank you so much for making it, My issue is for some weeks now the icons on all menu windows exept the main manu appear on top of the letters ( it worked fine when i installed the first time) 

**Screenshots**
[picture](https://imgur.com/9v5nLv1) (sorry for the non English letters)
![image](https://user-images.githubusercontent.com/25581533/180740305-97069d50-faba-455d-a427-0ca0e2041565.png)

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [x] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**`user.js` setup**
```
// ** Theme Related Options ****************************************************
// userchrome.css usercontent.css activate
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);

// Proton Enabled #127
user_pref("browser.proton.enabled", true);

// Proton Tooltip
user_pref("browser.proton.places-tooltip.enabled", true);

// Fill SVG Color
user_pref("svg.context-properties.content.enabled", true);

// CSS Color Mix - 88 Above
user_pref("layout.css.color-mix.enabled", true);

// CSS Blur Filter - 88 Above
user_pref("layout.css.backdrop-filter.enabled", true);

// Restore Compact Mode - 89 Above
user_pref("browser.compactmode.show", true);

// about:home Search Bar - 89 Above
user_pref("browser.newtabpage.activity-stream.improvesearch.handoffToAwesomebar", false);

// Browser Theme Based Scheme - Will be activate 95 Above
// user_pref("layout.css.prefers-color-scheme.content-override", 3);

// ** Useful Options ***********************************************************
// Integrated calculator at urlbar
user_pref("browser.urlbar.suggest.calculator", true);

// Integrated unit convertor at urlbar
// user_pref("browser.urlbar.unitConversion.enabled", true);

// Draw in Titlebar
// user_pref("browser.tabs.drawInTitlebar", true);
// user_pref("browser.tabs.inTitlebar",        1); // Nightly, 96 Above 
```

javascript
// Your setting
sorry i dont know how to find my settings

**Additional context**
i have also tried to delete anything reset all setings (new profile) and then do all the steps from the start coze i was using this code i found on reddit to modify a bit the pixels :
```
 /* Use Normal top and bottom padding for compact */
#PlacesToolbarItems .bookmark-item {
padding-top: 3px !important;
padding-bottom: 3px !important;}
/***Tighten up drop-down/context/popup menu spacing ***/
menupopup > menuitem, menupopup > menu {padding-block: 1px !important;}
:root {--arrowpanel-menuitem-padding: 4px 8px !important;}`
```
so even with clean install still the problem appears.

**Comment by black7375** [comment]
IMO,  This issue same as #331
Try to reinstall with the latest release.

If your Firefox version is `v102` or lower, you must set the `userChrome.compatibility.accent_color` option to `true`.
Conversely, if the Firefox version is `v103` or higher, it should not be set.

**Comment by Phantomia13** [comment]
u mean latest release of your code? i did before post and it didnt work(but i did the "master" i will try all options now), if u mean firefox i have 102.0.1 that seams to be the latest!

i aslo updated the `userChrome.compatibility.accent_color` to `true` but nothing changed, 
i will do some tests and experiments and if i have something different i will let you know! thanks a lot for your answer!

**Comment by Phantomia13** [comment]
Sorry i closed by mistake. i reopen in case any1 wants to write something

**Comment by Phantomia13** [comment]
u mean latest release of your code? i did before post and it didnt work(but i did the "master" i will try all options now), if u mean firefox i have 102.0.1 that seams to be the latest!

i aslo updated the userChrome.compatibility.accent_color to true but nothing changed,
i will do some tests and experiments and if i have something different i will let you know! thanks a lot for your answer!

**Comment by Phantomia13** [comment]
u mean latest release of your code? i did before post and it didnt work(but i did the "master" i will try all options now), if u mean firefox i have 102.0.1 that seams to be the latest!

i aslo updated the userChrome.compatibility.accent_color to true but nothing changed,
i will do some tests and experiments and if i have something different i will let you know! thanks a lot for your answer!

**Comment by black7375** [comment]
Yes. Now is the next release. https://github.com/black7375/Firefox-UI-Fix/releases/tag/v5.3.0

**Comment by Phantomia13** [comment]
u mean latest release of your code? i did before post and it didnt work(but i did the "master" i will try all options now), if u mean firefox i have 102.0.1 that seams to be the latest!

i aslo updated the userChrome.compatibility.accent_color to true but nothing changed,
i will do some tests and experiments and if i have something different i will let you know! thanks a lot for your answer!

(sorry i am new here and i closed and reopened the issue! i am rly sorry didnt know how it works)

**Comment by Phantomia13** [comment]
YES it worked, i updated with the link u provided with the latest release, before i downloaded from the main page that prop its not the latest release, but the 5.3.0 latest just fix the problem! thank you so much for all the work you do!
