### ISSUE TITLE
Missing icon in "Restore Previous Session" in history session of the hamburger menu

### ISSUE THREAD

**Issue by Progress200** [black7375/Firefox-UI-Fix#441]
**Describe the bug**

Icon in "Restore Previous Session" in history session of the hamburger menu is missing.

**Expected behavior**

An icon should appear like other buttons.
**Screenshots**

![image](https://user-images.githubusercontent.com/109966292/181266366-855bc8fa-9686-4a16-ba57-337ee28565ac.png)
![image](https://user-images.githubusercontent.com/109966292/181266257-1cc66549-b5ef-4e4f-ad0b-793d270fed4c.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Comment by black7375** [comment]
Try to use `v5.3.1` 

https://github.com/black7375/Firefox-UI-Fix/releases/tag/v5.3.1
