### ISSUE TITLE
The Findbar is white in Black/Dark mode...

### ISSUE THREAD

**Issue by Stepan-H** [black7375/Firefox-UI-Fix#447]
The Findbar has white background and dark front when browser is in Black/Dark mode.

If it is possible, it will be nice, the Findbar has adequate front and background color like menus due to browser theme... for dark theme dark background and light front.

**Comment by black7375** [comment]
It doesn't look bad on my Firefox.
![image](https://user-images.githubusercontent.com/25581533/181904413-c4b77587-988f-4e14-9d0b-286ece53736a.png)

Can you show the UI seen in your browser?

**Comment by Stepan-H** [comment]
![Screenshot 20220730134344](https://user-images.githubusercontent.com/31160576/181909405-2b7e72b6-83cc-44fd-9f80-b75f298bc209.JPG)

**Comment by Stepan-H** [comment]
It looks like there will be a problem with my browser, but I have no idea how to find it and I don't want to reinstall FF... I'll just try and search.

**Comment by Stepan-H** [comment]
So I managed to find it quickly. I set it to FF light theme and then back to dark and now it's OK.
