### ISSUE TITLE
Alternative tab close button arrangement: close button on all tabs + visible on hover

### ISSUE THREAD

**Issue by ShintoPlasm** [black7375/Firefox-UI-Fix#45]
**Is your feature request related to a problem? Please describe.**
The default Firefox close-button behaviour is awkward when more than 9 tabs are visible: the close button only appears after you select one of the tabs (when >9 tabs). In addition, your current userChrome.css shows the close button whenever a pinned tab is active, thereby hiding the pinned tab's favicon.

**Describe the solution you'd like**
I have long been using the following in my own userChrome.css and I respectfully recommend that you include the following code, or its equivalent, in your own userChrome.css file:

_.tabbrowser-tab:not([pinned="true"]):hover .tab-close-button:not([selected="true"]) {
  display: -moz-box !important;
}_

Currently, just adding the above code to your userChrome.css doesn't work as it should. However, I'd like to request that you replicate (in your own userChrome.css) the behaviour of the above code.

**Describe alternatives you've considered**
The userChrome.css file included in your otherwise excellent package follows the standard Firefox behaviour described above. I believe that my solution is better.

**Comment by black7375** [comment]
Considered after 1.0 release.

**Comment by black7375** [comment]
https://www.reddit.com/r/firefox/comments/nvlghq/lepton_v10_release/h16endh

Code Snippet
```css
.tabbrowser-tab .tab-close-button{
  display:none;
}
.tabbrowser-tab:not([pinned]):hover .tab-close-button{
  display:-moz-box !important;
}
```

**Comment by black7375** [comment]
![hover close](https://user-images.githubusercontent.com/25581533/123546621-e38bac00-d74c-11eb-998c-65b70bca3846.PNG)
It is now included.

**Comment by doodhout** [comment]
Did this change cause the tab close button to appear upon hovering over the tab?

I recently updated my Firefox-UI-Fix userChrome.css to a newer version and I'm wondering what has changed.

When I want to close a tab, I middle-click the tab using the scroll wheel click functionality. I do not need a close button for that.

When I want to select a tab, I just hover over it and left-click the tab. However, due to this change, I more often than not accidentally click the suddenly appeared close button on the tab instead, closing the tab unwillingly. This is annoying for me.

**Comment by dan2097** [comment]
Just to second @doodhout's comment, in the scenario where you have a large number of visible tabs (I'm running with browser.tabs.tabMinWidth 0), the on hover close button can occupy half the width of the tab making erroneously closing the tab annoyingly easy to do.

I don't think that there's an adjustmnt that will please everyone. Noting in the Tips wiki that commenting this particular CSS can disable the close buttons on non-active tabs may be useful. I also tend to use either middle-click and hence have no need for the close buttons.

**Comment by black7375** [comment]
People with laptops find it useful as there is no middle click button.
IMO, current value is better as the default.

Many people don't even know that you can close it with a middle click.
