### ISSUE TITLE
URL bar border flashes white when mouse leaves it

### ISSUE THREAD

**Issue by TheBrokenRail** [black7375/Firefox-UI-Fix#451]
**Describe the bug**
When my mouse cursor leaves the URL bar, the border flashes white.

**Expected behavior**
The border doesn't flash white.

**Screenshots**
[Screencast from 08-01-2022 11:37:35 PM.webm](https://user-images.githubusercontent.com/17478432/182286592-075885bb-0820-48b9-b66c-8a0de40defc8.webm)

**Environment:**
 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: ``102.0.1``
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): ``Yaru-dark``
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Comment by black7375** [comment]
Could you try `userChrome.compatibility.accent_color` to `true` && restart?

**Comment by TheBrokenRail** [comment]
This fixed it, thanks!

**Comment by infklinger** [comment]
I've got this exact issue, despite being on latest version and having ``userChrome.compatibility.accent_color`` set to ``true``
