### ISSUE TITLE
Close button hides favicon in active pinned tab

### ISSUE THREAD

**Issue by ShintoPlasm** [black7375/Firefox-UI-Fix#46]
**Describe the bug**
When a pinned tab is selected and active, the close button hides the tab's favicon.

**Expected behavior**
A pinned tab should not have a close button; this goes against the principle of pinning a tab.

**Screenshots**
See screenshots attached.

**Environment (please complete the following information):**
 - Firefox Version: 89.0
 - OS: Windows 10
 - Theme: Photon Colors

**Additional context**
I've suggested an alternative approach in a separate feature request: https://github.com/black7375/Firefox-UI-Fix/issues/45

**Screenshot 1 (Pinned tab not selected):**
![Pinned tab not selected](https://user-images.githubusercontent.com/35544416/120627614-c0c2ec00-c45b-11eb-8765-735e36a8f444.png)

**Screenshot 2 (Pinned tab selected):**
![Pinned tab selected](https://user-images.githubusercontent.com/35544416/120627673-cddfdb00-c45b-11eb-9cd5-3abe5cbdeb5b.png)

**Comment by gabri25ele** [comment]
yes, it's a behaviour (mistaken) of Firefox-UI-Fix (removing the chrome folder does not happen)

**Comment by black7375** [comment]
Duplecate: #10
