### ISSUE TITLE
Context menu color does not match the theme color in FF 105+

### ISSUE THREAD

**Issue by eaw4690** [black7375/Firefox-UI-Fix#466]
**Describe the bug**
Just upgraded to Firefox 105 (dev edition) in Windows 11 and the context menu color does match the theme color.

**Expected behavior**
Context menu color must match the color based on the theme.

**Screenshots**
FF 104:
![21](https://user-images.githubusercontent.com/104198709/189323042-8260500e-9df5-43d9-afb2-5ee6d936e310.png)
FF 105+:
![21](https://user-images.githubusercontent.com/104198709/189324797-bff4c3e8-3ecc-44f5-afab-0cd9def1ca0c.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [x] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 105.0b9 (Beta/Developer Edition), 106.0a1 (Nightly)
 - OS:
   - [ ] Linux
   - [x] Windows (10/11)
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [x] Alpenglow (System: Light)
   - [x] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): 
   - [x] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

<details><summary><strong><code>user.js</code> setup: </strong>Default</summary><br>

```javascript

```  
</details>

**Additional context**
I think mozilla made some changes. I can replicate the issue using [Firefox Color](https://color.firefox.com/) (see above image, in Popup Background). It seems that the [`popup`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme#colors) of the theme didn't apply the context menu color.

**Comment by eaw4690** [comment]
There something wrong in the latest commit: 
![21](https://user-images.githubusercontent.com/104198709/189532704-6a886355-38f2-4138-9e03-c02a9bbf830e.png)

**Comment by black7375** [comment]
Thanks to test, now will be works!
