### ISSUE TITLE
Release zips contain unneeded files

### ISSUE THREAD

**Issue by Roy-Orbison** [black7375/Firefox-UI-Fix#467]
**Is your feature request related to a problem?**
It isn't very user-friendly to fill the release archives with the files that are only relevant to development, etc. Github's automatic zips of each release (labelled *Source code*) already contain these files. Does Firefox need `__tests__/`, `yarn.lock` or `package.json` for your modifications to work?

**The solution I'd like**
For the archives to contain only the minimum required files, maybe plus the readme and licence.

**Alternatives I've considered**
`.gittributes`, but the presence of the readme in the release (when it's ignored in your attributes file) leads me to believe they're not generated using `git archive`.

**Comment by black7375** [comment]
That's a good suggestion.

From the next time, the release does not include files related to development, and the license files(`CREDITS`, `LICENSE`) have been placed in the root to make them clearer.

**Comment by black7375** [comment]
Try to new release!!

**Comment by Roy-Orbison** [comment]
Much better! Thank you. I notice the Waterfox file is gone, too, was that intentional?

**Comment by black7375** [comment]
Yes, That's only necessary for development.
