### ISSUE TITLE
`browser.proton.places-tooltip.enabled` is removed in Firefox 102+

### ISSUE THREAD

**Issue by eaw4690** [black7375/Firefox-UI-Fix#468]
Mozilla removed this about:config pref. in Firefox 102 (including ESR release).
https://bugzilla.mozilla.org/show_bug.cgi?id=1768004

![21](https://user-images.githubusercontent.com/104198709/190392195-c23a6017-113a-4d5b-9bc0-bac210ab82b6.png)

Firefox 91.0esr [will end support on Sep. 20, 2022](https://fx-trains.herokuapp.com/release/?version=esr).

Related: #328

**Comment by eaw4690** [comment]
Sorry for the title changes :)

**Comment by black7375** [comment]
One of the big projects using lepton is [waterfox](https://github.com/WaterfoxCo/Waterfox).
The [Waterfox G4](https://www.waterfox.net/docs/releases/g4.0.0) is based on Firefox `v91.0 ESR`.
In the case of the [Waterfox G5](https://www.waterfox.net/docs/releases/G5.0b1), it is based on Firefox `v102 ESR` and is still beta.

When Waterfox G5 is released, I will remove the code.
Thank you for reporting.

**Comment by black7375** [comment]
Watefox G5 has been released.
