### ISSUE TITLE
`userContent.page.proton_color.system_accent` doesn't work

### ISSUE THREAD

**Issue by BPower0036** [black7375/Firefox-UI-Fix#469]
**Describe the bug**
When you enable `-moz-bool-pref("userContent.page.proton_color.system_accent")` the color does change, but not to the correct one.
The color changes to a lighter blue but not to my accent color, see screenshots.

**Expected behavior**
Color should be my system set accent color.

**Screenshots**
first is pref disabled, second one pref enabled.
![afbeelding](https://user-images.githubusercontent.com/80090789/190848766-abae477a-1272-44fc-addd-0cad10651a7d.png)
![afbeelding](https://user-images.githubusercontent.com/80090789/190848699-73997035-79a3-4eff-a5a4-f4188c0d85e8.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 104.0.2
 - OS:
   - [ ] Linux
   - [x] Windows 10
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>
 
**Additional context**

**Comment by black7375** [comment]
Try to update theme && `widget.non-native-theme.use-theme-accent` to `true`.

**Comment by BPower0036** [comment]
Setting `widget.non-native-theme.use-theme-accent` solved it.
