### ISSUE TITLE
Can it be implemented as normal addon?

### ISSUE THREAD

**Issue by akeck** [black7375/Firefox-UI-Fix#47]
I'm using FF on several machines, work, home, notebook, ...
I love the FF feature, that syncs addons across machines. I install a new machine, login to my FF account, and have all addons installed, including AdBlocker,...

If this were an addon, I wouldn't have to see this ugly proton UI at all :)

**Comment by black7375** [comment]
It would be nice if possible, but I think it would be quite difficult.

**Comment by ojaha065** [comment]
WebExtensions API is pretty limited when it comes to editing the browser UI. Add-ons can only access handful of browser settings (listed [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserSettings)) and Themes (Standalone or combined with a browser extension) are [basically limited to chaging UI background images and colors](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme).

So sadly this doesn't seem possible.

**Comment by black7375** [comment]
Yes. I also think it's impossible.
Browser UI is not accessible for security reasons.

I'm closing because it's difficult for now.
