### ISSUE TITLE
URL auto-completion candidates are truncated if one_liner enabled

### ISSUE THREAD

**Issue by zptan** [black7375/Firefox-UI-Fix#471]
Lepton v6.2.0

**Describe the bug**

![image](https://user-images.githubusercontent.com/17807777/190949549-2bc987e9-5f62-4f3b-8b8c-ad03790cf491.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/17807777/190950327-0030fab1-b8e4-41f8-a375-61f2a485676d.png)

**Screenshots**

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version:  105.0 RC2
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>
 
**Additional context**

**Comment by black7375** [comment]
As far as I know, this was a bug in 6.1.0.

Would you like to download the latest version again?

**Comment by zptan** [comment]
> 

The version I used is the very latest v6.2.0

**Comment by black7375** [comment]
Ok, now it will be works

**Comment by zptan** [comment]
Thx, I confirm it is fixed.
