### ISSUE TITLE
URL bar is truncated on laptop (13.3') if one_liner enabled and there are many tabs

### ISSUE THREAD

**Issue by zptan** [black7375/Firefox-UI-Fix#472]
Lepton v6.2.0
one_liner enabled

**Describe the bug**
As the title says, on small display (13.3')

![image](https://user-images.githubusercontent.com/17807777/190951511-d815ea44-2b2d-425c-91de-8e2410d07cd8.png)

**Expected behavior**
The URL bar shows after switching to a bigger monitor (27')

![image](https://user-images.githubusercontent.com/17807777/190952249-5753dfb8-dd71-4451-9180-630575b02142.png)

**Screenshots**

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version:  105.0 RC2
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>
 
**Additional context**

**Suggestion**
Reserve a size / length for the URL bar

**Comment by black7375** [comment]
Here are two options.

- https://github.com/black7375/Firefox-UI-Fix/wiki/Options#url-bar-iconbox
  - `userChrome.hidden.urlbar_iconbox` to `true`
- https://github.com/black7375/Firefox-UI-Fix/wiki/Options#one-liner
  - `userChrome.tabbar.one_liner.responsive` to `true`

**Comment by zptan** [comment]
Thx, actually I mean the URL bar is too short in small display even the iconbox has been removed

Can we reserve a size / length for the URL bar?

![image](https://user-images.githubusercontent.com/17807777/190966435-3341aeee-e0fc-440f-bb1d-c20c036621ac.png)

**Comment by zptan** [comment]
Thx, I've applied the patch, but seems the URL bar is still short, is there any option / parameter to adjust the length of the URL bar?

**Comment by black7375** [comment]
You can use custom css.
However, smaller screens can cause side effects such as buttons going out.

```css
#urlbar-container {
  --uc-oneliner-urlbar-base-width: 50px;
}
```

**Comment by zptan** [comment]
I'll try, thx for your replies.
