### ISSUE TITLE
How To Change Bookmark Outline When Dragging

### ISSUE THREAD

**Issue by thunderstone135** [black7375/Firefox-UI-Fix#473]
**Is your feature request related to a problem?**
Not really. I don't think it's available yet. I already tried toggling `userChrome.theme.proton_color.dark_blue_accent` and `userContent.page.proton_color.dark_blue_accent` to `true`, but it didn't change the color of the item I'm trying to change.

**The solution I'd like**
I just want to ask if anyone knows how to change the color of the line that appears when dragging bookmark items.

**Screenshots or video**
![Imgur](https://imgur.com/ODOu1vx.png)

**Alternatives I've considered**
Aside from toggling the prefs mentioned above, I also tried changing the value of the following in userChrome and userContent 👇 
```
--win-accent-color
--win-accent-hover-color
--in-content-primary-button-background
--in-content-primary-button-background-hover
```

**Additional context**
N/A

**Comment by black7375** [comment]
Now it will be works.
