### ISSUE TITLE
Improvement First Tab space

### ISSUE THREAD

**Issue by BPower0036** [black7375/Firefox-UI-Fix#475]
**Is your feature request related to a problem?**
https://github.com/black7375/Firefox-UI-Fix/blob/master/src/padding/_first_tab.scss#L6-#L9
This current code doesn't work when having pinned tabs and the tabbar overflow is visible

**The solution I'd like**
```
:root:not([sizemode="normal"]) .titlebar-spacer[type="pre-tabs"] {
  display: -moz-box !important;
  width: var(--space-left-tabbar) !important;
}
```
However this code works always.

**Screenshots or video**

**Alternatives I've considered**

**Additional context**

**Comment by black7375** [comment]
It was an intentional decision, but I am thinking about changing the policy.
Temporarily use the following options.

- `userChrome.padding.first_tab.always`
