### ISSUE TITLE
Waste of vertical space on top of tabs bar

### ISSUE THREAD

**Issue by UncleScrooge85** [black7375/Firefox-UI-Fix#476]
Hello and first of all thanks for the good job in making available this UI fix.
The main reason for me to use this fix is to improve readibility and maximize the use of vertical space, since the new Proton UI is wasting a lot of that.
![Cattura](https://user-images.githubusercontent.com/102796534/191502168-dc9c4f1b-fca6-419a-9967-6b5922a69261.JPG)
Would you consider updating the UI fix to get rid of the extra lines of pixels on top of the tabs bar? It's 2 lines when in full-screen mode and 3 lines when in normal window mode.
Until Firefox 90 with Photon UI we didn't have any pixel line over the tabs bar and I'd just like to recover this waste of space.

The very first version of your UI fix already solved this issue, then the extra lines reappeared after a FF update and you fixed it again after some weeks, but then another FF update made these lines come back again and you never fixed it anymore.
Thank you for your consideration :)

**Comment by thunderstone135** [comment]
I think you need to toggle `userChrome.tab.connect_to_window` and `userChrome.tab.photon_like_padding` to `true`.
Aside from that, you also need to toggle `userChrome.tab.lepton_like_padding` to `false`.

**Comment by UncleScrooge85** [comment]
userChrome settings were already set as you mentioned

**Comment by thunderstone135** [comment]
I checked my settings and it looks like some of the changes I added in userChrome.css is making me see differently.
I disabled the changes in my userChrome.css and I noticed that `userChrome.tab.connect_to_window` is adding more space.
I toggled that pref off and 1px got removed. If you want to remove the remaining 1px, you can add this to your userChrome 👇 
```
#tabbrowser-arrowscrollbox > .tabbrowser-tab {
  margin-top: -1px !important;
}
```

**Comment by UncleScrooge85** [comment]
I haven't changed anything in my userChrome.css.
Toggling off `userChrome.tab.connect_to_window` doesn't have any effect, and it resets itself back to true upon restarting FF.

I believe these extra lines should be removed by default using the Photon style UI fix (because until FF 90 we didn't have the extra lines).
Please note the extra lines are 2px in full screen mode and 3px in window mode.

**Comment by thunderstone135** [comment]
> I don't think @black7375 changed anything in Firefox UI Fix. If anything, Mozilla constantly adds and changes their code.

I checked all usage of `.tabbrowser-tab` in Firefox UI Fix just now and I wasn't able to find anything that changes the margin of the Tab Bar. This is most likely caused by Mozilla.

**Comment by UncleScrooge85** [comment]
I didn't misunderstand you, I was just saying that I'm using the Photon style fix without any extra change to the userChrome.css, so that you can understand my scenario.
Toggling off `userChrome.tab.connect_to_window` and clearing startup cache still doesn't work and the pref keeps resetting back to true upon restarting FF.

Yes, I'm sure that @black7375 didn't change anythings and the problem is due to Mozilla changing their code. Still, I am merely suggesting to update the Photon style fix to remove these extra lines, since right now the fix is not "perfect" anymore these extra lines shouldn't be there in a Photon style UI.
I also remember this already happened some months ago and then @black7375 fixed it that one time, but the Mozilla "broke" it again.

**Comment by thunderstone135** [comment]
> I didn't misunderstand you, I was just saying that I'm using the Photon style fix without any extra change to the userChrome.css, so that you can understand my scenario.

This is noted.

> Toggling off `userChrome.tab.connect_to_window` and clearing startup cache still doesn't work and the pref keeps resetting back to true upon restarting FF.

That's strange. You should probably edit prefs.js directly. Of course, you need to fully exit Firefox before doing so.

> Yes, I'm sure that @black7375 didn't change anythings and the problem is due to Mozilla changing their code. Still, I am suggesting to update the Photon style fix to remove these extra lines, since right now the fix is not "perfect" anymore and these extra lines shouldn't be there in a Photon style UI. I also remember this issue already happened some months ago and then @black7375 fixed it that one time, but then Mozilla "broke" it again.

Well, you know Mozilla. They always go with asinine decisions that comes back to bite them.
That's why I switched to Waterfox. Not fully perfect, but at least some irritating changes are mitigated.

**Comment by black7375** [comment]
There are some information I need to make it a little clearer.
What's your OS and Firefox's version?

**Comment by UncleScrooge85** [comment]
I'm currently on Windows 10 21H2 and Firefox 105 but this issue appeared around June/July.
I forgot to mention that I use the Compact mode.
I just tried switching to Normal density and the 2 extra lines disappear, so I can confirm that the issue only happens in Compact mode.
However, there still is 1 extra line when in window mode (not full screen). So this is what happens:
Compact mode: 2 extra lines in full screen and 3 extra lines in window
Normal density: no extra line in full screen and 1 extra line in window

For me, the most important thing would be to remove the 2 extra lines in compact mode full screen. For the other 1 extra line in window mode, it would be nice to remove that as well but it would be a minor inconvenience if it is not possible.

**Comment by black7375** [comment]
It seems to work for me.

**Comment by UncleScrooge85** [comment]
I just tried it and now the situation is the same in compact mode and normal density:
Compact mode: 1 extra lines in full screen and 2 extra lines in window
Normal density: 1 extra line in full screen and 2 extra line in window

Moreover, nothing changed with the photon-style branch

**Comment by black7375** [comment]
@UncleScrooge85 Did the last update fix it?

**Comment by UncleScrooge85** [comment]
@black7375 nope, still 1 line in full screen and 2 lines in window mode, with either normal or compact density

**Comment by black7375** [comment]
That's weird. All of it was solved on my computer.
