### ISSUE TITLE
Item highlighting in dropdown selection boxes

### ISSUE THREAD

**Issue by AuRiMaS666** [black7375/Firefox-UI-Fix#477]
**Describe the bug**

After the latest updates to FF 105 and Lepton 6.2.0, I've noticed a highlighting issue when selecting items in dropdown boxes. It seems to occur in all theme styles, except the System one.

**Screenshots**

**Default FF Dark/Light/Alpenglow theme**
![1 1](https://user-images.githubusercontent.com/59185222/192086183-e9943e8c-8e5f-46b5-b3b8-04162b228046.png)
![1 2](https://user-images.githubusercontent.com/59185222/192086270-54f1a0ef-14e9-4243-9965-b2cf36a66f49.png)

**Lepton Dark/Light/Alpenglow theme**
![2 1](https://user-images.githubusercontent.com/59185222/192086346-6bc539d9-63ef-4002-8136-4d0cbfb16ca7.png)
![2 2](https://user-images.githubusercontent.com/59185222/192086357-217d1e48-65a1-4d3b-a88e-ff68fa9b47ab.png)

**Lepton System theme**
![3 1](https://user-images.githubusercontent.com/59185222/192086384-c48eee79-7b08-4794-be72-a66622bb2bd2.png)
![3 2](https://user-images.githubusercontent.com/59185222/192086399-c9a92875-4d44-45fd-8609-f6656d067bd3.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version:  105.0.1
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [x] Light
   - [x] Dark
   - [x] Alpenglow (System: Light)
   - [x] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

Default settings from the latest distribution.

**Comment by black7375** [comment]
Related issue: #466

- https://github.com/mozilla/gecko-dev/commit/cf26510de692c1e853cf5290c107bf79c9522a53

---

I changed it to work.
Thank you for detailed reports. 👍
