### ISSUE TITLE
Container Tab Line Position

### ISSUE THREAD

**Issue by Monmcgt** [black7375/Firefox-UI-Fix#478]
**Is your feature request related to a problem?**
It's quite weird in my opinion to have a container tab line at the bottom. Maybe there should be an option to set the line position.

**The solution I'd like**
Be able to edit the settings to move the line to the top.

**Image**
Now:
![image](https://user-images.githubusercontent.com/71365435/192871014-0c7c2d38-9667-40ab-b176-3d6a6e143950.png)
What I suggest:
![image](https://user-images.githubusercontent.com/71365435/192871984-4c195cf1-95b2-4dba-9498-d87272947bc4.png)

**Comment by black7375** [comment]
I haven't worked on document yet, but your proposal is included in 8.0.0.
- `userChrome.tab.container.on_top` to `true`
