### ISSUE TITLE
Customize Install (i.e icons only) 

### ISSUE THREAD

**Issue by Possibly-Matt** [black7375/Firefox-UI-Fix#48]
**Is your feature request related to a problem? Please describe.**
I was referred to this theme as a solution to get the panel icons back and this certainly works for that, however I am wondering if there is a way to customize which features could be installed. I've manually made an icons only edition here 
https://github.com/Possibly-Matt/Firefox-UI-Fix
I quite like the floating style tabs, but I like the tab dividers in this theme. 

**Describe the solution you'd like**
I'm not too well versed on javascript/css or how other themes do this but perhaps a configuration file could be read by js and only specific css run? 
My version wasn't too painful to edit because of the good commenting :) so thanks for that. So really customizing this theme should only take as long 
Alternatively multiple versions of the addon but that sounds like such a pain to maintain and ultimately not worth it

**Comment by black7375** [comment]
I've been busy with personal work today, so I'll review it in the morning.

**Comment by ali-gen** [comment]
☺️👍🙏🏼

**Comment by Possibly-Matt** [comment]
> I've been busy with personal work today, so I'll review it in the morning.

Absolutely no rush, this is probably at the bottom of the "nice to haves" list. Thank you for all the work you've put into this (and to all the folks at Mozilla!)

**Comment by black7375** [comment]
What I'm envisioning (just a plan yet)

This is to enable primary customization using the installer. #32
Installer solves the complexity of setting up JS, we can configure `about:preferences` menu to be customizable.

**Comment by 7k5x** [comment]
You're trying to kill me! I'll try that later.

**Comment by 7k5x** [comment]
#93 Currently a nofix, but will possibly be included in the unclear future.

**Comment by black7375** [comment]
Maybe version 3.0 will support floating tabs

**Comment by black7375** [comment]
![image](https://user-images.githubusercontent.com/25581533/124228547-e0e9d780-dafb-11eb-865e-eeca0d791b76.png)

https://github.com/black7375/Firefox-UI-Fix/tree/proton-style

Foundation work is complete.
