### ISSUE TITLE
Preference to hide all menu icons

### ISSUE THREAD

**Issue by adamp01** [black7375/Firefox-UI-Fix#481]
**Is your feature request related to a problem?**
Is it feasible to add all menu icons behind a preference, so that they can be easily toggled off. I was looking through existing preferences but didn't seem like turning all icons off was currently possible (appMenu and context menu).

**The solution I'd like**
Be able to remove all appMenu and context menu icons.

**Comment by black7375** [comment]
Sounds good.

I'll add `userChrome.icon.disabled` option.

**Comment by black7375** [comment]
Try to use [v6.3.0](https://github.com/black7375/Firefox-UI-Fix/releases/tag/v6.3.0).
Another factor that affects `waterfox` is the rounding of the new tab button like original photon design.
