### ISSUE TITLE
Container indicator is misplaced after firefox update

### ISSUE THREAD

**Issue by masihsaeedi** [black7375/Firefox-UI-Fix#482]
**Describe the bug**

Container indicator misplaced after nightly update.now indicator is above tab's text instead of under text.
**Expected behavior**

The container indicator should be under the tab's text.
**Screenshots**

![2022-10-15_00-06](https://user-images.githubusercontent.com/29687018/195939379-679493c1-9893-4255-9832-37e5029cd7eb.png)
**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [x] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version:107.0a1 
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [x] Other: ( element soft from colorways)

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>
 
**Additional context**

**Comment by black7375** [comment]
Are you using latest firefox nightly?
Tabbar related bugs are resolved in the latest version. (There was a time when there was a problem for about two days a day)

![image](https://user-images.githubusercontent.com/25581533/196000226-457de273-3431-405f-8bf5-c687f7adf2b1.png)

**Comment by masihsaeedi** [comment]
yeah the problem is resolved now.
