### ISSUE TITLE
Git Master is broken on latest Firefox Nightly update

### ISSUE THREAD

**Issue by Valmar33** [black7375/Firefox-UI-Fix#484]
Tab bar broken is borkened:

![Screenshot_20221019_145249](https://user-images.githubusercontent.com/5097518/196600649-5a45b6a7-a672-4cfd-a62c-ef60a99ea1b6.png)

Can provide more info if needed.

**Comment by Valmar33** [comment]
Tab bar works as expected if Firefox-UI-Fix is removed.

**Comment by black7375** [comment]
Now will be works

**Comment by Valmar33** [comment]
> Now will be works

Seems to be working now! Cheers! :)
