### ISSUE TITLE
After updated to v108.0a1 nightly, Firefox container indicator position

### ISSUE THREAD

**Issue by Progress200** [black7375/Firefox-UI-Fix#485]
**Describe the bug**
After updated to v108.0a1 nightly, Firefox **tab UI** becomes buggy and unusable. (It works fine when entering Troubleshoot mode)
**Buggy Firefox**
![image](https://user-images.githubusercontent.com/109966292/196886536-cf8415aa-c4ee-4125-a44e-9fd23d08b07e.png)
**When turning on troubleshoot mode**
![image](https://user-images.githubusercontent.com/109966292/196885906-895e7e66-5980-4e63-9b15-1fef2d735366.png)
**Expected behavior**
Normal Lepton behavior before the bug
![image](https://user-images.githubusercontent.com/109966292/196886079-cb6082cc-5c85-4d2d-9cf4-39db4e246bed.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

**Comment by black7375** [comment]
It seems duplicated #484
Try to latest commit.

**Comment by Progress200** [comment]
The latest commit fixed the bug. Thank you! But there is another bug on the tab.
![image](https://user-images.githubusercontent.com/109966292/196912695-dbd9a773-4871-4912-ab67-7d145e249236.png)

**Comment by black7375** [comment]
Now,it works correctly
![image](https://user-images.githubusercontent.com/25581533/197083888-419555ee-ca0a-4d8d-b5f0-d1b9693b735b.png)

**Comment by Progress200** [comment]
Thank you! It works correctly
