### ISSUE TITLE
Dinasaur image on error page disapear

### ISSUE THREAD

**Issue by Progress200** [black7375/Firefox-UI-Fix#489]
**Describe the bug**

There suppose be a dinosaur image on the error page "Hmm. We’re having trouble finding that site.". However, the image in the latest release disappear.
![image](https://user-images.githubusercontent.com/109966292/197158357-6941374b-5de6-43d0-91fa-50e5f6b892f6.png)
**Expected behavior**

The dinosaur image should appear like previous versions.
![image](https://user-images.githubusercontent.com/109966292/197158432-1b571d27-e589-4da3-8337-6d2492329821.png)
**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Comment by black7375** [comment]
Thank you I think there was a change in Firefox.
![image](https://user-images.githubusercontent.com/25581533/197319392-597eaf09-7d32-4de1-b730-d26f44d582c1.png)

**Comment by Progress200** [comment]
It fixed, thanks!
