### ISSUE TITLE
first tab padding with titlebar enabled

### ISSUE THREAD

**Issue by Coniferr** [black7375/Firefox-UI-Fix#490]
**The solution I'd like**
i'd like the first tab to have padding before it with title bar enabled. currently this only shows with titlebar disabled.

**Screenshots or video**
![image](https://user-images.githubusercontent.com/43714528/197318114-8dfa8843-6105-4406-8313-20eb58788c68.png)

**Comment by black7375** [comment]
It already exists as an option.

https://github.com/black7375/Firefox-UI-Fix/wiki/Options#first-tab-space
- `userChrome.padding.first_tab` to `true`

![image](https://user-images.githubusercontent.com/25581533/197319910-bdcc738f-b269-49d4-8a8e-6f64042fbcab.png)
