### ISSUE TITLE
Window controls overlap nav controls when tabbar autohide=true

### ISSUE THREAD

**Issue by adamp01** [black7375/Firefox-UI-Fix#494]
**Describe the bug**
On MacOS, the window controls overlap the nav bar controls when the tab bar is set to autohide and is hidden.

**Expected behavior**
Window controls should autohide with the tab bar.

**Screenshots**

<img width="337" alt="Screenshot 2022-10-24 at 12 00 33" src="https://user-images.githubusercontent.com/47503375/197516978-bde49e99-1076-4f05-ae6c-28492c855488.png">

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [ ] Windows
   - [x] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>
 
**Additional context**
Waterfox G5.0.1

**Comment by black7375** [comment]
Because of
```css
#TabsToolbar > .titlebar-buttonbox-container > .titlebar-buttonbox {
  appearance: auto;
}
```

It may take time because it's a bit tricky to deal with.

**Comment by black7375** [comment]
It's working now.

![image](https://user-images.githubusercontent.com/25581533/197655288-26ed3719-b4c4-490c-97b2-dd53056dd941.png)
