### ISSUE TITLE
Background Menu Popup

### ISSUE THREAD

**Issue by BPower0036** [black7375/Firefox-UI-Fix#495]
**Describe the bug**
General menu popup and menu popup in library or sidebar donnot have the same background color.
If you change in `fully_color`: `--panel-background: var(--menu-background-color) !important;` to red, like this: 
```
@media (-moz-windows-non-native-menus) {
  html#main-window menupopup:not(.in-menulist) {
    /* Above FF v105 #466 */
    --panel-color: var(--menu-color) !important;
    --panel-background: red !important; /* var(--menu-background-color) */
    --panel-border-color: var(--menu-border-color) !important;
  }
```
You can more clearly see the differnce in the screenshot.
 
**Expected behavior**
Library and sidebar menu popup have the same background-color as the general  menu popup.

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/80090789/197681384-78beeb3c-202c-46f7-991b-1b7aa2b93d2f.png)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows 10
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>
 
**Additional context**
Deleting `html#main-window` solves the problem, but I don't know if there will occur any negative side effects.

**Comment by black7375** [comment]
Unfortunately, the context of `Main Browser UI` and `Sidebar Internal` is separated, so the value of `main menu's color` cannot be used.
However, I found one thing wrong and corrected it.

![image](https://user-images.githubusercontent.com/25581533/198813116-ac670142-0ca3-4d12-8276-6a6d8b7b270e.png)
