### ISSUE TITLE
Favicon goes missing when tab is playing audio

### ISSUE THREAD

**Issue by maticahacic** [black7375/Firefox-UI-Fix#5]
The favicon in the tab disappears when said tab is playing audio.

![Screenshot from 2021-05-16 21-54-14](https://user-images.githubusercontent.com/25854455/118410782-856da280-b691-11eb-82b8-d23a9e7130a8.png)

It reappears when you hover over the tabs with the mouse.

![Screenshot from 2021-05-16 21-56-57](https://user-images.githubusercontent.com/25854455/118410847-d67d9680-b691-11eb-959f-4f7ad8ce817c.png)

**Comment by black7375** [comment]
Thank you report

**Comment by black7375** [comment]
I reimplemented sound tab.
https://github.com/black7375/Firefox-UI-Fix/commit/a722cfcb0a6d6e2f47f9b5fb56cb590f6deaeb10

And added a noticeable interaction.
![image](https://user-images.githubusercontent.com/25581533/118768116-2618b980-b86e-11eb-93d8-af5f7235f55a.png)


Has the problem resolved?

**Comment by maticahacic** [comment]
Kinda but when I'm not in tab icon is barely visible
This one is withe selected tab (no hover so that part is working as per your fix)

![Screenshot from 2021-05-21 00-08-05](https://user-images.githubusercontent.com/25854455/119054965-c84cb480-b9c8-11eb-82cf-950c612ac117.png)

Here you can see, heh, how dark icon is it almost hides itself.
![Screenshot from 2021-05-21 00-08-26](https://user-images.githubusercontent.com/25854455/119054973-caaf0e80-b9c8-11eb-8f08-96754ddde036.png)

**Comment by black7375** [comment]
What's your theme?
I'll test on it.

**Comment by black7375** [comment]
Could you try again?
If you still have problems, please let me know the theme.

**Comment by maticahacic** [comment]
Now it's perfect. Thanks for fixing this! 

I've tried this on Yaru Amber and Arc Dark on GNOME btw.

**Comment by black7375** [comment]
Thanks for the test!!
