### ISSUE TITLE
Selected Tab color

### ISSUE THREAD

**Issue by ctrlcmdshft** [black7375/Firefox-UI-Fix#504]
I using the dark theme in firefox with this but i dont have any colors on selected tab which make it harder to see which tab is selected am i missing something setting wise? 

![firefox_1105](https://user-images.githubusercontent.com/61129128/200688521-969b5d67-2f46-4238-8d98-d4b297627302.jpg)

**Comment by black7375** [comment]
Tab box-shadow(`userChrome.tab.box_shadow`) seems to be disabled.

The default setting should look like:
![](https://user-images.githubusercontent.com/25581533/199343694-ad87dd1a-b274-40b2-af55-692382e58ab3.png)
