### ISSUE TITLE
bug UI in second bookmark folder

### ISSUE THREAD

**Issue by xmtomcom** [black7375/Firefox-UI-Fix#505]
**Describe the bug**
view the picture
**Expected behavior**

![图片](https://user-images.githubusercontent.com/10548236/201672507-32b08711-8eaf-4ef0-a923-ae6942bac293.png)

**Screenshots**

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)

 - Firefox Version: <102.4ESR>
 - OS:
   - [ ] Mac

 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>
 
**Additional context**

**Comment by black7375** [comment]
Now, should be works!!

![image](https://user-images.githubusercontent.com/25581533/201977198-0fe75594-a967-4896-a845-0465ea2308ee.png)

**Comment by xmtomcom** [comment]
But It doesn't work properly on my mac , firfox ESR102,with lepton v6.4
<img width="1317" alt="屏幕快照 2022-11-17 下午10 31 21" src="https://user-images.githubusercontent.com/10548236/202474232-8a204db9-53b6-44ac-83b5-365176e75da1.png">

**Comment by black7375** [comment]
Are you using the latest commit?

**Comment by xmtomcom** [comment]
Yes， I used the lastest version6.4, Lepton
firefox for mac v102ESR

**Comment by black7375** [comment]
You should use latest commit, not latest release.
It's before the new version comes out.

https://github.com/black7375/Firefox-UI-Fix/wiki/Installation-Guide#2-download-files--unzip

**Comment by xmtomcom** [comment]
yes,I think I did it with the guide,and the lepton UI was effected,you can see the screen shot.
but the 2nd bookmark menu can't show properly
<img width="1342" alt="屏幕快照 2022-11-18 下午10 33 24" src="https://user-images.githubusercontent.com/10548236/202728901-cb72a2da-6080-44d5-905b-e115212433a2.png">
![Uploading 屏幕快照 2022-11-18 下午10.35.26.png…]()

**Comment by xmtomcom** [comment]
yes,I think I did it with the guide,and the lepton UI was effected,you can see the screen shot.
but the 2nd bookmark menu can't show properly
<img width="1342" alt="屏幕快照 2022-11-18 下午10 33 24" src="https://user-images.githubusercontent.com/10548236/202729667-adb56549-a856-4cf0-ac7c-8754cdd19324.png">
<img width="1091" alt="屏幕快照 2022-11-18 下午10 35 26" src="https://user-images.githubusercontent.com/10548236/202729714-dbacc969-11cd-4296-aebf-c0db9d4868d6.png">

**Comment by black7375** [comment]
No, You downloaded from release.
Since it is a release, you need to download the code directly.

![image](https://user-images.githubusercontent.com/25581533/202818073-0b9187f4-0a57-42c3-acee-09ec791fba19.png)

![image](https://user-images.githubusercontent.com/25581533/202818022-decdeb5a-6b3a-4aeb-ba94-2b2348c0bf1c.png)

**Comment by xmtomcom** [comment]
no,I downloaded the Firefox-UI-Fix-master.zip,and unzip it,do by the guide,but it doesn't work. 
<img width="1257" alt="屏幕快照 2022-11-26 下午4 01 50" src="https://user-images.githubusercontent.com/10548236/204079137-a8796361-5cc0-42ec-84d7-d57d95cf0b35.png">
<img width="880" alt="屏幕快照 2022-11-26 下午4 02 32" src="https://user-images.githubusercontent.com/10548236/204079143-f421c87e-7485-4614-b388-d192727f8f64.png">
<img width="713" alt="屏幕快照 2022-11-26 下午4 04 03" src="https://user-images.githubusercontent.com/10548236/204079148-98aae985-1614-4792-8541-a45b93a5b04a.png">
<img width="726" alt="屏幕快照 2022-11-26 下午4 04 21" src="https://user-images.githubusercontent.com/10548236/204079152-05081305-fc3a-49ae-b3f1-3579d6f2ed89.png">

**Comment by black7375** [comment]
It's strange. When the latest versions in `Catalina` and `Ventura`, they all fixed.
![image](https://user-images.githubusercontent.com/25581533/204085027-bdb3a7b9-ded2-4a7b-8dc2-9404e49db538.png)

---

I can't reproduce, so I will wait for someone else's report.

**Comment by Noceti** [comment]
After updating to Firefox 110.0.1 on windows.

![Bookmarks](https://user-images.githubusercontent.com/121315318/222891357-7223676d-4e5f-4a0b-b23e-d1c6d7ae2c1a.jpg)

**Comment by Noceti** [comment]
The latest commit 7.2.0 fixed the issue for me.

**Comment by black7375** [comment]
@Noceti Thank you for test!! :+1:

**Comment by xmtomcom** [comment]
> The latest commit 7.2.0 fixed the issue for me.

It is so strange, The latest commit 7.2.0 don't work well on my v111.0 x64 yet,compact mode.
win8.1_x64 
![图片](https://user-images.githubusercontent.com/10548236/229673996-195abf3d-7c95-41e8-9c01-16f12ab8eb55.png)
