### ISSUE TITLE
"Center Tab Content" glitches some tabs' end gradient

### ISSUE THREAD

**Issue by Gersonzao** [black7375/Firefox-UI-Fix#508]
**This bug has been reported in https://github.com/WaterfoxCo/Waterfox/issues/2899**

### What happened?

A bug happened! When there's a tab that its width has an approximate width of its title, the end gradient starts blinking on and off. Happens both with active and inactive tabs (never happened with unloaded tabs). My display resolution is 1366 (w) x 768 (h). Happens both when "Center Tab Label Only" is on or off

This bug also causes high CPU usage. I've tried switching between tabs and the high usage doesn't stop. It stops when I open a new tab, for example (it changes the width of all tabs, if there are tabs enough to cover the width of the display)

Debian 11 (stable) and Waterfox G5.1

Recording:

https://user-images.githubusercontent.com/85644671/202054122-40fd4aa4-86dd-4868-b09a-3c2dcdca5bb7.mp4

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Linux

**Comment by black7375** [comment]
Do you mean that [`userChrome.centered.tab.label`](https://github.com/black7375/Firefox-UI-Fix/wiki/Options#tab-1) was used?

**Comment by Gersonzao** [comment]
I'm not sure, I was told in https://github.com/WaterfoxCo/Waterfox/issues/2899#issuecomment-1318326261 to post this issue here, as I mentioned in the issue

**Comment by black7375** [comment]
Check out the following:

1. Go to `about:config`
2. Search `userChrome.centered.tab.label`

**Comment by Gersonzao** [comment]
The option is set to true

**Comment by black7375** [comment]
I adjusted the property and it seems to work.

**Comment by black7375** [comment]
Wait for [v6.5.1](https://github.com/black7375/Firefox-UI-Fix/releases/tag/v6.5.1) to be applied in waterfox

**Comment by Gersonzao** [comment]
G5.1.2 has been released and I didn't have any problems so far. Waterfox isn't my main browser any more and I have switched to openSUSE Leap. I will update if I get this problem again
