### ISSUE TITLE
Remove Tab Seperators

### ISSUE THREAD

**Issue by GeorgeCyriac** [black7375/Firefox-UI-Fix#510]
![azrhzarfznrjzd2tq3](https://user-images.githubusercontent.com/98342014/202755930-31195065-fa1a-48ec-be97-0ba0b6f5a08c.png)
- [x] OS: Windows
- [x] Browser: Firefox v.107.0
- [x] Distribution: Proton Style

Hi.
This isn't really a bug or anything. I just want to know how to disable tab seperators. I want to use a custom firefox CSS, but I need to disable tab seperators for that. 

**Methods I Tried:**
I read the **Wiki** and went through the **.css** files but couldn't find anything that worked. 
_Hoping you can help me,
Many Thanks_

**Comment by black7375** [comment]
It can be confusing because there are many options.

https://github.com/black7375/Firefox-UI-Fix/wiki/Options#distribution-1
![image](https://user-images.githubusercontent.com/25581533/202757282-a649da97-c8bb-4ca5-a27a-c7a36fd7d0ad.png)

---

`userChrome.tab.dynamic_separator` to `false` at **`user.js`** file && restart

**Comment by GeorgeCyriac** [comment]
I tried changing **userChrome.tab.dynamic_separator** to false in **user.js** and the issue still persists.

**Comment by black7375** [comment]
Check out the following:

1. Go `about:config`
2. Check next value
  - `userChrome.tab.dynamic_separator` to `false`
  - `userChrome.tab.dynamic_separtor` to `false` (Legacy value)

**Comment by GeorgeCyriac** [comment]
Changing both values in **user.js** worked for me.
Much obliged for helping me out. Also, I was surprised to receive such a quick reply. 
Thanks for the prompt response.

**Comment by black7375** [comment]
No worries, enjoy web browsing :smile_cat:

**Comment by Zabooby** [comment]
How would I change the colour of the tab separator?
