### ISSUE TITLE
Pinned tabs shadow

### ISSUE THREAD

**Issue by waclaw66** [black7375/Firefox-UI-Fix#513]
**Describe the bug**
Pinned tabs got a shadow in Firefox 108b at Windows.
Using v6.5.0

**Expected behavior**
No shadows at pinned tabs same as unpinned tabs.

**Screenshots**
not OK at pinned tabs
![obrazek](https://user-images.githubusercontent.com/15554561/203487835-288ec00f-43f0-4f27-ac66-ae6f611c4c74.png)
OK at unpinned tabs
![obrazek](https://user-images.githubusercontent.com/15554561/203488461-aebd4888-f174-480e-acde-98fabb8240c1.png)

**Environment:**

 - Distribution
   - [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)  Lepton-Photon-Style.zip
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [x] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

default
</details>
 
**Additional context**

**Comment by black7375** [comment]
As originally, clipping should be applied, but it does not apply in the latest Firefox.
In the stable version Firefox, works well.
https://github.com/black7375/Firefox-UI-Fix/blob/e7d2d36591e37c2ba03afb1b96455463a663ee8e/src/tab/_connect_to_window.scss#L19-L21

![image_2022-11-24_00-02-36](https://user-images.githubusercontent.com/25581533/203580888-e17ec94d-6f4a-4807-97d1-5f6cbd2a0990.png)

---

First of all, I wrote a compatible patch. Try to apply.

![image_2022-11-24_00-04-11](https://user-images.githubusercontent.com/25581533/203580900-a087617f-630c-48d7-ae14-a060d9935acd.png)

**Comment by waclaw66** [comment]
Yes, [229d08f](https://github.com/black7375/Firefox-UI-Fix/commit/229d08f5a3be52f2445abd1aa88a20d4999aa6bf) works for me in FF 108b5.

**Comment by black7375** [comment]
Thanks for quick feedback.
