### ISSUE TITLE
Rename repo to lepton-firefox-fix/lepton-firefox

### ISSUE THREAD

**Issue by xypnox** [black7375/Firefox-UI-Fix#514]
**Is your feature request related to a problem?**
It is related to the lack of a unique name id for the project.

**The solution I'd like**

A better repo name in relation to the current naming.

**Comment by black7375** [comment]
It was made for personal use, but was later branding.
(For historical reasons, it currently has a repository name)

I am aware of the shortcomings, but I will not change it because of the path dependency because there are many users who use `git pull`.

Thank you for your good suggestion.

**Comment by xypnox** [comment]
AFAIK [Github does redirect all requests after renaming](https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository) the repo as long as another repo of the same name is not created in the same account.
Thus the users using `git pull` will not face any problems.

**Comment by black7375** [comment]
Oh, it makes sense.
After the opening, I will mention on the release where traffic is concentrated.
Let's gather opinions from the community.

**Comment by roland-rollo** [comment]
Lepton or lepton-firefox would be good. `-fix` suffix in name is to long in my opinion.

**Comment by black7375** [comment]
Voting is in progress in #525

**Comment by black7375** [comment]
[`v7.0.0` has been released](https://github.com/black7375/Firefox-UI-Fix/releases/tag/v7.0.0) and maintains its current name.
![image](https://user-images.githubusercontent.com/25581533/210136660-a221491e-909a-4d87-a9bd-9b00e2fb6c0e.png)
