### ISSUE TITLE
Active pinned tab not displaying the favicon

### ISSUE THREAD

**Issue by mooms06** [black7375/Firefox-UI-Fix#52]
**Describe the bug**
Active pinned tab not displaying the favicon

**Expected behavior**
Active pinned tab should display the favicon
**Screenshots**
![Animation](https://user-images.githubusercontent.com/25405517/120698201-fcd36c80-c4ae-11eb-9df1-2a61cce3d131.gif)

**Environment (please complete the following information):**
 - Firefox Version: [89.0]
 - OS: Windows
 - Theme:
 - Tested on those two:
https://addons.mozilla.org/firefox/addon/quantum-system-for-proton/
https://addons.mozilla.org/firefox/addon/arc-darker-theme-we/

**Comment by black7375** [comment]
This will be discussed after the 1.0 release.

Temporary solution.
https://github.com/black7375/Firefox-UI-Fix/compare/hide-closebutton-at-pinned

Duplicate #10
