### ISSUE TITLE
Curve tabs like Photon??

### ISSUE THREAD

**Issue by StormJumper** [black7375/Firefox-UI-Fix#523]
**Is your feature request related to a problem?**

Curve sexy tabs as in Photon?
**The solution I'd like**

Photon has sexy curves not square corners can this be changed?
**Screenshots or video**

https://github.com/wilfredwee/photon-australis
**Alternatives I've considered**

Photon was my goto when it first released and was pleasing to the eyes.
**Additional context**

https://github.com/wilfredwee/photon-australis

**Comment by black7375** [comment]
It is implemented in the development version. #511

---

I will close because it is duplicated with #326
