### ISSUE TITLE
Error in SCSS

### ISSUE THREAD

**Issue by BPower0036** [black7375/Firefox-UI-Fix#533]
https://github.com/black7375/Firefox-UI-Fix/blob/26e0f1e24bc922819147d3d4a2b9fea24832e559/src/tabbar/_unscroll.scss#L21
Causes issue in plain css

**Comment by black7375** [comment]
It's a [Container Queries](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries).

- `layout.css.container-queries.enabled` to `true`

---

You still need to use the flag in Firefox, but you can track in the following issues.

https://bugzilla.mozilla.org/show_bug.cgi?id=1744221
