### ISSUE TITLE
Change Tab shape

### ISSUE THREAD

**Issue by robertheadley** [black7375/Firefox-UI-Fix#54]
Is it be possible to change the tab shape and outlining stroke information?

**Comment by black7375** [comment]
I don't know what do you want, but it's possible.

**Tab Shape**
https://github.com/black7375/Firefox-UI-Fix/blob/1a345f53ec2b293952068503baa9a450fe4b2bec/userChrome.css#L183-L188

**Tab Stroke**
https://github.com/black7375/Firefox-UI-Fix/blob/1a345f53ec2b293952068503baa9a450fe4b2bec/userChrome.css#L168-L182

**Comment by black7375** [comment]
I'll assume it's solved.
