### ISSUE TITLE
Broken separator above “Select all” item in website context menu

### ISSUE THREAD

**Issue by patrik-krajcovic2** [black7375/Firefox-UI-Fix#540]
### Describe the bug

When I right-click in a page in example google.com, then the separator above “Select all” context menu item appears and after millisecond disappears.

### Expected behavior

Separator should be still above “Select all” website context menu item.

### OS

Windows 11

### Firefox Version

Firefox stable v108.0.1

### Distribution

- [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [ ] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>

**Comment by patrik-krajcovic2** [comment]
I didn't fill “user.js setup” field, because I didn't change anything and I don't know anything with this file.

**Comment by black7375** [comment]
Could you show me a screenshot even if `context menu separator` has disappeared?

**Comment by patrik-krajcovic2** [comment]
![Missing separator above select all](https://user-images.githubusercontent.com/69351811/208599878-398f6eda-a6c4-4ad1-87ca-c7c1789cd242.png)

**Comment by black7375** [comment]
It seems to be related to [TabMixPlus](https://github.com/onemen/TabMixPlus).
Let's investigate later.

**Comment by patrik-krajcovic2** [comment]
I think that it is not related to TabMixPlus, I can reproduce it even without TabMixPlus.

**Comment by patrik-krajcovic2** [comment]
But with TabMixPlus disabled, it never appears. And with TabMixPlus enabled, it appears in a millisecond and then disappears.

**Comment by black7375** [comment]
Strangely, it's not reproduced
![image](https://user-images.githubusercontent.com/25581533/208762548-000069b9-4c72-4aab-a427-eee791f6de3e.png)

**Comment by patrik-krajcovic2** [comment]
Even in Firefox without Firefox UI Fix, the separator is missing.

**Comment by black7375** [comment]
If it doesn't matter, I'll close issue.
Thank you for reporting.

**Comment by patrik-krajcovic2** [comment]
Thank you for quick response, I will file a bug in Bugzilla.
