### ISSUE TITLE
Firefox 108.0.1 breaks Tabs

### ISSUE THREAD

**Issue by XDbored1** [black7375/Firefox-UI-Fix#543]
### Describe the bug

i can't even select tabs clicking on the blank space, it only works with keyboard shortcuts or "Tree Style Tab".

windows 10 21H2

the installer just silently crashes when i try to use it, and i don't remember how to install Lepton i just used the script last time, going to have to try and disable it after a bit of reading hopefully its not too hard, i think i am going to try setting up multiple Waterfox instances instead of using Firefox for anything after shit like this.

### Expected behavior

i want to be able to see and click on my tabs in the top bar

### Screenshots

![image](https://user-images.githubusercontent.com/60820470/208620021-c00c1c07-6c6b-4f4d-8b5c-c00485d72e45.png)

### OS

Windows 10

### Firefox Version

108.0.1 

### Distribution

- [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [X] System Default
- [X] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>

**Comment by mbenguigui** [comment]
Hi had the same issue, and an update fixed it.

**Comment by black7375** [comment]
It's already patched #484
Try to use last commit or version

**Comment by XDbored1** [comment]
copy paste latest patch worked, but idk why the powershell script kept crashing after selecting a style.

**Comment by black7375** [comment]
Can you show me the command and log you entered in powershell?

**Comment by XDbored1** [comment]
i was using right click run, but i had to open Powershell the slow way to stop it automatically closing, and then for some reason the execution policy got in the way the obviously broken security was easily disabled, and now i can see this error looks like it is complaining about the profile path do i have some weird character in it or something?

C:\Users\Jacob\AppData\Roaming\Mozilla\Firefox\Profiles\rwy23kli.default-release doesn't look too weird to me

![image](https://user-images.githubusercontent.com/60820470/208789185-491a54d9-7af7-4b68-a824-b2e74c0c9ebb.png)
![image](https://user-images.githubusercontent.com/60820470/208790487-98db4f20-823c-48c4-8271-0861b9f5a5dd.png)

**Comment by XDbored1** [comment]
![image](https://user-images.githubusercontent.com/60820470/208790973-106e1366-ee10-480c-8f11-8289646520a8.png)
it gives the same error if i run it from the actual profiles folder instead of downloads

**Comment by black7375** [comment]
That's definitely weird.

---

Is the following command the same result?
```powershell
Powershell -c "Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iwr https://raw.githubusercontent.com/black7375/Firefox-UI-Fix/master/install.ps1 -useb | iex"
```

**Comment by XDbored1** [comment]
![image](https://user-images.githubusercontent.com/60820470/208791561-2d66c23c-952c-49ea-9051-9a41ecd42ea8.png)
looks like its working

**Comment by black7375** [comment]
Thank you for testing. It helped me a lot.
It seems that there is a bug with a focus on installing the network.
I'll fix the bug later.
