### ISSUE TITLE
Missing padding in overflow menu for extension icons

### ISSUE THREAD

**Issue by dserodio** [black7375/Firefox-UI-Fix#544]
### Is your feature request related to a problem?

The extension icons in the overflow menu are too close to the text.  There's 1px between the icon and the text. For standard Firefox buttons, like Firefox Account and Firefox View, the padding is bigger, and perfect IMHO.

### The solution I'd like

Some extra padding between the extension icon and the text, similar to the builtin buttons, would be nice.

Thanks!

### Screenshots or video

![image](https://user-images.githubusercontent.com/233589/208721573-0f84873d-72ce-463b-a7cf-a98b9adc078a.png)

**Comment by black7375** [comment]
What's your OS?

**Comment by dserodio** [comment]
Sorry, I'm on macOS 12.6.2 (Monterrey) and Firefox 108.0.1

**Comment by dserodio** [comment]
The items in your screenshot (Save to Pocket, History, Save page and Customize toolbar) are all builtin features, and these have a reasonable padding for me too. Did you try installing an extension and moving its button to the overflow menu to see how it's displayed?

I just updated to the latest commit and the problem is still present for extension buttons. Is there something I can do to help troubleshoot this?

**Comment by black7375** [comment]
> Did you try installing an extension and moving its button to the overflow menu to see how it's displayed?

According to the proposal, it was possible to reproduce.

**Comment by black7375** [comment]
I fixed the bugs and created a new release.
Thank you for the report.

**Comment by dserodio** [comment]
Works perfectly. Thank you for this amazing project and for fixing this issue so quickly.
