### ISSUE TITLE
Folder label in another folder becomes cutoff when font size is changed

### ISSUE THREAD

**Issue by yeahitsterry** [black7375/Firefox-UI-Fix#549]
### Describe the bug

Changing global font size in userChrome.css in Lepton Proton v6.5.2 makes folder labels/names in other folders cut off. If there is a bookmark inside the folder with a long name, the folder label won't be cut off. My other computer is using an older version with the same global font size change, and there is no issues.

### Expected behavior

Folder labels should not be cutoff unless it's a really long name, but it wasn't for me.

### Screenshots

![Capture](https://user-images.githubusercontent.com/18452857/209658382-e3468d52-8dd7-45c6-9630-13fc2a9151c9.png)

### OS

Windows 11

### Firefox Version

v108.0.1

### Distribution

- [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [X] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [ ] System Default
- [X] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### Theme - More Info

Dracula Dark Theme
https://addons.mozilla.org/en-US/firefox/addon/dracula-dark-colorscheme/

### `user.js` setup

Default user.js that include in Leptop Proton

### Additional context

The global font size I am using is:
```css
* {font-size: 0.951rem !important;}
```

**Comment by black7375** [comment]
How about putting the next code?
```css
menupopup[placespopup="true"] {
  min-width: 30px !important; /* Use your custom size */
}
```

**Comment by yeahitsterry** [comment]
Thank you for your response.

The code worked, but ideally, I'm trying to find out a method for the width to be adaptive. I will use the code for now while I try to find a fix for myself.

**Comment by black7375** [comment]
This is a temporary solution before finding the cause because it is not reproduced on my computer.

**Comment by yeahitsterry** [comment]
`.menu-iconic.bookmark-item > label {
  min-width: 1000px !important;
}`

Using the code above fixes the adaptive width and the label cutoff, but unfortunately, the arrow is cutoff/disappears now.

**Comment by yeahitsterry** [comment]
Happy to report I found a way to prevent the cutoff.
`.menu-right {
  padding-left: 3px !important; /* adjust with custom size */
}`

By increasing the padding of the arrow icon, the folder label won't get cutoff. It started cutting off at 2px based on my setup.
