### ISSUE TITLE
Pinned tabs become "x to close" when active

### ISSUE THREAD

**Issue by David263** [black7375/Firefox-UI-Fix#55]
I've installed this UI fix, but it has a really bad side effect: when a pinned tab is selected, it changes the icon to an X for closing the pinned tab. This makes it way too easy to close a pinned tab by accident, contrary to the idea that a pinned tab should be permanent.

Until you fix this, I will have to return to my previously saved profile.

**Comment by black7375** [comment]
It will probably be removed after version 1.0.
Temporary solution.
https://github.com/black7375/Firefox-UI-Fix/compare/hide-closebutton-at-pinned

Duplicate #10
