### ISSUE TITLE
Feature request: Add option to hide “Minimize”, “Maximize” and “Close” buttons

### ISSUE THREAD

**Issue by patrik-krajcovic2** [black7375/Firefox-UI-Fix#550]
### Is your feature request related to a problem?

I don't like it. Because there is better alternative, like MinMaxClose button in Firefox Scripts (https://github.com/xiaoxiaoflood/firefox-scripts).

### The solution I'd like

Add about:config option to hide the “Minimize”, “Maximize” and “Close” buttons.

**Comment by black7375** [comment]
Try to use [`v7.0.0`](https://github.com/black7375/Firefox-UI-Fix/releases/tag/v7.0.0).
