### ISSUE TITLE
Please fix the popup menu of folder in bookmark toolbar.

### ISSUE THREAD

**Issue by whileloopa** [black7375/Firefox-UI-Fix#57]
The popup menus of folders in bookmarks toolbar have different style from the popup menu of the bookmarks menu toolbar button.

**Comment by black7375** [comment]
Do you mean this menu?

![image](https://user-images.githubusercontent.com/25581533/120766593-e9a1ba80-c509-11eb-8b98-927c8cc7fbdc.png)

**Comment by kopasjat** [comment]
y

**Comment by black7375** [comment]
Now, looks like this.
![image](https://user-images.githubusercontent.com/25581533/140677736-50a27310-c044-4a05-b2af-a56b0fd607b3.png)

**Comment by kr4ssi** [comment]
Still not themed when opening the url chrome://browser/content/places/places.xhtml directly. (It's my home-page)

**Comment by Zulith** [comment]
I think this is the issue I'm having. I always have my Bookmark Toolbar enabled, with some folders and links (usually just favicons, no text) for fast/easy navigation. Problem is, the folders I put in the Bookmark Toolbar have a different theming... they are still fat and round, and don't match the theming from the Bookmarks Menu (when I press ALT to show Menu Bar, and then click Bookmarks from there, it looks TOTALLY different)

The look theming from the Bookmarks Menu is the same theming I want in the folders on my Bookmark Toolbar.

Can this please be implemented?

**Comment by black7375** [comment]
Do you have any screenshot?
I think it'll be easy to understand if there is.

**Comment by whileloopa** [comment]
To understand the problem, first of all, you have to make the bookmark toolbar visible.  The real TOOLBAR  in the main window, not the node in the Library.
Then create a folder in the bookmark toolbar. Next put some bookmarks into the folder. Finally click on the folder.

**Comment by black7375** [comment]
Listening to the explanation, it may be different for each OS.
It looks good to create a new bug issue.
