### ISSUE TITLE
Hide the Bookmarks menu and other bookmarks buttons

### ISSUE THREAD

**Issue by sedut-pank** [black7375/Firefox-UI-Fix#573]
### Is your feature request related to a problem?

Hide the Bookmarks menu and other bookmarks buttons

### The solution I'd like

How can I hide these buttons in the bookmarks panel?
Bookmarks menu and other bookmarks

![изображение](https://user-images.githubusercontent.com/120640995/211305278-80ecf584-7bea-49cc-9f2b-35dac8c1ea80.png)

**Comment by Patricek0056** [comment]
I don't know what is the bookmarks panel, probably you are thinking the library sidebar. And, you think, that they should be hidden when are empty?

**Comment by sedut-pank** [comment]
I don't need these buttons, I don't use them
Bookmarks menu and other bookmarks

How can I remove them?

All my bookmarks are in folders in the bookmarks panel

**Comment by Patricek0056** [comment]
Fine, but you are thinking, that they should be hidden when are they empty?

**Comment by sedut-pank** [comment]
> 
Yes. I think that's better.

**Comment by Patricek0056** [comment]
I can't help you, because I don't know, but I think, that this would maybe require the JavaScript. 
Just wait for official response from the main developer of Firefox UI Fix, he is expert about these things. But yeah, if they are empty, then they should be hidden, I agree with this too.

**Comment by black7375** [comment]
There is a lot of options, so it's burdensome to add.

It's a simple modification, so it's a good case to modify `userChrome.css`.
- https://github.com/black7375/Firefox-UI-Fix/blob/master/userChrome.css

```css
#BMB_bookmarksShowAllTop + menuseparator,
#BMB_bookmarksToolbar,
#BMB_unsortedBookmarks,
#BMB_mobileBookmarks {
  display: none;
}
```

**Comment by sedut-pank** [comment]
> There is a lot of options, so it's burdensome to add.
> 
> It's a simple modification, so it's a good case to modify `userChrome.css`.
> 
>     * https://github.com/black7375/Firefox-UI-Fix/blob/master/userChrome.css
> 
> 
> ```css
> #BMB_bookmarksShowAllTop + menuseparator,
> #BMB_bookmarksToolbar,
> #BMB_unsortedBookmarks,
> #BMB_mobileBookmarks {
>   display: none;
> }
> ```

It didn't work for me.
I specified this code in userChrome.css

`#BMB_bookmarksShowAllTop + menuseparator,
#BMB_bookmarksToolbar,
#BMB_unsortedBookmarks,
#BMB_mobileBookmarks {
  display: none;`

![изображение](https://user-images.githubusercontent.com/120640995/221409336-ae3a7cbb-bc40-4a43-a858-7cfbf25095d6.png)

**Comment by black7375** [comment]
You're talking about the bookmark sidebar.

Unfortunately, I don't know about to choose the element of the sidebar bookmark.
It's not a standard CSS, you may need to read the source.
I don't have the time to invest here.
https://searchfox.org/mozilla-central/search?q=moz-tree&path=&case=false&regexp=false
