### ISSUE TITLE
Feature request: turn off the rounded corners by default on Photon style

### ISSUE THREAD

**Issue by noneistaken** [black7375/Firefox-UI-Fix#578]
### Is your feature request related to a problem?

I'm currently using branch `photon-style`, and there are some rounded corners around things like the reload/back buttons and the application menu (which I assume is from Proton).

### The solution I'd like

I would prefer there was an option to make those corners to be sharp/rectangular.

### Screenshots or video

![image](https://user-images.githubusercontent.com/90960821/213346510-64ad96ee-ef98-484b-9eea-56dbfe5c8ebe.png)
![image](https://user-images.githubusercontent.com/90960821/213346686-9bb587a4-e93f-49af-a075-0fcfada985d4.png)

### Alternatives I've considered

I did try editing some of the `.css` files under the `chrome` directory myself by replacing all the occurences of `border-radius` to 0, no luck.

### Additional context

I'm using Librewolf version 109.

**Comment by Patricek0056** [comment]
Open about:config and set userChrome.rounding.square_button to true

**Comment by Patricek0056** [comment]
Or you know about these options, and you think that these options should be turned on by default with Photon style?

**Comment by noneistaken** [comment]
> Or you know about these options

Ah, no, those options flew right past my eyes when I was looking through the CSS files, my bad. Thanks for pointing me at thhe https://github.com/black7375/Firefox-UI-Fix/wiki/Options page.

> this bug should have title: “Feature request: Turn off by default the rounded corners with Photon style”

Agreed, changing.

**Comment by black7375** [comment]
The answer was late to go on vacation.

---

Panel of photon design is right angle, and button has rounding.

![image](https://user-images.githubusercontent.com/25581533/213870319-d0aef698-ab28-46a6-9821-56c69e777bf5.png)

`photon-style` aims to imitate the tab shape, and the rest plans to maintain the rounding as the defaults to maintain consistency.
Thank you for your interest in the project.
