### ISSUE TITLE
Feature request: Add support for “Reload button” and “Stop button” extensions

### ISSUE THREAD

**Issue by Patricek0056** [black7375/Firefox-UI-Fix#581]
### Is your feature request related to a problem?

These extensions have photon icons.

### The solution I'd like

They should have proton icons (“Reload” and “stop” icons)

### Additional context

Links to mentioned extensions:
https://addons.mozilla.org/en-US/firefox/addon/reload-button/
https://addons.mozilla.org/en-US/firefox/addon/stop-button/

— If you think, that these extensions nobody use, and it would be useless to support them, then you can close this issue as not planned. But over 680 people are using them (Including me).
— And if you are asking, why I didn't post feature request to the developers of these extensions instead, it is because the developers probably wouldn't respond.

**Comment by black7375** [comment]
I think it's an impossible range(requiring Javascript) in this project.

**Comment by Patricek0056** [comment]
I posted feature request to the developers of these extensions, I hope, that they will respond.

**Comment by Patricek0056** [comment]
And can you tell me why is JavaScript required?
