### ISSUE TITLE
Firefox Scripts: The “Open a new private tab” button have wrong shape

### ISSUE THREAD

**Issue by Patricek0056** [black7375/Firefox-UI-Fix#583]
### Is your feature request related to a problem?

I have Firefox Scripts installed, and I noticed, that “Open a new private tab” button have wrong shape.

### The solution I'd like

Add support for Firefox Scripts's “Open a new private tab” button, and also the support for `userChrome.tab.bottom_rounded_corner` for that button.

### Screenshots or video

Open a new tab button have right shape:
![Right button shape](https://user-images.githubusercontent.com/69351811/213904094-ea7d0826-5d29-4e1e-aec0-9f832c875c0a.png)

Open a new private tab button have wrong shape:
![Wrong button shape](https://user-images.githubusercontent.com/69351811/213904097-af503d9c-eef6-47a8-b961-ce64dab1e988.png)

### Additional context

Firefox Scripts:
https://github.com/xiaoxiaoflood/firefox-scripts/

This same bug in Firefox Scripts:
https://github.com/xiaoxiaoflood/firefox-scripts/issues/225

I quote the first comment in Firefox Scripts bug number 225:
“IMO this is feature request for “Firefox UI Fix” - CSS is injected on #tabs-newtab-button and “only” Google duplicate ID in (x)html5.”

And if JavaScript would be required, then close this issue as not planned, and please let me know why and where is JavaScript required.

**Comment by black7375** [comment]
I do not plan to support https://github.com/xiaoxiaoflood/firefox-scripts/.
But if anyone makes a contribution, I will receive it.
