### ISSUE TITLE
Feature request: Transparent menus

### ISSUE THREAD

**Issue by Patricek0056** [black7375/Firefox-UI-Fix#585]
### Is your feature request related to a problem?

It would be beautiful to have transparent menus.

### The solution I'd like

Transparent menus like in Microsoft Edge on Windows 11 (With option to “turn off” and “change transparent level”).

### Additional context

If it wouldn't be possible to implement, please tell why and how.

**Comment by 2641a40fd44383320adde4b027a1d0b03bd550** [comment]
it is possible, but it may work out of the box only on macos
linux - possible, but webrender has to be enabled, even then transparency/blur depends on your compositor
windows 10 - possible with a third-party program, but if you don't have any, the window becomes impossible to click on
windows 11 - possible with [MicaForEveryone](https://github.com/MicaForEveryone/MicaForEveryone), but there is no difference between 10 and 11 in firefox css, so, better leave that to the user

changing the opacity is not possible via an about:config preference (only booleans, as firefox css does not support getting values out of them), but a css variable (maybe depending on the os) or multiple about:config preferences (pointless)

**Comment by black7375** [comment]
I haven't worked on document yet, but your proposal is included in 8.0.0.
- `userChrome.theme.transparent.menu` to `true`

**Comment by 117649** [comment]
> I haven't worked on document yet, but your proposal is included in 8.0.0.
> 
>     * `userChrome.theme.transparent.menu` to `true`

@black7375 
After upgrade to 117 this option seems have no effect at all.

**Comment by black7375** [comment]
@117649 Thank you. I'll look into it tomorrow. (It's time to go to bed at UTC+9)
