### ISSUE TITLE
Extension menu setting buttons are misaligned

### ISSUE THREAD

**Issue by eaw4690** [black7375/Firefox-UI-Fix#603]
### Describe the bug

The extension menu setting button is not aligned if the extension does not have an "Open Extension" option, like [Tabliss](https://addons.mozilla.org/addon/tabliss).

### Expected behavior

The extension menu setting button is aligned

### Screenshots
![0](https://user-images.githubusercontent.com/104198709/216606593-232cd7f5-0741-466c-84a6-49ec4144769f.png)

If pref `userChrome.panel.full_width_padding` is set to `true`, the hover highlight is bigger than the other one and the setting button is shifted to the right: ⬇️

https://user-images.githubusercontent.com/104198709/216598590-b9fb0519-c80a-4357-b789-761488d7712f.mp4

### OS

Windows 11, Windows 10

### Firefox Version

109.0.1 (stable), 110.0b9 (beta)

### Distribution

- [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [ ] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

<details><summary><strong><code>user.js</code> setup:</strong> Default</summary><br>

```javascript
// Your settings
```
</details>

**Comment by black7375** [comment]
Patched now.
