### ISSUE TITLE
Feature request: Add option to remove the “Back”, and “Forward” buttons

### ISSUE THREAD

**Issue by Patricek0056** [black7375/Firefox-UI-Fix#608]
### Is your feature request related to a problem?

There are some alternatives, in example: Mouse buttons that have back/forward functionality (I am using these mouse buttons in 99% of cases, I am rarely using back/forward buttons in navigation bar). 

Or another alternative is: Extensions, that have back/forward functionality.

### The solution I'd like

Add about:config option to remove the “Back”, and “Forward” buttons completely from the toolbar.

### Additional context

— This was possible before the Firefox's Australis redesign.
— This is easily possible in Pale Moon.
— I don't think auto-hide, I think remove.

**Comment by black7375** [comment]
There is a lot of options, so it's burdensome to add.

It's a simple modification, so it's a good case to modify `userChrome.css`.
- https://github.com/black7375/Firefox-UI-Fix/blob/master/userChrome.css

```css
#back-button,
#forward-button {
  display: none;
}
```
