### ISSUE TITLE
Feature request: Add option to remove the “Open application menu” button

### ISSUE THREAD

**Issue by Patricek0056** [black7375/Firefox-UI-Fix#609]
### Is your feature request related to a problem?

There are some alternatives, like: Buttons in toolbars; Menu bar; Opening about pages through address bar; Opening about pages through bookmarks; Keyboard shortcuts; and also the context menu items are alternative too.

### The solution I'd like

Add about:config option to remove the “Open application menu” button.

**Comment by black7375** [comment]
What's a `Open application menu`?

**Comment by Patricek0056** [comment]
Applications menu is also called hamburger menu, but since I have CustomCSSforFx as alternative then I can close this issue as not planned.
