### ISSUE TITLE
Feature request: Add option to remove the tabs

### ISSUE THREAD

**Issue by Patricek0056** [black7375/Firefox-UI-Fix#611]
### Is your feature request related to a problem?

Maybe this sounds ridiculous, but yes, I think this seriously.

There are some alternatives, in example: Extensions like “Tree Style Tab”, “Sidebery”, etc…

### The solution I'd like

Add about:config option to remove all tabs.

### Additional context

— If this would be impossible through CSS, then close this feature request as not planned.
— If this would break the “Tree Style Tab”, or “Sidebery” extensions, then close this feature request as not planned.
— I don't think auto-hide, nor remove the tab bar, I think remove tabs.

**Comment by black7375** [comment]
It's already exist feature

- https://github.com/black7375/Firefox-UI-Fix/wiki/Options#tab-bar-1
- https://github.com/black7375/Firefox-UI-Fix/wiki/Show-Off-Your-Config#vertical-tab

**Comment by black7375** [comment]
I did not understand why you needed a feature that would not be seen only the tabs.
Isn't the feature that we have enough?

**Comment by Patricek0056** [comment]
Fine, I don't want it, this bug is invalid.
