### ISSUE TITLE
Feature request: Add square corners support for the “Tracking protection” settings tables

### ISSUE THREAD

**Issue by Patricek0056** [black7375/Firefox-UI-Fix#618]
### Is your feature request related to a problem?

The “Tracking protection” tables doesn't have support for square corners.

### The solution I'd like

Add square corners support for the “Tracing protection” tables.

### Screenshots or video

Tracking protection tables:
![Tracking Protection have rounded corners](https://user-images.githubusercontent.com/69351811/217057780-fc578431-4627-4f69-b654-312e22ee2de2.png)

**Comment by 2641a40fd44383320adde4b027a1d0b03bd550** [comment]
I'd add the option, but I wouldn't want yet another one - there are too many of them already

**Comment by Patricek0056** [comment]
> I'd add the option, but I wouldn't want yet another one

So you think, that no more `about:config` options?

**Comment by Patricek0056** [comment]
I changed the bug title and description, because some tables have already support for square corners.

**Comment by Patricek0056** [comment]
Also fixed.
