### ISSUE TITLE
Feature request: Add option to remove the incognito indicator

### ISSUE THREAD

**Issue by Patricek0056** [black7375/Firefox-UI-Fix#624]
### Is your feature request related to a problem?

I don't like it, because it is big.

### The solution I'd like

Add about:config option to remove the incognito indicator from private mode.

### Screenshots or video

I think this (in the upper right corner):
![image](https://user-images.githubusercontent.com/69351811/218046782-b944a4ea-4897-4cb8-88a5-835c05efcce0.png)

**Comment by black7375** [comment]
This is already in `dev` branch.

- https://github.com/black7375/Firefox-UI-Fix/tree/dev
- https://github.com/black7375/Firefox-UI-Fix/commit/3bfa27199fa42210f6fa7b23db90e8494cdd53da

**Comment by Patricek0056** [comment]
And how can I disable it?

**Comment by black7375** [comment]
Please wait for `v8.0.0`

**Comment by Patricek0056** [comment]
Fine, I will wait.
