### ISSUE TITLE
Active tab separator (left) become thick in Firefox 110

### ISSUE THREAD

**Issue by rockenren** [black7375/Firefox-UI-Fix#628]
### Describe the bug

After updating to Firefox 110, tab separator from left side on active tab becomes a little thicker than before (in 109).
See the screenshots below.

### Expected behavior

Tab separators for active tab should look consistent from both sides.

### Screenshots

Firefox 110:
![image](https://user-images.githubusercontent.com/11333307/218933762-c31592ac-4a2e-45d4-86a5-959d52e1c958.png)
Firefox 109:
![image](https://user-images.githubusercontent.com/11333307/218933858-88fdabd7-dc9d-434f-a23a-19e2671d5011.png)

### OS

Windows 10

### Firefox Version

110.0 

### Distribution

- [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [X] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [X] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [ ] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>

**Comment by black7375** [comment]
Many attributes has been deleted, and the code must be rewritten.
In some cases, it may be difficult to implement.

- `beforeselected-visible` https://github.com/mozilla/gecko-dev/commit/968a0377089083adb5f622ba722e0055b678d8c7
- `first-visible-tab` https://github.com/mozilla/gecko-dev/commit/f46a7d03a60748d2e6d7afdd0229e46beefb51c0
- `last-visible-tab` https://github.com/mozilla/gecko-dev/commit/0fea6a7914f2d73b60d5e09fd10937d6405b02ea
- `beforehovered` & `afterhovered` https://github.com/mozilla/gecko-dev/commit/14f328f107bda75de75585dcf34a7d11df8b7fdd
- `beforeselected-visible` https://github.com/mozilla/gecko-dev/commit/8ec7bf5a6a2a431445f7d2bf46a2fb57b7396fa9
- `first-visible-tab` https://github.com/mozilla/gecko-dev/commit/ab88c0d61de139ad088648f48f4661660b2974ca
- `last-visible-tab` https://github.com/mozilla/gecko-dev/commit/e4262236d5da3dfb14feccc37326c9cf7334fb6b
- `beforehovered`, `afterhovered` https://github.com/mozilla/gecko-dev/commit/849bfbb19b7b033552fb4fe5ac992246c07da3e0

**Comment by black7375** [comment]
It's been re-implemented, and it should now work properly.

**Comment by black7375** [comment]
Try to new realese or pull commit please.

**Comment by rockenren** [comment]
> Try to new realese or pull commit please.

Updated to 7.1.1, the issue is fixed.
Thank you.
