### ISSUE TITLE
H

### ISSUE THREAD

**Issue by bizon666** [black7375/Firefox-UI-Fix#63]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Firefox Version: [write from `about:support` - `version`]
 - OS:
   - [ ] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [ ] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

**Additional context**

**Comment by black7375** [comment]
This issue seems like a mistake.

**Comment by nonetrix** [comment]
H
