### ISSUE TITLE
Feature request: Add option to remove the “Zoom button” from the address bar

### ISSUE THREAD

**Issue by Patricek0056** [black7375/Firefox-UI-Fix#633]
### Is your feature request related to a problem?

I'm rarely using it. I'm using the “Zoom Page WE” extension button instead.

### The solution I'd like

Add `about:config` option to remove the zoom button from address bar.

### Screenshots or video

I think this button:
![The zoom button](https://user-images.githubusercontent.com/69351811/219011309-c57483f0-b6e3-4a7b-b8b4-f9bc6e6f1003.png)

**Comment by black7375** [comment]
There is a lot of options, so it's burdensome to add.

It's a simple modification, so it's a good case to modify `userChrome.css`.
- https://github.com/black7375/Firefox-UI-Fix/blob/master/userChrome.css

```css
#urlbar-zoom-button {
  display: none;
}
```
