### ISSUE TITLE
The items under the gear menu in “about:addons” should have icons

### ISSUE THREAD

**Issue by Patricek0056** [black7375/Firefox-UI-Fix#634]
### Is your feature request related to a problem?

The items under the gear menu in extensions page have no icons.

### The solution I'd like

Add icons for the items under the gear menu.

### Screenshots or video

I think this menu:
![image](https://user-images.githubusercontent.com/69351811/219035286-e33b7dbd-5b14-43e8-a24a-ea7c91bfb78e.png)

**Comment by black7375** [comment]
It's implemented now.
![image](https://user-images.githubusercontent.com/25581533/221396411-d2c8da5b-dc15-4a1d-b0ea-fb5c36e7d27a.png)
