### ISSUE TITLE
Feature request: Add square corners support for the Forget buttons

### ISSUE THREAD

**Issue by Aleksandra0056** [black7375/Firefox-UI-Fix#639]
### Is your feature request related to a problem?

The forget buttons (“Five minutes”, “Two hours”, “24 hours”) haven't support for square corners. They are rounded even with `userChrome.rounding.square_button` enabled

### The solution I'd like

Add support for square corners for the Forget buttons.

### Screenshots or video

The mentioned buttons are marked with arrow in this screenshot:
![Forget buttons should support square corners](https://user-images.githubusercontent.com/69351811/219658004-041ee28b-c587-4ab7-9b4a-2b462cafd857.png)

**Comment by 2641a40fd44383320adde4b027a1d0b03bd550** [comment]
where may I be able to find that button ? that does not look like a firefox one

**Comment by Patricek0056** [comment]
No, it is Firefox! This is not a extension.
