### ISSUE TITLE
Feature request: Add square corners support for the screenshot tool's “Cancel” button

### ISSUE THREAD

**Issue by Patricek0056** [black7375/Firefox-UI-Fix#640]
### Is your feature request related to a problem?

The “Cancel” button under the screenshot tool isn't supporting square corners. They are rounded even with `userChrome.rounding.square_button` enabled.

### The solution I'd like

Add square corners support for the “Cancel” button in the screenshot tool.

### Screenshots or video

I think this button:
![Cancel button in screenshot tool should support the square corners](https://user-images.githubusercontent.com/69351811/219659919-a30e42fb-1cc0-47ac-907c-64f6cf6f85a7.png)

**Comment by black7375** [comment]
I have added rounding support for the screenshot button. 
Thank you for waiting for a long time.
