### ISSUE TITLE
Feature request: Add square corners support for the address bar entries

### ISSUE THREAD

**Issue by Patricek0056** [black7375/Firefox-UI-Fix#642]
### Is your feature request related to a problem?

The address bar entries aren't supporting the square corners. They are rounded even with `userChrome.rounding.square_button` enabled.

### The solution I'd like

Add square corners support for the address bar entries.

### Screenshots or video

I marked the corner with an arrow:
![Address bar items should support square corners](https://user-images.githubusercontent.com/69351811/219714413-f12da820-a4ce-4d97-96b9-fa438617c8c8.png)

**Comment by black7375** [comment]
It's already added by `userChrome.rounding.square_urlView_item`

- https://github.com/black7375/Firefox-UI-Fix/pull/511
- https://github.com/black7375/Firefox-UI-Fix/commit/196fb4c23e61e33e81fe4a77141046aaa3309966
