### ISSUE TITLE
Active tab too dim

### ISSUE THREAD

**Issue by lal12** [black7375/Firefox-UI-Fix#65]
In my opinion the active tab is not bright enough (dark mode), I sometimes have issues seeing what tab is active quickly. The old photon design had a brighter highlight color. (Same issue for normal and photon-style). 

Lepton (photon-style):
![grafik](https://user-images.githubusercontent.com/14139770/120897447-7d68a900-c626-11eb-848e-dc56884c7e6a.png)

Original Photon:
![grafik](https://user-images.githubusercontent.com/14139770/120897491-c0c31780-c626-11eb-919c-d897d84f5b9c.png)

**Comment by black7375** [comment]
The toolbar color is still adjusted.
More adjustments are honestly cumbersome.

I recommend using themes.

Sample
- https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/
- https://addons.mozilla.org/af/firefox/addon/quantum-system-for-proton/

**Comment by lal12** [comment]
No, Lepton explicitly ignores what is set in the theme and uses the background color for the toolbar.
See https://github.com/black7375/Firefox-UI-Fix/blob/68378ca020e4af28bf7cb60ad16ea099f4271fe8/userChrome.css#L183

The default Firefox themes actually define a different bg color: https://searchfox.org/mozilla-central/source/browser/themes/addons/dark/manifest.json (line 20)

**Comment by black7375** [comment]
It's intentional.
Tabs and toolbars should be connected and the same color.

We can change it later to do so only with the basic themes.

**Comment by black7375** [comment]
This is original photon's theme style.
![image](https://user-images.githubusercontent.com/25581533/120899656-5dce8200-c620-11eb-993f-43208237e548.png)

We will discuss the color again in the future, and it is possible that it will be fixed then. #24
