### ISSUE TITLE
The text runs over the icon

### ISSUE THREAD

**Issue by Someone-G** [black7375/Firefox-UI-Fix#658]
### Describe the bug

The text "Close all in tabs" runs over the icon. "Lepton's photon style" with default settings.

### Screenshots

![Снимок экрана (256)](https://user-images.githubusercontent.com/108881628/222923760-8772a8a9-099c-467a-b372-834ed604f94a.png)

### OS

Windows 8

### Firefox Version

110

### Distribution

- [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [X] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [X] Light
- [X] Dark
- [X] Alpenglow (System: Light)
- [X] Alpenglow (System: Dark)
- [X] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>

**Comment by Noceti** [comment]
Same thing after updating to Firefox 110.
Windows 7.

![Bookmarks](https://user-images.githubusercontent.com/121315318/222926795-69aad469-1793-4579-a152-422199082895.jpg)

**Comment by Patricek0056** [comment]
Also, the bookmarks menu is affected:
![image](https://user-images.githubusercontent.com/69351811/224538140-8d99cb65-d47f-4b61-8304-a02b708a51bf.png)

**Comment by black7375** [comment]
Try to new version.
If not works, please tell me.

**Comment by Noceti** [comment]
It's ok now :)
