### ISSUE TITLE
Attention Icon Not Vertically Centered

### ISSUE THREAD

**Issue by ArrJay64** [black7375/Firefox-UI-Fix#660]
### Describe the bug

With the following settings configured:

user_pref("userChrome.tab.connect_to_window", true);
user_pref("userChrome.tab.lepton_like_padding", true);

The green "attention" dot on pinned tabs is partially hidden by the favicon.

![image](https://user-images.githubusercontent.com/5177839/224117993-dc2bd70e-f073-4ebc-9a98-c288b0c9a6d4.png)

### Expected behavior

The attention dot should be centered vertically between the icon and the url bar.

![image](https://user-images.githubusercontent.com/5177839/224118633-48a590e5-4f37-44cf-93d5-928fc1735e0a.png)

### Screenshots

Current:
![image](https://user-images.githubusercontent.com/5177839/224117993-dc2bd70e-f073-4ebc-9a98-c288b0c9a6d4.png)

Proposed:
![image](https://user-images.githubusercontent.com/5177839/224118633-48a590e5-4f37-44cf-93d5-928fc1735e0a.png)

### OS

Windows 11

### Firefox Version

111.0

### Distribution

- [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [ ] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>
user_pref("userChrome.tab.connect_to_window", true);<br>
user_pref("userChrome.tab.lepton_like_padding", true);
</details>

**Comment by ShailikaS** [comment]
If this issue is still there, Can I work on this issue?

**Comment by black7375** [comment]
I forgot recently because I was busy. I'll check it!!

**Comment by black7375** [comment]
@ShailikaS Hello, it seems to work well in my environment.
Could you tell me your browser version and OS information?

![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/3639fa22-4463-46e8-94cb-f3690e8f0c75)
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/a4450219-c216-4d7e-8518-b2244846e9a5)

**Comment by ShailikaS** [comment]
@black7375 Hello, Now It's working fine for me Thanks.

**Comment by black7375** [comment]
@ShailikaS I think this issue can be closed.
Please let me know if you have another problem!!
