### ISSUE TITLE
Several glitched checkboxes in the Waterfox browser's about:preferences

### ISSUE THREAD

**Issue by Patricek0056** [black7375/Firefox-UI-Fix#663]
### Describe the bug

See the https://github.com/black7375/Firefox-UI-Fix/issues/600 and https://github.com/black7375/Firefox-UI-Fix/issues/637 for more details.

Sorry for lack of details, but I'm hurry.

### Expected behavior

These checkboxes should be in circular shape, because they are different.

### Screenshots

![Applications glitched checkboxes](https://user-images.githubusercontent.com/69351811/224475368-534c376e-e688-48db-be63-0f4576ba2357.png)
-------------------------
![Bookmarks toolbar postition glitched checkboxes](https://user-images.githubusercontent.com/69351811/224475369-c2e73bd3-6827-46fb-a985-e1e4136342ec.png)
-------------------------
![Dynamic themes glitched checkboxes](https://user-images.githubusercontent.com/69351811/224475374-847cddcd-d5cf-4f92-ab73-44269ac3c4a2.png)
-------------------------
![HTTPS-only glitched checkboxes](https://user-images.githubusercontent.com/69351811/224475377-a5535a4a-4332-4dce-b531-90050e4b44b6.png)
-------------------------
![Privacy glitched checkboxes](https://user-images.githubusercontent.com/69351811/224475380-2942b7bd-e136-4652-a618-e3ef026843a9.png)
-------------------------
![Search bar glitched checkboxes](https://user-images.githubusercontent.com/69351811/224475382-452801d8-d4f6-40ac-9249-ae55aa2cf604.png)
-------------------------
![Tab bar position glitched checkboxes](https://user-images.githubusercontent.com/69351811/224475389-18acea6c-7650-46ed-bed1-c32846364657.png)
-------------------------
![Updates glitched checkboxes](https://user-images.githubusercontent.com/69351811/224475391-43ab995a-d519-4179-b9a3-5046b3c31f46.png)
-------------------------
![Web appeareance glitched checkboxes](https://user-images.githubusercontent.com/69351811/224475393-f216b7c8-c876-43ca-8a81-4f483f53be08.png)

### OS

Windows 11

### Firefox Version

G5.1.3

### Distribution

- [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [X] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [X] Light
- [X] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [ ] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// I don't know, because I installed this yesterday, sorry.
```
</details>

**Comment by Patricek0056** [comment]
Now I found out, that I don't have the user.js file in the Waterfox.

**Comment by black7375** [comment]
I think waterfox team should update the theme.
