### ISSUE TITLE
Several square corners bugs in the Waterfox

### ISSUE THREAD

**Issue by Patricek0056** [black7375/Firefox-UI-Fix#664]
### Describe the bug

I found, that some `about:preferences` entries in the Waterfox aren't supporting the square corners.
(The “Find in Settings” and sidebar search fields are affected too)

I don't have the user.js file from Waterfox, but I'm sure, that all square corners settings are applied.

See also: https://github.com/black7375/Firefox-UI-Fix/issues/645

### Expected behavior

The mentioned entries in the `about:preferences` in the Waterfox should support the square corners.

### Screenshots

Search field:

![Field in the Applications isn't supporting square corners](https://user-images.githubusercontent.com/69351811/224476411-549819ed-5d8b-4155-9d2d-934552172ab5.png)
-------------------------
Web appearance buttons:

![Web appearance buttons aren't supporting the square corners](https://user-images.githubusercontent.com/69351811/224476416-ab8abe5c-fd2c-4b74-a5ae-6d7b50475bd3.png)
-------------------------
This table:

![Search Shortcuts table aren't supporting the square corners](https://user-images.githubusercontent.com/69351811/224476418-e6bd066a-7baf-4305-a425-85eb9e7f7541.png)
-------------------------
Other tables:

![First table in the Certificate manager](https://user-images.githubusercontent.com/69351811/224476420-4937a81a-9c62-4d9c-aa2b-efa475e2f901.png)

![Second table in the Certificate manager](https://user-images.githubusercontent.com/69351811/224476421-0cf47cfb-be43-4c9c-ba31-40aa5cdc1384.png)

![Third table in the certificate manager](https://user-images.githubusercontent.com/69351811/224476423-f30ed1f2-96d7-4d12-84bc-295bec6daea4.png)

### OS

Windows 11

### Firefox Version

G5.1.3

### Distribution

- [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [X] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [X] Light
- [X] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [ ] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>

**Comment by Patricek0056** [comment]
I want to tell you, that I don't use the Waterfox, I don't have it set as the default browser, but I have it installed only for testing purposes (Testing purposes like reporting issues, testing other features…).

**Comment by black7375** [comment]
I think waterfox team should update the theme.
