### ISSUE TITLE
Fix bug

### ISSUE THREAD

**Issue by damonmitchellsr1** [black7375/Firefox-UI-Fix#67]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Firefox Version: [write from `about:support` - `version`]
 - OS:
   - [ ] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [ ] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

**Additional context**
Fix bug

**Comment by black7375** [comment]
This issue seems mistake

**Comment by damonmitchellsr1** [comment]
Update

**Comment by black7375** [comment]
what bugs?
