### ISSUE TITLE
Photon-styled navigation button doesn't work

### ISSUE THREAD

**Issue by ryenyuku** [black7375/Firefox-UI-Fix#671]
### Describe the bug

Applying `userChrome.combined.nav_button` along with `userChrome.combined.sub_button.as_normal` does not give the expected photon-ish navigation button appearance and instead will still combine the back and forward navigation button.

### Expected behavior

Give the photon-ish navigation button just like in #511 at the "Photon with multirow" section.

### OS

Linux

### Firefox Version

111.0.1

### Distribution

- [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [X] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [ ] System Default
- [X] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### Theme - More Info

[Matte Black Green](https://addons.mozilla.org/en-US/firefox/addon/matte-black-green)

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// == Theme Distribution Settings ==============================================
user_pref("userChrome.tab.connect_to_window",          true); // Original, Photon
user_pref("userChrome.tab.color_like_toolbar",         true); // Original, Photon

user_pref("userChrome.tab.lepton_like_padding",       false); // Original
user_pref("userChrome.tab.photon_like_padding",        true); // Photon

user_pref("userChrome.tab.dynamic_separator",         false); // Original, Proton
user_pref("userChrome.tab.static_separator",           true); // Photon
user_pref("userChrome.tab.static_separator.selected_accent", false); // Just option

user_pref("userChrome.tab.newtab_button_like_tab",    false); // Original
user_pref("userChrome.tab.newtab_button_smaller",      true); // Photon
user_pref("userChrome.tab.newtab_button_proton",      false); // Proton

user_pref("userChrome.icon.panel_full",               false); // Original, Proton
user_pref("userChrome.icon.panel_photon",              true); // Photon

// Original Only
user_pref("userChrome.tab.box_shadow",                false);
user_pref("userChrome.tab.bottom_rounded_corner",     false);

// Photon Only
user_pref("userChrome.tab.photon_like_contextline",    true);
user_pref("userChrome.rounding.square_tab",            true);

// == Theme Custom Settings ====================================================
// -- User Chrome --------------------------------------------------------------
user_pref("userChrome.decoration.panel_button_separator",   true);
user_pref("userChrome.decoration.panel_arrow",              true);

user_pref("userChrome.combined.nav_button",                 true);
user_pref("userChrome.combined.sub_button.as_normal",       true);

user_pref("userChrome.padding.urlView_expanding",           true);
user_pref("userChrome.padding.urlView_result",              true);
user_pref("userChrome.padding.toolbar_button.compact",      true);

user_pref("userChrome.urlView.always_show_page_actions",    true);
user_pref("userChrome.urlView.move_icon_to_left",           true);

user_pref("userChrome.rounding.square_panel",               true);
user_pref("userChrome.rounding.square_panelitem",           true);

user_pref("userChrome.panel.full_width_separator",          true);
user_pref("userChrome.panel.full_width_padding",            true);
```
</details>

**Comment by ryenyuku** [comment]
Looks like the culprit is in https://github.com/black7375/Firefox-UI-Fix/blob/master/css/leptonChrome.css#L8186 where an incorrect check is being done, and will only give the photon-ish nav button if `userChrome.combined.urlbar.home_button` is enabled too

**Comment by black7375** [comment]
Try to use new version please!!

**Comment by ryenyuku** [comment]
> Try to use new version please!!

Yeah, the latest version fixed it. Thanks for the patch 👍🏻
