### ISSUE TITLE
Add icon for `Reveal Password` option in the context menu

### ISSUE THREAD

**Issue by eaw4690** [black7375/Firefox-UI-Fix#672]
### Is your feature request related to a problem?

Mozilla has just added/enabled a context menu option to reveal passwords in Firefox 112. If the password field is right-clicked, it will show a `Reveal Password` option in the context menu.

[v112 Nightly release notes](https://www.mozilla.org/en-US/firefox/112.0a1/releasenotes/)
[v112 Beta release notes](https://www.mozilla.org/en-US/firefox/112.0beta/releasenotes/)
> Right-clicking on password fields now shows an option to reveal the password.

### The solution I'd like

Add an icon for the `Reveal Password` option in the context menu when right-clicked on the password field.

### Screenshots or video

[Sample web page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password)

![1](https://user-images.githubusercontent.com/104198709/229082580-9dedead1-e6e9-4648-9397-7dbcf3bbadc5.png)

### Additional context

It's possible to enable the context menu option in `about:config` on Firefox 111 and below by setting `layout.forms.reveal-password-context-menu.enabled` to `true`.
https://bugzilla.mozilla.org/show_bug.cgi?id=1816988

**Comment by black7375** [comment]
Thank you for the good information. 
It' will be provide at next release.
![image](https://user-images.githubusercontent.com/25581533/229116230-77b879f7-249d-46b2-b8c2-42f78e8cff73.png)
