### ISSUE TITLE
Feature request: Add icon for the “Connect another device…” item

### ISSUE THREAD

**Issue by Patricek0056** [black7375/Firefox-UI-Fix#676]
### Is your feature request related to a problem?

The “Connect another device…” item in the Profile button doesn't have an icon.

### The solution I'd like

Add icon for the “Connect another device…” item.

### Screenshots or video

![image](https://user-images.githubusercontent.com/69351811/231993366-88ec8300-5d55-4f57-83bb-7670e11be90e.png)
(Just ignore my e-mail address in this screenshot)

**Comment by black7375** [comment]
This was a bug that was created by the icon disappearing from the Firefox and just handled it.
https://github.com/mozilla/gecko-dev/commit/3f431af957c1bc73cdf587555ae95dedb2097be2

**Comment by Patricek0056** [comment]
Thank you for response. Sorry, I didn't knew, that the icon was disappearing.
