### ISSUE TITLE
Use the “Code” icon for View Page Source

### ISSUE THREAD

**Issue by Patricek0056** [black7375/Firefox-UI-Fix#683]
### Is your feature request related to a problem?

I don't like the icon which is using the View Page Source (I think the icon looks like file with magnifier).

### The solution I'd like

It would be better to change that icon to the code icon.

I think, code icon in this style: </>

### Screenshots or video

The code icon screenshot:
![image](https://user-images.githubusercontent.com/69351811/232426152-55ed3e3a-875d-4bf2-8298-30b6ad496220.png)

The original icon which I don't like:
![image](https://user-images.githubusercontent.com/69351811/232427037-de08a2aa-87e9-4487-823c-85fdf2b13b68.png)

### Additional context

Inspiration: https://addons.mozilla.org/en-US/firefox/addon/view-page-source-button/

**Comment by Patricek0056** [comment]
If you like this idea of code icon for View Page source, then can I fix this issue myself? I think, that it wouldn't be difficult. 

Also, another problem is, that the “Syntax Highlighting” icon needed to be changed too.

**Comment by black7375** [comment]
I will not change the icon of `View page source` and not change.
However, `Syntax Highlighting` has the intention to change it later.

**Comment by Patricek0056** [comment]
Fine, I'm closing this.
