### ISSUE TITLE
Insecure password warning popup text is unreadable on certain themes

### ISSUE THREAD

**Issue by eaw4690** [black7375/Firefox-UI-Fix#686]
### Describe the bug

If you click on a password field on an insecure website, the popup text is unreadable based on the theme.
[Sample web page here](http://www.passwordmeter.com/)

### Expected behavior

Insecure password warning popup text must be readable on certain themes

### Screenshots

Without Lepton (Dark and dark-based themes)
![original_insecure_password_warining_dark](https://user-images.githubusercontent.com/104198709/232832377-6995d90e-ce3d-49bc-a9e2-96e4df9ba8fa.png)

System theme (dark)
![insecure_password_warining_system_dark](https://user-images.githubusercontent.com/104198709/232833428-f6fb0382-d0e7-4dff-a362-9ff7e74cd6d7.png)

Dark theme
![insecure_password_warining_dark](https://user-images.githubusercontent.com/104198709/232832362-be3edd3d-04a3-4e64-8802-c883494f0f9d.png)

Firefox Alpenglow (Dark)
![insecure_password_warining_alpenglow_dark](https://user-images.githubusercontent.com/104198709/232832384-ac5e791b-0ae2-4e52-9042-a6d4f1d338b3.png)

Activist – Bold
![insecure_password_warining_activist_bold](https://user-images.githubusercontent.com/104198709/232832393-d97558b5-b2cd-4298-9c23-f07ea60e64d2.png)

### OS

Windows 11, Windows 10

### Firefox Version

v112.0.1

### Distribution

- [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [X] Dark
- [ ] Alpenglow (System: Light)
- [X] Alpenglow (System: Dark)
- [X] System Default
- [X] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### Theme - More Info

Activist – Bold: https://addons.mozilla.org/en-US/firefox/addon/activist-bold_/

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Default settings used
```
</details>

**Comment by black7375** [comment]
Thanks for bug report :+1: 
It will be looks like this now.

Light
![image](https://user-images.githubusercontent.com/25581533/232938992-479b46a8-f596-48a2-bfcc-6def8b976200.png)

Dark
![image](https://user-images.githubusercontent.com/25581533/232939080-eb795f85-ae3c-4af9-afbb-1c92442e0028.png)

Alpenglow (Dark)
![image](https://user-images.githubusercontent.com/25581533/232939193-03c21567-cab2-43cd-ba6d-17b278c1e954.png)
