### ISSUE TITLE
Replace the “Shortcuts” icon in the Home settings

### ISSUE THREAD

**Issue by Patricek0056** [black7375/Firefox-UI-Fix#693]
### Is your feature request related to a problem?

There is a new (and better) icon in the PDF reader. I don't like the thick icon in the Home section in `about:preferences`.

**Replace this icon…**

![Old shortcuts icon](https://user-images.githubusercontent.com/69351811/233144266-d04883b3-9117-484b-800b-8f1e84791e80.png)

### The solution I'd like

**…With this icon:**

![Replace the Shortcuts icon with this icon](https://user-images.githubusercontent.com/69351811/233144333-45ba80ae-c530-4c7f-991b-5ac2687ad23b.png)

### Additional context

— I'm using Firefox 112.0.1, so the new icons in PDF reader are not available in the ESR I think.

**Comment by Patricek0056** [comment]
By the way, some of these new icons in the PDF were created thanks to me (because I reported that feature request in BugZilla).

**Comment by black7375** [comment]
I don't think current icon is bad.

**Comment by Patricek0056** [comment]
But why? The newer icon have thinner lines (and the old one is very thick).
