### ISSUE TITLE
Feature request: Add icon for the “Search history” item

### ISSUE THREAD

**Issue by Patricek0056** [black7375/Firefox-UI-Fix#697]
### Is your feature request related to a problem?

In the latest Nightly, there is a new “Search history” item, and this item doesn't have an icon.

### The solution I'd like

Add icon for the “Search history” item. I'm proposing the magnifier icon (Like in the “Find in page…”)

### Screenshots or video

As you see, there is no icon for this item:
![The new Search History item doesn't have an icon](https://user-images.githubusercontent.com/69351811/235047846-2dbe55b5-bc62-4d36-acff-80386f5b1648.png)

**Comment by black7375** [comment]
It's reflected [v7.3.1](https://github.com/black7375/Firefox-UI-Fix/releases/tag/v7.3.1)
