### ISSUE TITLE
Close button on clipped tabs ff113

### ISSUE THREAD

**Issue by gedem1** [black7375/Firefox-UI-Fix#704]
### Describe the bug

Hello. After updating to ff113 i noticed that close buttons disappeared from clipped tabs.

### Expected behavior

I fixed this by replacing:
```
	/** Clipped tabs - Show close button at hover *********************************/
@supports -moz-bool-pref("userChrome.tab.close_button_at_hover") {
  #tabbrowser-tabs[closebuttons="activetab"]
    > #tabbrowser-arrowscrollbox
    > .tabbrowser-tab:not([pinned])
    > .tab-stack
    > .tab-content
    > .tab-close-button:not([selected="true"]) {
    display: -moz-inline-box !important;
  }
```
With:
```
	/** Clipped tabs - Show close button at hover *********************************/
@supports -moz-bool-pref("userChrome.tab.close_button_at_hover") {
  #tabbrowser-tabs[closebuttons="activetab"]
    > #tabbrowser-arrowscrollbox
    > .tabbrowser-tab:not([pinned])
    > .tab-stack
    > .tab-content
    > .tab-close-button:not([selected="true"]) {
    display: flex !important; /**THIS IS THE FIX**/
  }
```

### Screenshots

![2023_05_20_02_05_38_](https://github.com/black7375/Firefox-UI-Fix/assets/134109505/273919f7-9039-4a9a-aadd-bb382f86307a)

### OS

Windows 10

### Firefox Version

113

### Distribution

- [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [X] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
 user_pref("userChrome.tab.close_button_at_hover.always",    true); // Need close_button_at_hover
```
</details>

### Additional context

https://www.reddit.com/r/FirefoxCSS/comments/11odffm/psa_incoming_changes_to_default_element/

**Comment by black7375** [comment]
First of all, thank you for suggesting issue and solution!!
This issue was processed in #696 and was released.

You can update to `git pull`/script or download the latest version (V7.3.0).
