### ISSUE TITLE
Last update seems to have broken pinned tabs

### ISSUE THREAD

**Issue by junkblocker** [black7375/Firefox-UI-Fix#706]
### Describe the bug

The pinned tabs other than the first one are rendered as a blank space.

### Expected behavior

Each pinned tab should render.

### Screenshots

![Screenshot_20230525_180745](https://github.com/black7375/Firefox-UI-Fix/assets/20190/e6061e3c-4741-4744-8983-b6f2a859ae3f)

### OS

Linux

### Firefox Version

113.0.1

### Distribution

- [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [X] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [X] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>

**Comment by black7375** [comment]
Hello, Are you try to latest version?
- https://github.com/black7375/Firefox-UI-Fix/releases/tag/v7.3.1

**Comment by junkblocker** [comment]
That works fine for me.  9f12ff2 was broken. My script has been pulling the latest HEAD on master, should I switch to only using releases?

**Comment by black7375** [comment]
Ok, I tested it in Linux environment and should work well in https://github.com/black7375/Firefox-UI-Fix/commit/396f06b45c4bf33fd2b68ddf86373395b95b4401.
I had a lot of work to do last time that I committed without testing it enough.

In general, the commit of the master should be stable because it is used to fix bugs.
This is an exceptional situation.

**Comment by junkblocker** [comment]
Thanks. Confirming that 396f06b (master) works too.
