### ISSUE TITLE
Could Firefox UI FIX Support Floorp ?

### ISSUE THREAD

**Issue by surapunoyousei** [black7375/Firefox-UI-Fix#710]
### Is your feature request related to a problem?

Floorp's code is proprietary, and some codes are missing, so Floorp makes additions and adjustments.

### The solution I'd like

I don't want to force you to do this, but I would appreciate it if you could add the specific code.

My solution would be to create CSS that loads when Floorp-specific settings are enabled.

### Screenshots or video

![image](https://github.com/black7375/Firefox-UI-Fix/assets/73892113/47295d76-0b5f-4a26-a3df-28d0744e0578)

### Alternatives I've considered

Modify by Floorp's developer

**Comment by black7375** [comment]
Can I see what code it is?
I think it can be supported if it doesn't cause side effects to Firefox.

Even if there is a side effect, there is a way.
As far as I know, waterfox has its own media query.
If you have a media query or a unique `about:config` value that runs only on Floorp, you can show it correctly.

**Comment by surapunoyousei** [comment]
```
  #usercssloader-menu {
    --menuitem-image: url("chrome://browser/skin/lepton/developer.svg");
  }
  #rebootappmenu {
    list-style-image: url("chrome://browser/skin/lepton/refresh-cw.svg");
  }
  #openprofiledir {
    list-style-image: url("chrome://browser/skin/lepton/folder.svg");
  }
  ```
  
  このような CSS が必要です。アイコンの欠落箇所はまだあります。。。

Floorp has its own status bar implemented by Floorp, but without icons. Because I don't have the technology to create icons, which is embarrassing.

**Comment by surapunoyousei** [comment]
Thank you.

**Comment by surapunoyousei** [comment]
Floorp 11 has a native implementation of vertical tabs. Please let me know if there is anything you don't like about the design.  Rework with respect to Firefox UI Fix

**Comment by black7375** [comment]
Added support for Floorp.
Where can I try Floorp 11?

**Comment by surapunoyousei** [comment]
https://github.com/surapunoyousei/Floorp/actions/runs/5295413586

This is Actions run. you can download app

windows: https://github.com/surapunoyousei/Floorp/suites/13670804810/artifacts/755499185
mac: https://github.com/surapunoyousei/Floorp/suites/13670804810/artifacts/755499186
linux aarch64: https://github.com/surapunoyousei/Floorp/suites/13670804810/artifacts/755499180
linux 86_64: (preparing)

**Comment by black7375** [comment]
## Feedback

`Workspace` and `Vertical tabbar` are very cool !!
Browser content rounding looks like Edge and Arc browser, is also impressive.

Here are some feedback:

### 1. Vertical tabbar supports

There is a problem with the bottom round of the tab, so I added a code for compatibility. https://github.com/black7375/Firefox-UI-Fix/commit/3058069e0ae76614ffbd1cb166997ec79807a078

### 2. Sidebar

Firefox's sidebar feature was not available.

Try to add 
- https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/
- https://addons.mozilla.org/en-US/firefox/addon/sidebery/
- https://addons.mozilla.org/en-US/firefox/addon/sidebar-note/

### 3. Button background color

The background color of the button is too dark when the `system default theme`.

![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/6cc2a653-7ee7-4ca7-a52d-60535d6faa03)

### 4. Extension page

I think it would be consistent if the side menu had a bar like `General` in the settings.

![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/fed59bf4-36f8-4a8f-8c87-1f372959b9f4)
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/6f90f0af-7aa6-4a56-833a-1402cae3b5a4)

### 5. Panel Setting

If you set `userChrome.icon.full` to `true`, set `userChrome.icon.panel_photon` to `false`.
If both are true, problems may occur in some layouts.

https://github.com/surapunoyousei/Floorp/blob/3da07d5fe6715309b1f40c899d4e8db146f07968/floorp/browser/app/profile/000-floorp.js#L345

### 6. Workspace Name

Putting the space seems to have a problem.

**Comment by surapunoyousei** [comment]
I see. I use Dark mode.  I didn't test it. we are sry.

1. Vertical tabbar supports:

Thanks !

2. Sidebar

If you use verticaltabbar,  Cannot use sidepanel addons.

4. Extension page

I will add it.

5. Panel Setting

I will change default preferences.

6. Workspace Name

sry, I cannnot understand. what means?

**Comment by surapunoyousei** [comment]
I've identified a few issues and will work to fix them!

Thank you for your feedback.

**Comment by black7375** [comment]
I'm really enjoying the experience, great project!

**Comment by surapunoyousei** [comment]
Fixed !

**Comment by black7375** [comment]
Quick commit!! Thanks.

**Comment by surapunoyousei** [comment]
Thank you for v7.4. 0 Release, I will replace Floorp's file.

**Comment by Illusiveman931** [comment]
> Floorp's code is proprietary

I thought Floorp free and opensource isn't it?

**Comment by black7375** [comment]
@Illusiveman931 Yes. floorp browser is opensource.
https://github.com/Floorp-Projects/Floorp

**Comment by Illusiveman931** [comment]
you are right but I just don't understand why the main developer of floorp made this confusing statement

**Comment by black7375** [comment]
In the past, Lepton had some problems because it did not consider compatibility and icons for floorp.

We are now well supported through cooperation with the floorp maintainer.

**Comment by Illusiveman931** [comment]
thanks for the answer, even if it doesn’t explain surapunoyousei’s statement, I guess it's not that important, sorry for disturbing you
