### ISSUE TITLE
Wrong sidebar animation

### ISSUE THREAD

**Issue by rehenoakoton** [black7375/Firefox-UI-Fix#714]
### Describe the bug

The animation of closing the sidebar does not depend on its actual width. Depending on the width of the sidebar, the animation ends sooner or later than the sidebar reaches the end of the window

### Expected behavior

Moving the sidebar to the window border

### Screenshots

https://github.com/black7375/Firefox-UI-Fix/assets/135052198/decd7687-e654-4fb2-b7fa-28fd3dda41ed

### OS

Linux

**Comment by black7375** [comment]
Are you investigating this problem and do you mean when a sidebar is created?

https://github.com/black7375/Firefox-UI-Fix/assets/25581533/0e8498f4-6b37-4d3a-9b19-ed703174e619

**Comment by black7375** [comment]
I think this issue was open enough.
