### ISSUE TITLE
Edit bookmark url in blue star menu doesn't work

### ISSUE THREAD

**Issue by Wronschien** [black7375/Firefox-UI-Fix#715]
### Describe the bug

In 'userChrome.css' the following code is provided as an option :
`#editBMPanel_locationRow {
  visibility: visible !important;
}`

But there was a code change in Firefox a few versions ago and this doesn't work anymore. Fortunately the problem has been solved on [reddit](https://old.reddit.com/r/FirefoxCSS/comments/104xehv/no_longer_displaying_url_field_in_the_edit_this/), the new correct syntax is :
`.editBMPanel_locationRow {
  display: initial !important;
}`

### Expected behavior

Use the new syntax to get it working again.

### OS

Windows 10

### Firefox Version

113.0.2

### Distribution

- [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [ ] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>

**Comment by black7375** [comment]
Thank you for reporting !! It is reflected in code, so close.
