### ISSUE TITLE
Reorganize files

### ISSUE THREAD

**Issue by hiltonjanfield** [black7375/Firefox-UI-Fix#72]
To simplify installation, it would be nice if the downloaded zip was organized so that the archive could simply be extracted to the profile folder. In other words, leave user.js in root, move everything else to a chrome/ folder.

**Comment by black7375** [comment]
https://github.com/black7375/Firefox-UI-Fix/pull/17#issuecomment-851834568

I've seen comments on Reddit in the past about using `git clone` to install.

---

But, At release, structure will be automatically cleaned up.
https://github.com/black7375/Firefox-UI-Fix/blob/master/.github/workflows/release.yml
