### ISSUE TITLE
Padding between pinned and unpinned tabs is visible again

### ISSUE THREAD

**Issue by filips123** [black7375/Firefox-UI-Fix#720]
### Describe the bug

Since a few days on Nightly, padding between last pinned tab and the first unpinned one is again larger and more noticeable.

### Expected behavior

Padding should be smaller/not noticeable, like it was before.

### Screenshots

![slika](https://github.com/black7375/Firefox-UI-Fix/assets/16626308/bd447e07-87ca-4d17-a9e6-63c52a67edbc)

### OS

Windows 10

### Firefox Version

116.0a1 (20230609214634)

### Distribution

- [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [X] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [X] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [ ] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```
userChrome.compatibility.os	true	
userChrome.compatibility.theme	true	
userChrome.decoration.animate	true	
userChrome.decoration.cursor	true	
userChrome.decoration.download_panel	true	
userChrome.decoration.field_border	true	
userChrome.fullscreen.overlap	true	
userChrome.fullscreen.show_bookmarkbar	true	
userChrome.icon.context_menu	true	
userChrome.icon.global_menu	true	
userChrome.icon.global_menubar	true	
userChrome.icon.library	true	
userChrome.icon.menu	true	
userChrome.icon.panel	true	
userChrome.icon.panel_full	true	
userChrome.icon.panel_photon	false	
userChrome.icon.panel_sparse	false	
userChrome.padding.bookmark_menu	false	
userChrome.padding.bookmarkbar	false	
userChrome.padding.global_menubar	false	
userChrome.padding.infobar	true	
userChrome.padding.menu	false	
userChrome.padding.navbar_width	true	
userChrome.padding.panel	false	
userChrome.padding.popup_panel	true	
userChrome.padding.tabbar_height	true	
userChrome.padding.tabbar_width	true	
userChrome.padding.toolbar_button	true	
userChrome.padding.urlbar	false	
userChrome.rounding.square_tab	false	
userChrome.tab.bar_separator	false	
userChrome.tab.bottom_rounded_corner	false	
userChrome.tab.box_shadow	false	
userChrome.tab.close_button_at_hover	true	
userChrome.tab.color_like_toolbar	false	
userChrome.tab.connect_to_window	false	
userChrome.tab.container	true	
userChrome.tab.crashed	true	
userChrome.tab.dynamic_separator	true	
userChrome.tab.dynamic_separtor	true	
userChrome.tab.lepton_like_padding	false	
userChrome.tab.letters_cleary	true	
userChrome.tab.multi_selected	true	
userChrome.tab.newtab_button_like_tab	false	
userChrome.tab.newtab_button_proton	true	
userChrome.tab.newtab_button_smaller	false	
userChrome.tab.photon_like_contextline	false	
userChrome.tab.photon_like_padding	false	
userChrome.tab.pip	true	
userChrome.tab.sound_hide_label	true	
userChrome.tab.sound_with_favicons	true	
userChrome.tab.static_separator	false	
userChrome.tab.static_separator.selected_accent	false	
userChrome.tab.unloaded	true	
userChrome.tabbar.as_titlebar	false	
userChrome.theme.built_in_contrast	true	
userChrome.theme.fully_color	true	
userChrome.theme.fully_dark	true	
userChrome.theme.proton_chrome	true	
userChrome.theme.proton_color	true	
userChrome.theme.system_default	true
```
</details>

### Additional context

This is probably because of a change in recent Firefox Nightly that replaced [`[first-visible-unpinned-tab]` selector with `:nth-child`](https://bugzilla.mozilla.org/show_bug.cgi?id=1837174), so CSS does not match the correct tab anymore. So, everything that references `first-visible-unpinned-tab` needs to be changed to use `:nth-child`. There probably also needs to be some additional work to keep it compatible with current stable release which still uses the original selector.

**Comment by black7375** [comment]
It hasn't been distributed in my nightly yet, so I'll test it and commit it after it's reproduced.

**Comment by black7375** [comment]
I applied a commit !! Thank you for the detailed report.
