### ISSUE TITLE
Install Script doesn't detect the Microsoft Store version of Firefox

### ISSUE THREAD

**Issue by KibSquib48** [black7375/Firefox-UI-Fix#729]
### Describe the bug

I tried using the install script in powershell to install the theme but it gave me an error saying it couldn't find the profile dir. I think it's because I installed Firefox through the Microsoft Store, which is packaged as an MSIX and might not have all of its folders available in the same place as unpackaged Firefox.

### Expected behavior

I expected it to find the profile dir and install

### Screenshots

![image](https://github.com/black7375/Firefox-UI-Fix/assets/33189136/40b89736-c544-432e-96d0-e026714f2c90)

### OS

Windows 11

### Firefox Version

v114.0.2

### Distribution

- [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [X] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

**Comment by black7375** [comment]
Thank you. Can you show me a `about:support`?
In my environment, it works well.

![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/559b5964-f475-4136-b941-a2ca8277eb59)

Perhaps win11 may be different.

**Comment by KibSquib48** [comment]
`about:support` gives me this
![image](https://github.com/black7375/Firefox-UI-Fix/assets/33189136/b9a7ff8f-39cd-4e99-82dc-805b246b9238)

but when I click open folder Explorer gives me this
![image](https://github.com/black7375/Firefox-UI-Fix/assets/33189136/e5701b96-ca93-4db3-b7d4-46d9d81b1101)

**Comment by black7375** [comment]
It seems to be a problem from Windows.
When searching, the following solution comes out:

- https://techcult.com/fix-desktop-refers-to-a-location-that-is-unavailable/
- https://recoverit.wondershare.com/location-is-not-available-error-in-windows-.html
- https://www.easeus.com/computer-instruction/fix-desktop-refers-to-a-location-that-is-unavailable.html

**Comment by black7375** [comment]
First of all, it doesn't seem to be a problem of scripts, so I'll close the issue.
