### ISSUE TITLE
I think there should be a bar indicating the selected tab, like in Photon.

### ISSUE THREAD

**Issue by NeoDishrag** [black7375/Firefox-UI-Fix#73]
Title. Right now it's a little difficult to tell the selected tab from other tabs.

**Comment by black7375** [comment]
You can use photon-style :smile: 
https://github.com/black7375/Firefox-UI-Fix/tree/photon-style

**Comment by NeoDishrag** [comment]
Thank you. How do I change the color of the bar?

**Comment by black7375** [comment]
I am planning an update related to color compatibility.

---

Temp solution

https://github.com/black7375/Firefox-UI-Fix/blob/d00749f4cdb24a16eff36def3a0081494cbf355f/userChrome.css#L219-L224
