### ISSUE TITLE
Use alternate row colour for Applications table

### ISSUE THREAD

**Issue by Patricek0056** [black7375/Firefox-UI-Fix#737]
### Is your feature request related to a problem?

The only table (as I know) which is not using alternate row colour is Applications table in `about:preferences`.

I mean, that first row is white, second is grey, third is white, fourth is grey…

### The solution I'd like

Use alternate row colour for applications table.

### Screenshots or video

Applications table is not using alternate row colour actually:
![Applications table should use alternate row colour](https://github.com/black7375/Firefox-UI-Fix/assets/69351811/dd7a3959-e338-4984-94b1-d74d4f8eca4c)

Example table which is already using alternate row colour:
![Example which is already using alternate row colour](https://github.com/black7375/Firefox-UI-Fix/assets/69351811/a8e5c899-0712-440e-baf8-0d8b54415a2d)

**Comment by black7375** [comment]
Nice idea.

Now, looks like this:
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/43637ad8-3da3-4b26-9e67-4ac5389701a6)
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/fb8b6606-0afa-44d3-aefa-f4d2ab48f5f8)
