### ISSUE TITLE
Make Installation Guide more clear

### ISSUE THREAD

**Issue by Progress200** [black7375/Firefox-UI-Fix#738]
### Describe the bug

Although this is just a very small issue, I wish the [installation guide](https://github.com/black7375/Firefox-UI-Fix/wiki/Installation-Guide) could have a minor change to make it more clear. In Windows, **Profile Directory** is known as **Profile Folder** and **Open Directory** is known as **Open Folder**. I wish you can mention this to make the installation guide more clear. Please also change the [Installation Guide at README.org ](https://github.com/black7375/Firefox-UI-Fix#installation-guide). Thank you.

### Screenshots

Linux
![120420140-4c9d2100-c353-11eb-8f7f-1d003c3166b5](https://github.com/black7375/Firefox-UI-Fix/assets/109966292/e34a022c-5133-40bd-a2c3-d90ae921504d)
Windows
![image](https://github.com/black7375/Firefox-UI-Fix/assets/109966292/7f822b77-2882-4842-b3a0-efda21c04a94)

### OS

Windows 11

### Firefox Version

v117.0a1

### Distribution

- [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

**Comment by black7375** [comment]
I think it's ambiguous to put in README.
Is there any sentence you think?

Sounds like a good suggestion.

**Comment by Progress200** [comment]
**My suggestion:**
_In [installation guide](https://github.com/black7375/Firefox-UI-Fix/wiki/Installation-Guide), change it to:__
Find the `Profile Directory (Linux)/Profile Folder (Windows)` entry and click the `Open Directory (Linux)/Open Folder (Windows)` button.
Linux:
![](https://user-images.githubusercontent.com/25581533/120420140-4c9d2100-c353-11eb-8f7f-1d003c3166b5.png)
Windows:
![Temp](https://github.com/black7375/Firefox-UI-Fix/assets/109966292/13d82fdf-9094-41ae-87cd-5cbf28b92578)
_In README.org, change it to:_
2. Find your profile directory
Open about:support in a new tab
Find the `Profile Directory (Linux)/Profile Folder (Windows)` entry and click the `Open Directory (Linux)/Open Folder (Windows)` `button.

**Comment by black7375** [comment]
After applying it, it seemed to be getting long, so I divided it into two sentences and updated it.
Thank you for document suggestion.

---

Find the `Profile Directory(Linux)`/`Profile Folder(Windows)` entry.  
Then, click the `Open Directory(Linux)`/`Open Folder(Windows)` button.
