### ISSUE TITLE
Multiple UI Bugs after updated to v117.0a1 (Nightly)

### ISSUE THREAD

**Issue by Progress200** [black7375/Firefox-UI-Fix#744]
### Describe the bug

I have discovered two different UI bugs after upgraded to Nightly v117.9a1.
1. When theme is being set to `System Theme`. Firefox no longer show the MS edge inspired theme instead showing the light/dark theme. 
![image](https://github.com/black7375/Firefox-UI-Fix/assets/109966292/eac190d9-f357-4eb1-9cf2-f362aadf99dd)
2. The UI of the pop up and container selection box is buggy.

![image](https://github.com/black7375/Firefox-UI-Fix/assets/109966292/acd71f7f-bc04-402a-9afe-92036df18822)
![image](https://github.com/black7375/Firefox-UI-Fix/assets/109966292/6da6d461-0822-4d5b-b6f9-77d1fcf72a22)

### Expected behavior

Work as what normally Lepton would behave.

### OS

Windows 11

### Firefox Version

v117.0a1 (Nightly)

### Distribution

- [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [X] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>

**Comment by black7375** [comment]
I checked briefly and it seems like a problem with the media query.

It works
```css
@media (-moz-platform: windows) {
}
```

But it doesn't works
```css
@media (-moz-platform: windows-win10) {
}
```

It seems to be a Firefox problem and needs to understand why it happened.
I'll create an upstream issue.

**Comment by ctrlcmdshft** [comment]
Same issue on FF117.0b2 on Windows 11, Hopefully your able to push a fix soon

**Comment by black7375** [comment]
This will be a breaking change and should be discontinued support for `windows7` and `windows8`.
Maybe we have to release a new major version.

**Comment by MagicalDrizzle** [comment]
> This will be a breaking change and should be discontinued support for `windows7` and `windows8`. Maybe we have to release a new major version.

It might be nice to dedicate 7.x.x for 115esr (last version to support w7 and 8), and 8.x.x for future versions going forward

**Comment by black7375** [comment]
> Is there a way i can manually fix this (the context menu icon/text overlap)

- Replace `(-moz-platform: windows-win10)` to `(-moz-platform: windows)` at `css/leptonChrome.css`/`css/leptonContent.css`

---

> It might be nice to dedicate 7.x.x for 115esr (last version to support w7 and 8), and 8.x.x for future versions going forward

I'll do some tests and release this weekend.

**Comment by ctrlcmdshft** [comment]
> > Is there a way i can manually fix this (the context menu icon/text overlap)
> 
>     * Replace `(-moz-platform: windows-win10)` to `(-moz-platform: windows)` at `css/leptonChrome.css`/`css/leptonContent.css`
> 
> 
> > It might be nice to dedicate 7.x.x for 115esr (last version to support w7 and 8), and 8.x.x for future versions going forward
> 
> I'll do some tests and release this weekend.

Changed every instance of `(-moz-platform: windows-win10)` to `(-moz-platform: windows)` in both files and still have issue

**Comment by Evo-c** [comment]
> > > Is there a way i can manually fix this (the context menu icon/text overlap)
> > 
> > 
> > ```
> > * Replace `(-moz-platform: windows-win10)` to `(-moz-platform: windows)` at `css/leptonChrome.css`/`css/leptonContent.css`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > It might be nice to dedicate 7.x.x for 115esr (last version to support w7 and 8), and 8.x.x for future versions going forward
> > 
> > 
> > I'll do some tests and release this weekend.
> 
> Changed every instance of `(-moz-platform: windows-win10)` to `(-moz-platform: windows)` in both files and still have issue

One alternative is to temporarily disable the icons, in leptonChrome search for `background-size: 16px !important;` and change it to 0px

**Comment by ctrlcmdshft** [comment]
> 

Thanks i used first one to do it for time being

**Comment by black7375** [comment]
Hello, I just opened the PR.
The following files should work normally!!

- https://github.com/black7375/Firefox-UI-Fix/blob/dev/css/leptonChrome.css
- https://github.com/black7375/Firefox-UI-Fix/blob/dev/css/leptonContent.css

**Comment by ctrlcmdshft** [comment]
> 

Working again after replacing the files 

Thank you

**Comment by black7375** [comment]
Firefox 117 seems to work well after its launch, so it closes.
However, since many people are expected to find an issue, the `pinned` is maintained for the time being.
