### ISSUE TITLE
Sidebar dropdown menu icons are missing in Firefox 116

### ISSUE THREAD

**Issue by eaw4690** [black7375/Firefox-UI-Fix#749]
### Describe the bug

Just updated to Firefox 116 and the sidebar dropdown menu icons are missing.

### Expected behavior

Sidebar dropdown menu icons are present

### Screenshots

Firefox 115
![115](https://github.com/black7375/Firefox-UI-Fix/assets/104198709/924e87d2-e287-4135-906c-436a3e96e58b)

Firefox 116
![116](https://github.com/black7375/Firefox-UI-Fix/assets/104198709/c016a9ff-b144-454f-96a7-ab663f292f9e)

### OS

Windows 11, Windows 10

### Firefox Version

v116.0 (stable)

### Distribution

- [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [ ] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Default settings used
```
</details>

**Comment by rockenren** [comment]
Same in Lepton's photon style.

**Comment by Patricek0056** [comment]
I can reproduce it too. Maybe Mozilla did some changes to sidebar's CSS. (And it is so annoying)

**Comment by black7375** [comment]
The structure has been changed from the panel menu to a regular menu.
Now, fixed!!

**Comment by eaw4690** [comment]
The latest commit fixed the missing icons, but the padding is too close than the extension that can utilize the use of sidebars, such as [Tree Style Tab](https://addons.mozilla.org/addon/tree-style-tab/):
![0](https://github.com/black7375/Firefox-UI-Fix/assets/104198709/6d7e2065-3889-44ba-8e44-8d8f5d0ca027)

**Comment by black7375** [comment]
What's your OS and Firefox?
Windows10, linux's v118 is works well
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/e92ba6d8-886e-4515-be94-d382d9e79ede)

**Comment by rockenren** [comment]
Windows 10, Firefox 116.0.1:

![image](https://github.com/black7375/Firefox-UI-Fix/assets/11333307/3d745d83-bad8-4c3b-9059-9b62360b107c)

**Comment by eaw4690** [comment]
> What's your OS and Firefox? Windows10, linux's v118 is works well !

Same as @rockenren
Firefox 116.0.1 (latest stable), also happens on Windows 11

**Comment by black7375** [comment]
Ok, thank you for feedback.
I've updated code.
