### ISSUE TITLE
Expand alternate row colour feature also for dialogue items (not only for tables)

### ISSUE THREAD

**Issue by Patricek0056** [black7375/Firefox-UI-Fix#751]
### Is your feature request related to a problem?

Alternate row colour has been implemented for some tables, however e.g. exceptions dialogues in settings are not supporting it.

List of dialogues without support for this feature:
- Enhanced Tracking Protections exceptions list,
- Saved logins exceptions list,
- Location, Camera, Microphone, Speaker Selection, Notifications, Autoplay & Virtual Reality permissions exceptions lists,
- “Block pop-up windows” exceptions list,
- “Warn you when websites try to install add-ons” exceptions list,
- Certification Manager > Servers list,
- HTTPS-Only mode exceptions list,
- DNS over HTTPS exceptions list.

### The solution I'd like

Add alternate row colours for items in mentioned dialogues.

### Screenshots or video

Expected results:
![Example which is already using alternate row colour](https://github.com/black7375/Firefox-UI-Fix/assets/69351811/c2b48389-139d-46f7-bc57-25935de14611)

Actual results in one of the mentioned examples:
![ETP exceptions list doesn't have support for alternate row colour](https://github.com/black7375/Firefox-UI-Fix/assets/69351811/ea7d4285-fba7-484b-b50e-2a4e6af868d3)

**Comment by Patricek0056** [comment]
Maybe I showed bad example in expected results, because that example is table and not dialogue, and this issue is about dialogues, but I will keep it here for illustration.

**Comment by black7375** [comment]
Hello, Now it works with dialog!!
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/041a9962-c0c9-4991-9e2f-819816ec3dcd)

Thank you for suggestion.
