### ISSUE TITLE
Double dividers in context menu

### ISSUE THREAD

**Issue by kanlukasz** [black7375/Firefox-UI-Fix#753]
### Describe the bug

![image](https://github.com/black7375/Firefox-UI-Fix/assets/30685349/2220d9e3-32d9-4f41-9cef-3c72bfda66a4)

### Expected behavior

It should not be duplicated

### Screenshots

See `Describe the bug`

### OS

Windows 11

### Firefox Version

116.0.1

### Distribution

- [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [X] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [X] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

My `user.js` is override from Firefox-UI-Fix. I don't change anything there

**Comment by black7375** [comment]
Try a newly released code!! #732
https://github.com/black7375/Firefox-UI-Fix/releases/tag/v7.5.0
