### ISSUE TITLE
Tabs bar has scroll buttons when it shouldn't have them, causing tiny scrolling area

### ISSUE THREAD

**Issue by Dwedit** [black7375/Firefox-UI-Fix#754]
### Describe the bug

The tabs bar has scroll buttons when it shouldn't have them, causing a tiny scrolling area.

Steps to reproduce:

* Set Browser Window to 960px wide (Half of 1920px wide screen)
* Open a total of 9 tabs.  There is no scrolling yet, and everything is fine.
* Open the 10th tab.  Now there is scrolling.
* Close one tab.  Despite that 9 tabs open had no scrolling before, now it has scrolling.
* Close another tab.  With 8 tabs open, the scrolling area is very small, around 8 pixels total, but the scroll buttons remain.
* Scroll buttons stay until only two tabs are open.

It looks like it's evaluating the width of the tab bar area minus the size of the scroll buttons, and that causes it to think there's not enough room.

The same problem also happens on a 1920px window after opening 24 tabs.

### Expected behavior

What should happen: Upon returning down to 9 open tabs (on 960px wide window), it should not put scroll buttons up.

### OS

Windows 10

### Firefox Version

116.0.2

### Distribution

- [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [X] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

User.js matches the one from Firefox-UI-Fix.

**Comment by Dwedit** [comment]
Appears to no longer be an issue in Firefox 131.

**Comment by black7375** [comment]
It's good news that the bug is gone.
