### ISSUE TITLE
Accent color on Dev edition?

### ISSUE THREAD

**Issue by luximus-hunter** [black7375/Firefox-UI-Fix#76]
**Describe the bug**
The accent color on the developer edition doesn't seem to work.

**Expected behavior**
The cyan color replaced with the windows accent color

**Screenshots**
![image](https://user-images.githubusercontent.com/49814847/121381588-2294c180-c946-11eb-8070-bcf004f03051.png)
![image](https://user-images.githubusercontent.com/49814847/121381603-258fb200-c946-11eb-826a-350bc2e3ee45.png)

**Environment (please complete the following information):**
 - Firefox Version: 90.0b5
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [x] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

**Additional context**
n/a

**Comment by black7375** [comment]
Check when using `Windows`.

**Comment by luximus-hunter** [comment]
How do you mean? im already using Windows 10

![image](https://user-images.githubusercontent.com/49814847/121677445-27788300-cab6-11eb-9c93-226d6f89ef75.png)

**Comment by black7375** [comment]
It was a memo that meant I would check.

When checking with version 88(photon), accent color is not used.
![image](https://user-images.githubusercontent.com/25581533/121711796-82b47080-caca-11eb-98a4-4793ea3fb1e1.png)
But I think your opinion is good.

**Comment by black7375** [comment]
Try using version `5.0.0` options.
https://github.com/black7375/Firefox-UI-Fix/wiki/Options#system-accent-color
