### ISSUE TITLE
[Proton] Broken vertical alignment of tabs label

### ISSUE THREAD

**Issue by SDK4rma** [black7375/Firefox-UI-Fix#761]
### Describe the bug

I just installed Firefox UI Fix on my fresh new W10 OS, but I encounter an issue on the vertical alignment of tabs label (see Screenshots). 

### Expected behavior

I expected the tabs label to be centered horizontally **and** vertically. 

### Screenshots

![image](https://github.com/black7375/Firefox-UI-Fix/assets/16545424/7f56289a-5d45-49e5-b729-555602cb25b0)

### OS

Windows 10

### Firefox Version

v116.0.3

### Distribution

- [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [X] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [X] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [ ] System Default
- [X] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### Theme - More Info

Beautiful Alpen Blue : https://addons.mozilla.org/fr/firefox/addon/beautiful-alpen-blue/

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Just uncommented these 3 lines 
user_pref("userChrome.centered.tab",                        true);
user_pref("userChrome.centered.tab.label",                  true);
user_pref("userChrome.centered.urlbar",                     true);
```
</details>

**Comment by black7375** [comment]
Try to `v8.1.0` or latest commit please.
It will be works well.
