### ISSUE TITLE
Remove Set as Desktop Background context menu items causes double separators to appear

### ISSUE THREAD

**Issue by MagicalDrizzle** [black7375/Firefox-UI-Fix#764]
### Describe the bug

Remove Set as Desktop Background context menu items causes double separators to appear. 
This is because `Set as Desktop Background` is separated from all the rest with two separators. Thus removing it cause two separators to appear.

This appears to be an oversight because this specific modification is included in the `userChrome.css` file.
```css
/* Disable Email Image/Audio/Video and Set as Desktop Background context menu items */
/*
 * #context-sendimage,
 * #context-sendvideo,
 * #context-sendaudio,
 * #context-setDesktopBackground {
 *   display: none !important;
 * }
*/
```

### Expected behavior

There should only be one separator.

### Screenshots

![28-08-23_13-59_file-34](https://github.com/black7375/Firefox-UI-Fix/assets/49761211/e0a58ae7-c792-4cbb-8be5-0f9598202d5d)![28-08-23_14-02_file-35](https://github.com/black7375/Firefox-UI-Fix/assets/49761211/d8600565-d0b5-4aa7-be76-59496bd79da1)

### OS

Windows 10

### Firefox Version

v116.0.3

### Distribution

- [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [X] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [X] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [ ] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

Unchanged from default.

**Comment by AuRiMaS666** [comment]
Yes, this needs to be hidden together with its dedicated separator.

https://github.com/stonecrusher/simpleMenuWizard/blob/12375ead3f48761456a6833fe1317ca07c8edf9f/simpleMenuWizard/image-context.css#L17C1-L18C75

**Comment by black7375** [comment]
Since #765 has been merged, I think this issue has been solved.
