### ISSUE TITLE
Update readme with shorter command

### ISSUE THREAD

**Issue by ShadowElixir** [black7375/Firefox-UI-Fix#769]
### Is your feature request related to a problem?

The powershell command is too big.

### The solution I'd like

Replace it with this command I made using a url shortener
irm cutt.ly/uifix | iex

**Comment by black7375** [comment]
First of all, thank you for your suggestion!!
I also think Powershell's command is too long :crying_cat_face:, but unfortunately there was a compatibility problem. #147

This is why the installing command of software like choco is very long.
- https://chocolatey.org/install
