### ISSUE TITLE
Related to Background Image

### ISSUE THREAD

**Issue by thunderstone135** [black7375/Firefox-UI-Fix#773]
### Is your feature request related to a problem?

Hi, I just want to ask if it is possible to remove the context menu items below 👇
- Open Image in New Tab
- Copy Image Link

When browsing the following pages 👇
- about:blank
- about:home
- about:newtab
- about:privatebrowsing

### The solution I'd like

I was actually able to remove Open Image in New Tab and Copy Image Link with this 👇
```
#context-copyimage, #context-viewimage {
  display: none !important;
}
```
However, I didn't want these context menu items removed on all websites.
Just on about:blank, about:home, about:newtab, and about:privatebrowsing.
So, I tried it with this 👇
```
@-moz-document url-prefix("about:blank"), url-prefix("about:home"),
url-prefix("about:newtab"), url-prefix("about:privatebrowsing") {
  #context-copyimage, #context-viewimage {
    display: none !important;
  }
}
```
I tried it on userChrome and userContent. It doesn't work.
I researched the issue and found that it can be done through JavaScript.
I checked if it was possible with userscript. It wasn't.
The only URL Patterns supported are http, https, file, ftp, ws, wss, data, and (chrome-) extension.
Another method came to mind, but it was too complicated so I'm not going to mention it here.

Putting that aside, some might wonder why I wanted those two context menu items removed.
You see, before I enabled `userContent.newTab.background_image`, those items were not present.
Those items would probably not bother some people, but it does bother me. I'm probably just OCD.

With that said, I posted here just in case I missed something that can be done in CSS.

### Screenshots or video

N/A

### Alternatives I've considered

N/A

### Additional context

N/A

**Comment by black7375** [comment]
Yeah, it's actually impossible only CSS.
However, you can use `pointer-events: none` for `userContent`'s image elements to make them unrecognized.

**Comment by thunderstone135** [comment]
I tried pointer-event, but it didn't work. It is still showing Open Image in New Tab and Copy Image Link.

**Comment by black7375** [comment]
I don't know what you did, but you have to apply it to the `image`.

For example, to prevent the context menu button from running on the logo on a new tab.

![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/5ce38654-02e7-49a6-aaa5-80c6aa1d8352)


```css
.logo {
  pointer-events: none;
}
```

**Comment by thunderstone135** [comment]
I was actually talking about the background-image associated with this 👇
https://github.com/black7375/Firefox-UI-Fix/blob/6d2cfe210ef3208c56aaf94aeffa569fdb0c1701/css/leptonContent.css#L493-L509
I can't seem to remove the context menu items that appeared after I enabled `userContent.newTab.background_image`.

**Comment by thunderstone135** [comment]
I probably should have added a screenshot in the first post 👇

![Imgur](https://imgur.com/7Wti37a.png)

**Comment by black7375** [comment]
I got it.
It's an unintended change of behavior, so I want to solve it, but CSS alone is quite tricky.

**Comment by thunderstone135** [comment]
I know, right? I'm still researching if there's a way to hide those context menu items without resorting to JavaScript.

The only success I had so far is adding this on userChrome.css 👇
```
#context-copyimage, #context-viewimage {
  display: none !important;
}
```
The only caveat is it disables Open Image in New Tab and Copy Image Link everywhere.

**Comment by black7375** [comment]
I'm sure @2641a40fd44383320adde4b027a1d0b03bd550 's amazing work has solved this bug

**Comment by thunderstone135** [comment]
Nicely done👍
