### ISSUE TITLE
Page Info tab icons are cut off

### ISSUE THREAD

**Issue by aphedges** [black7375/Firefox-UI-Fix#780]
### Describe the bug

In the "Page Info" window, the icons for the tabs at the top are obscured and the text is completely missing on macOS. I do not have this issue on my Windows machine.

### Expected behavior

The tabs should be entirely visible.

### Screenshots

![Screenshot of obscured dialog tabs in Firefox 117 on macOS](https://github.com/black7375/Firefox-UI-Fix/assets/14283972/a7e6acee-f552-4ebc-8358-bee609944edd)

### OS

Mac OS

### Firefox Version

117.0.1

### Distribution

- [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [X] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

No customization. The file is copied from <https://github.com/black7375/Firefox-UI-Fix/releases/download/v8.0.0/Lepton.zip>.

### Additional context

This isn't a new problem. I've been having it for a couple of months (possibly as far back as May), and I finally got around to reporting it now.

I experienced a similar problem before, which I reported in #302.

**Comment by black7375** [comment]
It should be works fine now.
The previous issue link was quite help. thank you

**Comment by aphedges** [comment]
I forgot to check whether this was fixed by the time I updated to the version with the bug fix. I can confirm it now works properly!
