### ISSUE TITLE
Add alternate row colour also for items in “Servers” section in Certificate Manager

### ISSUE THREAD

**Issue by Patricek0056** [black7375/Firefox-UI-Fix#783]
### Is your feature request related to a problem?

One of the last lists, which don't support alternate row colour is “Servers” section in Certificate Manager.

### The solution I'd like

Add alternate row colour for items in “Servers” section in Certificate Manager.

### Screenshots or video

![Servers section in certificate manager](https://github.com/black7375/Firefox-UI-Fix/assets/69351811/e7fa5252-6842-4921-9003-68fc638cc3ac)

**Comment by black7375** [comment]
It's solved at `v8.1.0`. Thanks!!
