### ISSUE TITLE
[Suggestion] Remove mega bar

### ISSUE THREAD

**Issue by ipmanlk** [black7375/Firefox-UI-Fix#79]
There are existing solutions to restore the old search bar such as: [Remove-Firefox-Megabar](https://github.com/WesleyBranton/Remove-Firefox-Megabar).  I think it would be great to include that in this project as well, even as an optional feature.

**Comment by black7375** [comment]
I tried it and first added it to the wiki.
https://github.com/black7375/Firefox-UI-Fix/wiki/Tips#restore-megabar

Some code might be suitable for compact mode.
I'll have a little work to do with compact mode later.

**Comment by black7375** [comment]
Some code has been reflected. https://github.com/black7375/Firefox-UI-Fix/commit/43fa950090af145d5d19b2e26d882c8672f262e9
