### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by damonmitchellsr1** [black7375/Firefox-UI-Fix#80]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Firefox Version: [write from `about:support` - `version`]
 - OS:
   - [ ] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [ ] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

**Additional context**
Fix-<[]()

**Comment by damonmitchellsr1** [comment]
Help

**Comment by black7375** [comment]
Please fill out the situation description and information correctly.
Without information, nothing can help.

**Comment by Shreejikhalasi** [comment]
Hello damonmitchellsr1, I am a beginner in this field but I would like to help with the bug problem, if you assigned it to me.

**Comment by damonmitchellsr1** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Environment (please complete the following information):**
>  - Firefox Version: [write from `about:support` - `version`]
>  - OS:
- > >    - [ ]**** Linux
>    - [ ] Windows
>    - [ ] Mac
>    - [ ] Others: 
>  - Theme:
>    - [ ] Light
>    - [ ] Dark
>    - [ ] Alpenglow(System: Light)
>    - [ ] Alpenglow(System: Dark)
>    - [ ] System Default
>      - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark
> 
> **Additional context**
> Add any other context about the problem here.
> Fix-<[]()

**Comment by black7375** [comment]
I gave you enough time, and I treat you as spam because I do the same thing even though I've told you many times.
