### ISSUE TITLE
Technical Issues

### ISSUE THREAD

**Issue by damonmitchellsr1** [black7375/Firefox-UI-Fix#81]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Firefox Version: [write from `about:support` - `version`]
 - OS:
   - [ ] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [ ] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

**Additional context**

**Comment by black7375** [comment]
Don't keep creating new issues
Duplicate #81
