### ISSUE TITLE
NOTICE: Floorp Browser Progressive Web Apps

### ISSUE THREAD

**Issue by surapunoyousei** [black7375/Firefox-UI-Fix#819]
### Is your feature request related to a problem?

Just a heads up. As you may know, I am currently adding a PWA implementation to Floorp. This requires some icons.

I am currently replacing the pre-Firefox Proton icons, but the design may not match and the Lepton look may be lost.

We have contacted you to see if a new icon is needed.

### The solution I'd like

Consider create icons

### Screenshots or video

![image](https://github.com/black7375/Firefox-UI-Fix/assets/73892113/de7cba41-2bb3-4b3d-a284-41f12cbf4a46)
![image](https://github.com/black7375/Firefox-UI-Fix/assets/73892113/74b77613-c624-488b-b679-4ed20b63d479)

**Comment by zapSNH** [comment]
I might be able to make some icons for it.

**Comment by black7375** [comment]
IMO, Although the last one seems hard to recognize as an `PWA Apps`,
I think these are fine for installing and deleting PWAs.

---

@surapunoyousei What do you think about @zapSNH icon?

Maybe it'll help [PWAsForFirefox](https://github.com/filips123/PWAsForFirefox) too.
cc @filips123

**Comment by surapunoyousei** [comment]
> I might be able to make some icons for it.
> 
> -- edit: see: https://www.figma.com/file/Iyym2tjRVlb7rxTR1Gmvr8/lepton?type=design&node-id=154%3A2&mode=design&t=a8V3q0FF83RF9L48-1
> 
> There are two variations of the icons, window and square. Let me know which one you like and if you have any feedback on these icons.

IMO, These icons seem to be "window" icons. All currently icons are difficult to recognize. 

![image](https://github.com/black7375/Firefox-UI-Fix/assets/73892113/30b1602b-3143-4c13-8905-8af520ca5639)

Good one is Microsoft Edge's icon (Fluent). Maybe it needs 4 squares in icons

![image](https://github.com/black7375/Firefox-UI-Fix/assets/73892113/64a66218-a800-4304-9853-2c050a82a93b)

**Comment by zapSNH** [comment]
> IMO, These icons seem to be "window" icons. All currently icons are difficult to recognize.

There's also a square version on the right.

> Good one is Microsoft Edge's icon (Fluent). Maybe it needs 4 squares in icons
> 
> ![image](https://user-images.githubusercontent.com/73892113/284034572-64a66218-a800-4304-9853-2c050a82a93b.png)

The 4 square icon kinda looks too similar to the container icon and it may confuse people. I can whip up a 4 square version though if you want.

![image](https://github.com/black7375/Firefox-UI-Fix/assets/134786889/d6d20c87-6b61-4c9d-a86d-14e332ae6334)

**Comment by surapunoyousei** [comment]
> > IMO, These icons seem to be "window" icons. All currently icons are difficult to recognize.
> 
> There's also a square version on the right.
> 
> > Good one is Microsoft Edge's icon (Fluent). Maybe it needs 4 squares in icons
> > ![image](https://user-images.githubusercontent.com/73892113/284034572-64a66218-a800-4304-9853-2c050a82a93b.png)
> 
> The 4 square icon kinda looks too similar to the container icon and it may confuse people. I can whip up a 4 square version though if you want. (right after i eat my lunch)
> 
> ![image](https://user-images.githubusercontent.com/134786889/284034802-d6d20c87-6b61-4c9d-a86d-14e332ae6334.png)

OK. I agree with you. I forget about that.

Looks like we'll have no choice but to compromise...

**Comment by black7375** [comment]
It certainly looks so similar.
- https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/a57e5cfe-cacf-4a3c-a064-5ff6b4bce7b8)

---
Fortunately, I have a couple of alternatives.

## Icons
### Cube
You have the option to deform the model itself, or to represent the mode in the lower right corner.
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/30cd001d-be87-4cbe-a490-f2af0ba4c718)

### Grid
You have the option to make it a dot or a rectangle.
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/5b45fce8-4102-4344-969a-85430271e8e0) ![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/ad59c57c-de02-42a3-b2a3-8c975196efd9)

## Variants

### Deform the model itself
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/0b3a53a2-5991-42b8-9cc8-332b6ede8d9b)

### Mode in the lower right corner
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/f0877b31-9b7a-45f4-93fd-0a8417575ee4)

### Combination of one icon and another
[In Chrome, for example](https://www.guidingtech.com/install-uninstall-pwas-chrome/), only the `Apps` icon is grid, and install utilize the existing icon.

![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/4158998a-0c51-4d42-8c1d-91967696517f)

![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/21465573-c135-4e9e-b5d1-0dc9691aa5e0)

**Comment by zapSNH** [comment]
I've made something similar Chrome's ![image](https://github.com/black7375/Firefox-UI-Fix/assets/134786889/45785400-8751-44ac-ac51-539e96a9f4d0) (and the PWAsForFirefox's) icon.

![image](https://github.com/black7375/Firefox-UI-Fix/assets/134786889/4eb73400-da75-4102-963d-bc490d5dd190)

What do you think about it?

**Comment by surapunoyousei** [comment]
In conclusion, the first icon you presented seemed to be a good choice.

**Comment by zapSNH** [comment]
> In conclusion, the first icon you presented seemed to be a good choice.

What version? Window or square?
![image](https://github.com/black7375/Firefox-UI-Fix/assets/134786889/19654577-7445-4228-bfd7-b593c5c790a1)

**Comment by surapunoyousei** [comment]
In conclusion, the first icon you presented seemed to be a good choice.

Square are better

**Comment by zapSNH** [comment]
I've added the square icons [zapSNH/lepton-icons](/zapSNH/lepton-icons) but I can change it if @black7375 wants a different icon.

**Comment by black7375** [comment]
Launch icon is beautiful!!
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/44f7fd44-dcf7-474f-b6d5-6fb093b35155)

Currently, the app icon looks like a single app, so it's better to make it look like you have multiple apps.
My idea is to place the dots inside a regular desktop icon with a border.

![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/e60f03b8-fcd5-496c-93af-c7e042cecbca)

It's probably consistent with mobile as well.
- https://acorn.firefox.com/latest/styles/iconography-q7JqGl5H
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/484c66e0-8b37-4b9b-b06d-cbcee63e1344)

**Comment by zapSNH** [comment]
How about this for the app icon (I assume you mean the `pwa-manage` icon)
![image](https://github.com/black7375/Firefox-UI-Fix/assets/134786889/5c914f76-30f5-4548-9aee-36bd71f6eda7)

**Comment by black7375** [comment]
Nice :+1: I like it.

**Comment by zapSNH** [comment]
I've pushed the svgo'd icons to [zapSNH/lepton-icons](https://github.com/zapSNH/lepton-icons) so you can get them there.

**Comment by black7375** [comment]
As soon as the CSS selector names in Floorp are stable, I'll add the icons. @surapunoyousei

**Comment by surapunoyousei** [comment]
Ok. I'll send infomation here.

**Comment by surapunoyousei** [comment]
The most of implementation of PWA has been completed and additional features may appear in the future, but we will report them once they are in place.

Please follow below CSS id & attribute.

"open-ssb" means, Not install page. The button will open installed PWA window(ssb window)

```CSS
#appMenu-ssb-button {
  list-style-image: url("chrome://browser/skin/install-ssb.svg");
}

#appMenu-install-or-open-ssb-current-page-button {
  list-style-image: url("chrome://browser/skin/install-ssb.svg");
}

#appMenu-install-or-open-ssb-current-page-button[open-ssb="true"] {
  list-style-image: url("chrome://browser/skin/install-ssb.svg");
}

#ssbPageAction-image {
  list-style-image: url("chrome://browser/skin/install-ssb.svg");
}

#ssbPageAction-image[open-ssb="true"] {
  list-style-image: url("chrome://browser/skin/install-ssb.svg");
}
```

**Comment by black7375** [comment]
I made a commit, check it out

**Comment by surapunoyousei** [comment]
Add a separate icon by @zapSNH .

I thought these would be included in Lepton but, I guess These not include it in Lepton.

**Comment by black7375** [comment]
I think we can close this issue now!!

**Comment by surapunoyousei** [comment]
Oh... I forgot it... My apologize.
