### ISSUE TITLE
Photon style: Line behind tab bar crosses active tab

### ISSUE THREAD

**Issue by cwyc** [black7375/Firefox-UI-Fix#82]
**Describe the bug**
The dark line behind the tab bar is also visible beneath the active tab, in the Photon style.
![Screenshot](https://user-images.githubusercontent.com/16950437/121633831-8ce65880-ca51-11eb-85e2-626a3a86b566.png)

**Expected behavior**
It should not be present beneath the active tab, such that the tab is connected to the address bar.
![Screenshot (fixed)](https://user-images.githubusercontent.com/16950437/121634036-e64e8780-ca51-11eb-8b2b-2d6428bbefbb.png)

**Screenshots**

**Environment (please complete the following information):**
 - Firefox Version: 89.0
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [x] System Default
     - GTK Theme Name(Only Linux User): Adwaita

**Additional context**

**Comment by black7375** [comment]
Do you use release 1.0 version?

It would have been resolved in the next version.
![image](https://user-images.githubusercontent.com/25581533/121634955-fd52a100-ca74-11eb-8c7b-0c8c2fd12013.png)

Try the latest `photon-stlye` branch.

**Comment by cwyc** [comment]
The latest version works. Thank you!
