### ISSUE TITLE
Active Tab has accent color in v121

### ISSUE THREAD

**Issue by jarupxx** [black7375/Firefox-UI-Fix#827]
### Describe the bug

Until v120, --win-bgcolor was used for the active Tab, but v121 uses an accent color. Using an accent color on black text can be difficult to read.

### Expected behavior

Active Tab will used --win-bgcolor.

### Screenshots

v120
![120](https://github.com/black7375/Firefox-UI-Fix/assets/20138367/f8f52f84-69ce-47eb-a47c-8a442d4d10d3)
v121
![121b2](https://github.com/black7375/Firefox-UI-Fix/assets/20138367/ab6ac8f3-9664-4177-a62f-1d2b2b1dd960)

### OS

Windows 11

### Firefox Version

v121b2

### Distribution

- [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [X] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>

### Additional context

Windows 11 Theme specify Light.

**Comment by YogurtProblems** [comment]
Seconded. My active tab is the exact same color as the others. 

![image](https://github.com/black7375/Firefox-UI-Fix/assets/140837729/cbb53da2-a1cd-406a-8ca9-f1950cf06626)

Light and Dark mode do the same thing. 

As a simple short term "fix", I have

userChrome.tab.photon_like_contextline == true

But that won't even stick with a restart.

**Comment by black7375** [comment]
MEMO: Commit in Firefox that are causing the problem.
https://github.com/mozilla/gecko-dev/commit/4ac6245eb928327070710d2966abb6344a240dd2


I've restored it back to its original value. (Considering backward compatibility)
