### ISSUE TITLE
How to make the "customize toolbar" button more easily visible?

### ISSUE THREAD

**Issue by 1Phase1** [black7375/Firefox-UI-Fix#83]
I can't understand why the "Customize Toolbar" button is currently hidden inside the the "more tools" menu. I'm actually not sure if this is a Proton change or a Lepton change. Is there some way I can modify it so that the button appears on the first menu that comes up when you open the Application Menu? I customize my toolbar fairly regularly, so it's a bit of a hassle getting to the button.

Is there some kind of modification I can make to the User.js file (or some other file) to place the button back on the main application menu?

**Comment by black7375** [comment]
Unfortunately, this is a change from Proton.

**Comment by 1Phase1** [comment]
Damn, I had a feeling that might be case. Well, thanks anyway, and thanks for making this great UI fix.

**Comment by 1Phase1** [comment]
> 
> 
> Unfortunately, this is a change from Proton.

Damn, I had a feeling that might be case. Well, thanks anyway, and thanks for making this great UI fix.

**Comment by black7375** [comment]
It's a change on XUL, so it's hard for me to fix.
CSS can be hidden but limited to creation.
