### ISSUE TITLE
Missing icons on builtin PDF viewer context menu when right-clicking drawing/images

### ISSUE THREAD

**Issue by erwin4270** [black7375/Firefox-UI-Fix#833]
### Describe the bug

Some context menu icons are missing on the PDF viewer (`pdf.js`) only when right-clicking the drawing/image.
[Example PDF here](https://s1.q4cdn.com/806093406/files/doc_downloads/test.pdf)

### Expected behavior

Icons are present on PDF editor context menu when right-clicking the drawing/image

### Screenshots

**Steps to reproduce:**
Make a drawing or add an image and right-click on it, and some icons on the context menu are missing.

Drawing
![0](https://github.com/black7375/Firefox-UI-Fix/assets/104198709/b2733ee1-d726-4b5a-9fe5-c6f85063ea31)

Editing images
![1](https://github.com/black7375/Firefox-UI-Fix/assets/104198709/62f5420c-72b3-4a4a-afc7-adb118d3e725)

https://github.com/black7375/Firefox-UI-Fix/assets/104198709/46611859-0c76-4d62-aa56-2ed642829d2d

### OS

Windows 11

### Firefox Version

v120.0.1 (stable)

### Distribution

- [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [ ] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

Using default settings

### Additional context

I'm using latest Lepton (8.5.0)

**Comment by black7375** [comment]
Added icons to the menu. :smile_cat:
