### ISSUE TITLE
Update bash script doesn't work when profile path contains spaces

### ISSUE THREAD

**Issue by gbdlin** [black7375/Firefox-UI-Fix#840]
### Describe the bug

When profile path contains spaces, update fails with weird git diff error when using install.sh script due to path being cut on the first space.

### Expected behavior

Update should success

### OS

Linux, Mac OS

### Firefox Version

Not applicable

### Distribution

- [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [X] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [X] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

**Comment by black7375** [comment]
I wasn't expecting a space in the name, thanks for the PR.

**Comment by gbdlin** [comment]
Default path on Mac OS (at least for me) contains `Application Support` directory
