### ISSUE TITLE
Address bar highlight is missing in dark mode on macOS

### ISSUE THREAD

**Issue by Anton2319** [black7375/Firefox-UI-Fix#851]
### Describe the bug

If the address bar is not selected, it is not highlighted in dark mode, starting with Firefox 121 on macOS with dark mode enabled. Bug does not seem to exist on Firefox 120 or in a light mode. The original (unmodified) firefox distribution does not have that bug either. I am running macOS 13.6.3 with the latest updates.

### Expected behavior

I grew accustomed to the aforementioned highlighting because it helps me with my visual memory

### Screenshots

<img width="1440" alt="Screenshot 2023-12-21 at 1 27 50 AM" src="https://github.com/black7375/Firefox-UI-Fix/assets/40764618/2a1e2b20-ee1a-4dea-95a0-e2fc2746764a">
<img width="1440" alt="Screenshot 2023-12-21 at 1 27 45 AM" src="https://github.com/black7375/Firefox-UI-Fix/assets/40764618/4749feca-6466-4551-aa89-76fe81a58f6a">
<img width="1440" alt="Screenshot 2023-12-21 at 1 27 37 AM" src="https://github.com/black7375/Firefox-UI-Fix/assets/40764618/25ffdd12-b44b-4e6a-90ef-4995a1e5f740">
<img width="1440" alt="Screenshot 2023-12-21 at 1 27 29 AM" src="https://github.com/black7375/Firefox-UI-Fix/assets/40764618/8a4439d4-cda3-4526-b0f4-544468953894">

### OS

Mac OS

### Firefox Version

v121.0

### Distribution

- [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [X] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [X] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

Default settings

**Comment by black7375** [comment]
Thanks. Now it looks like this:
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/c2c3e201-192c-4e7e-891a-9cbcac7c7bc6)

This is caused by Mozilla removing the color.
https://github.com/mozilla/gecko-dev/commit/b21a492ac7c3630407d8e36b8370c77550b4c56a
