### ISSUE TITLE
Weird lines on tabs

### ISSUE THREAD

**Issue by wealstarr** [black7375/Firefox-UI-Fix#859]
### Describe the bug

Tab separator has two lines instead of one. This happens only on non focused tabs. Might be related to shadow, not entirely sure though.

### Screenshots

![Capture](https://github.com/black7375/Firefox-UI-Fix/assets/26643729/8a5676d2-ed7b-4332-acbd-5266278f0720)

### OS

Windows 8

### Firefox Version

v115

### Distribution

- [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [X] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [X] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [ ] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>

### Additional context

I just installed the userchorme as detailed in readme.md and did not change anything else on a fresh firefox installation.

**Comment by black7375** [comment]
Maybe.. `userChrome.tab.static_separator` to `false`

**Comment by DumZee** [comment]
![New Project](https://github.com/black7375/Firefox-UI-Fix/assets/79674440/c0d3209c-07a3-4bf3-8020-bec435c8f3b1)
I only have this one little gray thingie that showed up 2 days ago next to the "Show your history" button...

[FF Nightly version 123.0a1 (2024-01-12) (64-bit)]

**Comment by wealstarr** [comment]
@black7375 Thank you for the response. Is the userchrome working on version 121? for me it doesn't do anything. Please respond  if possible so that I try with the fix you provided.

Many thanks.

**Comment by black7375** [comment]
That's resolved, so let's close it.
