### ISSUE TITLE
Incorrect background in active tab

### ISSUE THREAD

**Issue by gotyaoi** [black7375/Firefox-UI-Fix#861]
### Describe the bug

Possibly a reocurrence of #88. The portion of the background image being used for the active tab this time appears to be from the top left of the source image.

### Expected behavior

The portion of the image behind the active tab should be shown.

### Screenshots

![Screenshot 2024-01-09 212327](https://github.com/black7375/Firefox-UI-Fix/assets/2141918/0b67284e-290e-4141-b6cc-8aa4ea6e3b3a)

### OS

Windows 11

### Firefox Version

121.0.1

### Distribution

- [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [X] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [ ] System Default
- [X] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### Theme - More Info

https://addons.mozilla.org/en-US/firefox/addon/yakuza-paint/

### `user.js` setup

unchanged

### Additional context

Seems to have started on upgrading firefox to 121.

**Comment by black7375** [comment]
It should now work.

**Comment by gotyaoi** [comment]
Works perfectly, thank you!
