### ISSUE TITLE
active tab has transparent background

### ISSUE THREAD

**Issue by waclaw66** [black7375/Firefox-UI-Fix#865]
### Describe the bug

Active tab has transparent background while using system theme and it's difficult to distinguish from inactive tabs.

![obrazek](https://github.com/black7375/Firefox-UI-Fix/assets/15554561/d53aed44-a87d-4e46-9330-2dad1e3b83ee)

It's visible while dragging active tab

![obrazek](https://github.com/black7375/Firefox-UI-Fix/assets/15554561/bb431e1e-3460-4df2-8621-87fd78f72e7b)

It does few versions back, at least since version 121. Light and Dark theme look correct.

### Expected behavior

Active tab should have different color background

### Screenshots

System theme
![obrazek](https://github.com/black7375/Firefox-UI-Fix/assets/15554561/d53aed44-a87d-4e46-9330-2dad1e3b83ee)

Light theme
![obrazek](https://github.com/black7375/Firefox-UI-Fix/assets/15554561/81493ffa-3274-49d1-bc83-fcf9e7ffd861)

Dark theme
![obrazek](https://github.com/black7375/Firefox-UI-Fix/assets/15554561/76b83121-d582-4c60-b53e-71ab63fee76e)

### OS

Windows 10

### Firefox Version

123 b1

### Distribution

- [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [X] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [X] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

default

**Comment by waclaw66** [comment]
Fixed by https://github.com/black7375/Firefox-UI-Fix/releases/tag/v8.6.0

**Comment by black7375** [comment]
I've been busy lately that I haven't been able to pay attention to issues.
Thank you for checking
