### ISSUE TITLE
Theme tab/menu bar background not applied correctly

### ISSUE THREAD

**Issue by Redjard** [black7375/Firefox-UI-Fix#867]
### Describe the bug

Reproduction:
Create a new profile/installation of any Firefox version
Install Lepton with any settings
Install my theme (https://addons.mozilla.org/en-US/firefox/addon/oledfox/)
tab/menu bar doesn't apply the background correctly

### Expected behavior

This, but with Lepton active (it is not in this screenshot)
![image](https://github.com/Floorp-Projects/Floorp/assets/47570415/5c0b547d-b407-4860-8505-c03db322c30b)

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/47570415/c11f8586-cb5d-4e90-92d1-13311d9a9783)

### OS

Others

### OS - Others

Linux 64bit, Windows 10 64bit

### Firefox Version

Firefox 121.0, Floorp 11.8.2 (Firefox ESR 115.7.0)

### Distribution

- [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [X] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [X] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [ ] System Default
- [X] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### Theme - More Info

https://addons.mozilla.org/en-US/firefox/addon/oledfox/

### `user.js` setup

any/default

### Additional context

This is the theme used:
https://addons.mozilla.org/en-US/firefox/addon/oledfox/

I noticed the issue in Floorp originally, but it occurs in regular Firefox too. Here is the corresponding bug report [Floorp#832](https://github.com/Floorp-Projects/Floorp/issues/832)

**Comment by Redjard** [comment]
![image](https://github.com/black7375/Firefox-UI-Fix/assets/47570415/6048ca21-156b-47f3-b73c-c0c9dac951fc)
![image](https://github.com/black7375/Firefox-UI-Fix/assets/47570415/f3516b76-4e18-4004-b90c-9ba465d791fc)

**Comment by Redjard** [comment]
https://github.com/Floorp-Projects/Floorp/assets/47570415/325915f6-7f9c-4799-9f58-c5c6fa1a459c

**Comment by black7375** [comment]
I'll fix it this weekend.

**Comment by black7375** [comment]
This should have been resolved in [v8.6.0](https://github.com/black7375/Firefox-UI-Fix/releases/tag/v8.6.0).
