### ISSUE TITLE
Consider an installation that would allow git pulling for new changes and allow you to keep custom additions

### ISSUE THREAD

**Issue by travisnewman** [black7375/Firefox-UI-Fix#87]
A problem with the installation method is that you need to re-download each time and if you've made custom changes they will get overwritten when copying the new usercrhome.

Using imports you can keep multiple styles that are easily swappable, easily upgradable, and you can keep your custom styles between all of them.

For example, please see how this project works: 
https://github.com/ideaweb/firefox-safari-style

**Comment by ctrlcmdshft** [comment]
This would be a great to make updating much easier

**Comment by 7k5x** [comment]
The installer script on the master branch is just a pseudoscript and does practically nothing. I’m currently working on the installer script and I’ll consider adding a pull option.

**Comment by black7375** [comment]
https://github.com/black7375/Firefox-UI-Fix/pull/17#issuecomment-851834568

I also update with `git pull`, and people who have used git often are probably doing that.
This is why I keep the current file structure.

By the time the 2.0 version comes out, there will be 3 installation guides.
- Manual Install: current guide
- Release Install: using the official release
- Install for Developers: using `git clone` & `git pull`

**Comment by 7k5x** [comment]
@black7375 I think the `install.sh` could cover the `manual` and `release` installation methods. Most people just want to get a UI fix, not a painstaking handcopy installation That could crαp itself when improperly copied.

**Comment by black7375** [comment]
Yes, that's right.

**Comment by travisnewman** [comment]
This all sounds great, thanks! :)

**Comment by 7k5x** [comment]
partially included in #93

**Comment by black7375** [comment]
I think it has been solved through `v5.0.0`'s script.
- If there are any changes: Run `git stash` and `git stash pop` before and after `git pull`.
- If there are `user-overrides.js`, `userChrome-overrides.css`, and `userContent-overrides.css` files, [proceed with override](https://github.com/black7375/Firefox-UI-Fix/wiki/Options#using-scripts)

**Comment by bb010g** [comment]
I use symbolic links to a repository checkout, and the new v5 layout would be even smoother if the new `css` directory containing `leptonChrome.css` and `leptonContent.css` was named `leptonCss` or similar, so as to not conflict with any other CSS subdirectories in `$FIREFOX_PROFILE/chrome/`.
