### ISSUE TITLE
Icon for "Tabs Sharing Devices" drop down on Linux (Gnome)

### ISSUE THREAD

**Issue by happy-dude** [black7375/Firefox-UI-Fix#872]
### Is your feature request related to a problem?

Every menu on the toolbar has a corresponding icon; unfortunately, when interacting with a site (like Google meet) which may share video, microphone, camera, etc., a `Tabs Sharing Devices` menu appears and there is no corresponding icon from Lepton.

See attached screenshot.

### The solution I'd like

An icon appears for the `Tabs Sharing Devices` menu like every other item on the toolbar.

### Screenshots or video

![Screenshot from 2024-02-20 17-09-02](https://github.com/black7375/Firefox-UI-Fix/assets/1098725/5370e175-e518-4a50-9e60-0245034d8b89)

### Additional context

Application Basics
Name 	Firefox
Version 	125.0a1
Build ID 	20240220094730
Distribution ID 	mozilla-deb
Update Channel 	nightly
User Agent 	Mozilla/5.0 (X11; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0
OS 	Linux 6.5.0-1014-oem #15-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 19 11:03:48 UTC 2024
OS Theme 	Yaru-dark / Yaru
Application Binary 	/usr/lib/firefox-nightly/firefox-bin

**Comment by black7375** [comment]
Now supported!! Thanks for report.
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/631338f1-0318-44ba-8282-dfac67ba88cd)
