### ISSUE TITLE
Version comment user.js

### ISSUE THREAD

**Issue by martixy** [black7375/Firefox-UI-Fix#876]
### Is your feature request related to a problem?

This is very minor, all things considered, but it would be neat if user.js contained the version number as a comment at the top.

Would be nice to know which version one currently has, in case you forgot what you chose last time or when you updated last.

### The solution I'd like

Just put a comment at the top of user.js with the version number and flavor of each release.

E.g. `v8.6.0 ESR-Lepton-Proton-Style`

**Comment by black7375** [comment]
LGTM.
I'll apply it starting with the next release.

**Comment by black7375** [comment]
I forgot to automate it before release, so I manually marked it in user.js first.
