### ISSUE TITLE
Windows 11 Default Theme NOT Applying

### ISSUE THREAD

**Issue by Progress200** [black7375/Firefox-UI-Fix#877]
### Describe the bug

Windows 11 default theme does not apply correctly. The colour is not correct.
![image](https://github.com/black7375/Firefox-UI-Fix/assets/109966292/732ff3dd-b26e-4514-a572-47411d189974)

### Expected behavior

Correct theme (Floorp Browser)
![image](https://github.com/black7375/Firefox-UI-Fix/assets/109966292/e4affe3c-653f-4cf0-9bba-93daa89fd68d)

### OS

Windows 11

### Firefox Version

v126.0a1 (Nightly)

### Distribution

- [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [X] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>

**Comment by black7375** [comment]
How about turn on `userChrome.compatibility.os.win11` to `true`?

**Comment by Progress200** [comment]
![image](https://github.com/black7375/Firefox-UI-Fix/assets/109966292/8402d21c-3baa-4af2-9561-ad6e886c90b1)
No, it is still not working. (Left side Firefox color, right side correct color from Floorp Browser.) 
My current Firefox version is 127.0a1

**Comment by black7375** [comment]
If so, it was most likely caused by #880 
I predict that if you update to the latest commit, and change `userChrome.compatibility.os.win11` back to `false`, you'll get the old colors.
