### ISSUE TITLE
Incorrect background in active tab

### ISSUE THREAD

**Issue by gotyaoi** [black7375/Firefox-UI-Fix#88]
**Describe the bug**
I use a theme with a header image. I use the photon-style branch of this repository. Today I upgraded from https://github.com/black7375/Firefox-UI-Fix/commit/f65ee736642d359ef7eb3eab66257956f475214d to https://github.com/black7375/Firefox-UI-Fix/commit/edc4a4683855e33c47f449633bd2ca835b675825. It's a little hard to describe, but before the update, all tabs, including the active tab, showed the header image behind them, and the header image stayed still as the tabs moved over it. After the update, the inactive tabs are still correct, but the active tab is some fixed chunk of the header image (looks like it's a scaled down version starting at the left side) that moves with the tab. As far as I can tell, the commit that introduced it was https://github.com/black7375/Firefox-UI-Fix/commit/8226cdd7b5a5d5e6305cb2e91cc3a9a648e72dad. Also, it's somewhat difficult to tell the active tab now, as before there was a sort of white highlight to the active tab and now there is not.

**Expected behavior**
The active tab shows the theme's header image behind it, similarly to all the other tabs.

**Screenshots**
The active tab is the one I've marked. Notice the discontinuity in the header image behind it.
![image](https://user-images.githubusercontent.com/2141918/121759668-a92ed780-cadb-11eb-9c00-94b2d6599fc7.png)

**Environment (please complete the following information):**
 - Firefox Version: 89.0
 - OS:
   - [ ] Linux
   - [x] Windows
   - [x] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [ ] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

**Additional context**
Theme isn't one of the ones mentioned above, but the persona system. https://addons.mozilla.org/en-US/firefox/addon/yakuza-paint/

**Comment by black7375** [comment]
I checked. It's an obvious bug and needs to be fixed as soon as possible.

**Comment by black7375** [comment]
Now it looks almost the same as before (v88).

**Comment by gotyaoi** [comment]
I applied that change and it looks perfect.
