### ISSUE TITLE
browser.tabs.cardPreview.enabled revert back after closing the browser

### ISSUE THREAD

**Issue by seatg32** [black7375/Firefox-UI-Fix#885]
### Describe the bug

I've folders for bookmarks. I simply drag the tab to the appropriate folder to bookmark it, but with this unnecessary and ugly tab preview, it obscures the folders with its preview window. So, I can't just drag a tab and save it in a folder any more. I used what you suggested in the release note, I enabled this: “browser.tabs.cardPreview.enable" yet it reverts to false when I close the browser for some reason!

### Expected behavior

the preference “browser.tabs.cardPreview.enable" should stay true after I close the browser.

### OS

Windows 10

### Firefox Version

125.0.2 (64-bit)

### Distribution

- [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [X] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [X] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [ ] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>

**Comment by testitus** [comment]
Since "browser.tabs.cardPreview.enabled" is set at "true" in the user.js file, it overrides what is in about:config.

You need to edit manually user.js.

With the Search tool of your code editor, look for "browser.tabs.cardPreview.enabled" (it should be around lines 280-290, depending on your Firefox UI version and variant.)

If you don't have a code editor, you can use Notepad.



Also, for some general information, here is an article describing more in details the tab preview feature : https://www.omgubuntu.co.uk/2024/02/firefox-devs-working-on-tab-hover-previews

**Comment by seatg32** [comment]
> Since "browser.tabs.cardPreview.enabled" is set at "true" in the user.js file, it overrides what is in about:config.
> 
> You need to edit manually user.js.
> 
> With the Search tool of your code editor, look for "browser.tabs.cardPreview.enabled" (it should be around lines 280-290, depending on your Firefox UI version and variant.)
> 
> If you don't have a code editor, you can use Notepad.
> 
> Also, for some general information, here is an article describing more in details the tab preview feature : https://www.omgubuntu.co.uk/2024/02/firefox-devs-working-on-tab-hover-previews

you're absolutely right. I completely forgot about the user.js file, I'm a layman with zero experience in these things, it is not really an excuse, but accept my sincere apology for the inconvenience I made.
