### ISSUE TITLE
Address bar border with Firefox 126

### ISSUE THREAD

**Issue by shibotto** [black7375/Firefox-UI-Fix#889]
### Describe the bug

The active tab no longer draws on top of the address bar.

### Expected behavior

The address bar border to be hidden under the active tab.

### Screenshots

Firefox 125.0.3
![Schermata da 2024-05-14 17-21-11](https://github.com/black7375/Firefox-UI-Fix/assets/3816409/e37e778a-5324-4c0f-b550-44456839289e)

Firefox 126
![Schermata da 2024-05-14 17-21-50](https://github.com/black7375/Firefox-UI-Fix/assets/3816409/a8104064-11bd-47b9-820d-828e0e20aba1)

### OS

Linux

### Firefox Version

126

### Distribution

- [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [X] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### Theme - More Info

Graybird

### `user.js` setup

I don't know where that is, sorry. I just did `./install.sh` on a live environment.

**Comment by black7375** [comment]
This is an issue that can occur with some themes on Linux.
`border-top` was a problem, which I replaced with `box-shadow`.

**Comment by shibotto** [comment]
That's a smart idea, but the -0,01px `box-shadow` is probably the same as not no shadow at all. Setting it to -1px however makes it look just like before on every GTK+ theme I tried:

![Schermata da 2024-05-25 09-50-52](https://github.com/black7375/Firefox-UI-Fix/assets/3816409/2e445354-b2f8-460c-8dab-3cdae75559a7)
![Schermata da 2024-05-25 09-51-02](https://github.com/black7375/Firefox-UI-Fix/assets/3816409/793a8a10-ecbb-4d97-bc9e-8184cf8a3fe3)
![Schermata da 2024-05-25 09-51-27](https://github.com/black7375/Firefox-UI-Fix/assets/3816409/f7468d0b-4fb7-4f85-8c3d-9e296bb6ac16)
![Schermata da 2024-05-25 09-52-03](https://github.com/black7375/Firefox-UI-Fix/assets/3816409/b080f755-c837-480d-865b-62031d7806ed)
![Schermata da 2024-05-25 09-52-13](https://github.com/black7375/Firefox-UI-Fix/assets/3816409/33999f5d-55a6-4e46-b77e-c1dc671580e2)

But of course that doesn't work as well for Firefox own themes and that 1px border-like shadow becomes really an eyesore.

![Schermata da 2024-05-25 09-58-28](https://github.com/black7375/Firefox-UI-Fix/assets/3816409/6aebc5d1-a0df-44cc-9cb0-5acb91ffd0fe)
![Schermata da 2024-05-25 09-57-17](https://github.com/black7375/Firefox-UI-Fix/assets/3816409/d8ad5b19-72bb-4aac-8bcf-e9f43097cbf5)

If it's not possible to set it only when using the system theme, then probably your current solution is the best one.

**Comment by black7375** [comment]
Of course, bolding is only possible in Linux system themes.
Thanks to your feedback.

**Comment by black7375** [comment]
A bug-fixed version has been released.
- https://github.com/black7375/Firefox-UI-Fix/releases/tag/v8.6.2
