### ISSUE TITLE
Reduced address bar contrast using macOS system theme for v126.0

### ISSUE THREAD

**Issue by aphedges** [black7375/Firefox-UI-Fix#898]
### Describe the bug

When using "System theme — auto" on macOS, as of Firefox v126.0, the address bar is #ECECEC while the surrounding area is #EFEFEF, which is only 3 bits lighter.

### Expected behavior

When not using a custom style, the address bar is #F0F0F4 while the surrounding area is #F9F9FB, a full 9 bits of difference. The same amount of contrast is available when using this repo's custom style with Firefox's "Light" theme.

### OS

Mac OS

### Firefox Version

126.0

### Distribution

- [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [X] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

No change from the default settings for v8.6.1.

### Additional context

All hex values given are for a new profile. I do not understand why, but my existing profile has slightly different colors; however, the amount of contrast between the address bar and the surrounding area are the same regardless of using an existing or a new profile.

**Comment by black7375** [comment]
I was too busy to check the issue at the time.
This looks like the same issue as #897 , so we'll handle it in #897 .

**Comment by aphedges** [comment]
@black7375, you were correct. Your fix for #897 (260557f2571267a42ced87fed84c129a0aef4fff), fixed this issue as well!

Thanks for the fix!

**Comment by black7375** [comment]
Glad to hear that.
Have a great weekend!!!
