### ISSUE TITLE
[Not an Issue] Thank you for creating this!

### ISSUE THREAD

**Issue by toluschr** [black7375/Firefox-UI-Fix#9]
I just wanted to express my gratefulness for you having created this theme.
It looks substantially better compared to the default proton ui and chrome.

**Comment by black7375** [comment]
I think most of the major complaints have been resolved, but we will try to make a better UX.

Typical examples are animation and interaction.
https://github.com/black7375/Firefox-UI-Fix/issues/2#issuecomment-843867954

**Comment by black7375** [comment]
I was seriously considering whether I would leave Firefox, and I decided to fix it myself.
We will try to keep improving it in the future. 😄

**Comment by TurtleDino** [comment]
Thank you from me as well. Please continue to work on this project as I was considering leaving Firefox as well. Not for now with this awesome fix though!

**Comment by ojaha065** [comment]
The only major thing that was bugging me in the Proton design was the huge padding in the menus, especially in the bookmarks menu as all my bookmarks would no longer fit single screen height. This fixes that, so thank you for this from me as well. Other changes you've made seem nice and useful too but the padding was the only real dealbreaker for me.

**Comment by JG24** [comment]
Sir, You saved my life. I've been using Firefox since it was called Firebird. After updating the interface, my first thought was that I am abandoning this browser in favor of Chrome. You have extended the life of a red panda. Hopefully the people responsible for this change of layout will be kicked out of Mozilla.

**Comment by simonjulou** [comment]
Thank you for all your work. This "fix" keeps Firefox useable for me. Without it I'd be looking at changing to a different browser.

**Comment by squash0r4ng3** [comment]
My laptop has a 14" display with 1080p resolution, so vertical screen real state is very precious to me.
I wish ff devs would take stuff like this into account and not make the compact option not.. compact anymore.
Thank you so much for this fix, I'm sure it will help a lot of other people too.

**Comment by black7375** [comment]
There are also many complaints about the padding.
I was able to tolerate everything else, but the gaps were too inconvenient.

**Comment by Worble** [comment]
Thanks so much for this, I could honestly learn to live with the padding but the menu icons are an absolute lifesaver.

**Comment by Tafoplaka** [comment]
Hello. Like everyone else, i would like to thank you for this project. It looks fantastic. 

I only wish you could give an option for "tabs at bottom" as well. 
Same look as current just with tabs at bottom. 
Either way, this looks moreless like classic FF we all love. Yes i have tried other css codes for tabs at bottom but they miss all other features, plus they leave lots of space under menu bar which i cant seem to fix it.

Heres how it looks right now.  https://ibb.co/g6nkDzc **retro ftw**

**Comment by black7375** [comment]
@Tafoplaka 

The problem of the bugs that are still too much to manage additional themes is a priority.
Maybe we can discuss it later.

**Comment by MarcoCruz3011** [comment]
Thank you very much for this amazing work!! FF 89 got much better with it.
I´d like to suggest you to include the code to change the color of the active tab

  .tab-content[selected="true"] {
    background: rgba(65, 85, 145, 0.4) !important;
  }

**Comment by black7375** [comment]
@MarcoCruz3011

Thanks for the suggestion.
However, we need to be compatible with various themes, so I think we should keep the basic colors as much as possible.

**Comment by gresolio** [comment]
Oh man, thank you very much for this UI fix!
The course of development from Mozilla is slowly but surely destroying Firefox...

Firefox usage is down 85% despite Mozilla's top exec pay going up 400% https://calpaterson.com/mozilla.html

**Comment by dancemasterglenn** [comment]
Mozilla should seriously bring you on to make this the official UX, Lepton has made my browser so beautiful. Thank you!

**Comment by TheQuickFox** [comment]
Thanks a lot! Your fixed UI is so nice. And I recently updated it to get the full Aero Glass theme in Windows 7 as well. Awesome!

**Comment by black7375** [comment]
I think it's open now, so I'll close it.
