### ISSUE TITLE
Close duplicate tabs item in list all tabs & tabs context menu doesn't have an icon in latest Firefox update

### ISSUE THREAD

**Issue by Aleksandra0056** [black7375/Firefox-UI-Fix#903]
### Is your feature request related to a problem?

Close duplicate tabs item in the tabs dropdown menu doesn't have an icon in Firefox v127.0.0

![grafik](https://github.com/black7375/Firefox-UI-Fix/assets/69351811/e234d381-2ae4-4f59-886b-34b878f2f278)

### The solution I'd like

Add an icon to the mentioned item to be consistent with other menus.

**Comment by Aleksandra0056** [comment]
I noticed the same for tabs context menu

![image](https://github.com/black7375/Firefox-UI-Fix/assets/69351811/94a63f6c-345d-4acb-a058-e029d2b2dced)

**Comment by black7375** [comment]
I've finished applying the icon.
https://github.com/black7375/Firefox-UI-Fix/commit/df476af576b1ac000625423c6c06dd67fb4255fd

Thanks @zapSNH !!
