### ISSUE TITLE
In a dark style, the note font is in the background color selections and is not visible

### ISSUE THREAD

**Issue by PhoenixIndigo** [black7375/Firefox-UI-Fix#904]
### Describe the bug

In a dark style, the note font is in the background color selections and is not visible
https://addons.mozilla.org/ru/firefox/collections/17366156/My-extensions/?page=1

### Expected behavior

Note visibility in dark style

### Screenshots

<details><summary>Details</summary>
<p>

![](https://github.com/mozilla/addons/assets/107413021/19dbd71f-dc30-4503-9b22-fb32941e7de4)

</p>
</details> 

### OS

Windows 11

### Firefox Version

127

### Distribution

- [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [X] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [X] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [ ] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>

### Additional context

https://github.com/mozilla/addons/issues/14822

**Comment by PhoenixIndigo** [comment]
https://support.mozilla.org/ru/kb/perekhod-na-drugoje-ustroistvo
<details><summary>Details</summary>
<p>

![](https://github.com/black7375/Firefox-UI-Fix/assets/107413021/cfb6e67b-c4b5-44dc-9f5b-6bf157ca0262)

</p>
</details>

**Comment by black7375** [comment]
It has been improved and released.

![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/98fc34c7-7f1b-4442-aade-a2bbe5cd9407)
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/0c43a6a0-2ffe-47ef-8f02-6cdee6d228ce)


Let me know if you have any feedback.

**Comment by PhoenixIndigo** [comment]
https://addons.mozilla.org/firefox/
The language change panel and the text are of a white merging color.
In synchronization, when entering a confirmation code from an email, the numbers are white and merge with the white input line.

**Comment by black7375** [comment]
Could you show me a screenshot by any chance?

**Comment by PhoenixIndigo** [comment]
<details><summary>Details</summary>
<p>

![](https://github.com/user-attachments/assets/d3fed336-005b-46e7-97f2-6d408a89e709)
![](https://github.com/user-attachments/assets/c4e4250f-8d7e-4fec-9dc6-5f7d6ed96bb2)

</p>
</details>
