### ISSUE TITLE
Avatar alignment with Disconnected Account

### ISSUE THREAD

**Issue by B00ze64** [black7375/Firefox-UI-Fix#91]
**Describe the bug**
avatar-empty.svg is somewhat mis-placed when Firefox has an account, but it is disconnected.

**Screenshots**
![image](https://user-images.githubusercontent.com/15389810/121795218-2d797b80-cbfe-11eb-8f83-2b134fa5b231.png)

**Environment (please complete the following information):**
 - Firefox Version: 89
 - OS:
   - [ ] Linux
   - [x] Windows 7
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [x] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [ ] System Default

**Comment by black7375** [comment]
How can account disconnection be reproduced?

**Comment by sean1138** [comment]
i tried disconnecting from internet and then trying to sync with a firefox browser on linux (not using a profile account on windows currently) but did not get the "account disconnected"

Also tried restarting the browser while internet was disconnected, and sync now again, still no "account disconnected".

did find `fxastatus` used in panelUI.css to set various things
![image](https://user-images.githubusercontent.com/6720184/121810958-b7dad300-cc30-11eb-9f09-0b77fe823801.png)

BUT when i added `fxastatus="login-failed"` to the `id=appMenu-fxa-status2` element the menu broke.
![image](https://user-images.githubusercontent.com/6720184/121811161-84e50f00-cc31-11eb-9f91-a89bdec30785.png)
![image](https://user-images.githubusercontent.com/6720184/121811176-94fcee80-cc31-11eb-920e-1fb3961b438c.png)

**Comment by black7375** [comment]
@sean1138 
Thank you!!!

**Comment by B00ze64** [comment]
Hi, sorry, I do not use FxAccounts myself, I just have them setup so I can skin the menus, so I'm not sure how this particular profile ended-up as Disconnected. New code works fine :-)

**Comment by black7375** [comment]
Thanks for testing.
