### ISSUE TITLE
Translations table items are too height

### ISSUE THREAD

**Issue by Aleksandra0056** [black7375/Firefox-UI-Fix#910]
### Is your feature request related to a problem?

I first noticed this when alternate row colours were implemented.

Translations table items are too height when compared to "Applications" or "Search Shortcuts" tables.

### The solution I'd like

Shrink height for the Translations table items (from 43 pixels to 30 pixels) to be consistent with other tables (like Applications or Search Shortcuts).

And shrink height for the Header too (from 60 pixels to 43 pixels, further explained in my second comment).

#### Actual Translations table items height (43 pixels):
![Translations table items are too height](https://github.com/black7375/Firefox-UI-Fix/assets/69351811/113a4598-7c7f-42fb-bc6c-a03c8ae6bede)

----------

#### Height of Applications table items (30 pixels) for comparison:
![Applications table for comparison](https://github.com/black7375/Firefox-UI-Fix/assets/69351811/2d99a875-cfde-4176-bc8d-87048e97cf59)

**Comment by Aleksandra0056** [comment]
The header is too in height too (60 pixels):

![Header is also too height](https://github.com/black7375/Firefox-UI-Fix/assets/69351811/ec6a86af-e514-4e59-ab3f-b5d35936ee73)

**Comment by black7375** [comment]
IMO `30px` makes the button look tiny and out of scale with its surroundings.
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/e1d68b64-e663-417b-8ba1-c8f96eb98c0a)

So I'am going to adjust it to `45px`, `36px`.
![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/947a42de-a008-4cb3-9278-a586b390b7e1)

**Comment by Aleksandra0056** [comment]
I agree with the solution, so I'm closing this issue as solved.
