### ISSUE TITLE
Three new items in menu bar don't have icons in Nightly

### ISSUE THREAD

**Issue by Aleksandra0056** [black7375/Firefox-UI-Fix#917]
### Is your feature request related to a problem?

I discovered three new items in the menu bar in Firefox Nightly build from 12. June. But these items don't have icons.

#### The items are:
- Close Tab & Close Window (found in Menu Bar > File)
- Find Again (found in Menu Bar > Edit)

### The solution I'd like

Add appropriate icons to these items.

#### Close Tab & Close Window items:
![New Close Tab   Close Window items in the menu bar don't have icons](https://github.com/black7375/Firefox-UI-Fix/assets/69351811/114da6bc-c099-4351-80ea-24b0412d1f6b)

#### Find Again item:
![New Find Again item in menu bar don't have icon](https://github.com/black7375/Firefox-UI-Fix/assets/69351811/15e90569-dbf2-46cf-a9b5-c5625eccb19c)

**Comment by black7375** [comment]
I found the icon and included it in the release.
- https://github.com/black7375/Firefox-UI-Fix/releases/tag/v8.6.2
