### ISSUE TITLE
The website window turned smaller on Cachy browser

### ISSUE THREAD

**Issue by MohammedWaelElshiekh** [black7375/Firefox-UI-Fix#936]
### Describe the bug

Hi there, I tried a new browser called Cachy Browser and wanted to apply your UI-fixing installation to keep it clean, as I always do. However, the installer didn't recognize the profile path. I attempted to pass the path to the profile using the command ./install.sh -p "my profile", but it didn't work. Therefore, I edited line 339 in the main install.sh script to be "${HOME}/.cachy", and it worked. The issue now is that after this fix, the website window of the browser has become smaller than its frame, with a space between the browser's main frame and the website frame, similar to the Tor Browser. Any assistance with this issue?
![image](https://github.com/black7375/Firefox-UI-Fix/assets/82011471/cd6d3d6c-ce3a-4ee4-b64a-72931aa03921)

### OS

Linux

### OS - Others

Cashy OS

### Firefox Version

Cachy browser 127.0.2 (64-bit)

### Distribution

- [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

**Comment by black7375** [comment]
1. Can I get a compiled package? If not, I'll need to install the [CachyOS](https://cachyos.org/) on the VM and check it out.
2. Did you experience the same thing with Tor Browser?

For now, I'll look at the Tor browser.

**Comment by MohammedWaelElshiekh** [comment]
I cannot find a package for this browser, but I found the core of this browser on GitHub https://github.com/CachyOS/CachyOS-Browser-Settings I think it is based on librewolf.

**Comment by MohammedWaelElshiekh** [comment]
> 1. Can I get a compiled package? If not, I'll need to install the [CachyOS](https://cachyos.org/) on the VM and check it out.
> 
>     2. Did you experience the same thing with Tor Browser?
> 
> 
> For now, I'll look at the Tor browser.

https://github.com/black7375/Firefox-UI-Fix/issues/936#issuecomment-2199154697

**Comment by MohammedWaelElshiekh** [comment]
> 1. Can I get a compiled package? If not, I'll need to install the [CachyOS](https://cachyos.org/) on the VM and check it out.
> 
>     2. Did you experience the same thing with Tor Browser?
> 
> 
> For now, I'll look at the Tor browser.

No tor browser comes with this bug, I really don't know if it is a bug or just trying to prevent websites from getting which device i use.

**Comment by black7375** [comment]
Unfortunately, I can't reproduce it.
Could there be more conditions?

![image](https://github.com/black7375/Firefox-UI-Fix/assets/25581533/8238f14c-ca37-4505-b22d-452d373a2e8f)

**Comment by MohammedWaelElshiekh** [comment]
Try installing the system fully on you vm, I think it might be a package that interferes with the browser ?

**Comment by Aleksandra0056** [comment]
Try my steps:
1. Open your browser,
2. Go to `about:config` URL,
3. Skip warnings,
4. Find `privacy.resistFingerprinting.letterboxing` (create it if it doesn't exist),
5. Set `privacy.resistFingerprinting.letterboxing` to false,
6. Restart your browser.

NOTE: Don't change values you don't know about since manipulating your browser with `about:config` may make your browser unstable or insecure.

**Comment by MohammedWaelElshiekh** [comment]
It worked, thanks a lot for your help.
