### ISSUE TITLE
Tab Preview Option Name Change

### ISSUE THREAD

**Issue by AuRiMaS666** [black7375/Firefox-UI-Fix#947]
### Describe the bug

https://github.com/black7375/Firefox-UI-Fix/blob/4b6a1d787b8ebfebc26c6ebb33b9a9a7fe8dbdd2/user.js#L286

This option has been renamed since version 128 to:

```
browser.tabs.hoverPreview.enabled

browser.tabs.hoverPreview.showThumbnails
```

### OS

Windows 11

### Firefox Version

128

### Distribution

- [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [ ] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

Default user.js settings

**Comment by black7375** [comment]
Thanks!!
I've changed.
