### ISSUE TITLE
Missing `Play Tab` icon on tab right-click context menu

### ISSUE THREAD

**Issue by erwin4270** [black7375/Firefox-UI-Fix#955]
### Describe the bug

The Play icon is missing on the tab right-click context menu when a tab contains an audio or video file that haven't played first time (not pause)

### Expected behavior

Play icon is present on tab right-click context menu

### Screenshots

Steps to reproduce:

1. Drag an audio or video file into the tab bar.
2. Right-click on the opened tab.

https://github.com/user-attachments/assets/01c0cd66-8576-48c9-990d-f444b229d5eb

![0](https://github.com/user-attachments/assets/b045cae1-6dde-468c-8340-b63b355a8eec)

### OS

Windows 11

### Firefox Version

129.0 (stable)

### Distribution

- [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [ ] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
user_pref("userChrome.icon.menu",                 true);
user_pref("userChrome.icon.menu.full",            true);
```
</details>

### Additional context

Autoplay must be set on `Block Audio` or `Block Audio and Video` in `Settings > Privacy & Security > Permissions > Autoplay`.

**Comment by black7375** [comment]
Now, looks like this. Thanks.

![image](https://github.com/user-attachments/assets/a2c1ec97-e929-42fb-ac66-5e5caedf7575)
