### ISSUE TITLE
Cannot change the size of the sidebar on the right

### ISSUE THREAD

**Issue by newmomizi** [black7375/Firefox-UI-Fix#956]
### Describe the bug

When you set the sidebar position to the right, you can't change its size. Tested on Lepton and Lepton-Photon.

### Expected behavior

Can change the sidebar size, as when it is on the left.

### Screenshots

Firefox Default Design
![vlcsnap-2024-08-07-22h58m44s169](https://github.com/user-attachments/assets/7e8284fd-c501-4ed1-a55a-c6c0b7ab5d9b)

Lepton Design
![vlcsnap-2024-08-07-22h59m11s078](https://github.com/user-attachments/assets/6e6482c6-74f6-48d7-ac11-8f138bce3952)

### OS

Windows 11

### Firefox Version

128.0.3(Release), 131.0a1(Nightly)

### Distribution

- [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [X] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [X] Light
- [X] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [X] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>

**Comment by black7375** [comment]
That's weird, it should be possible.
![image](https://github.com/user-attachments/assets/d776993f-7b03-4eff-8245-2ba9e05036f8)

What does it look like when you search for sidebar in `about:config`?
![image](https://github.com/user-attachments/assets/a43bebae-fd92-46be-aaa5-8785b1ee39d0)

**Comment by newmomizi** [comment]
Thanks for your reply. This is my config.
![スクリーンショット 2024-08-09 201216](https://github.com/user-attachments/assets/615b2878-5755-44b2-981e-14f26b0ba282)
(sidebar.position_start=false. Others are default)

I created a new profile, installed Lepton theme, and took this screenshot. The problem still occurs

**Comment by newmomizi** [comment]
I updated Firefox(Nightly) and Photon theme, and the problem was fixed. Thanks
