### ISSUE TITLE
Tab bar closes unintentionally in full screen mode.

### ISSUE THREAD

**Issue by Tech-How** [black7375/Firefox-UI-Fix#979]
### Describe the bug

When you're in full screen mode (F11 during normal browsing), and move your mouse up to the bar, it slides down. However, these are two times where it slides back away when it should stay open.
- Your mouse hovers over the tab preview card when it appears
- Your mouse hovers over the bookmarks bar

Due to this, it's not possible to use the bookmarks bar when you are in fullscreen mode. I have the bookmarks bar set to always show, and I was on a website, if that helps.

### Expected behavior

The tab and bookmarks bar should stay open until the mouse fully moves off of the entire bar, and back onto the web content.

### OS

Linux

### OS - Others

Ubuntu 22.04 LTS

### Firefox Version

130.0

### Distribution

- [ ] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [X] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [X] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### Theme - More Info

Breeze (I'm using KDE Plasma v5.24.7)

### `user.js` setup

I'm using the user.js file provided from this repo.

### Additional context

Let me know if any additional information would be useful or if this can't be reproduced.

**Comment by HonoredShadow** [comment]
I have this issue also.  Using F11 I can't click on any of my bookmarks as they slide away before I can click on them.  Windows 11 23H3. Lastest official Firefox.

**Comment by black7375** [comment]
Improvements have been made to prevent hiding in related events.
See https://github.com/black7375/Firefox-UI-Fix/releases/tag/v8.6.3
