### ISSUE TITLE
Hidden tabs to narrow, not like tab list

### ISSUE THREAD

**Issue by benyaminl** [black7375/Firefox-UI-Fix#98]
**Describe the bug**
Hidden Tab to narrow not like tab list, it doesn't have any padding at all

**Expected behavior**
There're padding like tab list

**Screenshots**
![image](https://user-images.githubusercontent.com/2817332/122323420-3dbc8e00-cf51-11eb-8a45-fa0d89334997.png)

**Environment (please complete the following information):**
 - Firefox Version: [write from `about:support` - `version`]
 - OS:
   - [ ] Linux
   - [X] Windows 20H2
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [X] Light
   - [X] Dark
   - [X] Alpenglow(System: Light)
   - [X] Alpenglow(System: Dark)
   - [X] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

**Additional context**
None, see the image, should be add some rules for it.

**Comment by black7375** [comment]
I don't have time to investigate because I have a personal schedule now.
Maybe I'll check it out at night or tomorrow.

**Comment by black7375** [comment]
It's seems upstream problem.
![image](https://user-images.githubusercontent.com/25581533/122493940-0d6c0280-cfd8-11eb-97b8-eccbb265c819.png)

![image](https://user-images.githubusercontent.com/25581533/122493831-e31a4500-cfd7-11eb-9b32-6f69416a771c.png)

We could work it out, but let's report it first.

**Comment by benyaminl** [comment]
Oh it's from Firefox XUL itself? Does it seems intended to be like that?
Interesting.




Regards,
Benyamin Limanto
sent from my Sony XPERIA XZ Premium

**Comment by black7375** [comment]
I think it's a bug.
Hidden tab panel is not normally activated, so I guess they forgot it.

**Comment by black7375** [comment]
Once I fit it to our repository first.
