### ISSUE TITLE
New Context Menu Item Needs An Icon

### ISSUE THREAD

**Issue by thunderstone135** [black7375/Firefox-UI-Fix#987]
### Is your feature request related to a problem?

The upcoming Waterfox G6.5 (or is it G7?) added a new context menu without an icon.
It show up when you right click a bookmark folder.

### The solution I'd like

Please add an icon because it looks like a sore thumb.

### Screenshots or video

![Imgur](https://imgur.com/LgesEjS.png)

### Alternatives I've considered

I have tried to add an SVG icon myself, but I can't find it in the Browser Toolbox.

### Additional context

This is the SVG I wanted to add by the way.
![Tree](https://www.svgrepo.com/download/365836/tree-structure-thin.svg)
I think it fits since it's a tree structure.

**Comment by thunderstone135** [comment]
After some sleuthing, I was able to find its Class ID: _**#context_openAllBookmarksWithStructure**_
I found it in: _**Waterfox\browser\omni.ja\chrome\browser\builtin-addons\sidebar\options\options.html**_
However, even after putting it in userChrome.css and assign an icon, there seems to be no effect.

**Comment by black7375** [comment]
When I made the provided icon into 16x16, it was thin, so I used something similar from Fluent Icons!!
