### ISSUE TITLE
Provide a way to disable tab preview

### ISSUE THREAD

**Issue by antoyo** [black7375/Firefox-UI-Fix#991]
### Is your feature request related to a problem?

Yes, it seems this plugin will force the user to have tab previews: disabling the option for it will be reverted everytime Firefox is opened.

### The solution I'd like

I'd like a way to disable the tab previews that stays across restart.

**Comment by lolcatw** [comment]
At the root of your firefox profile, edit the `user.js` file. In there, modify this line:

```
user_pref("browser.tabs.hoverPreview.enabled", true);
```
It's `true` and we don't want that. Set it to false. Then, restart firefox. It should force it to being false from there on out.

**Comment by lolcatw** [comment]
@black7375 unsure who to mention, but this fixes the issue. ^^^

**Comment by black7375** [comment]
I've been busy lately so I'm late in replying.
This was an intentional setting, so you can turn it off by changing `false` in `user.js`.

Thank you for writing the solution for me. @lolcatw 

https://github.com/black7375/Firefox-UI-Fix/blob/d60a75341618756810b0269c93bc2b0dfd977174/user.js#L289
